### ISSUE TITLE
Add code coverage thingy & get to 90%+

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#100]
## Problem

Without static type checking or a compiler, we need to test the heck out this thing!
## Solution

Use [flow](https://flowtype.org/) and/or add code coverage generation to `grunt test` process.
- [ ] Set minimum threshold and tie it to Travis
- [ ] Display badge on README
- [ ] See this handy little bot: `https://github.com/ethereum/go-ethereum/pull/2455#issuecomment-209975901`
- [ ] Make sure it counts tests performed through Nightmare

**Comment by sandrina-p** [comment]
Same as #420, I don't see this to be a high priority for us to finish the Prototype.

We also have #632 saying the same thing and it has Low priority. My suggestion is:
1. update this issue with the additional info at #632
2. close #632 as duplicated.
3. Replace the priority label to Low.

What do you think @taoeffect?

**Comment by taoeffect** [comment]
I'm going to close this in favor of #632 and #528.
