### ISSUE TITLE
Fix Design System Page

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1008]
### Problem

One of the recent PRs made it so that `/app/design-system` page doesn't load anymore.

### Solution

Fix!

**Comment by SebinSong** [comment]
Hi people,
What's the purpose of wrapping a page component with a function when defining a route for it?

![image](https://user-images.githubusercontent.com/17641213/97795476-8302a880-1c6b-11eb-8aad-11aed163f869.png)

Just asking this question because removing the arrow function fixes the bug..!

Thanks.

**Comment by taoeffect** [comment]
Nice catch @SebinSong! I bet this was introduced in #948. So closing this would require:

- Verifying consistency in how the `component:` attribute is filled. From a quick glance, it seems like it might be that whenever a component is loaded using `lazyLoadView`, then the route uses the `() =>` syntax, and whenever a component is directly imported, e.g. like `import DesignSystem from '@pages/DesignSystem.vue'`, then it shouldn't, which is the case here.
- However, we need to lazy-load more things, it shouldn't make sense that for the final build of the app we bundle the entire design system into the main bundle, so it too should be lazyily loaded here, and I think that is the way to go about fixing it. In other words, not removing `() =>`, but using `lazyLoadView` to load it instead of the `import DesignSystem from '@pages/DesignSystem.vue'`.
- Finally, verify that it properly lazily loads still when visiting the page, e.g. in Firefox Dev Edition, [enable throttling, and set it to something like 2G](https://github.com/okTurtles/group-income-simple/pull/948#discussion_r487351051) and then visit the route, and verify that it still loads
