### ISSUE TITLE
Modularize bulma/font-awesome to cut down on CSS

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#101]
## Problem

We're loading too much CSS and that could impact performance. Chrome's audit feature shows that we're not using 93% of the css on a page.
## Solution

- http://bulma.io/documentation/overview/modular/ <- this
- https://github.com/stipsan/bulma-loader ?

**Comment by taoeffect** [comment]
Or better yet, [switch to svg](https://sarasoueidan.com/blog/icon-fonts-to-svg/).

**Comment by sandrina-p** [comment]
Nowadays using SVG with `<use>` and sprites is much better (flexible and smaller) than using a font-family (ex: font-awesome) Font-awesome also provides SVGs source, so we would need to:
- Analyze what icons we are using
- Download font-awesome svgs
- Replace old icons for svgs

**Comment by taoeffect** [comment]
Closed in #573
