### ISSUE TITLE
Mobile UI issue: random user icon blockie not showing up [$400 bounty]

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1025]
### Problem

While testing via `grunt dev --tunnel` (see #1020) on Mobile Safari, I noticed that the randomly generated user icon doesn't appear when you tap your name in the sidebar userlist:

![a3](https://user-images.githubusercontent.com/138706/100533051-efae8b80-31b4-11eb-84cf-672a2261bbf1.jpg)

This is likely a problem in one of these files:

- `imageUpload` function in `frontend/utils/image.js`
- `frontend/views/components/AvatarUpload.vue`
- `frontend/views/components/Avatar.vue` (and any containing components that are using it)

Thanks @Silver-IT for pointing out the image domain is being set to `localhost` when it shouldn't be.

### Solution

Find where the image's domain is being set to `localhost`, and replace it with the domain of the website. This can often be done by referencing `window.location.origin`.

### Bounty

$400 bounty for a clean solution to this (paid in cryptocurrency).

**Comment by taoeffect** [comment]
*Note: might want to test with `ngrok` as well (e.g. `ngrok http 8000` after running `grunt dev`) to verify that this isn't an issue with the `loca.lt` tunnel.

EDIT: Just tested this with `ngrok`, and seems to be an issue there too.

**Comment by taoeffect** [comment]
Adding a $300 bounty for closing this issue for non-contractors (meaning, if you don't have a development contract with okTurtles, and you'd like to close this issue, you can work on it, and if we accept your PR, you'll receive the bounty).

Anyone else can add to the bounty too if they'd like by following these simple steps:

1. Donate the amount you'd like to dedicate to this issue [to the okTurtles Foundation](https://okturtles.org/donate/).
2. Make a comment here (or privately to us via Gitter or Slack) the same day letting us know you'd like your donation to be used for a bounty to close an issue, and which issue that is.

**Comment by Silver-IT** [comment]
I created a Ubuntu 21.10 VPS server for this and could get an [address](http://66.42.110.182/).
Having found an avatar issue while testing, I inspected the element and found that the avatar URL starts with `localhost`.
It needs to be the URL that must be saved in the server.
![image](https://user-images.githubusercontent.com/57976479/143562685-575c5335-3313-4e30-b61f-b7083a235b53.png)
This issue is not related to the mobile and it breaks in the desktop browser either no matter which OS it is.

**Comment by taoeffect** [comment]
Great job identifying the issue @Silver-IT! This is actually a *super* easy thing to fix, it shouldn't take long at all to fix this. I thought the problem was 5x as hard as it actually appears to be and overestimated the bounty, ~~so I lowered it from $400 to $300, but that's still a great deal for what should be just a ~1 to 3-line fix.~~

Edit: *After chatting with another teaming about the bounty amount, I decided that this was my mistake and the bounty should remain as it was, so I'm raising it back to $400.

**Comment by taoeffect** [comment]
To give a bit of a time-saving hint since I lowered the bounty on this one: the places most likely to be worth checking are:

- `imageUpload` function in `frontend/utils/image.js`
- `frontend/views/components/AvatarUpload.vue`
- `frontend/views/components/Avatar.vue` (and any containing components that are using it)

**Comment by taoeffect** [comment]
*After chatting with another teaming about the bounty amount, I decided that this was my mistake and the bounty should remain as it was, so I'm raising it back to $400.

**Comment by Silver-IT** [comment]
Fixed. There was an error to set file path when we upload file.
`backend/routes.js` has registration for file upload API and it returns the full path even though we can not know the published backend path in the backend source code. That was the error.

**Comment by taoeffect** [comment]
Closed in #1113
