### ISSUE TITLE
Console error in GroupCreationModal during GroupMincome step

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1026]
### Problem

It is unclear to me whether this is in `master` or whether this is in @pieer's #1004, because the error doesn't occur every time, only sometimes:

<img width="871" alt="Screen Shot 2020-12-02 at 1 08 07 PM" src="https://user-images.githubusercontent.com/138706/100931568-8e7e0500-349f-11eb-8f5b-f0b47f6a1759.png">

For whatever reason, this validation in `GroupCreationModal.vue:170` is passed in a `null` value sometimes:

```js
        [L('Oops, you entered 0 or a negative number')]: mincomePositive,
```

This leads to an exception thrown by `commaToDots`, which doesn't expect a `null` parameter:

```js
function commaToDots (value: string | number): string {
  // ex: "1,55" -> "1.55"
  return typeof value === 'string' ? value.replace(/,/, '.') : value.toString()
}
```

### Solution

Find out why sometimes `vuelidate` is passing in a null value, and either modify the validation or the function `mincomePositive` to handle `null` values.

**Comment by snowteamer** [comment]
Apparently this error occurs in two steps:

1. When the user presses the `Enter` key in the input field while it is still empty, this triggers input validation in an attempt to submit the form, notwithstanding the fact that the "Next ->" button is still greyed out.

2. Then, as the default value for `mincomeAmount` has been configured to be `null` in the `data()` block of `GroupCreationModal.vue`, that `null` value gets passed in to the validation process, causing the error in `commaToDots()`.

Replacing `null` by `''` does seem to prevent the error.

**Comment by taoeffect** [comment]
@snowteamer Fantastic work investigating this! 🔍  Seems like an easy fix for whoever would like to send it in! 😄
