### ISSUE TITLE
Add i18n linter rules for using vue variables in i18n tags

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1027]
### Problem

While reviewing #1004 I [noticed](https://github.com/okTurtles/group-income-simple/pull/1004/files#r534499657) that [our `i18n` linter](https://github.com/okTurtles/group-income-simple/blob/master/scripts/validate-i18n.js) that @snowteamer wonderfully implemented appears to be missing a rule to catch the use of double-braces (Vue.js variables):

```pug
i18n Replying to {{replyingTo}}
```

### Solution

Throw an error that says Vue.js variables aren't allowed, and to use `:args` parameter with i18n tag and single-braces in the string to pass in variables.

/cc @snowteamer

**Comment by snowteamer** [comment]
So shall we just disallow any occurrence of `{{` in the `i18n` tag?

This would be much simpler to identify than checking if there is a valid JavaScript expression between matching double curly braces, and as far as I know double braces are unlikely to be used in an `i18n` tag outside Vue.js variables.

**Comment by taoeffect** [comment]
> So shall we just disallow any occurrence of `{{` in the `i18n` tag?

Yep!

**Comment by taoeffect** [comment]
Closed by @snowteamer in ##1031!
