### ISSUE TITLE
Cleanup package.json dependency fields

### ISSUE THREAD

**Issue by snowteamer** [okTurtles/group-income#1045]
### Problem

There are currently a few issues with our dependencies in package.json file:

- The `buffer`, `velocity-animate` and `vue-script2` modules do not seem to be actually used, but are still listed as dependencies.
- The `chalk` module is listed as a dev dependency, but is used in the backend.
- The `form-data` module is only used in `test/backend.test.js`, therefore it should be listed as a dev dependency instead of a regular one.

These assertions can be tested by scanning the codebase with `git grep`.

### Solution

Update the contents of the `dependencies` and `devDependencies` package fields:
- Move `chalk` into regular dependencies.
- Move `form-data` into development dependencies.
- Unlist `buffer`, `velocity-animate` and `vue-script2`, at least temporarily, unless they are actually used.

**Comment by taoeffect** [comment]
`buffer` is a required dependency without which the project won't build, but the others, sure!
