### ISSUE TITLE
🚨 Potential Security Vulnerability - huntr.dev

### ISSUE THREAD

**Issue by huntr-helper** [okTurtles/group-income#1062]
#### ⚠️ Potential Vulnerability in group-income-simple

👋 Hello, @taoeffect, @sandrina-p, @hubudibu - @ranjit-git has disclosed a potential vulnerability in your repository. To validate or invalidate this potential vulnerability, please visit https://huntr.dev/bounties/1-other-group-income-simple and join our community in helping secure open-source code.

---

#### ☎️ Need further support?

Come and join us on our [Discord](https://huntr.dev/discord) and a member of our team will be happy to help! 🤗

cc - @JamieSlome

**Comment by taoeffect** [comment]
Thanks for sending this in @ranjit-git! I believe we're actually aware of this issue. @snowteamer is currently working on addressing it in #975. If that doesn't fix it then yeah we welcome a separate PR. But please hold off for now simply searching the project for usages of `v-html`.

**Comment by taoeffect** [comment]
@ranjit-git A bounty has been sent to you. Thanks for sending this in! Please check your email. 😄

**Comment by taoeffect** [comment]
Closed by @snowteamer in #1073!
