### ISSUE TITLE
Switch to Vuex 2.0

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#107]
### Problem

- We're using an outdated version of Vuex
- Even though we've now updated to the latest version (I think), our code hasn't been modernized for it (I don't think?)

### Solution

Look through the release notes and verify that we're doing things "the Vux 2.0 way":

- lots here: https://github.com/vuejs/vuex/releases/tag/v2.0.0-rc.1
- & more: https://github.com/vuejs/vuex/releases

**Comment by taoeffect** [comment]
#115 is a duplicate but a more up-to-date duplicate.

**Comment by taoeffect** [comment]
Oops, just realized #115 wasn't a dup.

**Comment by taoeffect** [comment]
*edited OP.

**Comment by vijayee** [comment]
This was completed in #129
