### ISSUE TITLE
Some navigation links in User Settings are not fully working [$30 bounty]

### ISSUE THREAD

**Issue by snowteamer** [okTurtles/group-income#1072]
### Problem

It seems like these two internal navigation links don't work as expected:

- The `Troubleshooting` link in `AppLogs.vue`
- The `See application logs` link in `Troubleshooting.vue`

Although clicking on either link does update the browser location URL, as well as which app section title is highlighted in the sidebar, however the main diplayed content doesn't change.

### Solution

These links should just work as expected. Perhaps using an SBP `OPEN_MODAL` event could help, but neither `AppLogs.vue` nor `Troubleshoting.vue` seem to be implemented as modals, unlike their container namely `UserSettingsModal.vue`.

### Bounty

$30 bounty for a clean solution to this (paid in cryptocurrency).

**Comment by taoeffect** [comment]
Adding a $30 bounty for closing this issue for non-contractors (meaning, if you don't have a development contract with okTurtles, and you'd like to close this issue, you can work on it, and if we accept your PR, you'll receive the bounty).

Anyone else can add to the bounty too if they'd like by following these simple steps:

1. Donate the amount you'd like to dedicate to this issue [to the okTurtles Foundation](https://okturtles.org/donate/).
2. Make a comment here (or privately to us via Gitter or Slack) the same day letting us know you'd like your donation to be used for a bounty to close an issue, and which issue that is.
