### ISSUE TITLE
Fix all console errors (e.g. Navigation Duplicated errors) [$125 bounty]

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1079]
### Problem

In trying to upgrade Cypress, @snowteamer noticed in #1078, that NavigationDuplicated errors were preventing the tests from passing.

### Solution

Find and fix all of these errors. They're visible in the console during many of the tests.

See also previous related issue: #686

### Bounty

$125 bounty for a clean solution to this (paid in cryptocurrency).

**Comment by ArkaprabhaChakraborty** [comment]
Hi i want to work on this issue. Could you please provide me with some more details?

**Comment by taoeffect** [comment]
Hi @ArkaprabhaChakraborty, what sort of details are you looking for?

If you're wondering how to run the program locally, there are two ways of doing it: manually using `grunt dev`, and through the Cypress tests. Both ways are documented on our README:

- https://github.com/okTurtles/group-income-simple#basic-workflow

**Comment by Silver-IT** [comment]
Actually, this `NavigationDuplicated` error occurs when the same URL is requested to be rendered.
I can see that this `NavigationDuplicated` error occurs when we log out and also have found the code which makes this error.
`frontend/views/components/tabs/TabWrapper.vue -> beforeDestroy() -> this.$router.push`
I have created `logExceptNavigationDuplicated` function which @taoeffect mentioned in [this ticket](https://github.com/okTurtles/group-income-simple/issues/686) and used to handle errors.
