### ISSUE TITLE
Safari bug SVGs

### ISSUE THREAD

**Issue by Anna-Kaschel** [okTurtles/group-income#1080]
Hi everyone,

My github website has one Safari bug since the last Safari update. The SVGs in the footer do not align. When you open the website in Firefox and Google Chrome you will see how it is supposed to look. Do you have any idea how to solve this bug?

This is my site:
[ @taoeffect edits: possibly SEO link-spam removed ]

You can inspect the code in the footer here:
[ @taoeffect edits: possibly SEO link-spam removed ]

<img width="815" alt="Screen Shot 2021-07-04 at 4 15 07 PM" src="https://user-images.githubusercontent.com/79549801/124398303-08e75f80-dce3-11eb-98a5-181a19784e70.png">
<img width="828" alt="Screen Shot 2021-07-04 at 4 14 56 PM" src="https://user-images.githubusercontent.com/79549801/124398304-08e75f80-dce3-11eb-875a-b3fccdb5dc61.png">

Thank you for your help!
Anna

**Comment by taoeffect** [comment]
Hi Anna, this has nothing to do with our project. Please open only project related issues or we'll have to report and block your user account.

**Comment by Anna-Kaschel** [comment]
Hi Greg, I am sorry. I was not aware I was posting the question in your thread. No need to threaten to block me from Github.

**Comment by taoeffect** [comment]
We've had problems with spammers before, and this seemed like it might be spam. 🤷
