### ISSUE TITLE
Error in Cypress tests: Cannot read property 'incomeDetailsType' of undefined

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1081]
### Problem

Periodically (perhaps not on every run) the following error will appear in `master` in the Cypress console when running the `group-contributions.spec.js` tests:

```
captureLogs.js:157 uncaught Vue error in render: TypeError: Cannot read property 'incomeDetailsType' of undefined
    at Proxy.__vue_render__$2 (Contributions.vue:3)
    at VueComponent.Vue._render (vue.esm.js:3557)
    at VueComponent.updateComponent (vue.esm.js:4075)
    at Watcher.get (vue.esm.js:4488)
    at Watcher.run (vue.esm.js:4563)
    at flushSchedulerQueue (vue.esm.js:4319)
    at Array.<anonymous> (vue.esm.js:1989)
    at flushCallbacks (vue.esm.js:1915)
```

We've tracked this bug down to access of `ourGroupProfile` within `Contributions.vue` during specific moments when that returns undefined because this getter in `group.js` is allowed to return undefined and we do not check for that:

```js
    groupProfile (state, getters) {
      return username => {
        const profiles = getters.currentGroupState.profiles
        return profiles && profiles[username]
      }
    },
```

### Solution

There are two solutions to this bug. One is to make `groupProfile` return an empty object for a non-existent profile, e.g. something like this:

```js
    groupProfile (state, getters) {
      return username => {
        const profiles = getters.currentGroupState.profiles
        return profiles && profiles[username] || {}
      }
    },
```

However, that's not super clean. It makes sense to return undefined for a profile that doesn't exist. So perhaps a better solution is to handle this undefined case in `Contributions.vue` somehow.

There are several unchecked accesses of `ourGroupProfile` in `Contributions.vue`:

- Line 5: `add-income-details-widget(v-if='!ourGroupProfile.incomeDetailsType')`
- Line 181: `const amount = this.ourGroupProfile[this.ourGroupProfile.incomeDetailsType]`
- Line 186: `return this.ourGroupProfile.incomeDetailsType === 'incomeAmount'`

If we add checks for `undefined` here the error should go away.

**Comment by Silver-IT** [comment]
@taoeffect, I don't think this issue is happening at the moment. I guess it is already fixed by this line below in `beforeMount` lifecycle.
```
const profile = this.ourGroupProfile || {}
```
