### ISSUE TITLE
Fix regression in PR #1073 - Missing link for "updating your income details."

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1087]
### Problem

PR #1073 changed the way the `i18n` tag behaves and this broke a link in `Payments.vue` that's supposed to appear here over the words "income details":

<img width="710" alt="Screen Shot 2021-08-27 at 6 05 53 PM" src="https://user-images.githubusercontent.com/138706/131201383-4926302f-6bc7-42de-b0ea-b6bad69a7d29.png">

```pug
      i18n.has-text-1(
        @click='handleIncomeClick'
        :args='{ \
          r1: `<button class="link js-btnInvite" data-test="openIncomeDetailsModal">`, \
          r2: "</button>" \
        }'
      ) You can change this at any time by updating your {r1}income details{r2}.
```

### Solution

Find & fix!

**Comment by snowteamer** [comment]
Whitelisting the `<button>` tag in `translations.js` seems to fix the broken link, as well as using an anchor tag rather than a button tag in the `r1` and `r2` arguments above.
