### ISSUE TITLE
Darkmode color fixes

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1109]
### Problem

Some of the colors for Darkmode are a bit off.

#### Dashboard bar colors

<img width="624" alt="Screen Shot 2021-11-19 at 5 13 47 PM" src="https://user-images.githubusercontent.com/138706/142709055-16b1efd3-e690-474a-b184-2e0b3d6b84c6.png">

<img width="599" alt="Screen Shot 2021-11-19 at 5 14 28 PM" src="https://user-images.githubusercontent.com/138706/142709058-1613feb7-0c40-43d0-98b5-6cb0829f062b.png">

Something about these just doesn't look right.

#### Tooltip background

<img width="399" alt="Screen Shot 2021-11-19 at 4 44 31 PM" src="https://user-images.githubusercontent.com/138706/142709081-2ddbc588-aedb-4716-8f18-0f168b802fc7.png">

The text is barely readable, and I can't quickly find in Figma what this was supposed to be. Was it designed? If so what should it be? If not, can it please be designed?

### Solution

Address above with a new color scheme.

**Comment by leihla** [comment]
I've reviewed the color scheme for dark mode.

### Dashboard Colors
It seems that the bars are not showing the correct labels. 
In the screenshots @taoeffect uploaded there's 3 fields: "Total covered", "Total Given" and "Surplus" - where total covered and total given are the same value.  We should instead have what is in the design: "Total needed" "Total Given" and "Surplus".

<img width="821" alt="Screen Shot 2021-12-20 at 13 10 35" src="https://user-images.githubusercontent.com/158178/146772336-2a94110a-0c14-4674-8b57-1702ec7741db.png">
<img width="839" alt="Screen Shot 2021-12-20 at 13 10 42" src="https://user-images.githubusercontent.com/158178/146772341-71e5e8d4-da37-406f-ad96-ce94c3ddf7bc.png">

In this scenario of only 3 fields, the colors to be used are the orange, blue and green that appear correctly. The salmon color should not appear.

Figma Reference: https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?node-id=3043%3A524
----

 

### Tooltips
<img width="455" alt="Screen Shot 2021-12-20 at 12 55 15" src="https://user-images.githubusercontent.com/158178/146770805-45b3f2b7-4e72-4b92-9d6b-8a64c16944dc.png">

- Margarida had designed a version of the tooltip that seems to be incorrectly implemented. [Left side]
Background-color: #E8E8E8 and text-color: #383C3E

- As an alternative we can keep a darker color for the background to stay in line with our banners styles [Right side]
Background-color: #4E5254 and text-color: #FFFFFF

Any preference, @taoeffect?

---

**Comment by leihla** [comment]
As per our talk, I've updated the red color for dark mode from a salmon, to more of an orange red.

Old Color:
<img width="852" alt="Screen Shot 2022-01-10 at 15 27 07" src="https://user-images.githubusercontent.com/158178/148792129-db12d245-1f21-400f-8ebc-11d0e8c014c5.png">

<img width="365" alt="Screen Shot 2022-01-10 at 15 26 34" src="https://user-images.githubusercontent.com/158178/148792124-a72646f0-865c-4485-82fc-4ac73487290f.png">

New color:
<img width="846" alt="Screen Shot 2022-01-10 at 15 26 40" src="https://user-images.githubusercontent.com/158178/148792126-9d50a1d7-eeb2-4327-be34-f44db94eb991.png">

<img width="373" alt="Screen Shot 2022-01-10 at 15 26 11" src="https://user-images.githubusercontent.com/158178/148792118-93194a36-2221-434f-bd2d-1a54b7233d2d.png">

This color substitutes the DT Danger color and is #FF4B40
