### ISSUE TITLE
Find out why cypress test case breakes

### ISSUE THREAD

**Issue by Silver-IT** [okTurtles/group-income#1111]
### Problem

The cypress test case *`test/cypress/integration/group-paying.spec.js`* breaks. Seems like an incorrect index to select user.

### Solution

Find out the reason and fix so that it won't make error again!

**Comment by taoeffect** [comment]
@Silver-IT Can you give more background about this? Is this related to #1048? Because #1048 is clear that there's a problem that only happens on some occasions, which doesn't indicate that a test case is broken, but that something else is broken. All of our Cypress tests, including the ones in `group-paying.spec.js`, are passing.

**Comment by Silver-IT** [comment]
@taoeffect, As you can see the following two screenshots, the workflow of this test case is to select `user3-` among the `payList`. Even though `user3-` is the first item of the `payList`, cypress is going to select `user3-` with the index 1.

![image](https://user-images.githubusercontent.com/57976479/143189896-85efd93c-bf75-4a99-a2a7-0c3e29cbc921.png)

**Comment by Silver-IT** [comment]
Oh, something weird. On my local, this index needs to be 0. And also in terms of logic, that index needs to be 0 in my opinion.
I made a PR and checked the Travis test, and I saw that the test case failed with index 0 and succeeded with index 1.
I can not understand why...
So I just converted the PR to draft.

**Comment by taoeffect** [comment]
@Silver-IT I replied: https://github.com/okTurtles/group-income-simple/pull/1112/commits/79ae9d0e0bd122fc4c2b7b2e5cfb9646414796c6#r756464905

**Comment by taoeffect** [comment]
I'm gonna close this for now because AFAICT the index is correct, but if you'd like to re-open it feel free!
