### ISSUE TITLE
Ask users whether they want to change their income details when the mincome changes

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1125]
### Problem

Related to #952 - this issue addresses the problem of what needs to be done when the mincome changes and the user is pledging.

At the moment we don't prompt the user to do anything, and this really isn't the right answer because the user set their mincome in the first place based on a question, which is whether or not they made less than the mincome (whatever it was originally).

So when a proposal passes to increase the mincome, their answer to that question might change too.

### Solution

Prompt the user a Yes/No question when a mincome proposal passes and ask them:

> **The mincome has changed to $X.
> 
> **Do you make at least $X per month?**
>
> Buttons: No / Yes

If they click "No", open the modal for the income details.

Two issues need to be closed to do this:

- #1124 - Emitting a notification in the `sideEffect` of `proposalVote` action
- #1126  The design and implementation of a non-dismissable prompt to ask the user a question

**Comment by taoeffect** [comment]
Closing this to keep everything consolidated to existing issue #952, and referencing this issue from there.

**Comment by taoeffect** [comment]
Actually - re-opening since the other issue is a discussion issue, and this is an issue specifically for implementing one of the bullet points.

**Comment by SebinSong** [comment]
@taoeffect 
Thanks for helping with debugging the issue with `chelonia.js` and it did fix the issue I had.
Now that we've decided to work not only for pledging member's case but also for a receiving member, I've got another question here.
What should be the question in the prompt pop-up for a receiving member(who just have gotten switched to a pledger with 0 contribution)?
Do you think we can just use the same message up in the description which is below?

> **Do you make at least $X per month?**
>
> Buttons: No / Yes

The reason I got wondering was that, they are automatically switched to a pledger based on the assumption that their monthly income is over the updated mincome and thought asking this question afterwards kind of doesn't make sense.
what is your opinion?
Thanks.

**Comment by taoeffect** [comment]
Great question!

How about:

> **Automatically switched to pledging $0**
> 
> You now make more than the mincome. Would you like to increase your pledge?
> 
> Buttons: Yes / No

**Comment by SebinSong** [comment]
@taoeffect sounds good. will update the PR with them.
