### ISSUE TITLE
Enhance gi.notifications domain to make notifications more visible [$80 bounty]

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1128]
### Problem

The fact that there's an open proposal isn't advertised very well, and this can lead to stagnant proposals and a worse user experience.

### Solution

Enhance the notifications API (see the `gi.notifications` domain) so that it:

- Add an unread indicator to the browser tab. Research the best way(s) to do this. Feel free to post ideas below.
- Post an OS notification via the browser (https://developer.mozilla.org/en-US/docs/Web/API/notification ?)
- Add a red dot to the group icon in the groups sidebar when you're in multiple groups to show that a group has an active proposal pending. This involves closing  #1129

### Bounty

$40 bounty for a clean solution to this (paid in cryptocurrency).

**Comment by taoeffect** [comment]
*Note: edited the issue title & added a bounty

**Comment by Silver-IT** [comment]
> Add an unread indicator to the browser tab. Research the best way(s) to do this. Feel free to post ideas below.

To do this, we can use [favico.js](https://www.npmjs.com/package/favico.js).
I have already tried in a brief way and it works awesome.

**Comment by taoeffect** [comment]
@Silver-IT sounds good, that looks like an OK dependency to add. It has no additional dependencies of its own. 👍
