### ISSUE TITLE
Discussion: should we store usernames as hashes?

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1135]
### Problem

It's unclear whether or not this is a problem, and that's why I'm opening this issue as a discussion to hear people's thoughts.

The question at hand is whether or not the usernames should be stored in files as hashes (as everything else), or whether we should keep the `name=[username]` prefix.

Some tradeoffs:

Pros:

- Adds by default a small boost in privacy (security theater though? see cons)

Cons:

- Sysadmin would have little idea how many users are using their server - can figure it out, but is a pain
- This can decrease incentives for people to run the server, if by default it's difficult for them to know basic stats like how many users are using their server or how many groups are being hosted
- Since it makes no sense to encrypt usernames, it's ultimately security theater, and trivial for a server operator with some basic knowledge of JavaScript to modify the code to save the usernames.

### Solution

There is no solution at this time. This is just a discussion, and an open issue for people to be aware of the tradeoffs we're making for transparency's sake.

**Comment by Silver-IT** [comment]
Why should sysadmin count the number of users easily?
Is it only to make it easy to get an idea of a number of users and groups, how they are growing, ...?

In order to hide usernames, I think we use `encryption` and `decryption` for the usernames only?
So it could be `name=[encrypt(username)]`. As far as I know, `bcrypt` encryption returns a different value each time from the same input.
Regarding the encryption method, I think the simpler, the better.
What about using XOR encryption/decryption with the predefined key?

**Comment by taoeffect** [comment]
@Silver-IT bcrypt is hashing, not encryption.

We can't encrypt the usernames because we'd like to support the ability for users to directly message each other even when they're not in the same group, and in order to support that feature the names must be unencrypted.

I don't think it's much of an issue ultimately because usernames are things people can invent, and so they aren't identifiers of individuals.

**Comment by taoeffect** [comment]
Yeah, the more I think about this the more convinced I get that this isn't a real issue, since there isn't much of a privacy concern for two reasons:

1. Usernames can be invented - they don't strongly identify an individual.
2. There is no way to protect against the server operator from modifying the code to store them anyway.

So I think I'll close this issue since there is no clear problem that can be solved with the features that we want implemented, but we can continue discussing it if people want.
