### ISSUE TITLE
Prevent CodeQL from blocking normal merging

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1136]
### Problem

We use Github's CodeQL action thingy as part of our PR check pipeline on GH.

However, it's recently started [being super annoying](https://github.com/okTurtles/group-income-simple/runs/4515023404), causing our PRs to have a red ❌ on them when they should be a green ✅.

Although there are many issues with this "code quality" check (like being broken when you tell it to dismiss a warning), the major one for this issue is that it is actually breaking PRs over code that has nothing to do with the PR! In [this case](https://github.com/okTurtles/group-income-simple/runs/4515023404) it was checking files in `historical/`.

### Solution

Find out if there's a way to stop this behavior. If not, let us know, and we'll disable it.

**Comment by snowteamer** [comment]
These links seem promising:
- https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#specifying-directories-to-scan
- https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#defining-the-severities-causing-pull-request-check-failure

**Comment by taoeffect** [comment]
I think we just ended up getting rid of it. TBH it never helped with anything.
