### ISSUE TITLE
TypeValidator objectMaybeOf makes error with boolean type

### ISSUE THREAD

**Issue by Silver-IT** [okTurtles/group-income#1137]
### Problem

`boolean` TypeValidator which is defined in `frontend/utils/flowTyper.js` returns `TypeError` when the data has boolean-typed false value. That's because it throws TypeError when `!validations[key](data[key])` is falsy value, and `boolean` TypeValidator returns `false` as boolean which is also falsy value.

The followings are the definition of the `boolean` and `objectMaybeOf` TypeValidators.
```
export const boolean = (
  function boolean (value, _scope = '') {
    if (isEmpty(value)) return false
    if (isBoolean(value)) return value
    throw validatorError(boolean, value, _scope)
  }
  : TypeValidator<boolean>
)
```

```
export function objectMaybeOf (validations: Object): Object {
  return function (data: any) {
    object(data)
    for (const key in data) {
      if (validations[key]) {
        if (!validations[key](data[key])) {
          throw new TypeError(`${key} has bad value: ${data[key]}`)
        }
      }
    }
    return data
  }
}
```

### Solution

I recommend to take the `objectOf` as a reference, it works fine with `boolean` TypeValidator.

**Comment by taoeffect** [comment]
@Silver-IT I think this bug was fixed in a recent PR I sent. Could you verify?

**Comment by Silver-IT** [comment]
> @Silver-IT I think this bug was fixed in a recent PR I sent. Could you verify?

Yeah, It is fixed. Good work, @taoeffect

**Comment by taoeffect** [comment]
OK in that case closing this issue.
