### ISSUE TITLE
UserSetting Form submit makes error when press Enter key

### ISSUE THREAD

**Issue by Silver-IT** [okTurtles/group-income#1147]
### Problem

In `UserSetting` page, just focus on the `DisplayName` input field.
Press Enter and check the console. There will be an error occurred regarding the form submit.
![image](https://user-images.githubusercontent.com/57976479/150070364-5a3c4be3-404e-4402-9a35-364424b77829.png)

### Solution
Need to check the code and can use `stopPropagation` or `preventDefault` depending on how the code is implemented.

**Comment by taoeffect** [comment]
This looks like a duplicate of #1155.
