### ISSUE TITLE
Localize/Internationalize user-facing strings from the beginning.

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#116]
## Problem

People speak different languages.
## Solution

Pick a library/format that works well with localization software and make all the user-facing strings ready for localization from the very beginning. It's much harder to do this later on.

**Comment by vijayee** [comment]
So it seems key/value lookups based on static markup files is the prevailing method. The library http://i18next.com/ looks very promising at this approach as an already implemented framework with nice feature sets

**Comment by taoeffect** [comment]
@vijayee Go for it! 😄

**Comment by vijayee** [comment]
#134 is now ready to be reviewed

**Comment by vijayee** [comment]
Completed in #134
