### ISSUE TITLE
Contract sync error is there in group contract

### ISSUE THREAD

**Issue by Silver-IT** [okTurtles/group-income#1176]
### Problem

Let's think about the following workflow

1. user1 creates a group
2. user2 joins the group and then user3 joins too with the same invitation link
3. user2 proposes to remove user3 and user1 approves. IMPORTANT thing is that user3 needs to be offline at this moment meaning that user3 doesn't sync the contract at this moment.
4. user2 leaves the group by himself
5. user3 tries to login and join with the invitation link but get message of `Oh no! This invite is not valid` and fails to join group.

![image](https://user-images.githubusercontent.com/57976479/158510740-3ae2acc8-9176-4761-b1c4-760921bc75e6.png)

### Solution

I guess there is a mistake in syncing group contract inside `gi.actions/group/join` action.
Need to track the contract actions backwards one by one and find the reason out.

**Comment by taoeffect** [comment]
@Silver-IT I'm not understanding the bug... some questions:

1. Which invite link was used? A special invite link for that user, or the generic invite link that's created when the group is first created?
2. Doesn't it make sense for user3 to not be able to join since they were removed?

**Comment by Silver-IT** [comment]
1. Generic invite link, which is created automatically when the group is created.
2. The problem is that we got error in console. And that's the reason why user3 can not join the group. It seems like it's the correct workflow that user3 can not be joined if he was kicked by proposal. But if then, there needs to be no error in console.

**Comment by taoeffect** [comment]
> It seems like it's the correct workflow that user3 can not be joined if he was kicked by proposal. But if then, there needs to be no error in console.

OK, what's the error in the console? Can you copy/paste it and update the issue with it?

BTW, just fyi, truly removing members hasn't been implemented yet because we need the E2E protocol for that.

**Comment by Silver-IT** [comment]
Yeah. That's the future thing.
The current thing is to fix this error and remove all the errors in console.

![image](https://user-images.githubusercontent.com/57976479/158513780-1e7b6a51-8c0b-420c-8c24-06bbc6522378.png)
This image shows the error when user3 reopen the browser. User3 closed the browser before user1 approves the user2's proposal to remove user3.

![image](https://user-images.githubusercontent.com/57976479/158514179-a24cea02-30fd-4639-841f-67cab9ad4a6f.png)

The second image shows the errors user3 got when he tries to log in again with the generic invitation link.
