### ISSUE TITLE
Pubsub doesn't reconnect after server has been restarted [$50 bounty]

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1183]
### Problem

If the server has been restarted (say due to an update), the client doesn't reconnect once it's back up.

### Solution

Track down the bug and fix it.

EDIT: based on a convo on Slack w/@snowteamer, it looks like this is an issue that can occur when the client gives up reconnecting.

There are two issues here:

1. We should keep trying to reconnect indefinitely.
2. In the case where the setting for pubsub tells it to give up after some period, it should update the banner to reflect that we've given up and the user should try refreshing the page.

<img width="1056" alt="Screen Shot 2022-03-22 at 6 06 07 PM" src="https://user-images.githubusercontent.com/138706/159603776-9ce7a343-69e6-4339-86f8-6bc5fdc2669c.png">

### Bounty

Issue is open to contractors or non-contractors. Non-contractors can get paid via bounty. We're posting a bounty of $50 for a clean solution to this issue.

**Comment by snowteamer** [comment]
What reconnection failure message would be best?
- `We could not connect to the server. Refreshing the page might help.`
- `We could not connect to the server. You might want to refresh the page.`
- `We could not connect to the server. Please try refreshing the page.`
- `We could not connect to the server. Please refresh the page.`
- something else?

And should it rather start with `Could not...` or `We could not...` ? I'd say the latter, but I'm not sure.

**Comment by dotmacro** [comment]
`We could not connect to the server. Please try refreshing the page.` sounds best to me.

Error/alert messages should be consistent, so we should use "we" language & complete sentences in all of them, or none.
