### ISSUE TITLE
Chat jumps from top to bottom

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1216]
### Problem

When the chat is selected, instead of immediately starting at the bottom, it "jumps" to the bottom:

![chat-issue mov](https://user-images.githubusercontent.com/138706/164611883-f4f5d831-d32d-4819-9234-f5db7b02902f.gif)

### Solution

Ideally, the behavior is similar to Slack, each chat channel remembers its scroll position and goes to it, unless there's a new message, according to the [figma designs](https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?node-id=14747%3A184), it should try to place the oldest newest message as close to the top of the chat view as possible, using a `----------- new ------------` separator (see Figma).

**Comment by taoeffect** [comment]
*edited the Solution

**Comment by Silver-IT** [comment]
Correct. We should save the scroll position for each channel...

**Comment by Silver-IT** [comment]
- Saved scroll position in the Pull Request #1279 .
- Implement Unread messages in the Pull Request #1292
