### ISSUE TITLE
debounce the banner on contract sync

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1220]
### Problem

Sometimes the page kinda "jumps" because the contract sync is happening but it happens too fast.

### Solution

The banner should appear if the contract sync is taking more than 2 seconds to finish, and should remain open for at least 2 seconds if it appears.

Use the `debounce` function from `giLodash.js` to accomplish this.

**Comment by snowteamer** [comment]
What about other global banner events, for example when the app goes disconnected/reconnected?

Should the same minimal delays be enforced in such case? Or maybe slightly different delays according to the given event type?
