### ISSUE TITLE
Force users to enter their payment details if they indicate they're receiving [$25 bounty]

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1225]
### Problem

Some users will indicate they have a financial need but will forget to entire their payment details. This makes it difficult for other users to pay them with manual mode because it increases coordination costs.

### Solution

The income details form should error if no payment details are entered.

### Bounty

$25 bounty for a clean solution to this (paid in cryptocurrency).

**Comment by SebinSong** [comment]
Hi @taoeffect 

Got a question regarding details of the task.

![image](https://user-images.githubusercontent.com/17641213/179682073-50a64a41-e5f7-46be-bece-5ee1c005c28e.png)



**Q1.**

> Some users will **indicate they have a financial need** but will forget to entire their payment details. 

Does clicking on this "No, I don't" radio option is how the user indicates intending to be a receiver of fund?

**Q2.** If the answer of Q1 is yes, are we aiming to make the 'payment info' field be mandatory in this task?

**Comment by taoeffect** [comment]
> Does clicking on this "No, I don't" radio option is how the user indicates intending to be a receiver of fund?

Yes.

> Q2. If the answer of Q1 is yes, are we aiming to make the 'payment info' field be mandatory in this task?

Yep! So the `(optional)` label needs to be removed.

**Comment by SebinSong** [comment]
@taoeffect 
Thanks for clarification.

I've got a follow-up question.

![image](https://user-images.githubusercontent.com/17641213/179697844-126664a0-271f-4f47-962a-8a821aa22c96.png)

Does showing a banner saying "Entering payment details is required." sound like a good idea?
Or is there a better validation sentence you would suggest?

**Comment by taoeffect** [comment]
@SebinSong Yes, that works.

I recommend the following error message: "Payment details required. Please let people know how they can pay you."
