### ISSUE TITLE
"Duplicate keys detected:" in ChatMain.vue

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1227]
### Problem

I'm not sure if this happens in `master`, but it definitely happens in many of the Cypress tests in my PR (#1224).

An error will flash in the console during the tests. It won't prevent the tests from passing, but it clearly indicates something is wrong:

<img width="971" alt="Screen Shot 2022-04-24 at 3 53 09 PM" src="https://user-images.githubusercontent.com/138706/165000158-12d0a30b-03fa-4571-b24f-b6312a7c64bb.png">

### Solution

Based on the error message, something is affected by `setMessageEventListener`, possibly a `v-for` loop. I am guessing it might be `:key='message.id'`.

**Comment by Silver-IT** [comment]
I can see that it happens only with options `{ BypassUI: true }`.
