### ISSUE TITLE
Proposals generated by automated bans should make it clear they are client-generated [$20]

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1242]
### Problem

When the automated ban system generates a proposal to remove a member, it appears too much like the user is the one that generated it:

<img width="814" alt="Screen Shot 2022-04-28 at 11 46 47 AM" src="https://user-images.githubusercontent.com/138706/165831037-0cc32eb8-3d85-43c3-a593-e8bfd2e49b72.png">

### Solution

Instead of "{Username} is proposing", change the text to read: "Automated ban sent by {username}'s client:"

Proposals that are automated will need to marked / identified as such so that the UI can easily identify them. Do this by editing `'gi.actions/group/autobanUser'` to:

- add an attribute `automated: true` to `proposalData` when creating the proposal
- add the same attribute to `passPayload` to help us debug failed cases like the one in the screenshot above
- update the group.js contract to accept these parameters via the validations if necessary (will likely be necessary)
- update the proposal .vue UI

### Bounty

$20 bounty for a clean solution to this (paid in cryptocurrency).

**Comment by SebinSong** [comment]
@taoeffect

created a PR [here](https://github.com/okTurtles/group-income/pull/1394) for closing this issue.
besides implementing the requirements for `group.js` contract in the issue description, UI update was done based on this comment by Lehila [here](https://github.com/okTurtles/group-income/issues/1284#issuecomment-1155080107) in another relevant ticket. 

cheers,

**Comment by taoeffect** [comment]
I believe this was closed by #1365 - again sorry for my oversight!
