### ISSUE TITLE
Emit notifications for all of the various important situations [$40 bounty]

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1247]
### Problem

Currently we do not emit notifications when important events happen in the group (e.g. members join/leave, proposals created, passed, rejected, etc.)

### Solution

For all of the features we currently support that notifications can be emitted for, use the table in #663 as guidance and emit them.

See also related sub-issue #1124. Closing this will close that issue too.

### Bounty

$40 bounty for a clean solution to this (paid in cryptocurrency).

**Comment by SebinSong** [comment]
@taoeffect I'm currently working on this issue and have worked on **'Member added'**, **'Member removed'** and **'Member left'** from this table below([original source](https://github.com/okTurtles/group-income/issues/663#issue-492988756)).

| Event | Copy |Links to |
| ------------- | ------------- | ------------- |
| Member added | _Your group has a new member! Say hi to [new_member_name]!_  | General group chat channel | 
| Members added<sup>[1]</sup> | _Your group has [#] new members! Say hi!_  | General group chat channel | 
| Member removed (via proposal)| _[member_name] was kicked out of the group. Contributions were updated accordingly_  | Contributions page | 
| Members removed (via proposal)<sup>[1]</sup> | _[member_name] and [#] others were kicked out of the group. Contributions were updated accordingly_  | Contributions page | 
| Member left (by their initiative)| _[member_name] has left your group. Contributions were updated accordingly_  | Contributions page | 
| Members left (by their initiative)<sup>[1]</sup> | _[member_name] and [#] others left your group. Contributions were updated accordingly_  | Contributions page | 
| Income details are 6 months old or more | _You haven't updated your income details in [amout_of_months]. Would you like to review them now?_ | Income details modal | 
| 1 week to send monthly contributions | _Don't forget to send your [month_name] contributions!_ | Contributions page | 
| Pending payment confirmations<sup>[1]</sup> | _You have [#] pending payment confirmations._ | Pay group page | 
| New proposal open | _[member_name] wants to [proposal_type_description]<sup>[2]</sup>. Vote now!_ | Dashboard proposals (anchor link) | 
| Proposal closed verdict | _[member_name]'s proposal to [proposal_type_description] was approved / not approved by your group._ | Archived proposals | 


But as the works rather deeply touch the group contract, I thought it needs your look&opinion regarding how it needs to be implemented.
Do you think it's great idea for me to push a PR for these three items and get them reviewed first and then work on the rest itemsbased on the PR review of these? (it's going to help clarifying how/where to implement them within the other contract files)

**Comment by taoeffect** [comment]
@SebinSong

>  Do you think it's great idea for me to push a PR for these three items and get them reviewed first and then work on the rest itemsbased on the PR review of these? (it's going to help clarifying how/where to implement them within the other contract files)

Sure! That sounds like a good idea. 👍

**Comment by taoeffect** [comment]
@SebinSong has everything in this issue been done?

**Comment by SebinSong** [comment]
@taoeffect 

_- Income details are 6 months old or more_
_- 1 week to send monthly contributions_
_- Pending payment confirmations_

in the above table are the items that are not implemented yet. I can pick these ones up as my TODOs next week.

**Comment by SebinSong** [comment]
Hi @taoeffect,
need a help with clarifying the requirements for below two:

_**1.** Pending payment confirmations (You have [#] pending payment confirmations.)
**2.** 1 week to send monthly contributions (Don't forget to send your [month_name] contributions!)_


**Q1.** Does **1.** here means that, as soon as the group goes into the new distribution period, a notification is sent to every pledging members that lets them know how many payment items to make they have?

**Q2.** Does **2.** here means that, if it has been over 1 week since the distribution period changed and the pledging members have any payment item they haven't completed yet, we send this notification?

Thanks,

**Comment by taoeffect** [comment]
> Q1. Does 1. here means that, as soon as the group goes into the new distribution period, a notification is sent to every pledging members that lets them know how many payment items to make they have?

That's what seems to be implied, but IMO we shouldn't do this because if users change their income details that can change the number of payment TODOs. So instead we could just let them know it's the start of a new distribution period.

> Q2. Does 2. here means that, if it has been over 1 week since the distribution period changed and the pledging members have any payment item they haven't completed yet, we send this notification?

No I think it means there's 1 week left before the next distribution period starts. So if they have any outstanding TODOs to be done, and there's only 1 week left to do them, it can remind them to complete it.

**Comment by SebinSong** [comment]
@taoeffect  Thanks for the clarification. here are some follow-up questions.

**Q1.**
>  instead we could just let them know it's the start of a new distribution period.

Does _**'A new distribution period has started. Would you like to check your payment TODOs?'**_ sounds good as the notification copy?

**Q2.** For _'1 week to send monthly contributions'_ notification, The table above suggests _'Don't forget to send your [month_name] contributions!'_ as the notification copy. But how do we decide which month to put in **[month_name]** here?
Let's say, the distribution period is **3th, Feb, 2023**. Then it easily makes sense to put Feburary there. But what if the distribution period is something like **22th, Feb, 2023**, which is closer to the end of the month than it is to the begining. Should we still put Feburary in this case too?

Thanks,

**Comment by taoeffect** [comment]
> Does 'A new distribution period has started. Would you like to check your payment TODOs?' sounds good as the notification copy?

I like the first part. I think the 2nd sentence could be modified though to:

- For pledgers: *A new distribution period has started. Please check Payment TODOs* (when clicked, takes them to the Payment TODOs page)
- For receivers: *A new distribution period has started. Please update your income details if they've changed.* (when clicked, opens the income details modal)

> Q2. For '1 week to send monthly contributions' notification, The table above suggests 'Don't forget to send your [month_name] contributions!' as the notification copy. But how do we decide which month to put in [month_name] here?
Let's say, the distribution period is 3th, Feb, 2023. Then it easily makes sense to put Feburary there. But what if the distribution period is something like 22th, Feb, 2023, which is closer to the end of the month than it is to the begining. Should we still put Feburary in this case too?

Let's not make things hard on ourselves. Nobody will hate us if we just write: *1 week left before the distribution period ends - don't forget to send payments!* (and only send this to pledgers who still have open TODOs)
