### ISSUE TITLE
Do not allow duplicate chatroom names

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1254]
### Problem

Currently duplicate channel names are allowed.

### Solution

Prevent channels with a duplicate name from being created. Do a check in two places:

1. A check in the chat creation modal using vuelidate if possible (so that the field is immediately marked red)
2. A check in either the validation or the process function the chatroom creation message

This is similar to doing logic checks on "both the frontend and the backend", except for us the "backend" is the contracts themselves.

**Comment by Silver-IT** [comment]
> A check in either the validation or the process function the chatroom creation message

Should we implement this validation in chatroom contract validate function?
I am not sure this is good way but I want to check the duplication in the `gi.actions/group/addChatRoom`.
In this function, we call two functions; `gi.actions/chatroom/create` and `gi.contracts/group/addChatRoom`.
As to check duplication, it needs to access the `getChatRooms` getter of the current group, I think `gi.actions/group/addChatRoom` is the best place to validate duplication.
