### ISSUE TITLE
Click link to copy doesn't work in Safari on Desktop

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1255]
### Problem

A recent PR messed up the behavior of Safari on Desktop when clicking to copy a link.

It should should display a tooltip saying the link was copied but instead a share menu appears:

<img width="683" alt="Screen Shot 2022-04-30 at 1 23 18 PM" src="https://user-images.githubusercontent.com/138706/166121464-c6b6d27d-6636-4a28-93e5-a90064e1f25d.png">

### Solution

Fix, while not breaking Safari on Mobile, which should bring up the share menu.

/cc @abdulazizali77

**Comment by abdulazizali77** [comment]
@taoeffect this probably means that Safari has the Web Share API defined https://caniuse.com/?search=web%20share%20api
what should be investigated is if other browsers have 'Copy to clipboard' when the share menu comes up, i assume in terms of behaviour 'Share this link' should be inclusive of all methods including 'Copy to clipboard' and mail etc

**Comment by taoeffect** [comment]
Yeah that's a fair point. The share menu on iPhone does have a "copy" button available, but it's not available on most desktop browsers afaik. Should come up with some kind of consistent rule for this.

**Comment by abdulazizali77** [comment]
what does 'More...' in Safari show?

**Comment by abdulazizali77** [comment]
apparently seems like an issue on Safari, though i am unsure what the version is
https://discussions.apple.com/thread/252923714

**Comment by abdulazizali77** [comment]
![image](https://user-images.githubusercontent.com/23547158/166127764-c4cce26f-2044-40f8-95f0-a9ec9c477c7d.png)
Chrome

![image](https://user-images.githubusercontent.com/23547158/166127792-4f0dd420-dea4-4915-ab65-098d3eca48ea.png)
Edge

Consistent with the caniuse table, Firefox 80.0.1 doesnt have `navigator.share` hence copies to clipboard 

I guess one kludge would be to check if its Safari desktop and explicitly copy to clipboard. doesnt seem to be any immediately elegant/extensible/modular way to do that that doesnt involve a good degree of architecture.

**Comment by taoeffect** [comment]
Oddly enough it brings up the System Preferences, which actually *does* have a "Copy link" thing in it, that I had to move up to the top:

<img width="780" alt="Screen Shot 2022-04-30 at 6 12 02 PM" src="https://user-images.githubusercontent.com/138706/166127952-f6a34309-6dd3-4701-bddd-d0fceb163345.png">

But it still doesn't show up in the menu, even after relaunching Safari. Seems like a bug in macOS.

**Comment by abdulazizali77** [comment]
Can you share the MacOS and Safari versions?

**Comment by taoeffect** [comment]
macOS 12 (Monterey) with Safari 15.4, but I wouldn't use such specifics personally. I'd just create a function that checks specific user agents (e.g. "desktop safari" and any others where copy link makes more sense) and then use copy link for those.

**Comment by abdulazizali77** [comment]
more of basing those versions and testing higher or lower versions to recreate the issue
