### ISSUE TITLE
Renaming group during creation results in wrong default group icon [$20 bounty]

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1260]
### Problem

If you give your group a name in the Group Creation modal, go forward a step, go back and rename it to something else, then the icon that's generated doesn't get updated.

Here we see 2 "T"'s in the navbar instead of a "T" and a "Z":

<img width="508" alt="Screen Shot 2022-05-02 at 2 16 16 PM" src="https://user-images.githubusercontent.com/138706/166329212-1263c25d-d47d-4d77-966d-276ab4a8a160.png">

### Solution

Fix.

### Bounty

$20 bounty for a clean solution to this (paid in cryptocurrency).

**Comment by dotmacro** [comment]
Is this a duplicate of #1148 ?

**Comment by taoeffect** [comment]
Oops, you're right! Thanks @dotmacro!
