### ISSUE TITLE
Implement DMs using chatroom.js contract

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1277]
### Problem

DMs currently don't work.

### Solution

Implement DMs using the chatroom.js contract.

Replace the Mailbox contract with the Chatroom.js contract. In other words, the identity contract, instead of having a mailbox contract associated with it, should have a chatroom contract associated with it.

**Comment by Silver-IT** [comment]
My plan is to work on this issue after we implement enough features in the group contract.
- [x] Unread message
- [ ] Paste image from the clipboard
- [ ] URL detect from the messages and redirect when user clicks
- [x] Select username using `@`
- [x] Notification when there are any mentions using `@`; `@AlexJin`, `@here`, `@all` ...

**Comment by taoeffect** [comment]
>  Paste image from the clipboard

@Silver-IT This is low priority right now, so that can wait.

Also, I think it's safe for you to implement this before, because when my changes for #1214 are merged, upgrading contracts should work OK. And also, the live server group will be re-created as well after versioning is introduced.

**Comment by taoeffect** [comment]
Edited issue to add:

> Replace the Mailbox contract with the Chatroom.js contract. In other words, the identity contract, instead of having a mailbox contract associated with it, should have a chatroom contract associated with it.

**Comment by Silver-IT** [comment]
> Replace the Mailbox contract with the Chatroom.js contract. In other words, the identity contract, instead of having a mailbox contract associated with it, should have a chatroom contract associated with it.

Is this mean DM is not related to the group?
For example, DM is only unique for each workspace while in Discord DM is unique for each account.

So DM between User1 and User2 is unique no matter user1/user2 is currently in Group1 and Group2, ...
Is that correct?

**Comment by taoeffect** [comment]
Well, there is no relationship between groups and DMs, they are completely separate.

Each identity contract has a “mailbox” that others can write to. It is essentially a list of messages from various users.

`[{from: “u1”, msg: “hi”}, {from: “u2”, msg: “hello”, …]`

How we display these in the UI I think hasn’t been designed yet, but yes it should be outside of groups. Let’s discuss this on Slack in more detail.
