### ISSUE TITLE
Fix distribution algorithm - wrong value calculated for "Amount sent" total

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1283]
### Problem

In the live group, I think I adjusted my pledge upward from $50 to $100 and somehow actually ended up being told to pay more than I was supposed to:

<img width="271" alt="Screen Shot 2022-05-22 at 9 03 19 PM" src="https://user-images.githubusercontent.com/138706/169741157-c6f92a80-00fd-4300-b998-38c359d11b93.png">

### Solution

Figure out why this happened and fix.

**Comment by dotmacro** [comment]
In the live group, I recorded a $50 payment, which was 100% of my pledge. When the UI updated, my TODO list suddenly had a $10 payment to a different member. (Another example of a user being asked to pay more than they pledged.)

**Comment by taoeffect** [comment]
One immediate fundamental problem that I'm noticing (and it's not the same problem as the ones above), is that the "Amount sent" total value is based on the unadjusted distribution, which means that it's whatever you're pledging right now, and using this posthumous algorithm it should be the total you pledged at the start of the payment period. However, we aren't storing that information anywhere at the moment.
