### ISSUE TITLE
Design proposal for automated bans

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1284]
### Problem

Automated bans are system generated proposals to remove a member because their client might be broken / hacked. However, currently visually they look too much like a member consciously chose to ban someone (see #1242).

### Solution

Create a more visually distinct design for them so that users don't think they personally to ban someone, but that it's part of an automated system.

**Comment by leihla** [comment]
Update automated ban to new layout. 

### Old layout:
<img width="772" alt="Screenshot 2022-06-14 at 12 46 05" src="https://user-images.githubusercontent.com/158178/173569964-6f02f2d8-71cb-4f86-94ca-ba1148481454.png">

---

### New Layout:

<img width="785" alt="Screenshot 2022-06-14 at 12 47 57" src="https://user-images.githubusercontent.com/158178/173570279-8567940f-0138-4bf6-9c58-f685819b4086.png">

**Changes**:
- Show group avatar next to proposal icon
- Add [Automated] before proposal title
- Keep description as is

---
@taoeffect can you assign this issue to the correct person?

**Comment by taoeffect** [comment]
Closing in favor of #1304 and #1300.

**Comment by SebinSong** [comment]
@taoeffect 
I would love to pick up this issue if no one else is already looking into it. :)
where in the [Group Income 2.0 figma ](https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0)does this new design live in?

Also, could you help with describing the steps to take in the app to generate that 'automated ban proposal' UI?

cheers,
