### ISSUE TITLE
Need a design to show percentage of TODOs that were actually completed in Support History

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1286]
### Problem

The Support History widget currently shows how close the group is to reaching its mincome goal each month. It doesn't show how well the group did in actually completing the payments they were instructed to make.

### Solution

Design something in the Support History widget to show for each month the % of the total amount that should have been sent.

Could simply be a second row of bars.

**Comment by leihla** [comment]
This has been designed already https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?type=design&node-id=23342%3A251404&t=OYjm7ACensmK2Bix-1
