### ISSUE TITLE
Consolidate designs for new Notifications "Mark all as read" designs

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1289]
### Problem

1. There's no way to "mark all as read"
2. Leihla thinks we should also separate the counter from from the number of read messages, and have it be the count of notifications seen (I think?)

<img width="516" alt="Screen Shot 2022-05-31 at 1 21 22 PM" src="https://user-images.githubusercontent.com/138706/171277823-b45b6c42-3f45-4154-85ac-9838faf5b50f.png">

### Solution

Leihla, please see this thread and most recent comment there, copied here in case the Figma link breaks: https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN?node-id=4107:0#185708510

> leihla ok sounds good.
> 
> I think my preference is to combine the 1st and the 3rd. Having "Mark all as read" on the left, and having a dropdown in the top-right to access the notification settings too.
> 
> Could you please consolidate these, update the other designs, and create the relevant issue(s) for Pierre Schweiger ?

**Comment by leihla** [comment]
@taoeffect I've created 2 new options according to your feedback.  

- Option 4 keeps the settings link that already exists and adds the Mark all as read at the bottom
- Option 5 changes the settings link to a settings icon, which is more discrete (I prefer this option)

Regardless of the option the notification settings page is not implemented.

<img width="969" alt="Screenshot 2022-06-14 at 15 45 01" src="https://user-images.githubusercontent.com/158178/173606934-69c78e6c-5b87-4cdb-b936-de27d9b1fcbc.png">


which do you prefer?

**Comment by taoeffect** [comment]
@leihla - Let's go with Option 5. :)

Feel free to close this issue after Figma is cleaned up.

**Comment by leihla** [comment]
Updated page 12. Notifications on figma with "Mark as Read" and other option 5 modifications.

https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?node-id=4107%3A0
