### ISSUE TITLE
People joining the chat channel multiple times

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1296]
### Problem

On the live server, I see multiple join entries for both Leihla and Ricardo:

<img width="550" alt="Screen Shot 2022-06-05 at 12 27 50 PM" src="https://user-images.githubusercontent.com/138706/172067303-480fc44e-bee5-417b-9633-c3481375047a.png">

### Solution

Find out why this is happening and fix.

**Comment by Silver-IT** [comment]
Having tested on my side with the latest version #1299 of Pull Request, it doesn't happen even if user joins again after leaving group by himself or being kicked by proposal.
If this happens again in the live server after we merge Pull Request #1299, I should debug the events of live server.
Actually, I thought I've fixed this long time before. A bit weird...

**Comment by taoeffect** [comment]
@Silver-IT What about when users logs out and re-logs in on different devices?

**Comment by Silver-IT** [comment]
Actually, I missed this test case. Never thought about this. I will test this situation.

**Comment by Silver-IT** [comment]
Correct. This happens when the user tries to login in different devices...
