### ISSUE TITLE
Implement new proposals design

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1300]
### Problem

This issue piggybacks off of #1288 (design new proposals UI).

We've got the designs finished now thanks to @leihla's great work, and what remains is to implement them.

### Solution

Closing this issue involves implementing all of the new design changes that @leihla [mentioned](https://github.com/okTurtles/group-income/issues/1288#issuecomment-1155061508), **\_except\_:**

- The modal that appears for "See All Proposals". I think this still needs to be designed (#1302). There will be a separate implementation issue for this once it's designed.
- The modal that appears when "Generic Proposal" is clicked. See separate issue #1303 for this.
- Archiving of proposals. This should be done in a separate PR, see issue #925 for that.
- New automated ban designs. That should be saved for a separate PR. See issue #1304 for that.
- Implement dropdown for new proposals UI. See #1362

**Comment by leihla** [comment]
Just a quick note to say that proposals in the dashboard should show most recent at the top and older at the bottom. Currently is the other way around.

**Comment by taoeffect** [comment]
Closed by @pieer in #1325
