### ISSUE TITLE
Design modal for "See All Proposals"

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1302]
### Problem

I could be mistaken, but I wasn't able to find the designs for the "See All Proposals" modal that's supposed to appear when that button is clicked.

### Solution

Create a design for that modal.

**Comment by leihla** [comment]
@taoeffect this was already designed and i believe implemented as well. 

https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?type=design&node-id=1988%3A1261&t=OYjm7ACensmK2Bix-1
