### ISSUE TITLE
Implement new design for automated ban proposals.

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1304]
### Problem

See the problem description in the related design issue #1284.

### Solution

Implement the new design #1284.

This issue depends on #1300 being closed.

**Comment by SebinSong** [comment]
@taoeffect
I would love to pick up this issue if no one else is already looking into it. :)
where in the [Group Income 2.0 figma ](https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0)does this new design live in?

Also, could you help with describing the steps to take in the app to generate that 'automated ban proposal' UI?

cheers,

**Comment by taoeffect** [comment]
Awesome, so based on Slack convo it sounds like you'll take on #1312 first, and then perhaps this issue, so I'll assign it to you as well.

**Comment by dotmacro** [comment]
> where in the [Group Income 2.0 figma ](https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0)does this new design live in?

The new designs are [here on Figma](https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?node-id=23053%3A270467)

**Comment by SebinSong** [comment]
@dotmacro Thanks Andrea! :)

**Comment by SebinSong** [comment]
- the original context for the task: https://github.com/okTurtles/group-income/issues/1242
- target design on the figma: https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?node-id=3043%3A524

**Comment by SebinSong** [comment]
@taoeffect 
it looks like [this PR](https://github.com/okTurtles/group-income/pull/1325) involves large amount of potential merge conflicts with this task for `ProposalItem.vue` and `ProposalBox.vue` components.
Do you think it's better for me to wait until that PR is merged?
Or if that PR is likely to be merged soon with no much change requests, I can maybe merge Pierre's PR(feature branch) into mine now and start working on top of his current work progress.

what's your thoughts?

**Comment by taoeffect** [comment]
> it looks like this PR involves large amount of potential merge conflicts with this task for ProposalItem.vue and ProposalBox.vue components.
Do you think it's better for me to wait until that PR is merged?

If that's the case, then yes, better to wait, as PR #1325 is not ready yet.
