### ISSUE TITLE
Navigation bar hides vote buttons on mobile.

### ISSUE THREAD

**Issue by CrazedCoding** [okTurtles/group-income#1309]
### Problem

The vote buttons at the bottom of the page are hidden behind the phone navigation buttons on Android's default chrome browser:

![Screenshot_20220620-130910](https://user-images.githubusercontent.com/18431780/174651602-1f85b502-3cbb-4901-8303-773b874e9dea.png)

### Solution

Increase the padding at the bottom of the page.

**Comment by taoeffect** [comment]
@CrazedCoding Can you please check this again? I think this should be fixed now.

**Comment by CrazedCoding** [comment]
@taoeffect There was no vote present, so I created a vote so that someone with an android could check using the live system.

Maybe I should try joining with a dummy account, or testing this offline with multiple accounts?

It doesn't show me the vote buttons if I'm the one to make the proposal.

**Comment by taoeffect** [comment]
> Maybe I should try joining with a dummy account, or testing this offline with multiple accounts?

Better to do that in a test group that you create

**Comment by CrazedCoding** [comment]
![Screenshot_20230531-193800](https://github.com/okTurtles/group-income/assets/18431780/152f88d5-7ac8-4cc8-873b-4b9b2efe01e5)

Fixed, @taoeffect !
