### ISSUE TITLE
Darkmode issue for invite proposal

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1314]
### Problem

The circular copy icon is not clearly visible:

<img width="755" alt="Screen Shot 2022-06-24 at 11 49 06 AM" src="https://user-images.githubusercontent.com/138706/175647174-4ae47709-8336-4033-9ded-7fb10ee57424.png">

### Solution

Design the correct dark theme for this, close this issue, and then open an implementation issue.

**Comment by leihla** [comment]
Sorry, this was broken on updating the proposals widget. It is fixed now.

See on figma: https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?node-id=3043%3A524

<img width="832" alt="Screenshot 2022-06-27 at 14 24 24" src="https://user-images.githubusercontent.com/158178/175952570-e9f06b9d-292b-4e7f-86cd-7823287eac21.png">

**Comment by taoeffect** [comment]
Thanks @leihla! Opened #1320.
