### ISSUE TITLE
The "next distribution date" banner shows the wrong date

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1316]
### Problem

In our test group the banner shows the next distribution date as being in the past:

<img width="865" alt="Screen Shot 2022-06-26 at 7 28 59 PM" src="https://user-images.githubusercontent.com/138706/175848936-3962a642-6cb6-42db-ac53-cd589b37c2c4.png">

### Solution

Make it show the correct date.

**Comment by Silver-IT** [comment]
@taoeffect, I think this issue is already fixed in any of previous commits. I can't find this issue at the moment.

**Comment by taoeffect** [comment]
Yeah I think it might be fixed too....
