### ISSUE TITLE
Add limit to eventsAfter (formerly eventsSince)

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1324]
### Problem

Currently ~~`eventsSince`~~ `eventsAfter` has no limit enforced on it, and this can lead to the server being asked to deliver a very large number of messages in one go, potentially leading to performance issues.

### Solution

Add a maximum limit, and have `syncContract` call `eventsAfter` multiple times as needed.

**Comment by snowteamer** [comment]
Seems a bit tricky to do given the way `eventsAfter` is currently implemented, namely pushing events in _reverse order_ into a stream one at a time (latest event first, then older events until the given event hash is reached).

What I think could be done is
1. Use a circular list to hold up to `MAX_EVENTS_AFTER` events in memory.
2. That list will progessively fill up while iterating through the contract log. When the list is full, an event will be dropped whenever a new one is added.
3. Stream the circular list contents to the client once the given event hash is reached

**Comment by taoeffect** [comment]
@snowteamer that's not a bad idea. The best way to address this issue really is by addressing #354, but until that's designed & implemented, what you suggested above sounds like a good compromise, and you've already implemented this datastructure in the code for the logs I think. 👍

**Comment by taoeffect** [comment]
Closed by @corrideat and @snowteamer in #1876
