### ISSUE TITLE
Design for displaying inactive users

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1332]
### Problem

It's a problem for the health of a group if pledgers are not making their pledges, and if monetary receivers are not logging in.

### Solution

Perhaps somewhere near the support history of pledges completed (#1286) design a list of inactive that users, something that contains the following information:

```
- Mark (monetary receiver, last login: <date>)
- Joe (pledger, last pledge: <date>, last login: <date>)
- ...
```

**Comment by leihla** [comment]
This has been designed an implemented on the Dashboard widgets.
