### ISSUE TITLE
Design for prompting users to send thanks for receiving pledges

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1333]
### Problem

Currently there's no automatic prompt for thanking pledgers who have sent their payments.

### Solution

Similar to how Duolingo prompts users to send congrats to other users when they make some achievement (just a popup with two buttons, one to send congrats and the other to dismiss), GI should automatically prompt users to send thanks to those who sent their pledges to them, and there should be a corresponding "person thanked you" display to the pledger.

We may want to incorporate the notifications for this as well (e.g. a notification under the bell each time you receive a pledge).

**Comment by dotmacro** [comment]
If we're adding prompts to thank, then users should be prompted to send thanks regardless of what kind of of contribution they received. Can we edit this issue to apply to all contributions, should we open a new issue for other contributions, or should we wait to see what works best with "thanks" design flow?

**Comment by leihla** [comment]
### Overview

**Problem**
Currently there's no automatic prompt for thanking pledgers who have sent their payments.

**Solution**
Add a simple way for a receiver of a contribution to send a thank you note to the pledger, and for the pledger to view it. 

**What changed:**

For receivers:
- Payments - Received tab show "Send thank you note" option on the more actions button
- Notifications - Add notification for payments received 
- Create thank you modal 

For pledgers:
- Notifications - Add a notification for thank you notes received 

----

**Updated Flows:**

## 1. Payments - Received tab (receivers)

- [ ] Add "Send thank you note" option on the more actions button
- [ ] Once clicked, user should be redirected to 4.Payment (receiving) - Thank you Modal 
<img width="1443" alt="Screenshot 2022-10-03 at 15 32 33" src="https://user-images.githubusercontent.com/158178/193603721-aa8f2eec-22f6-4718-b483-4ff8cdf6579b.png">
<img width="721" alt="Screenshot 2022-10-03 at 15 32 43" src="https://user-images.githubusercontent.com/158178/193603732-fb841bcf-a78d-4ed8-a9ec-17da6762e309.png">
<img width="721" alt="Screenshot 2022-10-03 at 15 32 48" src="https://user-images.githubusercontent.com/158178/193603734-efe090e0-c47b-428a-817f-b16101667206.png">

---
## 2. Notifications - Add notification for payments received (receivers)

- [ ] When a payment is received, the user should receive a notification
- [ ] Clicking the notification should show the Payment details modal
- [ ] Clicking "Send thanks" on the modal should open the "Thank you Modal"


<img width="1442" alt="Screenshot 2022-10-03 at 15 35 00" src="https://user-images.githubusercontent.com/158178/193604432-305c30d1-7d97-4c0a-a719-f8ef73533385.png">
<img width="1442" alt="Screenshot 2022-10-03 at 15 35 11" src="https://user-images.githubusercontent.com/158178/193604439-5de85aae-722d-4f41-9f8a-5ad7d2256b5c.png">
<img width="721" alt="Screenshot 2022-10-03 at 15 32 43" src="https://user-images.githubusercontent.com/158178/193604449-1d55d31e-5366-401c-b0f2-195b6dd64275.png">
<img width="721" alt="Screenshot 2022-10-03 at 15 32 48" src="https://user-images.githubusercontent.com/158178/193604444-37cfeacb-1b93-405e-af8e-316aefbbc29e.png">

Figma flow: https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?node-id=23482%3A253597

---
## 3. Notifications - Add a notification for thank you notes received (pledgers)

- [ ] When a thank you note is received, the user should receive a notification
- [ ] Clicking the notification

<img width="1441" alt="Screenshot 2022-10-03 at 15 39 24" src="https://user-images.githubusercontent.com/158178/193605257-73b81152-33f2-4815-9053-640af6da5bac.png">
<img width="1438" alt="Screenshot 2022-10-03 at 15 39 32" src="https://user-images.githubusercontent.com/158178/193605265-ac07e616-b69f-430b-937a-5ba55c89c186.png">
 should show the Thank you modal


Figma: https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?node-id=23482%3A253599
