### ISSUE TITLE
Do not allow punctuation in usernames [$40 bounty]

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1335]
### Problem

When mentioning users in chat, it would be weird if someone were named `@bob?` instead of `@bob` Because then you'd have mentions that looked like this:

```
@bob? are you there?
```

Instead of:

```
@bob are you there?
```

Also, punctuation could introduce bugs in how the @mentions are parsed.

### Solution

Create a validation function that returns `true` or `false` and is used to validate the username in both `SignupForm.vue` as part of the vuelidate validations, and in `contracts/identity.js` as part of the validation for `'gi.contracts/identity'`.

I recommend using regex's `\b` to check for this: https://www.regular-expressions.info/wordboundaries.html

And for the contract validation you'll need to create a function. Have a look at how this validation in `group.js` is written:

```js
    'gi.contracts/group/inviteRevoke': {
      validate: (data, { state, meta }) => {
        objectOf({
          inviteSecret: string // NOTE: simulate the OP_KEY_* stuff for now
        })(data)

        if (!state.invites[data.inviteSecret]) {
          throw new TypeError(L('The link does not exist.'))
        }
      },
```

You'll need to create a similar type of validation.

See also related issue: #1189 - Force usernames to be lowercase

### Bounty

$40 bounty for a clean solution to this (paid in cryptocurrency).

**Comment by snowteamer** [comment]
After discussing it on Slack, the requirements for username validation have been updated to:
- Only alphanumeric characters or hyphens. This should reduce likelihood of homoglyph issues. Meanwhile, usernames containing hyphens are already used in our test cases.
- No leading, trailing, or multiple consecutive hyphens.
- Max 80 characters.
