### ISSUE TITLE
Pick a different user generated event to trigger Notification permissions request

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1345]
### Problem

In the recent group mentions PR that was merged (#1311), the `mousemove` method of requesting notification permissions doesn't seem to work in Firefox on our production server:

<img width="866" alt="Screen Shot 2022-07-13 at 8 36 03 PM" src="https://user-images.githubusercontent.com/138706/178726426-d41280da-c541-4073-83ae-9058146b6f2e.png">

Somehow we missed this, perhaps due to different behavior between production and development, or different browsers.

### Solution

Try a different user-generated event. @snowteamer suggested a mouse click, so we can try that for when the user clicks on "Chat" in the nav.

**Comment by Silver-IT** [comment]
I have a good idea to request permission when users click this button.
![image](https://user-images.githubusercontent.com/57976479/178851983-92950fb8-baac-48f7-864f-f631a2c807bf.png)

**Comment by Silver-IT** [comment]
If we do this way, the problem is that it doesn't request permission when user logins in another device.

Then, what about to request permission also when user clicks `Login` button and successfully logs in?

**Comment by taoeffect** [comment]
@Silver-IT Let's discuss this over Slack and post our conclusion here when we've reached one

**Comment by taoeffect** [comment]
Based on Slack convo: we'll leave it as in #1348 - upon "Login" clicked, ~~and upon "Awesome" clicked when joining a group.~~ EDIT: we've changed our mind and agreed to move it from "Awesome" into Signup.
