### ISSUE TITLE
Pressing Enter in proposals modal doesn't work

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1356]
### Problem

Whether it's the modal for "Add new members", or the modal for "Change minimum income", pressing `<Enter>` doesn't result in the "Next ->" button being pressed.

### Solution

Find and fix.

**Comment by Silver-IT** [comment]
I think #1155 should be fixed too. I guess these two issues are similar.

**Comment by SebinSong** [comment]
@taoeffect @Silver-IT 
Just sent a PR **[here](https://github.com/okTurtles/group-income/pull/1360)** for closing both this issue and #1155 

Also, per @Silver-IT suggestion in the issue description of #1155, I went through

`/contributions`
`/group-settings`
`IncomeDetails.vue`

pages/modal and hitting enter there all seems to work as expected (performing corresponding submission action)
But pls go ahead and comment if you find any other places in the app where a similar bug happens. I can have a look at them later on as well.
