### ISSUE TITLE
Have an admin setting to disable public chatrooms (and/or a group whitelist)

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1359]
### Problem

Moderating public chatrooms can be a headache. Such chatrooms could also be used as a method to target servers and get them taken down by posting illegal content to them.

### Solution

- Create an admin setting to disable the ability to create public chatrooms
- Have a whitelist that allows some pre-approved groups to have public chatrooms

**Comment by Silver-IT** [comment]
@leihla, I don't think we have design for this at the moment.

**Comment by leihla** [comment]
@taoeffect @Silver-IT we have a design for this, here it is: 

https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?type=design&node-id=24085%3A274064&t=d98TkE9zYYyezfEv-1
