### ISSUE TITLE
Implement dropdown for new proposals UI

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1362]
### Problem

From Figma: https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?node-id=23055%3A389974

This doesn't exist yet and needs to be implemented:

<img width="257" alt="Screen Shot 2022-07-23 at 5 50 09 PM" src="https://user-images.githubusercontent.com/138706/180597925-7a08d5c4-6d2c-4cdb-a986-c80a6a86ac8d.png">

### Solution

Implement. Depends on #1353 being merged first.

**Comment by SebinSong** [comment]
@taoeffect I've got a question regarding the expected action of this 'remove member' item in the dropdown.

<img width="257" src="https://user-images.githubusercontent.com/17641213/181202610-a368e7e6-694a-4e25-b0b1-f55ea826572b.png">

Currently `RemoveMember.vue` modal gets immediately unloaded if no username is passed as a query string, like in `http://localhost:3000/app/dashboard?username=u1&modal=RemoveMember`.
( reference: [`created()` hook of `RemoveMember.vue`](https://github.com/okTurtles/group-income/blob/347938ddd7c33d77923b393ea3d057a81cbbb896/frontend/views/containers/proposals/RemoveMember.vue#L48))

Question is, What is supposed to happen when this menu item is selected (when we don't know who to remove)?

**Comment by taoeffect** [comment]
@SebinSong Great question!

Can you have it open up `GroupMembersAllModal` with a special property that tells it to display a "Remove Member" button instead of the "Add to channel" button?

You can pass in a parameter to a modal with the `openModal` function as the second parameter. Then modify `GroupMembersAllModal` to display either `"Add to channel"` or `"Remove member"` depending on the value of the property.

**Comment by SebinSong** [comment]
looks like no additional work for this issue is needed. so closing it. (if not, pls feel free to re-open it.)
