### ISSUE TITLE
Important chatroom privacy settings design changes needed

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1364]
### Problem

1. The current UI does not display the 3 chatroom privacy levels: private-to-group (default), private-to-specifics-members, and public. There is an [outstanding Figma comment related to this](https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN?node-id=5419:53#189541848).
2. The current UI doesn't warn users that public chatrooms are completely public. Not at the privacy-selection screen during creation, nor in the main UI when users are considering joining, or have joined the UI.

### Solution

1. Modify the chatroom creation UI from a toggle-switch to a drop-down and clearly explain the privacy implications of all 3 different chatroom types.
2. For public chatrooms, display warnings at chatroom creation, in the chatroom navbar on the right (e.g. pick a good icon), in the "join chatroom" panel when users are considering joining, and then in the chatroom itself when users have joined.

After these design changes have been implemented, close this issue and open a new one to implement these designs, and assign the same Github tags to it as this issue.

**Comment by leihla** [comment]
@taoeffect completed the design changes for this issue and created a new development issue with the documented solution here https://github.com/okTurtles/group-income/issues/1380
