### ISSUE TITLE
Test failing with ChelErrorUnexpected on Windows

### ISSUE THREAD

**Issue by snowteamer** [okTurtles/group-income#1391]
### Problem

On Windows, the test `group-member-removal/"user2 rejoins the groupA"` fails roughly 6 times out of 10 for me. This doesn't happen on Linux though.

When that test fails, it's always with the same `ChelErrorUnexpected` error, whose formatted log output looks like:
```sh
[
  "debug",
  "[sbp] state/vuex/commit",
  [
    "addNotification",
    {
      "avatarUsername": "user2-259",
      "body": "ChelErrorUnexpected during handleEvent for 'ae' from <b>TODO: signing keyID</b> to '21XWnNVTbzHn94hyF6s86Ddvz8iPcXRRfcE2WoZttZBoEzhqmv': ''",
      "icon": "exclamation-triangle",
      "level": "danger",
      "linkTo": "/app/dashboard?modal=UserSettingsModal&section=application-logs&errorMsg=",
      "scope": "app",
      "read": false,
      "timestamp": 1661194596936,
      "type":"CHELONIA_ERROR"
    }
  ]
]
```
### Solution
Find and fix

**Comment by taoeffect** [comment]
@snowteamer could you add a Solution section to this? If you don't have suggestions you can just put "Find and fix"
