### ISSUE TITLE
Redesign Voting System Step during Group Setup to Remove Disagreement Rule

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1393]
### Problem

There are a few issues with asking users to choose between the percentage rule and the disagreement rule during setup:

1. Most users won't understand the difference, and will find it confusing. This is unnecessary friction during setup. Anyone who really wants the disagreement rule can choose it later in the group settings if necessary.
2. Our implementation of the disagreement rule isn't complete anyway, there are a couple of bugs related to it: #1295 #877

### Solution

All we need is for users to choose the threshold for the percentage rule. So create a new design that's simpler, and just for the percentage rule for that step.

**Comment by dotmacro** [comment]
To add (in agreement): 
Most commonly, I've seen the disagreement rule implemented as "consensus" (i.e. 100% threshold) or "consensus minus 1". Because groups will be small, any users who really want the disagreement rule could also choose a % threshold that approximates the same result.

**Comment by leihla** [comment]
Update Group Creation flow to simplify voting system:

- Remove disagreement number option 
- Update copy 
- Remove disagreement number option from group settings


![5 1  Group Creation](https://user-images.githubusercontent.com/158178/189693930-fed3f617-befe-49e4-8885-17b09fb0e482.png)
![5 2  Group Creation](https://user-images.githubusercontent.com/158178/189693932-4fae4e13-b61a-471f-a506-d0e47cadcbdc.png)
