### ISSUE TITLE
Create admin dashboard with basic features

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1401]
### Problem

We don't have an admin dashboard for Chelonia, and we need one so that we can monitor basic stats and restrict how many signups and groups there are.

### Solution

Design an admin dashboard.

- When it's first run on a fresh install, need to sign up an admin user with a password. Username might simply be `admin`, and only the password needs to be decided by the user. Create 2 password fields to confirm password.
- Ability to login / logout as the admin user.
- Display basic stats
  - How many users have signed up, including paged and searchable list of usernames
  - How many contracts are stored (with future ability to show contracts by type, click on a contract and see more details about it, including how many other contracts are part of that contract)
  - Total amount of space used

**Comment by leihla** [comment]
@taoeffect is there something missing from the dashboard that was designed? Can I close this issue?

**Comment by taoeffect** [comment]
@leihla yeah I think this is closed 👍
