### ISSUE TITLE
Dashboard tab Skeleton

### ISSUE THREAD

**Issue by pieer** [okTurtles/group-income#1403]
### Problem

At the moment there is no interface to display all the different user activities and inactivities

### Solution

Implement design solution found in "Design for displaying inactive users [#1332](https://github.com/okTurtles/group-income/issues/1332)" and "Need a design to show percentage of TODOs that were actually completed in Support History [#1286](https://github.com/okTurtles/group-income/issues/1286)"

**Comment by taoeffect** [comment]
Think this was either closed or a duplicate of #1449
