### ISSUE TITLE
Password confirmation field design needed for SignUp form

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1412]
### Problem

Since we don't have account recovery implemented, it's really important that users don't mistype their password when signing up, but we only have a single password field in the signup form instead of two.

### Solution

Design a second password field.

Corresponding Figma comment: https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN?node-id=2737:154#268150575

**Comment by leihla** [comment]
@Greg please find two options for the new password confirmation field. Let me know which you prefer.
1. 
![1  Sign up](https://user-images.githubusercontent.com/158178/191059220-1131aa63-25f6-4db7-b055-426c30edd08e.png)
2.
![2  Sign up](https://user-images.githubusercontent.com/158178/191059227-02038db3-f6e8-4d09-a9cf-bf422fea9150.png)

@taoeffect regarding password rules, are we going to impose any rules?

Created issue #1415 that needs to be updated once the design is finalized.
