### ISSUE TITLE
Add "Confirm Password" field to Sign Up form

### ISSUE THREAD

**Issue by leihla** [okTurtles/group-income#1415]
**Problem**
Since we don't have account recovery implemented, it's really important that users don't mistype their password when signing up, but we only have a single password field in the signup form instead of two.

**Solution**
Add "Confirm Password" field that the user must fill to create an account. Make sure that both passwords match.

![1  Sign up](https://user-images.githubusercontent.com/158178/191059814-80a634d7-ae14-4107-8588-c9f7de49388a.png)
![2  Sign up](https://user-images.githubusercontent.com/158178/191059820-0728b0bb-497d-4b0c-ad43-d3b11f97ac61.png)

**Figma**: https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?node-id=2737%3A154

**Comment by SebinSong** [comment]
Hi @taoeffect, @leihla 
is this the option we choose to implement? 

<img src='https://user-images.githubusercontent.com/17641213/192127370-c686b26e-1d4a-44bc-b62f-d9682868ffef.png' width='470'>

Do you think we would also want to present the user with a red validation sentence when the `confirmed password` field is not identical to `password` field? if so, what sentence do we want to use?

Thanks,

**Comment by taoeffect** [comment]
@SebinSong 

>  is this the option we choose to implement?

Yes, I like that one, it's not as "long" as the other. However on mobile I think the password fields should still stack on top of one another.

>  if so, what sentence do you want to use?

How about: "Passwords do not match."

**Comment by SebinSong** [comment]
@taoeffect sounds good and short enough for the size of the field.
