### ISSUE TITLE
Trying to get identity profile before sync the identity contract

### ISSUE THREAD

**Issue by Silver-IT** [okTurtles/group-income#1420]
### Problem

1. User1 creates a group and shares the invitation link with User2 and logs out.
2. User2 joins the group by the invitation link and goes to the group chat room (`General` channel)
3. User2 mentions User1 and logs out.
(In this situation, User1 has already logged out so he doesn't sync all the events of Group and Chatroom)
4. User1 logs in and gets error.
(User2 mentioned User1 so it would make a notification which needs to access the sender(User2)'s identity contract to get display name and picture. But at this point, User1 could not have completed to sync the identity contract even completed to sync group contract)

So I disabled to do something when the identity contract is not synced like the following.
```
const identityState = rootGetters.globalProfile2(groupID, username)
  if (identityState) {
    makeNotification({
      title: `# ${chatRoomName}`,
      body: text,
      icon: identityState.picture,
      path
    })
  } else {
    // this happens when identity contract of username is not synced yet
    // this means when new user joins the group and mentions immediately when I am absent
  }
```
model/contracts/chatroom.js L66 ~ L77

### Solution

To be honest, not sure what should we do for this. @taoeffect can decide this.

My options for the solution are
- Ignore this case
- Sync group contract and then identity contract. After that, chatroom contract

**Comment by taoeffect** [comment]
@Silver-IT the only thing you need `identityState` there is for the picture, is that right? If so, just post a notification without a picture.

**Comment by Silver-IT** [comment]
Hahaha. Awesome Solution. :)
