### ISSUE TITLE
Tapping new member joined notification doesn't work on mobile

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1431]
### Problem

![bug](https://user-images.githubusercontent.com/138706/193923004-339f388f-0a28-4af5-ba33-ad3aca37e5bf.jpeg)

Tapping this notification in Brave doesn't switch me to the chat as expected.

### Solution

Find & fix bug.

**Comment by Silver-IT** [comment]
@taoeffect, I have just tested this issue in the mobile Brave browser and noticed it works fine.
I think this issue is already fixed by another commit for another bug fix.

Please try to test on your side again, and keep me updated.

**Comment by taoeffect** [comment]
Huh, you're right. Seems to have been fixed.
