### ISSUE TITLE
Forgot to hide disagreement rule in voting dropdown

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1436]
### Problem

The disagreement rule still appears in the UI in one place we forgot:

![Screen Shot 2022-10-12 at 2 05 45 PM](https://user-images.githubusercontent.com/138706/195447971-fafd6a03-a598-4fa7-a06b-3336e7a791f5.jpg)

### Solution

Don't delete the code, but instead comment it out or something so that the remaining traces of the disagreement rule are visually no long present.

**Comment by dotmacro** [comment]
Sorry I didn't see this issue yesterday, or think about it sooner.

"Change to percentage base" doesn't make much sense as a standalone option. Can we change the text to "Change percentage base"? (This could be done by editing the remaining option, or adding it and  commenting out both original options, whichever makes the most sense.)

**Comment by SebinSong** [comment]
Thanks Andrea,

the payment has been received and thanks for including the extra 15 mins :)

Regards,
Sebin

2022년 10월 14일 (금) 오전 10:38, Andrea Devers ***@***.***>님이 작성:
