### ISSUE TITLE
Implement Activity Dashboard Tab

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1449]
### Problem

The [Activity Tab](https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?node-id=23766%3A357406) isn't implemented and needs to be.

### Solution

Go through an implement the streaks and inactivity fields (*except for the non-monetary contributions streak!* — that [is still being discussed](https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN?node-id=23766:357406#297122208) as we have no way to measure it at the moment).

Take care to:

- Use the group contract state to store information about streaks
- Store this information in an efficient way in the state (think to yourself: "how much information will this be to store in-memory for a group that's been running for 2 years?"). If the information is too big, then think about using `'gi.db/archive/*'` selectors instead of the in-memory state.
- Test thoroughly locally, and then bump the contracts versions before submitting a PR

You can split this issue up into multiple PRs, implementing different activity / inactivity labels.

**Comment by SebinSong** [comment]
Will split the work into multiple PRs like below

<img src='https://user-images.githubusercontent.com/17641213/199736930-c9abd160-cf1b-46f7-aeec-da9922285d6a.png' width='560' >

**Comment by SebinSong** [comment]
Hi @taoeffect 

Got questions regarding 'Streaks' part of this task.



Q1. **'Group streak of 100% support for N months'**
Does the streak have to be n 'most recent' histories? for examples,

Apr - 70%
**May - 100%
Jun - 100%
Jul - 100%**
Aug - 80%
Sep - 70%
**Oct - 100%
Nov - 100%**

if there is a support history like above, even though there was 3 streaks of 100% support in the past(May, Jun, Jul), do we still honour the 2 of the most recent streaks(Oct, Nov)? and if there is no >=2 number of latest 100% support records, Do we not show this sentence?

Q2. **'N members have on-time payment streaks'**
Likewise, does the streak we count here have to be the most recent ones? also, the count of streaks each member in N members has isn't necessarily the same, right?

Thanks,

**Comment by taoeffect** [comment]
@SebinSong 

> Q1

That number counts the number of recent months (not including the current month) that had 100%. The second we have a month that doesn't have 100%, it resets back to 0. Does that make sense?

And keep in mind the Vuex state only stores 6 months worth of data for those numbers, so you will have to remember the current streak and increment by 1 each time we get a new 100%.

> Q2

We calculate the number in the same way as we do for Q1 - but for each individual member we keep track of their individual streak. So right, it could be different for different members, one might have 2, the other might have 3, etc.

**Comment by dotmacro** [comment]
Q3. How does zero in the denominator affect streaks? 
For example, if no payments need to be made one month (i.e. n/0 payments) because everyone has already met the mincome, does that:
A) count as 100% for the group, and therefore continue the group streak? (I'd vote certainly yes because the group has 100% met its mincome needs)
B) count as on-time payment for individuals, and therefore continue individual streaks? (I also vote yes because they have still made all necessary payments)

**Comment by taoeffect** [comment]
> Q3

Sure! If for some reason there is no need (only people pledging) then yeah, I guess that counts.

**Comment by SebinSong** [comment]
@taoeffect @dotmacro thanks for the answers.

**Comment by SebinSong** [comment]
Hi @taoeffect,

I've been thinking about 'how to' regarding the chunk 2, which is 'inactivity' section, and need a help in clarifying some of the sentences.

<img src='https://user-images.githubusercontent.com/17641213/200266243-100602d3-e94f-4189-8f39-0feaf2c87f63.png' width='360'>


**Q1. 'N members' have missed payments.**
This can sound obvious but is 'N' members here any **pledging members** that didn't make their payments in **the previous** distribution period?

**Q2. 'N' members haven't voted in the last 'M' proposals.**
is 'M' here is fixed as 2 always? for example, let's consider below scenario.

<img src='https://user-images.githubusercontent.com/17641213/200271432-3054cbe7-82cb-4f85-8d1b-bfef81a2ab7d.png' width='440'>

In here, Do we still write '3' members haven't voted in the past 2 proposals, when **user1** is the only member who hasn't voted on **all of** the 2 most recent proposals?

Also, what if there is less than 2 number of previous proposals?
Do we write 'N members' haven't voted on the last proposal then?

Q3. It's more of a suggestion than a question but would you think it's a good idea to change **'N members didn't log in last week'** to **'N members haven't logged in in the past M days'**?
I thought it would be easier to implement while achieving the similar purpose of checking whether users have recently logged in or not.

Regarding how to implement it in the `group.js`, I was thinking of creating an object field in the group state that looks something like,
`lastLoggedIn: { user1: timestamp1, user2: timestamp2, ... }`
which will get updated each time the group member logs in. and then we can use this timestamp to see if it's within the past M days. Does it sound good?

Thanks,

**Comment by taoeffect** [comment]
> Q1. 'N members' have missed payments.
> This can sound obvious but is 'N' members here any pledging members that didn't make their payments in the previous distribution period?

This is a very good point, I think the problem is that we don't have designs for what happens when you click on that link, which will make everything clear.

When the link is clicked, it should expand to show which members have streaks of missing payments. In other words:

```
Joe Schmoe missed 5 payments
Roger Silver missed 1 payment
```

> Q2. 'N' members haven't voted in the last 'M' proposals.
> is 'M' here is fixed as 2 always? for example, let's consider below scenario.

I think we should treat this the same as the missed payments, except we only show members who have a streak of 2 missed proposals or more.

So in your example it would be only user1.

> Q3. It's more of a suggestion than a question but would you think it's a good idea to change 'N members didn't log in last week' to 'N members haven't logged in in the past M days'?

Yes, I agree! We can make it 14 days or more.

> which will get updated each time the group member logs in. and then we can use this timestamp to see if it's within the past M days. Does it sound good?

Yeah that sounds good. It could also go into their groupProfile object, but if you think this is better then go for it!
