### ISSUE TITLE
Wrong due date shown in UI

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1450]
### Problem

The screenshot below illustrates the problem. It shows how the UI will tell the user that the due-date is "October 31st", but when November 1st arrives, the new TODOs are not visible in the Payments screen, and it also explains why.

Note: in the screenshot below, `g` refers to the global Vuex getters, and `date` refers to the current date when I took the screenshot (in this case, `"2022-11-01T22:11:40.457Z"`):

![Screen Shot 2022-11-01 at 3 22 22 PM](https://user-images.githubusercontent.com/138706/199353594-07728913-6114-42c1-b856-aaa31b34c745.jpg)

The problem is that the due date is saved as `"2022-11-01T00:00:00.000Z"` (which signifies the very end of October 31st / the very beginning of November 1st), while the period-stamp is saved as `"2022-11-02T00:00:00.000Z"`, a full day later.

The getter `currentPaymentPeriod` is what determines what TODO list is displayed, and it, in turn, depends on `periodStampGivenDate`.

As such, there's a 24-hour period after the due-date shown to the user during which `periodStampGivenDate` will return the period stamp for the previous period. In other words, we're plugging in `date` to `periodStampGivenDate`, and it's returning the period stamp for the previous period:

```js
getters.periodStampGivenDate("2022-11-01T22:11:40.457Z")

// => returns "2022-10-03T00:00:00.000Z"
```

### Solution

Here are the various dates we're dealing with in this example:

- Current date: `"2022-11-01T22:11:40.457Z"`
- Previous period stamp: `"2022-10-03T00:00:00.000Z"`
- Next period stamp: `"2022-11-02T00:00:00.000Z"`.
- Date returned by `dueDateForPeriod`: `"2022-11-01T00:00:00.000Z"`
- Due date shown to user (in Pacific Time Zone): `October 31st`

Now, technically, all of the values returned by the getters seem correct - but the date shown to the user is clearly wrong.

In this example, the switchover with a fresh set of TODOs for pledgers happens once the current date is `>= "2022-11-02T00:00:00.000Z"`.

I think fixing this should be as simple as making `dueDateForPeriod` return the `periodAfterPeriod` for that period stamp.

FWIW, in that case, `humanDate(g.periodAfterPeriod(g.periodStampGivenDate(date)), { month: 'short', day: 'numeric' })` returns `"Nov 1"` as the due date, which would work. However, if we make this the due date shown to the user, there is some hour of November 1st (today) at which payments for the current period will no longer be accepted, and we currently do not show the hour of the due date to the user (cc @leihla).

**Comment by Silver-IT** [comment]
@taoeffect, this seems weird to me. How could `dueDate` be before the `periodStampGivenDate`?
![image](https://user-images.githubusercontent.com/57976479/225214834-ac6efb41-9f71-4f75-9ab3-e6e32888ed2a.png)

**Comment by Silver-IT** [comment]
Currently, 'Next Distribution Date' is set as `dueDateForPeriod` in `PaymentNextDistributionPill.vue`.
This seems weird to me and I think it should be set as `periodAfterPeriod`.

![image](https://user-images.githubusercontent.com/57976479/225226810-abd81161-c223-499c-8aae-e7f59ac9dae1.png)

**Comment by Silver-IT** [comment]
Logically, `dueDateForPeriod` should be 1 millisecond before `periodAfterPeriod`, I think.

**Comment by Silver-IT** [comment]
Additionally, I found many weird things in displaying date times.

We use `toISOString` inside the contract in order to avoid the mistakes in time handling. All the `periodStamp` is in ISO formatted which is in UTC time zone and which can't be meaning the beginning of the day in different time zones.
But we display only the date (e.g. Apr 20) no matter which time zone the user is in.
I think we should make the design more clear so that there won't be any confusions.

cc: @taoeffect, @leihla

**Comment by taoeffect** [comment]
> Logically, `dueDateForPeriod` should be 1 millisecond before `periodAfterPeriod`, I think.

I think to keep it simple we can keep them the same. The word "due" can be interpreted in 2 different ways, and it's perfectly OK to interpret it as "due by this time - at or after which you are late". Also, 1 millisecond difference will make no difference to users. That is faster than a mouse click. Keeping them the same will also reduce unnecessary complexity.

> But we display only the date (e.g. Apr 20) no matter which time zone the user is in.
I think we should make the design more clear so that there won't be any confusions.

We should display the due date to the user in their local timezone using `humanDate`, and I think we should also display the hour and the minute that it is due too, so that there's no confusion.

**Comment by Silver-IT** [comment]
> Keeping them the same will also reduce unnecessary complexity.

Okay

> I think we should also display the hour and the minute that it is due too, so that there's no confusion.

I think so too. We should update the design to display hour and minute.

**Comment by taoeffect** [comment]
> We should update the design to display hour and minute.

I've made [a comment](https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN?node-id=23123:225402#400396096) on Figma, but for now please just go ahead and add it yourself using `humanDate`
