### ISSUE TITLE
Basic event log system for frontend

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#146]
### Problem

Frontend needs to be able to handle events and update its UI & state accordingly. This hasn't been implemented yet but with our backend and event format more or less figured out (once #144 is merged), we can begin this in earnest.

### Solution

- Create dummy test data that simulates a log of events in the frontend
    + Figure out the main type of events (group creation, identity registration, voting to add/remove identities, payment sent, payment received, chat message, profile updates) — *note: some of these might later be removed from the log and placed into a separate ephemeral messaging system, but for now they're all going into the log*
- Integrate it with Vuex
- Demonstrate scrolling through time (forwards & backwards) by creating a debug-slider component that's visible to developers. Scrolling causes the state to change (and the view to change, but only if you're on a page where a state change affects the view)
- Have a way to efficiently persist the event log in the browser

**Comment by vijayee** [comment]
Completed with #155
