### ISSUE TITLE
Integrate frontend event system with backend

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#147]
### Problem

A functioning frontend system that only handles test/dummy data isn't useful to anyone.

### Solution

Once #146 is finished, hook up the frontend to the backend. This should not be much of a leap, as the backend behaves exactly like a dumb store, only difference is the pubsub notification stuff, but that also should be easy to implement because it's little different than the debug slider in #146.

**Comment by vijayee** [comment]
Completed with #155
