### ISSUE TITLE
Implement Design for Support History TODO tab

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1471]
### Problem

Implement the Support History TODO design of #1286.

![Screen Shot 2022-12-03 at 7 25 01 PM](https://user-images.githubusercontent.com/138706/205472737-3d0f21a7-9a33-4c9c-ad39-f454ffe1b68b.jpg)

### Solution

Update the group.js contract to implement this.

Note that closing this issue also requires closing  #1432.

**Comment by SebinSong** [comment]
Figma link: https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?node-id=23766%3A357406&t=A8sJihWTSrTI7ehQ-0

**Comment by SebinSong** [comment]
Hi @taoeffect,
I actually have been referencing this  [`SupportHistory.vue`](https://github.com/okTurtles/group-income/blob/master/frontend/views/containers/contributions/SupportHistory.vue#L74) for this issue (as it has similar UIs) and seem to have spotted an issue with it. (Although, it's not in the scope of this issue)

<img src='https://user-images.githubusercontent.com/17641213/206882459-177479c4-dbf0-4ca9-84d6-1421e091b275.png' width='440'>

If I was not mistaken, It appears that the calculation for the percentage value for each previous period is wrong atm. 

Currently it looks like below,
`total: numReceivers === 0 ? 0 : totalDistributionAmount / (this.mincome * numReceivers)` 
which is pretty much `totalDone / totalTodo`. But the denominator here as `(this.mincome * numReceivers)` seems incorrect. it's actually based on the assumption that the amount each payee receives a month is always as much as the mincome, when it's actually `(mincome - their monthly income)`.
Do you think this should be corrected? Please let me know if I'm wrong though, but if it does need correction, I can work on fixing this as part of this task. Thanks.

**Comment by taoeffect** [comment]
@SebinSong You're right, the denominator should be fixed as you describe. Great catch! 👍
