### ISSUE TITLE
Implement Backend Dashboard designs

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1475]
### Problem

Backend dashboard designs are mostly ready and we need to get started on implementing them.

Figma link: https://www.figma.com/file/u20MatYNOsBSDDJLbz2WPq/Chelonia-Dashboard?t=piVFHQ2JPJdRv74Q-0

### Solution

Implement them.

This issue is assigned to @SebinSong, if there are any questions please post on Slack.

**Comment by SebinSong** [comment]
# Chelonia dashboard front-end task Todos

The working branch is **[here](https://github.com/okTurtles/group-income/compare/master...sebin/task/%231475-chelonia-dashboard-frontend_design-implementation)** **(sebin/task/#1475-chelonia-dashboard-frontend_design-implementation)** , which is where you can check all the commit history so far. Once all the TODOs here are completed, it will be merged to **the PR #1483** .
Development progress will be constantly updated in this check-list along with screenshots when needed.

## Step 1. Dashboard page

<img src='https://user-images.githubusercontent.com/17641213/216448337-abbf7570-102e-4e62-9a2d-8ce561894b60.png' width='430'>


- [x] Implement navigation side-menu / toolbar
- [x] Implement client-side routing
- [x] Build the stat card generic vue-component
- [x] Implment the page design and fill the page with the temporary dummy data/text

[ screenshot ]

<img src='https://user-images.githubusercontent.com/17641213/217375596-87fa0d29-cc59-4339-b5de-1868045cc030.png' width='430'>

<img src='https://user-images.githubusercontent.com/17641213/225829428-e7ad6d12-febe-4cca-9c52-c9222b6bd42c.png' width='430'>


## Step 2. Contact page

<img src='https://user-images.githubusercontent.com/17641213/216449379-938ae641-8bfd-4cd0-9e98-522ca4b70a86.png' width='430'>

<img src='https://user-images.githubusercontent.com/17641213/216449474-826df271-3d3c-4a57-a131-b3400b9eae02.png' width='430'>

- [x] Build the dropdown generic component
- [x] Build a modal
- [x] Implement the page design and fill the page with dummy data/text
- [x] Build a tooltip for contract id

[ screenshots ]

<img src='https://user-images.githubusercontent.com/17641213/225828868-ac6d905c-6157-486f-9323-6b947fa5b78b.png' width='430'>

<img src='https://user-images.githubusercontent.com/17641213/225829093-d0ca50e2-96e4-4f53-abf7-d76add12b8f1.png' width='430'>

<img src='https://user-images.githubusercontent.com/17641213/225829845-c9b9afc6-d2d4-4428-9a37-675bd9ef1d50.png' width='430'>


## Step 3. Users page

<img src='https://user-images.githubusercontent.com/17641213/216450108-ed6856ec-8a15-45f5-b093-a971f42f85b2.png' width='430'>

- [x] Implement the page design and fill the page with dummy data/text

[ screenshots ]

<img src='https://user-images.githubusercontent.com/17641213/226169605-94e85c4e-a172-4788-9ed6-c9f92f01a84a.png' width='430'>

<img src='https://user-images.githubusercontent.com/17641213/226169636-c2c96c57-4a32-449b-a414-df8f64b95672.png' width='430'>

## Step 4. Accounts page

<img src='https://user-images.githubusercontent.com/17641213/216450346-cdf8a2bc-9add-43b9-97f3-c22b3d06597f.png' width='430'>

- [x] 4-1. Build the text input generic component
- [x] 4-2. Build Radio button generic component
- [x] 4-3. Build the information card generic component
- [x] 4-4. Implement page design and fill the page with dummy data/text

## Step 5. Billing page

<img src='https://user-images.githubusercontent.com/17641213/216451072-636e3fcb-3e80-424a-8130-20e476b97ddf.png' width='430'>

- [x] 5-1. Build payment methods UI
- [x] 5-2. Build the 'input with suffix' generic component
- [x] 5-3. Implment the page design and fill the page with dummy data/text

## Step 6. Implement lazy-loading of pages
- [x] 6-1. Create 'Loading' page
- [x] 6-2. Create 'Error' page
- [x] 6-3. Implement lazy-load logic for all pages other than the first landing page

## Miscellaneous
- [x] Implement light / dark theme
- [x] Build a landing page
- [ ] Create logo for the project
- [ ] (Optional) Create a /design-system page for efficient development

**Comment by SebinSong** [comment]
@taoeffect Hi Greg,
I'm currently on building this dropdown filter in Step 2('contracts' page). what would be the filter options in this page?

<img src='https://user-images.githubusercontent.com/17641213/218199456-ffe98cdb-748a-4c2d-8bc1-c114f14b230a.png' width='400'>

(Or is it okay to give  'option 1' , 'option 2' types of placeholder items to it until the dashboard is actually connected with the real data?)

Thanks.

**Comment by taoeffect** [comment]
@SebinSong it would be the various different contract types (e.g. the values under `Type` column)

**Comment by SebinSong** [comment]
Hi @taoeffect ,
I think most of the UI side of work is complete and presentable now. So I just created a preview github page(link below) where you can click&navigate around things.

https://sebinsong.github.io/chelonia-dashboard-preview/

There are some minor stuff left in the **[above todo list](https://github.com/okTurtles/group-income/issues/1475#issuecomment-1414385345)** and I'm aiming to get them done in a couple of weeks, before I get back to working on any issue for GroupIncome. hope it looks good.

**Comment by SebinSong** [comment]
@taoeffect 

<img src='https://user-images.githubusercontent.com/17641213/230758670-9ef76a58-6949-44db-9ac9-0cbed1a5a6dd.png' width='320'>

This logo up here is actually not a project logo but an arbitrary icon that I chose as a placeholder. Judging by the issue list, Leilha seems to be busy with multiple other works on GI. I have actually been learning a vector graphic skill (Adobe illustrator) over the past several weeks, and I can try and create a logo vector graphic for Chelonia dashboard by myself over the next couple of weeks. (thinking of creating probably 3 candidate images that I present to you guys and then get feedbacks on what we finally use)

Does it sound good? :)

**Comment by taoeffect** [comment]
@SebinSong sure, that would be awesome, I'm curious/excited to see what you come up with!

**Comment by SebinSong** [comment]
@taoeffect thanks, will try my best!

**Comment by snowteamer** [comment]
Awesome work @SebinSong! Very well done!

**Comment by taoeffect** [comment]
Think this has been closed by @SebinSong
