### ISSUE TITLE
Fix misc issues with Activity Tab

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1482]
### Problem

![Screen Shot 2023-01-17 at 4 23 59 PM](https://user-images.githubusercontent.com/138706/213045947-c677015d-3564-49d5-b70b-75526ea81c5e.jpg)

There are several issues related to pluralization in English, and also missing information about the length of members steaks.

### Solution

1. UI needs to show how long a person's streak is. Above it only says their name, but we need to show, for each member with a streak, how many months long their streak is:

    ![Screen Shot 2023-01-17 at 4 26 53 PM](https://user-images.githubusercontent.com/138706/213046844-3acdcb02-a713-4573-bc57-a0915d2e9cec.jpg)

2. English needs improvements related to plurals:

   - For singular, instead of "1 member haven't entered income details", it should say, "1 member hasn't entered income details"
   - Zero (0) is treated the same way as plural, so instead of "0 member haven't voted in the last 2 proposals", it should read: "0 members haven't voted in the last 2 proposals"

3. We should add a group streak for 100% TODO payments too.

**Comment by SebinSong** [comment]
Hi @taoeffect , I've got a question regarding a requirement here.

> 3. We should add a group streak for 100% TODO payments too.

What does **100% TODO payments** mean here?

If it means the case where all pledging members in a group makes full pledges in the distribution period, That's what below item counts (`streaks.fullMonthlyPledges` in `group.js` contract).

<img src='https://user-images.githubusercontent.com/17641213/213594924-600c2bcd-46c1-4e7e-99f6-7801f2a9120e.png' width='360'>

Thanks,

**Comment by taoeffect** [comment]
> If it means the case where all pledging members in a group makes full pledges in the distribution period, That's what below item counts (streaks.fullMonthlyPledges in group.js contract).

These should correspond to the Support % and TODO % tabs.

So 100% Support corresponds to Support % streaks, and 100% TODO corresponds to TODO % streaks.

**Comment by SebinSong** [comment]
Thanks @taoeffect
But it seems to me like 100% support also means 100 % Todo payments, if I am not misunderstood.

Looking at[ the figma](https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?node-id=1204%3A0&t=2VmgfFb4YvzJa34K-0) below and the way I implemented Todo history tabs in [this PR](https://github.com/okTurtles/group-income/pull/1473),

<img src='https://user-images.githubusercontent.com/17641213/213610062-accb26e7-dd4c-4ba5-8d65-bb73d5afea65.png' width='520'>

Support history =  **amount pledged / total amount to pledge**
Todo history = **number of payment items completed / total number of payment items to make**

which means, 100% of support history also means 100 % of todo history and the other way around holds true too.
So `streaks.fullMonthlyPledges` value counts streaks for both. Is it correct?

Thanks

**Comment by taoeffect** [comment]
> which means, 100% of support history also means 100 % of todo history and the other way around holds true too.

No, that's not true. Look at our group, if everyone does their TODOs we do not get 100% support.

If we get 100% support, then usually yes it does mean 100% todos too (depending on the algorithm we're using. for the current one that is true).

**Comment by SebinSong** [comment]
@taoeffect I got it. looking at the logic I created for `streaks.fullMonthlyPledges` in a previous task again, it actually checks the **'number'** of payment items completed in a period not the **'total amount'** pledged, which means it's actually a streak value for 100% TODO history. But currently we are using this value as 100% support history in the UI.

<img src='https://user-images.githubusercontent.com/17641213/213594924-600c2bcd-46c1-4e7e-99f6-7801f2a9120e.png' width='340'>

Then can I update this sentence in the UI to **'Group has a streak of 100% TODO payments of N months'** and work on implementing streaks of 100% support history in `group.js` contract? (I think this is going to be the last question before making additional change)

Thanks,

**Comment by taoeffect** [comment]
@SebinSong Yes that sounds right 👍

**Comment by SebinSong** [comment]
Hi @taoeffect, can I work on this issue as part of[ this Active PR](https://github.com/okTurtles/group-income/pull/1473) of mine? (rather than pushing it as a standalone change and merging it to that later on?) Cheers.

**Comment by taoeffect** [comment]
@SebinSong Yes, I know usually we encourage 1PR per issue, but in this case it's OK to make an exception 👍
