### ISSUE TITLE
Implement notifications and sounds for the messages

### ISSUE THREAD

**Issue by Silver-IT** [okTurtles/group-income#1489]
### Problem
Currently, notifications and sounds are only working for the direct messages and mentions.
According to the updated design, it must be able to be configured in the notifications settings.
UI is already implemented in the PR #1463, so the functionality needs to be done.

### Solution
1. Save the configuration for notifications and sounds in the storage.
2. Make notifications and play sounds according to the configuration inside the function `messageReceivePostEffect` from `model/contracts/chatroom.js`.

**Comment by Silver-IT** [comment]
@taoeffect, I have two things to confirm before starting this ticket.
In the `Notification` page in user settings, there is a general setting for the notifications.
![image](https://user-images.githubusercontent.com/57976479/217130491-7817ea6d-2e29-4c2c-a91c-e10bc9d6d661.png)
If the notification is enabled here, the general setting (which is to make notifications and sounds only for mentions and dms) will work, and individual configuration will override it.
But if the notification is disabled in the user settings, no notifications will work regardless of the individual notification configurations.

So two questions I will make.
1. Is the workflow which is mentioned above correct? Especially, when the notification in user settings page is disabled.
2. What about the sounds? Is there any general settings which we can configure in user settings page? Because I can't find the designs for sounds.

**Comment by taoeffect** [comment]
@Silver-IT I actually think none of these settings should be implemented right now. They should all be greyed out / disabled.

The reason is:

- "Push notifications" refers to mobile notifications, the ones you get on your phone, and those cannot be implemented until  #1456 is closed.
- Emails cannot be implemented until #1490 is closed

**Comment by Silver-IT** [comment]
@taoeffect, So you mean `Push Notifications` in User Settings page doesn't affect to the web browser notification when user receives messages?

**Comment by taoeffect** [comment]
@Silver-IT I'm saying, that if we want to make this refer to the browser notifications, we need to name it something else. Perhaps just "Notifications". The words `Push Notifications` refers to a very specific type of notification - a mobile phone notification.

EDIT: Alex pointed out on Slack that I appear to be mistaken about this: https://web.dev/notifications/
