### ISSUE TITLE
Design 'remove avatar' option

### ISSUE THREAD

**Issue by SebinSong** [okTurtles/group-income#1491]
### Problem
Currently there is no way in the app for the users to remove the avatar image they previously uploaded. There should be an option that allows users to revert their avatars back to the default alphabet initials, which is something similart to the 'Remove photo' button in below screenshot of Slack.

<img src='https://user-images.githubusercontent.com/17641213/217957792-905c6e59-b3a2-431a-a497-497617fa7ab4.png' width='460'>

### Solution

Create a design for this.

**Comment by SebinSong** [comment]
Once it's ready to be picked up for implementation, pls let me know.

**Comment by leihla** [comment]
This has been designed and can be seen here @SebinSong 

https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?type=design&node-id=25762%3A285577&t=d98TkE9zYYyezfEv-1
