### ISSUE TITLE
Fix undefined exception in GroupMembers

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1492]
### Problem

On our test server this code is throwing from `GroupMembers.vue`:

```js
    directMessages() {
      return this.ourContacts.filter(e=>Object.keys(this.mailboxContract.users).includes(e) && this.mailboxContract.users[e].joinedDate).map(e=>this.ourContactProfiles[e])
    }
```

![Screen Shot 2023-02-11 at 3 36 45 PM](https://user-images.githubusercontent.com/138706/218285667-43f51881-7e37-44af-b350-0d09d739e75c.jpg)

### Solution

Find and fix the bug. Based on the error message it might be that `this.mailboxContract.users` is `undefined`

**Comment by Silver-IT** [comment]
Nice Catch, @taoeffect.
Actually it's from `ChatMembers.vue` , not `GroupMembers.vue`. And this error will be fixed once we merge the PR #1463.
