### ISSUE TITLE
Archive Chatroom

### ISSUE THREAD

**Issue by Silver-IT** [okTurtles/group-income#1500]
### Problem

The Figma design says that the chatroom would be archived when the creator leaves it.
To archive chatroom means that the members are able to access and check the previous messages but no longer able to send any more messages. I don't think the Figma design is fully provided for the details.
1. The confirm button title when the creator tries to leave channel. `Leave and Archive` or `Leave and Archive Channel` or ...
2. How does it look like when a user is on the archived chatroom
3. How to unarchive the archived chatroom

### Solution

1. Confirm the workflow and make a design
2. Clone the Figma design in frontend
3. Implement workflow

**Comment by leihla** [comment]
@Silver-IT I've tested on Slack and even if you're the channel creator you can leave the channel and it will have the same behaviour as it has to other users. There's no archive option. Where in figma did you see the archive comment?

I think we should just implement the leave channel flow as per designed here https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?node-id=23766%3A273986&t=2oJycBX07BbzexcQ-1

**Comment by Silver-IT** [comment]
@leihla, I know Slack doesn't archive channel even the creator leaves the channel.
But I remember this is what you described [here](https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN?node-id=23766:274012#368726136).

**Comment by leihla** [comment]
@Silver-IT lets remove the archive option and I'll remove that comment from Figma. If the Admin the channel, the channel is deleted.

**Comment by leihla** [comment]
@Silver-IT well, slack keeps on changing the behaviour so it's not really easy to know, and in all honesty I don't know what @taoeffect prefers in terms of data. From what i've seen again, they do keep all channels in an archive even if they have 0 members, which means that even if the admin of the channel leaves the channel, they have access to it later. 

@taoeffect I think you need to be the one deciding this, if we want to keep data from old groups and archive everything and let users come back to groups later, or, if the admin leaves the group, the group is deleted and data  as well.

<img width="595" alt="Screenshot 2023-04-14 at 08 35 16" src="https://user-images.githubusercontent.com/158178/231976115-5243a073-dbda-445a-9b04-4cbeda7ac82a.png">
<img width="929" alt="Screenshot 2023-04-14 at 08 35 36" src="https://user-images.githubusercontent.com/158178/231976128-3f1825aa-a496-4f39-8fc6-1c6187cf07f7.png">
<img width="940" alt="Screenshot 2023-04-14 at 08 35 49" src="https://user-images.githubusercontent.com/158178/231976132-d258a67f-3ca5-4834-a3ac-9f533b3c47c8.png">

**Comment by taoeffect** [comment]
@Silver-IT @leihla Since you're asking me for my opinion on how it should work, how about this:

- Anyone can leave the channel.
- The channel can have zero members and still be joined and used later.
- If there is one person in the channel, and that person is the creator of the channel, then they can be given the option to delete the channel, which deletes all of the messages in the channel. We currently do not have a way to delete a contract on the server implemented, this would need to be done first before this feature could be implemented.

Does that work?

**Comment by Silver-IT** [comment]
@taoeffect, so you mean there will be no `Archive channel` function. Right? Actually, it's fine to me.

1. Anyone can leave the channel. [ALREADY IMPLEMENTED]
2. The channel can have zero members and still be joined and used later. [ALREADY IMPLEMENTED]
3. Delete Channel. [NOT YET IMPLEMENTED]

If we shouldn't have `Archive Channel` feature, we should update the Figma. And also close the PR #1512 and this issue too.

**Comment by taoeffect** [comment]
> If we shouldn't have Archive Channel feature, we should update the Figma

I'll leave that for @leihla when she gets back.

> And also close the PR #1512 and this issue too.

Done!
