### ISSUE TITLE
Switch to TypeScript from FlowType

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#151]
### Problem

As neat as FlowType is, sometimes it's kinda dumb: `https://github.com/facebook/flow/issues/3041`

It might be worth exploring TypeScript to see if it's any smarter.

### Solution

Check out:

- http://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html
- https://blogs.msdn.microsoft.com/typescript/2016/12/14/writing-dts-files-for-types/
- https://blog.mariusschulz.com/tags/typescript

TypeScript might be just as dumb, but can't know unless we try.

EDIT: OTOH, [this just popped up](https://alligator.io/vuejs/components-flow/).

**Comment by taoeffect** [comment]
To be clear, we're considering going from this:

![](http://leftoversalad.com/c/015_programmingpeople/PP4.png)

*+ FlowType*

To this:

![](https://pbs.twimg.com/media/CzTYhYrXAAAkgEm.jpg)

*Source: http://leftoversalad.com/c/015_programmingpeople/*

**Comment by taoeffect** [comment]
It seems possible to do type checking in .vue files with TypeScript:

- https://herringtondarkholme.github.io/2016/10/03/vue2-ts2/

Unlike Flow:

- https://github.com/facebook/flow/issues/2691#thread-subscription-status
- https://stackoverflow.com/questions/40105053/how-to-get-flow-to-properly-work-with-vue-2-webpack

**Comment by taoeffect** [comment]
~~Flow is better.~~

**Comment by taoeffect** [comment]
Per @sandrina-p commentary, Flow is good for our needs and TypeScript doesn't offer enough to be worth switching to at this point. :)

**Comment by sdegutis** [comment]
Considering a few things:

* The current FlowType setup in this repo is not currently functioning (afaict)
* Significant parts of this codebase are not currently typed at all
* Most of FlowType is compatible with TypeScript, and the remainder is easy to convert
* TypeScript has stronger tooling support (e.g. VS Code)
* TypeScript has seen far more significant adoption than FlowType in the past couple years

Thus I suggest reconsidering TypeScript.

(I only briefly mentioned this point in Slack but didn't really put forth any reasons behind it.)

**Comment by taoeffect** [comment]
> The current FlowType setup in this repo is not currently functioning (afaict)

AFAIK it's functional, just needs to have its errors fixed (#528).

> Significant parts of this codebase are not currently typed at all

Closing #528 will increase type coverage to what is necessary for flow to pass.

> * Most of FlowType is compatible with TypeScript, and the remainder is easy to convert
> * TypeScript has stronger tooling support (e.g. VS Code)
> * TypeScript has seen far more significant adoption than FlowType in the past couple years

These just aren't compelling enough reasons for us to make the switch at this point in time.
