### ISSUE TITLE
Update layout for chats to display more information

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1523]
### Problem

The chatroom layout currently is very limiting the amount of messages that are visible because of margins and padding:

![Screen Shot 2023-03-30 at 2 04 34 PM](https://user-images.githubusercontent.com/138706/228964220-59f2a937-0ba6-46da-bd27-6f60ff55dce5.jpg)

Most chat apps use smaller margins/padding between elements.

### Solution

Play around with all of the margins/padding for the entire layout, not only for the messages themselves, but the surrounding content, until more information is visible and it still looks good.

**Comment by leihla** [comment]
I've reviewed the designs and for Deskop, we should reduce the overall padding of chat elements from 40px to 24px. 
<img width="1512" alt="Screenshot 2023-05-01 at 15 27 01" src="https://user-images.githubusercontent.com/158178/235471132-537da57f-5a77-42d6-af7e-af077db722c5.png">
<img width="1512" alt="Screenshot 2023-05-01 at 15 27 14" src="https://user-images.githubusercontent.com/158178/235471147-9cc13bad-4d76-4fd9-8c5f-e3f4cd15f82a.png">


We also need to correct margins and padding of internal chat elements as the .c-divider which should have the margins removed and should be also within the 24px padding from the chat limits and for the general chat messages, always remove the margin-bottom of the last paragraph of the message.  See below


<img width="1442" alt="Screenshot 2023-05-01 at 15 49 53" src="https://user-images.githubusercontent.com/158178/235471427-af9150e4-516d-4a1b-922d-ad2ce9d30a87.png">

**Comment by taoeffect** [comment]
Thanks @leihla!

Some questions:

On which Figma designs did you update these margins/padding? Can you link to them so that I can direct either Alex or Sebin to implement? I checked on Figma and these were still at their old values:

![Screen Shot 2023-05-01 at 6 11 11 PM](https://user-images.githubusercontent.com/138706/235558393-2ce3c307-91bb-45e4-8aa1-1805a95ad61a.jpg)

Also, could you post screenshots like the above for what it looks like when there are consecutive messages from the same person?

**Comment by leihla** [comment]
Hey @taoeffect here's the figma links:

- https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?node-id=23766%3A267763&t=GI5k8apWohE2FTRk-1
- https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?node-id=23903%3A266312&t=GI5k8apWohE2FTRk-1
- https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?node-id=25142%3A271136&t=GI5k8apWohE2FTRk-1

**And a preview of multiple messages from the same person:**
<img width="825" alt="Screenshot 2023-05-03 at 10 20 03" src="https://user-images.githubusercontent.com/158178/235878306-d5f24c91-cf3d-40c9-82b7-c7de26947c95.png">

**Comment by taoeffect** [comment]
Great work @leihla! Closing in favor of implementation issue #1570 and assigning to @Silver-IT
