### ISSUE TITLE
Validations on SignUp form aren't triggered when LastPass fills in fields

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1525]
### Problem

When a user is using LastPass to fill in their information on the Sign Up form, the validations aren't triggered when they should be.

This can lead to confusion, where their username is automatically filled in with a capital letter, but they cannot sign up because the sign up button is greyed out.

It appears that the sign up button is disabled correctly by the validators, but the red error message telling the user that they cannot use capital letters isn't shown for some reason.

### Solution

Find out why the red error message isn't shown when the username field is autofilled by LastPass with a capital letter and fix it.

**Comment by Silver-IT** [comment]
@taoeffect, can you please upload the video if possible?

**Comment by taoeffect** [comment]
This is a problem @leihla ran into, I'll ask her.

**Comment by leihla** [comment]
@taoeffect @Silver-IT here's the video: https://drive.google.com/file/d/149MdOzt01ReJXL-NMDL3zvTdxhiTnunB/view?usp=drivesdk

**Comment by Silver-IT** [comment]
@leihla, nice video. I can see that it's `Log In` form. I will add that validation in the `Log In` form either.

**Comment by taoeffect** [comment]
@Silver-IT Although the video @leihla uploaded might have shown the problem with the Login Form, that's not the issue, as the original problem happened on the SignUp form. The problem was that Leihla's LastPass extension was filling out the fields in a way that was not triggering the validations at all.

@leihla if you can, maybe you could record another video that shows this with the SIgnUp form?

**Comment by Silver-IT** [comment]
Yeah, @leihla can you please upload the video that shows the issue with the SignUp form?

And I can see that the Chrome Extension is installed in your browser which automatically fills the input field.
I guess that Chrome Extension injects the script and updates the values of input fields to the previously-saved value in the following way.
```
document.querySelector('[name="username"]').value = 'Leihla'
```
As far as I know, it's not possible to listen to this change event and do the validation. I have already tested this kind of forced change which doesn't make any event and also that the `change` event is not handled.
So I think the validation could be checked when user click `Login` or `Sign Up` button.

cc: @leihla, @taoeffect

**Comment by taoeffect** [comment]
> So I think the validation could be checked when user click Login or Sign Up button.

That sounds like a great idea 👍

**Comment by Silver-IT** [comment]
It does the validation when user click `Login` or `Sign Up` button actually. But I have found one more problem.
Additionally, what we should take care of is that
**`this.form.username`(or `this.form.password`) is not updated when injected script updates the username(or password) input value.**
So I think `this.form` should get updated when user click `Login` or `Sign Up` button considering the case that input values could be updated by chrome extension and injected script.

**Comment by taoeffect** [comment]
@Silver-IT the main issue that Leihla was encountering was the SIgnup button was disabled, so she couldn't click it after the extension filled out the form

**Comment by Silver-IT** [comment]
@leihla, you uploaded the video showing your test in `Login` form.
But you said it was in `Sign Up` form in the description of this issue. Can you please upload the video showing your issue in `Sign Up` form?

**Comment by leihla** [comment]
@Silver-IT I've tested now and it shows an error saying the username cannot contain uppercase letters. 
<img width="654" alt="Screenshot 2023-05-23 at 09 41 29" src="https://github.com/okTurtles/group-income/assets/158178/f371a9c2-9c7c-4e3a-ab69-666783221a0e">

In the test I've made, it does take a while to show the error message on the username.

https://drive.google.com/file/d/1Fkr9qbCrnkhclitFRtOHDErIeCSqRUt4/view?usp=drivesdk

**Comment by Silver-IT** [comment]
@taoeffect, do you think what more can I do except add validation rules in `Login` form. I can see the validation works in `Sign Up` form.

**Comment by taoeffect** [comment]
@Silver-IT sure 👍

**Comment by taoeffect** [comment]
@leihla So it sounds like this isn't an issue...? The validations do work?

**Comment by leihla** [comment]
@taoeffect the validation from LastPass still doesn't work on the login screen, but on the Login screen I don't think we validate Uppercase for username. Besides "Invalid username or password" maybe we can add, make sure username is lower case.

https://drive.google.com/file/d/1EUQ9mwTgl6kaKDPEeLbmee2oRCDDTzNP/view?usp=drivesdk

**Comment by Silver-IT** [comment]
So @leihla, the problem is in `Login` page, isn't it?
If there are no issues in `SignUp` page, the only solution would be to add validation rules in `Login` page.
If there are any issues in `SignUp` page, I need to take a deep look again.

**Comment by taoeffect** [comment]
@Silver-IT yeah it sound like it's just the `Login` page, so yeah your PR looks good, I'll double-check this week!
