### ISSUE TITLE
Color palette update needed

### ISSUE THREAD

**Issue by Silver-IT** [okTurtles/group-income#1538]
### Problem

I guess a few colors are not determined yet in the color palette.
![image](https://user-images.githubusercontent.com/57976479/232347115-c6292f9f-4b79-4118-8fdc-696b9b8c25d8.png)

### Solution

- [x] Decide the colors and update Figma
- [x] Update the `frontend/model/settings.colors.js` according to the figma change

**Comment by leihla** [comment]
@Silver-IT I've updated figma with new colors. 


<img width="563" alt="Screenshot 2023-05-01 at 16 10 08" src="https://user-images.githubusercontent.com/158178/235474299-855317a8-97a8-4159-9cfd-bd308974797a.png">

figma: https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?node-id=3210%3A32947&t=zkvGIlDiziHDKdBr-1

**Comment by taoeffect** [comment]
Closed by @Silver-IT in some recent PR.

**Comment by Silver-IT** [comment]
It's in this PR. https://github.com/okTurtles/group-income/pull/1541
