### ISSUE TITLE
Update .git/config to fsck the objects

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#154]
### Problem

Git doesn't (or didn't) verify integrity of data.

https://groups.google.com/d/msg/binary-transparency/f-BI4o8HZW0/MDmnWideAgAJ

### Solution

Add this to `.git/config` (perhaps using a `preinstall` script or a git hook):

```
# for $deity's sake, check that anything we're getting is complete and sane on a regular basis
# https://groups.google.com/forum/#!topic/binary-transparency/f-BI4o8HZW0
[transfer]
    fsckobjects = true
[fetch]
    fsckobjects = true
[receive]
    fsckObjects = true
```

Everyone should have that in their global `~/.gitconfig` anyway.

**Comment by dotmacro** [comment]
Can we close this in favor of #359 ?
