### ISSUE TITLE
Create a proposal for changing the distribution date

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1543]
### Problem

If the wrong distribution date is accidentally set when the group is first created, there is currently no way except by recreating the group that this can be fixed.

### Solution

Create a way to fix this by passing a proposal. Allow the change to be applied immediately without voting if the group is currently in the first distribution period and the proposal is being created by the group creator.

**Comment by SebinSong** [comment]
@taoeffect I self-assigned this issue thinking there's been a design created for this, but cannot find it in our figma.
Is there one? if not, I think this should wait until it's made.

**Comment by taoeffect** [comment]
@SebinSong There isn't one, and it's up to you if you want to wait. I would imagine it would combine the existing designs for creating proposals with the [existing design](https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?node-id=24083%3A270160&t=vCChzv37QFhEASGc-1) for setting the distribution date using the dropdown. If you'd like to do that yourself without waiting for an official design, or wait for the design - either way I'll leave that decision up to you!

**Comment by SebinSong** [comment]
@taoeffect Ok, I will work on it that way then(combining the existing designs).

**Comment by Silver-IT** [comment]
@taoeffect, we should add two types of proposal here.
- Change distribution date
- Change currency [Not sure to add, or always disable it at the moment]
![image](https://github.com/okTurtles/group-income/assets/57976479/e27dae17-8444-4245-aa00-7c343fb4261e)

That `Change distribution date` will be visible only for group creator and only when the group is in the first distribution period. Right?

**Comment by taoeffect** [comment]
@Silver-IT It's visible to everyone, however, before we've entered the first distribution period the group creator is able to change it and have it applied immediately.

**Comment by Silver-IT** [comment]
Others can also create the proposal (to change distribution date) in the first distribution period. Then, it works just like the normal proposal. 66% should vote and agree to make it applied. Right?

**Comment by taoeffect** [comment]
> 66% should vote and agree to make it applied. Right?

It's whatever the currently voting threshold for the group is, just like all the other proposals.

Also, to be clear, the group creator can immediately apply the change while we're waiting to enter the first distribution period. If they chose the default date, it's about a 3 day waiting period (if I remember correctly).

**Comment by Silver-IT** [comment]
@taoeffect, I found a weird workflow.
If the group has less than 3 members, anyone(not only group creator) can change group settings by creating proposal.
- Change mincome
- Change voting rules
- Whatever

Is this our intended workflow? I think only group creator could do this.

**Comment by taoeffect** [comment]
@Silver-IT yeah you're right, we should restrict it to the group creator

**Comment by Silver-IT** [comment]
@taoeffect, we can change distribution date only before the first distribution period is not started.
Or is it possible to update distribution date in the second or third distribution period?

**Comment by taoeffect** [comment]
@Silver-IT Great question! Yes, you're right, it is safe only to change the distribution date before the first distribution has started. We should display an error message saying something like `Cannot change distribution date after we've entered the distribution period. In a future version this might change.`

**Comment by Silver-IT** [comment]
@taoeffect, I guess we should make notification after the `distribution date` is updated. Right?
