### ISSUE TITLE
Clear vuex state on logout

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1549]
### Problem

As @Silver-IT observed, `'gi.actions/identity/logout'` doesn't completely clear the vuex state on logout, and this could be causing issues in some Cypress tests, and just in general is bad hygiene.

### Solution

Delete the `logout` Vuex mutation, and create `'state/vuex/reset'` instead, and call `store.replaceState(initialState)` in there. Then, in `'gi.actions/identity/logout'`, instead of `sbp('state/vuex/commit', 'logout')` call `sbp('state/vuex/reset')`

**Comment by Silver-IT** [comment]
@taoeffect, I recommend to use **Object.assign** in `sbp('state/vuex/commit', 'logout')` just like how we did in `settings` and `notifications` `vuexModules.js`. So keep the current `'logout'` commit and update the content only.

I tried to use `store.replaceState` and got errors and it would be because `settings` and `notification` vuex states are all cleared.

**Comment by Silver-IT** [comment]
Additionally, I found one more issue that **ephemeral.finishedLogin** is not initiated when we log out. So it is always `yes` if the user logs in at least once, even he logs out, and try to log in again.

**Solution**
I think we should set it `'no'`, when the `LOGOUT` even is occurred. We can do this in `main.js`.
```
sbp('okTurtles.events/on', LOGOUT, () => {
    this.ephemeral.finishedLogin = 'no'
    ...
})
```

**Comment by Silver-IT** [comment]
These two updates in PR #1534 (vuex, finishedLogin) fixed the login issue in Cypress which was breaking many test cases.

**Comment by taoeffect** [comment]
@Silver-IT 

> These two updates in PR #1534 (vuex, finishedLogin) fixed the login issue in Cypress which was breaking many test cases.

I don't see the `this.ephemeral.finishedLogin = 'no'` in `main.js` in that PR?
