### ISSUE TITLE
ChatRoom UnreadPosition should not be updated while logging in

### ISSUE THREAD

**Issue by Silver-IT** [okTurtles/group-income#1553]
### Problem

If users join the chatroom, we don't care in the previous messages if they've read or not and we check the only new messages to decide if they are read or unread.
Meaning that while joining the chatroom, we should update unread message position to the latest message.
But the problem is that `sbp('chelonia/contract/isSyncing', contractID)` is used in `setReadUntilWhileJoining` function to check if it's joining in chatroom contract.
But we should take care that we also sync contracts when we log in. So after log in, the unread position is always set to the latest message. (This is bug)
Additionally, I think we should set the unread message position to the latest when user log in in a new device.

### Solution

1. `Joining` chatroom comes from the sideEffect functions of the group and mailbox contract.
2. ~~Login in a new device means `sbp('gi.db/settings/load', username)` returns `undefined`. We check this in `gi.actions/identity/login`~~.

We can use **vuex** or **okTurtles.data** to save if it's sign-in in a new device or join.

**Comment by Silver-IT** [comment]
@taoeffect, is this description clear to you?

**Comment by taoeffect** [comment]
@Silver-IT Yes it's much clearer now, thank you!

**Comment by Silver-IT** [comment]
I don't think we should take care of the previous settings from indexedStorage which we can get by calling `sbp('gi.db/settings/load', username)`. We need to take care of `sbp('chelonia/contract/sync', chatRoomID)` in `group` and `mailbox` contracts because this will be called in both cases; **join**, and **first login in a new device**.

**Comment by taoeffect** [comment]
>  Additionally, I think we should set the unread message position to the latest when user log in in a new device.

I think we should keep the unread messages synchronized across devices, so that if you lose your device and log in again you can be properly notified about all the unread messages you missed.

This suggests storing the unread message position in the user's mailbox contract.

**Comment by taoeffect** [comment]
>  Additionally, I think we should set the unread message position to the latest when user log in in a new device.

I agree that for now it's a good idea to save the unread positions locally in the Vuex store, local to each device.

In the future, after we've implemented state snapshots (#354), we can save them on the mailbox contract. This way, if a device is lost, you can see all your unread messages that you've missed on the new device after logging in. But for now let's save it on Vuex store so that we're not sending too many messages to the mailbox contract.
