### ISSUE TITLE
Markdown in chat

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1558]
### Problem

We have no way of styling chat.

### Solution

Support basic markdown rendering.

This will obviously need a new dependency. The usual rules for adding new dependencies apply:

- Find the dependency that accomplishes what we need to do with the absolute minimum amount of additional code
- Find the dependency that is extremely well written and self-contained
- Make sure to pick a dependency that has few bugs
- Make sure it has few if any other dependencies

**Comment by Silver-IT** [comment]
I think `markdown-it` library seems good. https://www.npmjs.com/package/markdown-it
It has only 5 dependencies and only a few issues remaining.

**Comment by SebinSong** [comment]
It's implementing all the text styling in blue boxes in below screenshot

<img src='https://github.com/okTurtles/group-income/assets/17641213/1fc1a460-3d09-410c-ac96-74fca63cae70' width='460' >

**Comment by SebinSong** [comment]
@taoeffect 
If you want to track the commit history for my weekly Todos, the feature branch:
[sebin/task/##1558-markdown-in-chat](https://github.com/okTurtles/group-income/commits/sebin/task/%23%231558-markdown-in-chat/)

**Comment by SebinSong** [comment]
[ DEV MEMO ]

Possibly helpful resources:
- https://github.com/hl037/vue-contenteditable

**Comment by SebinSong** [comment]
@taoeffect If you would like to track the commit history for my weekly Todos, the feature branch is:
[sebin/task/##1558-markdown-in-chat](https://github.com/okTurtles/group-income/commits/sebin/task/%23%231558-markdown-in-chat/)

**Comment by SebinSong** [comment]
[ DEV MEMO ]
Possibly helpful resources:
- https://github.com/hl037/vue-contenteditable

**Comment by taoeffect** [comment]
Closed by @SebinSong in #1815!
