### ISSUE TITLE
Mobile Chat UI improvements

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1562]
### Problem

Related to #1523, the mobile chat UI has an unnecessary border that takes up space:

![Screen Shot 2023-04-28 at 3 36 44 PM](https://user-images.githubusercontent.com/138706/235265088-e3c331fb-8a3c-470d-99fa-e2dd4d5d4578.jpg)

### Solution

Remove this border on all screens that don't have the side navbars.

**Comment by leihla** [comment]
@taoeffect updated in Figma
