### ISSUE TITLE
Impl: Update layout for chats to display more information

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1570]
### Problem

This is an implementation issue for implementing the design updates from #1523.

### Solution

Please implement the design/layout updates related to margin/padding mentioned in this comment: https://github.com/okTurtles/group-income/issues/1523#issuecomment-1532703769

Also, this [Mobile] update for how the chat looks: https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?type=design&node-id=26056%3A283397&t=WWXBArWhx0WmOPmp-1 - removes all the borders in chat mode to give more space

**Comment by taoeffect** [comment]
Edited to add:

> Also, this [Mobile] update for how the chat looks: https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?type=design&node-id=26056%3A283397&t=WWXBArWhx0WmOPmp-1 - removes all the borders in chat mode to give more space

**Comment by Silver-IT** [comment]
@leihla, @taoeffect, new mobile design (with no margins) is only for chat page, isn't it?
In Dashboard page for example, it will look like the following.
![image](https://user-images.githubusercontent.com/57976479/237037641-4cefe0e4-97f3-4578-927b-f57335661080.png)

**Comment by taoeffect** [comment]
@Silver-IT yes it's only for the chat. It's up to Leihla if she wants to change this aspect for mobile too. Mainly we needed it for chat.

**Comment by leihla** [comment]
@Silver-IT Yes, we were only changing the chat pages. We can maybe later change all of them, in that scenario in mobile we would probably need to reduce the border radius os the white sections.

**Comment by Silver-IT** [comment]
@leihla, @taoeffect, I think we should use the new layout only in `phone` and `tablet`.
To be honset, I prefer the previous design in `desktop`. Just shared two in `desktop` view.
![image](https://github.com/okTurtles/group-income/assets/57976479/d9dc80cf-6f46-43cc-bbe8-c89900710b03)
