### ISSUE TITLE
Create Vuex module for chat related settings

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1571]
### Problem

The `state.js` file is quite large still and we are slowly improving its organization. We've already moved a lot of state & mutations & getters into two separate vuex modules: `'~/frontend/model/notifications/vuexModule.js'` & `'~/frontend/model/settings/vuexModule.js'`, but the chat related settings are still in `state.js`

### Solution

Similar to how the notifications and settings vuex modules work, create a `model/chatroom/vuexModule.js` file & folder and move the chatroom related state/mutations/getters into that and update all dependent files.

**Comment by taoeffect** [comment]
Waiting for @corrideat's e2e-protocol PR

**Comment by SebinSong** [comment]
@Silver-IT Just assigned myself to this issue! Thanks.

**Comment by SebinSong** [comment]
Hi @taoeffect
In your opinion, should all the DM related getters (e.g. [`ourGroupDirectMessages`](https://github.com/okTurtles/group-income/blob/8d4a6b34fadfc35a5d9524ddb557e6f0e75b4a0c/frontend/model/state.js#L572C3-L612C5)) also be moved to chatroom Vuex module? At first I thought it was obvious to do so but then realised some of them are derived from the props & getters in the identity contract (`identity.js`).

EDIT:
The work is largely done and I've moved every DM related stuff to the vuex module for the chat there. If this is not what we want, I can revert this work back.

**Comment by taoeffect** [comment]
@SebinSong sorry for the late response. I don't have a good answer. I think improving the readability and organization of the code (as long as it doesn't break anything) is generally a good thing. If you managed to do that - great! 😄 👍
