### ISSUE TITLE
[Mobile] Notifications header position wrong

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1572]
### Problem

![notification-margin](https://user-images.githubusercontent.com/138706/236374158-45948a05-1b9a-43a0-875b-37db2e6e5dcc.jpg)

1. The position of the heading is wrong
2. The margins/padding on the list border are wrong

### Solution

Match the design:

![Screen Shot 2023-05-04 at 8 50 50 PM](https://user-images.githubusercontent.com/138706/236374231-feebabbc-c2ec-4d6d-8cb7-b4a9555b0e82.jpg)

**Comment by Silver-IT** [comment]
I have found that this is not only happening in Notifcations Modal. It happens almost all the modal.
`Add Income Detail`, `Archived Proposals`, `Group Members`, ...

So it seems like it's modal issue.
