### ISSUE TITLE
[Mobile] Reaction in chat broken

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1574]
### Problem

On Safari iOS. When clicking on a reaction:

![broken-reaction 1](https://user-images.githubusercontent.com/138706/236376184-6fe8b397-5053-4852-8c4c-d7e74c9d8313.jpg)

This is what happens:

![broken-reaction](https://user-images.githubusercontent.com/138706/236376199-310c2526-92e2-4d43-bbb8-fec4a45a88f4.jpg)

### Solution

Fix.

**Comment by dotmacro** [comment]
![image](https://user-images.githubusercontent.com/13082264/236385213-c80f968a-b316-4053-bec2-2a731c51c099.png)
On my mobile browser (iOS Safari), I can see the "add reaction" option (it looks like for @taoeffect it is behind the compose field), and tapping that does indeed pull up the emoji picker and let me choose an emoji reaction. However, the reaction does not appear anywhere -- not on the device with which it was added, nor on the other machine where I'm logged in, and they also do not appear to other logged in users.

**Comment by Silver-IT** [comment]
Nice catch. Thanks for detailed description, @taoeffect, @dotmacro.

**Comment by Silver-IT** [comment]
We can divide this issue into two parts.
- [ ] One is that `Menu is not displaying at the top of page`
- [x] The other is that `makeEmoticon event is emitted twice`.

The second issue is related to the `Click` event of `Menu-Item`. We didn't notice this before but I've just tested and can say `Click` event handler of all the MenuItems are executed twice.

**Comment by Silver-IT** [comment]
I have just relocated the first issue (`One is that Menu is not displaying at the top of page`) in the #1573 for the following reasons.
- Similar reasons I guess. They are all related to `TextArea` element. It happens in other pages too when user focus on `TextArea` element.
- In order to merge the PR #1589 soon.
- I can not reproduce this issue on my side so it's hard for me to fix it.
