### ISSUE TITLE
[Mobile] Multiple issues with dashboard page layout

### ISSUE THREAD

**Issue by dotmacro** [okTurtles/group-income#1577]
### Problem

Sub-problem 1: Elements are stacked, making it difficult to see what's going on in the header/nav section. 

![image](https://user-images.githubusercontent.com/13082264/236378917-a0fcf97a-2ff9-4639-b6ea-65cb5859c342.png)

a) The "i" menu icon overlays the group name, making it difficult to read the group name, and very difficult to tell there's a clickable "i" there rather than just smooshed group name text.

b) The hamburger menu overlays the group icon, and after it is expanded and collapsed, it also overlays the group name.

![image](https://user-images.githubusercontent.com/13082264/236378827-a8498251-637f-45ac-bbf0-80cba493027e.png)

Sub-problem 2: Implementation of menu anchoring isn't user-friendly
A pull-to-refresh (not applicable, but not sure how else to describe the over-scroll up) leaves the hamburger menu at the top of the screen. That seems fine. However, the "i" menu moves with the group name, still making it very hard to distinguish as a clickable menu rather than smooshed group name text. 

![image](https://user-images.githubusercontent.com/13082264/236378963-2b5a7e00-d63d-4f14-9b58-a672a8c25c66.png)

### Solution

Fix, per Figma designs.

**Comment by taoeffect** [comment]
Jinx! 😄  #1576
