### ISSUE TITLE
Member loses their income details after logging in on mobile??

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1579]
### Problem

A member logged into a group on desktop, entered their income details successfully and saved them.

They then logged in on the mobile device, and suddenly their income details were gone!

The messages this user sent to the database after updating their income details the first time included `'gi.contracts/group/inviteAccept'` (presumably from the mobile device), `'gi.contracts/group/joinChatRoom'` and `'gi.contracts/group/updateLastLoggedIn'`.

### Solution

Figure out why their income details got wiped. Keep in mind that during this time other users might have logged in as well and performed similar actions.

**Comment by taoeffect** [comment]
@Silver-IT I think I might have found the issue here thanks to @corrideat.

In `controller/actions/identity.js` there is this line:

```js
...encryptedAction('gi.contracts/identity/setLoginState', L('Failed to set login state.'))
```

It should be:

```js
...encryptedAction('gi.actions/identity/setLoginState', L('Failed to set login state.'))
```

And related calls should be updated accordingly to use the new selector name

**Comment by Silver-IT** [comment]
I think this issue is duplicated to the Issue #1575. The following is what I find as reason.
- The reason why income details are cleared is because the following line is executed.
```
Vue.set(state.profiles, meta.username, initGroupProfile(meta.identityContractID, meta.createdDate))
```
It's in the `process` function of `gi.contracts/group/inviteAccept`.
- Notification could be added only when the following line is executed.
```
sbp('gi.notifications/emit', 'MEMBER_ADDED', { // emit a notification for a member addition.
    createdDate: meta.createdDate,
    groupID: contractID,
    username: meta.username
})
```
It's in the `sideEffect` function of `gi.contracts/group/inviteAccept`.

**Comment by taoeffect** [comment]
> It's in the process function of gi.contracts/group/inviteAccept.

Indeed you are right! That's what caused this issue, in this case the user used the invite link again on their mobile device to login instead of just logging in, and that reset their profile!
