### ISSUE TITLE
"Oops, you entered 0 or a negative number" for non-number values

### ISSUE THREAD

**Issue by corrideat** [okTurtles/group-income#1586]
### Problem

1. When creating a new group, on step 3, if one enters a non-numeric value (e.g., 'abc'), the error shown is 'Oops, you entered 0 or a negative number'.

### Solution

The error message should say that an invalid value was entered, maybe with something to the effect of 'only positive numbers are allowed'

**Comment by Silver-IT** [comment]
I think we should not add more error message.
We can change validation order and display `The amount must be a number (e.g. 100.75)`.
