### ISSUE TITLE
Chat: "Add description" not linked

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1592]
### Problem

If a user is not the chatroom creator, we still show an "Add description" link, but it is not clickable:

![Screen Shot 2023-05-12 at 10 08 19 AM](https://github.com/okTurtles/group-income/assets/138706/b187ea8a-1a63-474a-80f6-644437905e43)

This is confusing.

### Solution

In this situation, we should do one of two things to address this. Either:

1. Remove the link/text completely
2. Allow it to be clicked but display an error saying "Only the chatroom creator is allowed to set the description"

**Comment by leihla** [comment]
We should remove the "Add description" link for anyone that is not a group admin.
