### ISSUE TITLE
Limit group membership to Dunbar's Number

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1614]
### Problem

In an upcoming blog post on Sybil attacks we'll explain why Group Income limits groups to [Dunbar's Number](https://en.wikipedia.org/wiki/Dunbar's_number).

### Solution

When a user attempts to invite a new member via proposal after the group has 150 members, display an alert saying: `Group sizes are limited to Dunbar's Number to prevent fraud.`

EDIT: On second thought, we may want to allow people who really want to create large groups to be able to do so. However, we should warn them about the risks of fraud that can happen if they choose to do this. So for this issue, instead of preventing them from creating a group with more members, we can post a warning using `gi.ui/prompt` that asks:

> Groups over 150 members are at significant risk for fraud, [because it is difficult to verify everyone's identity](https://en.wikipedia.org/wiki/Dunbar's_number).
> 
> Are you sure that you want to add more members?
>
> Yes / Cancel

With the default being "Cancel".

**Comment by dotmacro** [comment]
> So for this issue, instead of preventing them from creating a group with more members, we can post a warning

I disagree with this change because users have been conditioned to not read and consider error messages but rather to click whatever button makes the error message go away.  

We should stick with the original solution.

**Comment by taoeffect** [comment]
> I disagree with this change because users have been conditioned to not read and consider error messages but rather to click whatever button makes the error message go away.

That's why the default button is the cancel button.

> We should stick with the original solution.

The original solution prevents groups from adding more than 150 members, which is something we shouldn't do. We should warn them, but not prevent them from doing what they want if they really want it.

**Comment by taoeffect** [comment]
Compromise: https://github.com/okTurtles/group-income/pull/1648#pullrequestreview-1480624257
