### ISSUE TITLE
Minor bugs in dashboard

### ISSUE THREAD

**Issue by Silver-IT** [okTurtles/group-income#1621]
### Problem

1. Can not select the text inside the notification even though it seems like that the clickable area is the `income details`.
![image](https://github.com/okTurtles/group-income/assets/57976479/920c3c80-960c-47ad-9cc3-eae89f6b7443)
2. Currently it is `Different than` instead of `different from`. I think it should be `different from`.
![image](https://github.com/okTurtles/group-income/assets/57976479/bf20f983-3c55-41dc-b6d4-b049923381ef)

### Solution

Fix it

**Comment by taoeffect** [comment]
@Silver-IT 

> Always clickable notification

Could you elaborate a bit please on what the issue is?

> `Different than` instead of `different from`

It does say "different than" already in the screenshot?

**Comment by Silver-IT** [comment]
> Could you elaborate a bit please on what the issue is?

I wanted to select the text inside the notification, but it's always clickable and always display a modal.

> It does say "different than" already in the screenshot?

I think it should be `different from`.

**Comment by Silver-IT** [comment]
@taoeffect , updated the description. Sorry for my poor description.

**Comment by dotmacro** [comment]
> I think it should be `different from`

Either is ok, but as I understand it, `different from` is considered correct in British English and some propose it's also more correct in American English.  https://www.merriam-webster.com/words-at-play/different-from-or-different-than
