### ISSUE TITLE
Store payment periods as a doubly linked list

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1631]
### Problem

The way payment periods are stored at the moment is somewhat poorly designed.

It is based on the assumption that a payment period must be exactly 30 days long, and to move forward and backward through payment periods we add/subtract 30 days to a string to figure out what the next/previous period was.

Storing payment periods this way will break how we calculate streaks if:

- We change how long a payment period is
- We for some reason have to force the group into the next payment period (e.g. by calling `'gi.contracts/group/forceDistributionDate'`)

### Solution

It would be better if we stored payment periods as a doubly-linked list, with each payment period pointing to and referencing the previous and next payment period.

A payment period then:

- Is referenced by a UUID
- Contains within it the start date of the period (e.g. `startDate: "<ISOString>"`)
- Contains within it a pointer to the previous period (e.g. `prevPeriod: "<uuid>"`)
- Contains within it a pointer to the next period (e.g. `nextPeriod: "<uuid>"`, that is set once a new period is created)
- Contains its own UUID (e.g. `id: "<uuid>"`)

This fundamentally changes how we find and reference payment periods. For example, this code from `SupportHistory.vue` has to be changed:

```js
    periods () {
      const periods = [this.currentPaymentPeriod]
      for (let i = 0; i < MAX_HISTORY_PERIODS - 1; i++) {
        const period = this.periodBeforePeriod(periods[0])
        if (comparePeriodStamps(period, this.firstDistributionPeriod) < 0) break
        else periods.unshift(period)
      }
      return periods
    }
```

Similarly, anything using `paymentsByPeriod` needs to be updated. The way payments are stored in the archive needs to be updated too because it uses the period stamp in the key name:

```js
const archPaymentsKey = `payments/${username}/${period}/${contractID}`
```

And also this mysterious `payment.period` reference here in `RecordPayment.vue`:

```js
@click='openModal("PaymentDetail", { id: payment.hash, period: payment.period })'
```

Which I believe comes from this code in `'gi.contracts/group/archivePayments'`:

```js
newSentOrReceivedPayments[receivedOrSent].push({ hash, period, data, meta, amount: data.amount })
```

Of course, there are probably many other places that need to be updated.

**Comment by Silver-IT** [comment]
Nice issue it is. :+1:
