### ISSUE TITLE
Proposals from one group appear in another group sometimes

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1637]
### Problem

While showing the app to a friend, who created his own group and invited me (resulting in me being in 2 groups), I saw in his group a cancelled proposal from our group:

![Screenshot 2023-06-04 at 6 57 39 PM copy](https://github.com/okTurtles/group-income/assets/138706/f656d282-182d-41f1-887c-5880f03e0b69)

The steps to reproduce are similar to #1636, although I'm not exactly sure how to reproduce consistently.

### Solution

Find and fix bug. Proposals from one group should never appear on another group.

**Comment by Silver-IT** [comment]
If I re-describe this issue.

### Problem
All the archived proposals are shared between all groups.

### Solution
Check `'onProposalArchived'` function in `ProposalsWidget.vue` and how `this.ephemeral.archivedProposals` gets updated.
In `'onProposalArchived'` function and `currentGroupId` watcher, we should update `this.ephemeral.archivedProposals` calling a function `updateArchivedProposals` (which should be newly created).
And in `updateArchivedProposals` function, we should make `setTimeout` for the first archived proposal to be removed from the list in a day.

**Comment by Silver-IT** [comment]
Having checked this issue in the latest `master` branch, it appears to no longer be happening. I think this issue should be closed.
@taoeffect, you can close this issue.
