### ISSUE TITLE
Investigate localization alternatives

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#164]
### Problem

Our custom localization stuff:

- Might not support comments properly...
- There might be other libraries out there worth exploring that are maintained by someone else

This isn't a big problem, so marking this issue low-priority.

### Solution

Investigate the other stuff out there. Some links, feel free to comment with others:

- https://github.com/kazupon/vue-i18n
- https://github.com/Polyconseil/vue-gettext
- http://element.eleme.io/#/en-US/component/i18n

**Comment by sandrina-p** [comment]
By now I think we are pretty sure we'll stick with our solution, the `i18n` component. So, does it still make sense to keep this issue open?

**Comment by taoeffect** [comment]
Yep, good call!
