### ISSUE TITLE
Error after leaving a group related to chatroom

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1645]
### Problem

In my account on GIG, I was invited to join another group. Then I left that group. Some time later this error appeared:

> [chelonia] ERROR 'Error' in processMutation for <op_ae|21XWnNPCeyhCGgatyS7JHAjT1sjMetSyNTCPeKKaMxRvLWKkdW of 21XWnNHw72vW9p4KbNLXggv827ByRJM2iiBVyhLZuEBkwUGCbD>: Can not leave the chatroom which greg are not part of Error: Can not leave the chatroom which greg are not part of

<img width="1634" alt="Screen Shot 2023-06-07 at 12 48 42 PM" src="https://github.com/okTurtles/group-income/assets/138706/1c8bd125-a753-44d7-b2dd-75d2a3378416">

### Solution

Find and fix the problem.

**Comment by Silver-IT** [comment]
@taoeffect, can you please upload the groupincome.db which makes this error? I tried many times in different cases, I can not produce that error.

PS: The previous database file `groupincome.db` doesn't make this error.

**Comment by Silver-IT** [comment]
With this database(`groupincome.db`) you provided through DM recently, I can not produce the error your pointed.

**Comment by taoeffect** [comment]
@Silver-IT Let's go over this when you get back, as this is a fairly high-priority issue and we need to make sure we can fix this.

**Comment by Silver-IT** [comment]
Using the `groupincome.db`, I didn't get the error which is described here in this issue but I got another error.
![image](https://github.com/okTurtles/group-income/assets/57976479/5651812e-a988-4411-8b6e-06b417f6abee)

**Comment by Silver-IT** [comment]
Finally, I met the error and noticed that two `gi.contracts/chatroom/leave` messages are created.

**Comment by Silver-IT** [comment]
Oh, no. It's weird actually. I did produce that error only ONCE yesterday, and can not reproduce that error again yet.
It's needed to try more, but I guess this issue is related to the time taken to sync the contract (group or chatroom, not sure).

**Comment by Silver-IT** [comment]
YES. Finally, I got this error again and I can share the steps to reproduce. It's easy to reproduce this error using Multi-Container Addon in Firefox. Let's say we have three tabs (**tab1**, **tab2**, **tab3**) with different session.

Steps to reproduce
- **tab1**: user1 creates a group
- **tab2**: user1 logs in (so totally two sessions for user1)
- **tab3**: user2 joins the group
- **tab1**: user1 leaves the group
- **tab3**: BANG

**Comment by taoeffect** [comment]
Since this issue is related to low-level details @corrideat is working on, I've reassigned him to it

**Comment by taoeffect** [comment]
Closed in #1779
