### ISSUE TITLE
Remove duplicated notifications

### ISSUE THREAD

**Issue by Silver-IT** [okTurtles/group-income#1654]
### Problem
To join/leave group makes duplicated notifications.
![image](https://github.com/okTurtles/group-income/assets/57976479/47e6c7df-3179-4695-9601-47f7477b6d1e)
**Steps to reproduce**
- user1 creates a group
- user2 joins the group
- user3 joins the group
- user2 leaves the group
- user2 joins the group again and sees duplicated notifications

### Solution

Fix it

**Comment by Silver-IT** [comment]
I can see this is because of vuex, not of the workflow of contract or creating notifications.

So solution could be to remove all notifications of GroupA, when leaves GroupA.

**Comment by taoeffect** [comment]
Closed in #1722 (to `e2e-protocol`)
