### ISSUE TITLE
Move recent user activity (login dates) in server-side key-value store instead of in contracts

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1656]
### Problem

The group contract is currently being filled with `'gi.contracts/group/updateLastLoggedIn'` messages, which really are not that important and don't need to be kept in the contract chain, as that slows down contract syncing and wastes space unnecessarily.

Similar information (that is constantly updated) should be stored outside of the contract chain - directly in the key-value store.

### Solution

Remove `'gi.contracts/group/updateLastLoggedIn'` and instead set this information directly on the key-value store. Make sure to encrypt it using the latest group key, and make sure that only group members can write to these keys.

Create an API to use for this purpose - to create a secure key-value store that only authorized users can write to. Make sure that keys with the `private` prefix cannot be accessed / read via this API or via the `/file` API (or any other APIs that return the contents of the database).

EDIT: e.g. `_private_kvstore_{contractID}_{key}`

**Comment by corrideat** [comment]
How would this work? Because an advantage of actions is that they can do permission checking and validation, and there are also protocols in place to handle out-of-order messages, which are important for consistency.

I think that for the case of `updateLastLoggedIn`, it could make sense to split it for each member, or to store it for a key belonging to the identity contract instead.

**Comment by taoeffect** [comment]
Well, I don't think we want to store it under the member's identity contract, because we want it to be stored in a central place related to the group. We don't want each user to issue multiple queries to retrieve this information (one for each user in the group), rather instead do a single query to ask for this information, and receive the lastLoggedIn information for everyone in the group in a single request.

So it would need to be stored under the group contract.

It's true that there would be no solid permissions model here to restrict users from updating other user's lastLoggedIn info... but hopefully that's not a big deal.

Regarding consistency, that's a good point... it's theoretically possible that two users could log in at the same exact time, and both update that key to update their logged in info (which could theoretically result in one of their updates being ignored).
