### ISSUE TITLE
Expiry of general invitation link

### ISSUE THREAD

**Issue by Silver-IT** [okTurtles/group-income#1657]
### Problem
If the general invitation link is expired before 3 members joined, there is no way to get the invitation link in dashboard.

### Solution
I think `Add new members` modal should be opened, when user clicks `+ Add` button or creates `Add new member` proposal.

**Comment by Silver-IT** [comment]
@taoeffect, should we regenerate a new welcome invitation or just open `Add new member` modal in this situation?

**Comment by taoeffect** [comment]
@Silver-IT A lot of the code related to invites has been modified in `e2e-protocol` so let's just open the modal for now
