### ISSUE TITLE
Add 'Replace Photo' button to the 'Edit Avatar' Modal.

### ISSUE THREAD

**Issue by SebinSong** [okTurtles/group-income#1658]
### Problem
The Figma design for the issue #1491 is ready now.

![image](https://github.com/okTurtles/group-income/assets/17641213/71809dc1-2f0c-4608-b489-1464c9902e9b)

Link:
https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?type=design&node-id=25762%3A285577&t=d98TkE9zYYyezfEv-1

### Solution
Implement it.

**Comment by SebinSong** [comment]
Hi @leihla,
I have a question regarding the new flow in the design.


https://github.com/okTurtles/group-income/assets/17641213/b9bf07e4-619d-4f27-9b09-4d02adaf8526

As you can see from the video here, the existing flow in the app is that once you click on the 'change avatar' button, the app launches the browser's file selection interface and it's mandatory to select a file in order to open the 'Edit Avatar' modal.

**Q1.** Are we changing this here so that, if there's avatar already and the user clicks the 'change avatar' button, the app shows the 'Edit Avatar' modal straight away?
**Q2.** If the answer to **Q1** is yes, What does the user have to do to update their avatar to a new photo from this new 'Edit Avatar' Modal? Should this modal have another button(e.g. 'Select file') there that launches file selection interface?

<img src='https://github.com/okTurtles/group-income/assets/17641213/4253e223-bb6d-434d-8b96-426f377506cb' width='440'>


cc @taoeffect

**Comment by taoeffect** [comment]
@SebinSong While we're waiting for @leihla to respond, please go ahead and make it work this way:

- Instead of a "Remove Photo" button, rename it to "Replace Photo".
- When "Replace Photo" is clicked, the file selector dialog appears to select a different photo.

**Comment by SebinSong** [comment]
@taoeffect Thanks for the answer.
Don't you think that we need both 'Replace Photo' and 'Remove Photo' in that modal though? If we replace it, there is no way for user to reset their avatar to the default image. Or Would you have better idea than putting three buttons('Replace Photo', 'Remove Photo' and 'Save' button) in there?

**Comment by taoeffect** [comment]
@SebinSong I'm not a huge fan of 3 buttons... most dialogues only have two. I don't think it would look good to have 3 different buttons. Plus, the idea of "Remove Photo" is really saying, "Replace Photo with blockie" anyway, so it isn't really removing anything but doing a replacement of sorts anyway.

**Comment by SebinSong** [comment]
@taoeffect Ok, so sounds like you want the original solution then: having the 'Remove Photo' button and replacing the avatar with the blockie image if it's clicked. do you?

**Comment by taoeffect** [comment]
@SebinSong sorry for the confusion, no, I am suggesting *not* using the "Remove Photo" design at all. Having the "Remove Photo" button replaced with a "Replace Photo" button, that lets you pick a new one.

**Comment by SebinSong** [comment]
According to the discussion with Greg in the Slack group-chat, the task has now been changed to simply adding 'Replace Photo' button to the modal instead of implementing 'Remove avatar' feature in the app.

cc. @leihla
