### ISSUE TITLE
Typing indicator

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1665]
### Problem

It's often useful to know when someone is typing in the same chatroom as you.

### Solution

~~Use the server's key-value store to store this information on a key that maps to the chatroom contract, e.g. `<contractID>/typing`~~, and then use websockets to receive updates.

~~This issue depends on #1656 being closed first.~~ EDIT: no it doesn't. See commentary below. This issue can be closed simply by using the pubsub system.

**Comment by snowteamer** [comment]
Not sure if persisting this information on the server's key-value store is necessary at all. And this could incur quite many DB calls.

Instead, clients could just send `startTyping `and `stopTyping` websocket messages (with a suitable throttling), which would then be dispatched to room subscribers.

Agreed, clients would not immediately know who is typing upon reconnecting or joining a chatroom. They would have to wait for newer messages. But that's probably not a big deal compared to the saved DB calls and complexity.

**Comment by taoeffect** [comment]
@snowteamer It would be nice though if we could address this issue somehow:

> Agreed, clients would not immediately know who is typing upon reconnecting or joining a chatroom

Maybe an in-memory key-value store?

**Comment by taoeffect** [comment]
@snowteamer Thinking on this more, I agree with you. There's no reason to even use an in-memory key-value store for this. I agree that we can use the pubsub system alone to close this issue. There's a potential issue with using an in-memory key-value store in that it would open an attack surface to crash the server by putting tons of garbage there.

**Comment by SebinSong** [comment]
@taoeffect 
The feature branch for this task is **[sebin/task/#1665-typing-indicator](https://github.com/okTurtles/group-income/commits/sebin/task/%231665-typing-indicator)**, if you would like to track the commit history for weekly TODOs.

**Comment by taoeffect** [comment]
@SebinSong note that I just merged a relevant PR from @snowteamer - https://github.com/okTurtles/group-income/pull/1792 - please make sure to merge the latest changes from `e2e-protocol` to your branch as the pubsub system API is more generic now, and seems relevant to the typing indicator issue

**Comment by taoeffect** [comment]
Closed by @SebinSong in #1805!
