### ISSUE TITLE
'Anyone' invite link is accessible via 'Add members' menu even after it's revoked.

### ISSUE THREAD

**Issue by SebinSong** [okTurtles/group-income#1670]
### Problem
[ Steps to reproduce ]

1. `user-1` signs up and creates a group `G1`
2. `user-2` signs up and gets invited to the group `G1`.
3. `G1`'s group-size is < 3 now. then, revoke the 'anyone' invite link of `G1` using `user-1`.
<img src='https://github.com/okTurtles/group-income/assets/17641213/e675db00-b48b-4187-b24e-db80a027d24e' width='460'>

4. After it's revoked, click on 'propose adding a new member' menu below it.
<img src='https://github.com/okTurtles/group-income/assets/17641213/2bc6dc20-cdd5-417d-9346-6c8fe2015a74' width='460'>

5. The modal still has the revoked invite link in it.
<img src='https://github.com/okTurtles/group-income/assets/17641213/9ac50c81-b502-40d5-a9cd-81853910f122' width='460'>

### Solution
Discuss the expected behaviour of this case and make a fix.

**Comment by SebinSong** [comment]
@taoeffect 
As a fix for this issue, Should we make it impossible to revoke the 'anyone' link if the number of group members is < 3?

**Comment by taoeffect** [comment]
@SebinSong 

>  As a fix for this issue, Should we make it impossible to revoke the 'anyone' link if the number of group members is < 3?

That sounds like an easy fix! Go for it! 😄
