### ISSUE TITLE
Creating DMs on mobile is confusing - needs button

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1680]
### Problem

Mobile users are used to tapping things. It's not clear here how the DM group is supposed to be created:

![Screen Shot 2023-07-28 at 10 15 37 AM](https://github.com/okTurtles/group-income/assets/138706/7e82dd91-eea3-40d5-ba0f-a9759cb3a39a)

Normally there is a button somewhere that you tap to create the DM. The user might be confused and not realize they need to press the "return" key.

### Solution

On both mobile *AND* desktop, add a button, either inside of the input field (once at least 1 user has been entered into the input field), or outside of it just below (on mobile) or next to it (on desktop) that says `Create`.

**Comment by SebinSong** [comment]
While investigating this issue, I found this bug too. Will include a fix for it as well when sending a PR.

<img src='https://github.com/okTurtles/group-income/assets/17641213/9b92efce-de30-46fb-91b6-29bede44e03d' width='430'>

cc. @taoeffect

**Comment by taoeffect** [comment]
Nice find @SebinSong !
