### ISSUE TITLE
Manifest not found error upon contract file change in development 

### ISSUE THREAD

**Issue by snowteamer** [okTurtles/group-income#1692]
### Problem

A 404 Not Found error related to chelonia/private/loadManifest sometimes occurs after saving a contract file change in development, and the page is either blank or an alert saying "contract sync error" pops up.

#### Steps to reproduce:
- Run `grunt dev` without persistence enabled, i.e. `GI_PERSIST` should not be set
- Open the app in the browser
- Create an user account
- Save a change to e.g. `group.js`. The change must result in a new version of the file, and must not match any previous version of it, so that a new manifest is generated.
- When the app reloads, the page stays blank and the following error shows up:
![image](https://github.com/okTurtles/group-income/assets/64228468/6b8ca306-6494-4276-b70f-49bd5d3ae53f)

Manually reloading a second time doesn't help, only rebuilding the app does.

### Solution

 `manifest.json` is automatically updated on contract file change, but maybe contracts are not re-deployed accordingly.

**Comment by taoeffect** [comment]
~~I am not able to reproduce this.~~ EDIT: see comment below

You're running this in WSL, right?

Perhaps it's some Windows related quirk...

**Comment by snowteamer** [comment]
Yes I am, so that's possible. It could also be caused by a Linux vs MacOS difference

**Comment by taoeffect** [comment]
@snowteamer Woah - scratch that! I **am** able to reproduce it!

Sorry, you're right I had to make a more substantial change to the `group.js` contract — adding comments wasn't enough. Now I get the same error! 😮 

I'm 99% certain this used to work just fine. So I'm guessing some recent change to Gruntfile.js probably broke things.
