### ISSUE TITLE
Remove "Private DMs", "Group DMs" everywhere and use "DirectMessages" instead

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1697]
### Problem

The difference in the code between "Private DMs" and "Group DMs" is causing many problems both conceptually and otherwise with the `e2e-protocol` branch.

There should be no difference between these two. "Private DMs" **are** Group DMs with a group of 2.

### Solution

1. Remove all code related to "Private DMs" and replace with "Group DMs" only
2. All DMs must have a `privacyLevel` of `PRIVATE`, not `GROUP`.
3. The `ChatMembers.vue` component is named `GroupMembers`. This is wrong and causing confusion because there is already a component called `GroupMembers`. All components **must** have the same name as the file name. Fix this by renaming the component to `ChatMembers`.
4. Fix all UI issues that result.

**Comment by Silver-IT** [comment]
Since we would have only `Group DMs`, and no `Private DMs`, should we remove the word `group` either?
And just name it `DirectMessages`. What do you think, @taoeffect?

**Comment by taoeffect** [comment]
@Silver-IT Yeah that sounds good 👍

**Comment by taoeffect** [comment]
Closed in #1709 and merged to `e2e-protocol`
