### ISSUE TITLE
Setup Travis CI

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#17]
Depends on #8.

**Comment by AnObfuscator** [comment]
Added Travis CI file here:
https://github.com/okTurtles/group-income-simple/pull/26

**Comment by taoeffect** [comment]
@AnObfuscator see my comment there. also don't forget that this issue depends on #8, which should now be much easier to do because #24 was done. I don't want to setup travis until `npm test` (which should just be a script alias for `grunt test` in `package.json`) works, as otherwise every PR will have a message on it saying that there's an issue with the PR.

**Comment by AnObfuscator** [comment]
This should be ready to go, thanks to #8 being closed and #26 being merged. Just need to enable this repo in Travis CI by someone with appropriate privs.
