### ISSUE TITLE
Switch to Webpack

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#170]
### Problem

I spent several hours on #169 trying to get rollupify to work, and failed. The almost-but-not-quite-working solution was beginning to become incredibly ugly and unwieldy:

```diff
   function gencfg (out, paths, isLazy) {
     var c = {
       options: {
-        transform: [script2ify, 'vueify', ejsify, 'babelify'],
+        // NOTE: THE ORDER HERE MATTERS! Transforms are applied LEFT->RIGHT
+        // https://github.com/nolanlawson/rollupify#using-alongside-other-transforms
+        // transform: [script2ify, 'vueify', ejsify, 'babelify'],
+        transform: [script2ify, ejsify, ['rollupify', {
+          config: {
+            plugins: [
+              require('rollup-plugin-vue')({compileTemplate: true}),
+              // require('rollup-plugin-babel')({exclude: 'node_modules/**'}),
+              require('rollup-plugin-babel')({
+                exclude: 'node_modules/**',
+                babelrc: false,
+                presets: [["es2015", {"modules": false}], "stage-3"],
+                plugins: ["transform-flow-strip-types", "transform-inline-environment-variables", "transform-class-properties", "external-helpers"]
+              }),
+              require('rollup-plugin-node-resolve')({
+                jsnext: true,
+                preferBuiltins: true,
+                browser: true
+              }),
+              require('rollup-plugin-commonjs')({
+                include: 'node_modules/**'
+              })
+            ]
+          }
+        }]],
```

Note to mention a bunch of extra dependencies:

```json
    "babel-plugin-external-helpers": "6.22.0",
    "rollup-plugin-babel": "2.7.1",
    "rollup-plugin-commonjs": "7.0.0",
    "rollup-plugin-node-resolve": "2.0.0",
    "rollup-plugin-vue": "2.2.19",
    "rollupify": "0.3.9",
```

### Solution

By switching to Webpack we should be able to get the rollup features without having to pull our hair out. And we'll be able to simplify our grunt file. Maybe.

- Webpack + TypeScript: https://webpack.js.org/guides/webpack-and-typescript/ (#151)
- We'll get rollup's [tree-shaking in Webpack 2](http://www.2ality.com/2015/12/webpack-tree-shaking.html)
- ~~Make sure TypeScript + Babel work with Webpack~~ Apparently [there's not much need to use Babel with TypeScript!](https://blog.mariusschulz.com/2016/12/09/typescript-2-1-async-await-for-es3-es5). But if we need it for some reason anyway, [there's this](https://www.gurustop.net/blog/2015/10/27/babel-typescript-compiler-gulp).
- Vue supports hot module reloading with it quite well
- While we're being hip, maybe consider switching to gulp as well (or npm scripts)

EDIT: More notes:

- [`vue init webpack my-project` now scaffolds the project with Webpack 2!](https://twitter.com/vuejs/status/827658207858397185)

**Comment by danawoodman** [comment]
I'd be down to take this guy on

**Comment by danawoodman** [comment]
My thought is to create a directory along side `frontend` (maybe `client`?) and create a very basic webpack + vue implementation and then selectively start moving things over so we can make sure we’re migrating everything right. There are a lot of moving parts and trying to get it working with the current codebase may be a rabbit hole. Might be best to just transfer things over file-by-file till every has been moved. Thoughts?

**Comment by taoeffect** [comment]
> Thoughts?

I'd like to do a pre-planning / chat before any such work begins, to make sure it's necessary etc.

**Comment by taoeffect** [comment]
Stale. See #456.
