### ISSUE TITLE
Verify / ensure that this.latestEvents in ChatMain *always* has event from the correct chatroomId

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1700]
### Problem

While debugging problems with `ChatMain.vue`, @corrideat and I discovered that right now it's not 100% clear that `this.latestEvents.push(..)` always pushes an event from the right chatroom.

`this.latestEvents.push(..)` is called in two places:

1. `listenChatRoomActions` - which is called (in his branch) from `EVENT_HANDLED`. There is a check to ensure that `contractID === this.summary.chatRoomId`, however, it isn't clear that this necessarily means that `this.latestEvents` has the events for `contractID`
2. `renderMoreMessages` - uses a mixture of `this.messageState.prevTo` and `this.currentChatRoomId`, but again it's not clear that `this.latestEvents` corresponds to those. Are we even 100% sure that `this.messageState.prevTo` and `this.currentChatRoomId` correspond to each other?

### Solution

1. Investigate all of these questions.
2. Either write a proof below that `this.latestEvents` always corresponds to the correct chatroom, or modify the code so that it's guaranteed to be the case.

Please note: if you are making any code changes, those code changes **must** happen on a branch off of [`e2e-protocol-ricardo`](https://github.com/okTurtles/group-income/tree/e2e-protocol-ricardo) — **NOT** `master`!

**Comment by Silver-IT** [comment]
Nice catch, @taoeffect and @corrideat.

I have also discovered the same problem several times and fixed several stuff causing this issue. The reasons I remember were
1. Wrong naming of the key when saving data in storage
2. Redundant calling `sbp` functions to get the events
3. ...

Hope this is helpful.

**Comment by taoeffect** [comment]
Closed in #1709 and merged to `e2e-protocol`
