### ISSUE TITLE
Feature: Export payments history as CSV

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1704]
### Problem

To make it convenient to use the app with accounting programs for whatever needs users may have, we need a way to export the data to a more usable format, like CSV, and we currently have no such feature.

### Solution

Add a link or button to the "Completed" and "Received" tabs that says "Export.", that when clicked saves a `.csv` file of all of the received or sent transactions. Remember that some users might have both tabs available (because they switched from being a pledger to a receiver or vice versa).

**Comment by SebinSong** [comment]
Once the design for this functionality is ready, please give me a heads up.

**Comment by SebinSong** [comment]
@taoeffect 
Until Leihla creates the design, this is going to be a temporary button that extracts **all** (not sure if there will be a filter option that selects the period range and stuff) payment items into a CSV. 

<img src='https://github.com/okTurtles/group-income/assets/17641213/9ef97163-0c14-419d-9acd-1e9199845d92' width='420'>

**Comment by leihla** [comment]
@SebinSong I've added the designs for export payments to figma. 

Basically we'll add a button to export to the table, and a modal to select the payment period. I've created the period by year, but we could select by distribution date. In the dropdown should be a "All" option either way.

<img width="720" alt="Screen Shot 2023-09-12 at 12 15 04" src="https://github.com/okTurtles/group-income/assets/158178/05dd4d4b-99f9-4f86-ad6b-dcb99636c226">

<img width="717" alt="Screen Shot 2023-09-12 at 12 15 11" src="https://github.com/okTurtles/group-income/assets/158178/1c3113fa-729f-4ada-ad21-3ecce0c1b13c">

Regarding the CSV itself, it should have all the fields that appear on the payment details. Are you thinking of having all payments in the same sheet or separating the sheets by sent and received? Also, will the Todo appear in the CSV as well?


<img width="320" alt="Screen Shot 2023-09-12 at 12 20 37" src="https://github.com/okTurtles/group-income/assets/158178/5314bd45-2166-4eff-af02-c433c07b3e30">

**Comment by SebinSong** [comment]
Thanks @leihla, 

Regarding this,
> Are you thinking of having all payments in the same sheet or separating the sheets by sent and received? 

I was thinking of making them downloadable as a separate file depending on which tab is currently active. For example, if the button is clicked while the user is in 'Sent' tab, it only put together payment items in 'Sent' table.

What's your thoughts on this @taoeffect ?

**Comment by taoeffect** [comment]
@SebinSong 

> I was thinking of making them downloadable as a separate file depending on which tab is currently active

I agree, with the additional suggestions:

1. Make it clear that the currently selected tab is what decides what is being exported by setting the title of the modal that appears (e.g. when "Sent" is selected, the modal should say "Export Sent Payments")
2. There should be a checkbox in the modal to export all periods that disables the dropdown when checked. I added this as a request here: https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN?node-id=26552:97082&mode=design#553987744 /cc @leihla

**Comment by SebinSong** [comment]
@leihla , @taoeffect 
I was adding the 'Export CSV' button to the table and as you can see from the below screenshot, the available space on the right side of the tab menus is not wide enough that the buttons are forced to move down below them, which makes it look ugly.

<img src='https://github.com/okTurtles/group-income/assets/17641213/195b9f8c-4a3b-4ea5-b4b6-3bd4d502e4f2' width='440'>

Besides that, if a user ever switches from 'pledger' to 'receiver', they can end up having all three menus(Todo, Sent, Received) rather than two and in this case the available space will be narrower.

Do you guys think the position of 'Export CSV' button should be moved to somewhere else that won't have this problem?

**Comment by taoeffect** [comment]
@SebinSong i agree, can you try moving it below the table?

**Comment by SebinSong** [comment]
@taoeffect 
I have moved it down the table but let me know if you think there is better place to put it.

<img src='https://github.com/okTurtles/group-income/assets/17641213/9773fee6-1cc9-40ff-8b35-458c48baad78' width='480'>

EDIT:
Also, regarding your comment in figma saying,

 > Can you add a checkbox here that says: "Export all periods" and when checked, disables the dropdown?

I've added below checkbox next to the dropdown label, but likewise let me know if you think there is better place.

<img src='https://github.com/okTurtles/group-income/assets/17641213/8ed0cdc6-4bf3-4503-97c9-2a3157577826' width='480'>

**Comment by taoeffect** [comment]
@SebinSong 

![s1](https://github.com/okTurtles/group-income/assets/138706/158c7159-2bb1-412d-9f09-d67f2b1b378c)

![s2](https://github.com/okTurtles/group-income/assets/138706/33faf18f-6210-4e9a-8d61-13adee5b5ed0)
