### ISSUE TITLE
Chatroom doesn't save the previous scroll position

### ISSUE THREAD

**Issue by Silver-IT** [okTurtles/group-income#1711]
### Problem

When a user enters the chatroom, it should scroll to the last position where the user was viewing.
But it doesn't save the previous scroll position and only scrolls to the bottom.
It only happens in **e2e-protocol** branch, not **master** branch.

### Solution

WORK ON **e2e-protocol** branch or other branch which is created from it, and fix it.

**Comment by taoeffect** [comment]
Closed in #1730 by @Silver-IT
