### ISSUE TITLE
Duplicated joining group

### ISSUE THREAD

**Issue by Silver-IT** [okTurtles/group-income#1715]
### Problem

Steps to reproduce
- user1 creates a group
- user2, user3 joins the group
- user1 proposes to add a new member user4
- user2 [, user3] accepts the proposal and logs out
- an invitation link is generated for user4
- user2 opens the invitation link (for user4) and logs in (NOT sign up)
- wrong notification, wrong message in General chatroom, wrong joinedDate in group profile, ...

### Solution

**Activity**
- If the group member opens the invitation link and tries login, nothing should be happened except login.
- If the group member opens the invitation link and tries login, error message should be displayed, something like "You have already joined the group".

**Invitation link validation**
- Should keep valid
- Should turn to invalid

@taoeffect, what do you think is the best solution?

**Comment by taoeffect** [comment]
I think these are the correct answers:

> If the group member opens the invitation link and tries login, error message should be displayed, something like "You have already joined the group".

> [Invitation link] Should [be kept] valid

Also, question for you: how is it that user2 was able to open the invite link in the first place? As far as I know, the invite link is never shown to user2, but only to the person who created the proposal.

**Comment by Silver-IT** [comment]
> Also, question for you: how is it that user2 was able to open the invite link in the first place? As far as I know, the invite link is never shown to user2, but only to the person who created the proposal.

Yeah, that's correct. It never shown to user2.
While I was working with the issue #1645, I created a proposal for new member and copied the invitation link. And then opened it in the another tab (using Multi-Container Addon in Firefox) which was wrong tab. And noticed weird problems.

**Comment by Silver-IT** [comment]
If I simply the steps to reproduce,

- u1 signs up and creates a group
- u1 copies the invitation link
- u1 opens a new browser and goes to the invitation link and do **log in**

**Comment by Silver-IT** [comment]
> If the group member opens the invitation link and tries login, error message should be displayed, something like "You have already joined the group".

@taoeffect, I can see that the existing joining workflow is designed to go to the dashboard if the group member tries to open invitation link. So, I don't think we should not create another screen for `You have already joined the group`. Is that fine?
PS: Sorry for making questions [in here](https://github.com/okTurtles/group-income/issues/1715#:~:text=%40taoeffect%2C%20what%20do%20you%20think%20is%20the%20best%20solution%3F) before enough investigation.

**Comment by taoeffect** [comment]
> So, I don't think we should not create another screen for `You have already joined the group`. Is that fine?
PS: Sorry for making questions [in here](https://github.com/okTurtles/group-income/issues/1715#:~:text=%40taoeffect%2C%20what%20do%20you%20think%20is%20the%20best%20solution%3F) before enough investigation.

Yeah, that's no problem 👍 

And sorry for not noticing this question until just now!

**Comment by taoeffect** [comment]
I'm pretty sure this has been closed by the recent changes in `e2e-protocol-ricardo`, please let me know if that's not the case.
