### ISSUE TITLE
Find out precise space savings (if any) of protobufs in localforage

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#172]
### Problem

We wanna make sure the log has plenty of room for events, but we don't know whether protobufs or [objects via the "Structured Clone Algorithm"](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm) use less space in IndexedDB.

### Solution

Either find an API to measure the size of objects, or find an API to measure the size of the entire IndexedDB log, and use that to figure out which is better in terms of savings, and by what percentage.

Possibly relevant links:

- http://www.andygup.net/calculate-size-of-indexeddb-database/
- https://stackoverflow.com/questions/26257183/detecting-available-storage-with-indexeddb
- https://www.w3.org/TR/IndexedDB/
- https://w3c.github.io/IndexedDB/
- https://www.raymondcamden.com/2015/04/17/indexeddb-and-limits
- https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm

**Comment by vijayee** [comment]
Ok so this was surprising. I conducted this test with completely empty IndexedDB's in chrome for each serialization and then measured the size of the db through chrome. It appears that the native encoding in IndexedDB is smaller than the protobuf serialized version

protobuf: 10.1kb 
native:  3.3kb
Steps to produce:
I used the group creation page to create a group.
You must first empty your IndexedDB using these instructions
```
In Chrome, go to "Settings" (or "Preferences" under the Chrome menu)
Click "show advanced settings" (at the bottom of the page)
Go to "Privacy" > "Content Settings" > "All cookies and Site Data" > find the domain where you created the IndexedDB
Hit either the "X" or click "Indexed Database" > Remove
```
In this same menu there will be a size report of the IndexedDB instances for a domain. You will use this to take the total size.

Start your dev instance and navigate to the Group Creation page and create a group with  the following data.

```
Object {version: "0.0.1", type: "Group", parentHash: "", data: Object}
data
:
Object
changePercentage
:
"58"
contributionPrivacy
:
"Very Private"
creationDate
:
"2017-02-07T17:23:12.966Z"
founderHashKey
:
"alsdfjlskdfjaslkfjsldkfj"
groupName
:
"The Villains"
incomeProvided
:
"2564"
memberApprovalPercentage
:
"73"
memberRemovalPercentage
:
"71"
openMembership
:
true
__proto__
:
Object
parentHash
:
""
type
:
"Group"
version
:
"0.0.1"
__proto__
:
Object
```
You may then navigate back to the same page you used to delete you IndexedDB initially and  find the current size. Delete the instance again and repeat the process for the next serialization
