### ISSUE TITLE
Group icon not updated in Group Switcher when group name updated

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1735]
### Problem

![Screenshot 2023-09-22 at 9 32 26 AM](https://github.com/okTurtles/group-income/assets/138706/5d73a4bf-52af-4d34-9d5c-4d14868ea240)

*Screenshot: "U" is shown instead of "T"*

Scenario:

- u1 is in group "A" and invites u2 to join "A"
- u2 joins and also creates their own group
- u1 modifies their group name form "A" to  "B"
- u2 still sees "A" in the group switcher

This happens when groups do not have profile icons.

### Solution

Update the letter icon in the switcher as needed.

**Comment by Silver-IT** [comment]
@taoeffect, it's not a letter. It's a picture, and it is not changed on the `u1`'s side either. In order to update it, it is necessary to upload another picture.

**Comment by taoeffect** [comment]
@Silver-IT Yes go ahead 👍

**Comment by Silver-IT** [comment]
So should we close this issue?
