### ISSUE TITLE
[e2e protocol] Welcome screen is not supposed to show the side menu

### ISSUE THREAD

**Issue by SebinSong** [okTurtles/group-income#1738]
### Problem

in `e2e-protocol` branch, Welcome to 'Group name' screen has this bug where it shows the side menu.

<img width='580' src='https://github.com/okTurtles/group-income/assets/17641213/5f65ba92-a4d5-47e5-9a17-79d5c16a255c'> 

cc. @taoeffect 

### Solution

Fix it.

**Comment by taoeffect** [comment]
I think the reason for this was that if there was an error while joining groups we wanted the user to still be able to:

- Access the menu to log out
- Access the menu to see the error logs
- Access the menu to perform other actions if necessary (that might be added in the future)
- EDIT to add: When a user is part of multiple groups, it's useful to display part of the navigation while they're waiting in the "pending lobby"

**Comment by taoeffect** [comment]
Closed by #1748

Also forgot to mention one more reason:

- When a user is part of multiple groups, it's useful to display part of the navigation while they're waiting in the "pending lobby"
