### ISSUE TITLE
Set priority of groupId

### ISSUE THREAD

**Issue by Silver-IT** [okTurtles/group-income#1741]
### Problem

Since the process to join group is updated, user could have two types of groups (in their `state.contracts`).
One is the group which user has already successfully joined, and the other is the group which user is waiting the keys to join.
If the users try to login in a new browser or kicked from the current group by someone else, they should be redirected to anther group. So which group should be selected?
If a user has these two types of groups, the one of fully-joined groups should be set as the next `currentGroupId`.
But this logic is not implemented in the current code base.

### Solution

Implement the logic in the function `'gi.actions/identity/updateLoginStateUponLogin'`.
Especially, inside the following `if` statement.
```
if (!state.currentGroupId) {
  ...
}
```
This logic should also be implemented in the `sideEffect` of `'gi.contracts/group/removeMember'`.

**Comment by taoeffect** [comment]
Closed in #1773
