### ISSUE TITLE
Disable buttons and add spinner to them

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1742]
### Problem

In various parts of the app, there are buttons that perform operations that are asynchronous.

For example, when creating a DM in `e2e-protocol` branch, it takes a while to create the contracts and dismiss the modal. During this time the creation button should be disabled so that it cannot be clicked twice accidentally. However it is not:

![Screenshot 2023-09-27 at 10 28 08 AM](https://github.com/okTurtles/group-income/assets/138706/cbe62881-769e-4de3-b31a-d4d3d9b3ae99)

### Solution

On a branch off of the `e2e-protocol` branch, go through the app and check every button that creates contracts or performs any sort of long-running operation.

Make sure that the button cannot be clicked twice while the operation is running, and that it displays a spinner like this:

![Screenshot 2023-09-27 at 10 29 21 AM](https://github.com/okTurtles/group-income/assets/138706/8a18cad7-89a0-4591-a702-0bb80f11bdf3)

Make sure the buttons are **immediately** disabled when they are clicked.

**Comment by SebinSong** [comment]
More places in the front-end code (other than `NewDirectMessageModal.vue`) where I spotted the same issue:

- [x] `NewDirectMessageModal.vue`
- [x] `CreateNewChannelModal.vue`
- [x] `EditChannelDescriptionModal.vue`
- [x] `SendThankYouModal.vue`
- [x] `PollToVote.vue`
- [x] `ChatMembersAllModal.vue`

**Comment by taoeffect** [comment]
Closed in #1750
