### ISSUE TITLE
Error notification system

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#175]
### Problem

Currently there is no notifications system to inform the user of errors (for example, failed group creation, or going offline/online, etc.).

### Solution

- **First: brainstorm an API for a class based on categorizing all the possible types of errors / infos / warnings that the frontend might experience.** What needs to be shown to the user and how? What should be logged? etc.
- Discuss, research, propose, and implement a generic frontend-wide notification system for logging and displaying errors and info messages to the user. First look at how other apps do it (e.g. Slack) and also what they use.
- Look for a modern & Vue-friendly framework for this. There's problem already one designed specifically for vue here: https://github.com/vuejs/awesome-vue (just search for "notification", there are several things there, including something called vue-bulma, which even has [vue-bulma-notification](https://github.com/vue-bulma/notification)).
- Also make sure to catch all uncaught errors/exceptions. [`errorHandler`](https://vuejs.org/v2/api/#errorHandler) works for vue-specific errors. Make sure to catch others too.

Some dialog helpers:

- http://bulma.io/documentation/components/modal/
- https://github.com/javisperez/vuedals
- https://github.com/euvl/vue-js-modal
- https://github.com/javisperez/vue-dialog

Related:

- #610 - do this first

**Comment by taoeffect** [comment]
*Updated notes above.

**Comment by sandrina-p** [comment]
Should this notifications system also inform the user about other stuff besides errors ? (info, messages, warnings, reminders, etc.. ) ? Implementing that with a solid design guidelines would be ✨

**Comment by taoeffect** [comment]
Yes, look to Slack & Discord for inspiration.

**Comment by dotmacro** [comment]
Can we close this in favor of #688 & #689 ?

**Comment by taoeffect** [comment]
@dotmacro I see why it might be a good candidate for closing, but for now let's keep it open since those issues refer to specific components of an error notification system, and this refers to the entire system itself

**Comment by sandrina-p** [comment]
We have Erros system pretty munch handled thanks to #788, #688 and #595. Can we close this?

**Comment by taoeffect** [comment]
Yep!
