### ISSUE TITLE
[Bug] Dismissing a payment causes user to get banned

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1751]
### Problem

1. Set up a group with a mincome of 1000 and 3 users and add income details, with u1 pledging $200, u2 with $800 income (needing $200), and u3 with income $750 (needing $250).
2. Once all income details are entered, enter the following command into the console for u1:

    ```
    sbp('gi.actions/group/forceDistributionDate', { contractID: sbp('state/vuex/state').currentGroupId })
    ```

3. Then click the "TODO" tab, and click the 3 dots to bring up the menu next to a TODO. Click "Dismiss this payment":

![Screenshot 2023-10-04 at 9 32 15 AM](https://github.com/okTurtles/group-income/assets/138706/3488b273-20fa-4bf9-93e4-7cfcc7df376e)

You should see the following errors in the console:

![Screenshot 2023-10-04 at 9 31 29 AM](https://github.com/okTurtles/group-income/assets/138706/268c2f46-c35c-433e-84df-7865ae034a74)

Additionally, u1 will be kicked from the group for sending a malformed message.

### Solution

There are a few issues going on here.

- For some reason in `PaymentRowTodo.vue`, it thinks the payment has a hash. In `cancelPayment` the `if (this.hash)` passes, even though it shouldn't. Why does the payment have a hash? These are TODOs, they haven't been sent yet... so it shouldn't have a hash.
- It's not clear to me why TODOs can be dismissed at all, and I do not think we've implemented support in the distribution algorithm for dismissing payments. It's also unclear to me the circumstances under which dismissing a TODO would make sense (cc @dotmacro @leihla), and such circumstances are not described in the [Figma designs](https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?type=design&node-id=7781%3A4530&mode=design&t=TOKBVgW4JGfiOyV6-1). Even if there were a legitimate reason to dismiss TODOs, to get this working we would need to make changes to how we handle the output of the distribution algorithm, and that would be a very difficult endeavor in of itself.

So, at the very least, let's just not allow TODOs to be dismissed. Hide this menu item. If a payment TODO row has no menu items associated with it, the 3 dots should be hidden as well. I am also curious why the `PaymentRowTodo.vue` has a hash associated with it at all...

**Comment by SebinSong** [comment]
@taoeffect 
Yeah, I agree canceling a "todo" payment doesn't make sense too. 
`PaymentRowSent.vue` actually has the same logic in there which does make sense in that context. Should we remove the `dimiss-payment` menu from `PaymentRowTodo.vue` rather than just hiding it? The hash value for a todo payment item is created on the fly in [here](https://github.com/okTurtles/group-income/blob/0ecaf6be7920de512255494fdc0c453a3cab9193/frontend/views/pages/Payments.vue#L345) within `Payments.vue` page and is used to identify a specific payment item here and there. I can also probably rename it to something else (like `id`).

**Comment by taoeffect** [comment]
> PaymentRowSent.vue actually has the same logic in there which does make sense in that context. Should we remove the dimiss-payment menu from PaymentRowTodo.vue rather than just hiding it? 

Sure, but since there's no items in the menu at that point, the 3 dots to trigger the menu should also be hidden.

> I can also probably rename it to something else (like id).

That might be dangerous as some other code might rely on it being named `hash`, and I'm guessing we want to maintain consistency in the codebase.

**Comment by dotmacro** [comment]
I wrote a reply last week but don't see it above, sorry! 

> let's just not allow TODOs to be dismissed. Hide this menu item. If a payment TODO row has no menu items associated with it, the 3 dots should be hidden as well.

Yes, I agree. Until we determine the circumstances when a payment can be dismissed, let's just not allow it.
