### ISSUE TITLE
Switch to latest Bulma

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#176]
### Problem

We're using an outdated version of Bulma (again).

### Solution

- Delete as much [non-bulma custom CSS code](https://github.com/okTurtles/group-income-simple/pull/173/files#r100223368) written for our UI stuff
- Research [vue-bulma](https://github.com/vue-bulma) and decide (1) what's it's useful for, (2) whether it makes sense for us to use it instead of raw Bulma

**Comment by vijayee** [comment]
Fixed in #173
