### ISSUE TITLE
'Remove Member' button is shown and makes error unexpectedly

### ISSUE THREAD

**Issue by Silver-IT** [okTurtles/group-income#1760]
### Problem

Steps to reproduce
- [Tab1] u1 signs up, and creates a group
- [Tab2] u2 joins the group
- [Tab3] u3 joins the group, and logs out
- [Tab2] u2 creates a proposal to remove u3, DO NOT click 'Awesome' button at the last step
- [Tab1] u1 approves the proposal
- [Tab2] u2 still sees the proposal modal, and one more red button `Remove Member`. If u2 clicks this button, he gets error.
![image](https://github.com/okTurtles/group-income/assets/57976479/97758326-082a-42de-87ca-477e49a90ba1)

### Solution

Define the workflow and implement it
- The modal should be closed as soon as the proposal is completed
- The modal should not display `Remove Member` button

cc: @taoeffect

**Comment by taoeffect** [comment]
Closed in  #1764
