### ISSUE TITLE
Simplify and remove `JOINING_GROUP_CHAT`

### ISSUE THREAD

**Issue by Silver-IT** [okTurtles/group-income#1766]
### Problem

I think we shouldn't use many global variables like `JOINING_GROUP`, `JOINING_GROUP_CHAT` if possible.
While I was investigating the joining group process, I have noticed that `JOINING_GROUP_CHAT` could be removed.

### Solution

There is a way to remove global variable `JOINING_GROUP_CHAT` in `controller/actions/group.js` and `model/contracts/group.js`. If we set `JOINING_GROUP` in the following way (just before and after syncing), we don't need to take care of `JOINING_GROUP_CHAT`.

```
// params.originatingContractID is set, it means that we're joining through an invite link,
const isJoiningGroup = !!params.originatingContractID
const preEffectBeforeSync = isJoiningGroup
  ? () => { sbp('okTurtles.data/set', 'JOINING_GROUP-' + params.contractID, true) }
  : () => {}
const postEffectAfterSync = isJoiningGroup
  ? () => { sbp('okTurtles.data/set', 'JOINING_GROUP-' + params.contractID, false) }
  : () => {}

console.log('@@@@@@@@ AT join for ' + params.contractID)
preEffectBeforeSync()
await sbp('chelonia/contract/sync', params.contractID)
postEffectAfterSync()
```

**Comment by Silver-IT** [comment]
https://github.com/okTurtles/group-income/issues/1716#issuecomment-1763543551

I will remove the `skipInviteAccept` optional parameter while working on this issue.

**Comment by taoeffect** [comment]
Both `JOINING_GROUP_CHAT` and `skipInviteAccept` have been removed in `e2e-protocol`.
