### ISSUE TITLE
PWA darkmode issue

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1793]
### Problem

While testing out the PWA PR that was [recently merged](https://github.com/okTurtles/group-income/pull/1770), I noticed an issue related to saving the PWA to the home screen on mobile in dark mode. The top part of the screen is white when it should be the same color as the rest of the background:

![](https://github.com/okTurtles/group-income/assets/138706/bc45b726-c3e6-4693-8a57-342a1733cd85)

### Solution

Make sure the background matches in both dark-mode and light-mode.

**Comment by SebinSong** [comment]
Reference for the possible solution:
https://community.mojeek.com/t/suggest-dark-mode-background-for-pwa-web-manifest/232
https://css-tricks.com/meta-theme-color-and-trickery/

`<meta name="theme-color" content="var(--something)" />` does not work
: https://css-tricks.com/meta-theme-color-and-trickery/#aa-custom-properties

**Comment by taoeffect** [comment]
Closed in #1800
