### ISSUE TITLE
Wrong file attachment detection in the chatroom

### ISSUE THREAD

**Issue by SebinSong** [okTurtles/group-income#1811]
### Problem
In a chatroom, when a random text string is selected and dragged over the chatroom message UI, it's perceived as a file attachment and below overlay screen is triggered. This is wrong and should be corrected.

https://github.com/okTurtles/group-income/assets/17641213/0f99fe2d-381e-484e-9022-9ef1449c6c6f

### Solution
Fix it.

**Comment by taoeffect** [comment]
Closed by @SebinSong in #1813
