### ISSUE TITLE
Weird failure-to-scroll scrolling glitch in chatroom

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1817]
### Problem

On macOS (@corrideat was unable to reproduce on Linux) I encountered a weird glitch in `e2e-protocol-ricardo` (and probably in `e2e-protocol`)

1. [Container Tab 1] u1 creates group, copies invite link, visits general chatroom
2. [Container Tab 2] u2 joins group using link, visits general chatroom, and starts posting messages `1`, `2`, `3`, ... , `0` at the rate of about 2 messages per second
3. [Container Tab 1] u1's chat has not scrolled to follow new messages

### Solution

Fix the problem so that u1's chatroom follows the new messages.

**Comment by Silver-IT** [comment]
@taoeffect, this issue seems to be because of the Firefox Multi-Container Addon. If we don't use that Addon, this issue won't be happening.

https://github.com/okTurtles/group-income/pull/1904#issuecomment-2034255875

**Comment by taoeffect** [comment]
@Silver-IT I see. I guess we can close this then. If someone else encounters this outside of Firefox Multi-Container Addon, then let us know and we'll re-open!
