### ISSUE TITLE
Create initial app loading screen

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1822]
### Problem

In PR #1521, to address #1765, @corrideat added this `v-if` to the router in `frontend/index.html`:

```html
<router-view v-if="ephemeral.ready" class="l-page"></router-view>
```

This causes a blank white page to appear on initial page load for a bit.

### Solution

Create a `v-else` and set it to a page that shows a simple loading page to indicate that the app is loading.

Create a branch off of `master` (by the time you see this issue Sebin, `e2e-protocol` should be merged)

**Comment by SebinSong** [comment]
Hey @taoeffect @corrideat,
it's just a question out of curiosity but why did `ephemeral.ready` need to be set up this way (below) instead of definitng it in `data () { ... }` block and then doing `this.ephemeral.ready = true`?

```js
...
}).finally(() => {
  Vue.set(this.ephemeral, 'ready', true)
})
...
```

**Comment by taoeffect** [comment]
@SebinSong That's a good question. While I can't speak for @corrideat I think there's no reason why you couldn't do it that way. In fact I think that would be better as it's more idiomatic.
