### ISSUE TITLE
Make a generic step-by-step setup assistant for the group creation & others

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#183]
### Problem

*Note: We previously had an issue on this #93*

Right now the Group Creation screen is too cluttered. There are too many questions, too many boxes, etc.

### Solution

We can reduce the perceived cognitive load by splitting up the information input using a setup assistant type thing. Each of the 3 columns can be its own step in the setup assistant, and when the user clicks "Next", they'll fly to the left and be replaced by the next column in a Vuejs transition (possibly using Velocity.js to do it, or tween.js, whichever's better).

From #93 we concluded that this setup assistant is best done not by creating a custom component, but by re-using the vue-router somehow.

EDIT: It seems to make sense to make it a generic system supporting transitions between arbitrary vue components, so that the 3 columns can be steps, and so that Invite.vue (which can also be a standalone view) can be one of the steps.

**Comment by dsernst** [comment]
Current:

![image](https://user-images.githubusercontent.com/6340841/27418226-8aca614a-56ce-11e7-86f8-fc814885959c.png)

---------------------

If I understand this, the simplest way to close this issue is to split this screen into 3 individual screens? Ideally with nice transitions?

**Comment by taoeffect** [comment]
Closed by #325. 🎉 😄
