### ISSUE TITLE
Unexpected page redirection upon refresh page

### ISSUE THREAD

**Issue by Silver-IT** [okTurtles/group-income#1832]
### Problem

**Steps to reproduce**
- `u1` signs up, and creates a new group
- `u1` goes to the `General` chatroom
- `u1` refreshes the page, and gets redirected to the `Dashboard` page

**What should be happening**
In step 3, `u1` should not get redirected to `Dashboard` page. He should be in `General` chatroom page.

### Solution

Fix this.

**Comment by Silver-IT** [comment]
Having tested in the other pages, I have noticed that page refresh in any pages will redirect to the `General` page.

**Comment by taoeffect** [comment]
@Silver-IT This looks like a duplicate of #1830, which was fixed recently by @SebinSong in #1831. Are you sure you're testing latest `master`?

**Comment by Silver-IT** [comment]
@taoeffect, you're right. After pulling the latest commit, I couldn't reproduce this issue. Seems like it is already fixed, so I will close this issue.
