### ISSUE TITLE
Username should be displayed instead of contractID

### ISSUE THREAD

**Issue by Silver-IT** [okTurtles/group-income#1837]
### Problem

**Steps to reproduce**
- [Tab1] `u1` signs up, and creates a group
- [Tab2] `u2` joins the group
- [Tab3] `u1` logs in, and check the notification
- [Tab3] contractID is used instead of username in the notification (Attached screenshot)
![image](https://github.com/okTurtles/group-income/assets/57976479/032976b9-1448-4410-b0ac-4c5f43454baf)

**What should be happening**
- [Tab3] Username should be used instead of contractID

### Solution

Fix it

**Comment by taoeffect** [comment]
Wow! Great catch @Silver-IT!! 😱 

And not only that, but there are errors in the [Tab3] console too!

![Screenshot 2024-02-08 at 9 49 15 AM](https://github.com/okTurtles/group-income/assets/138706/cda0051a-c17c-4865-ba02-b2a963287445)

All of these needs to be fixed as part of this issue. 👍
