### ISSUE TITLE
Make the Group Creation screen Real™.

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#184]
### Problem

Right now we have some questions there that aren't really the best questions we could be asking for the setup. For example:

- "Is your group open to new members?" — This is unclear, as right below it we ask them how many members it takes to approve a new member, regardless of what the answer to this question is.
- The sliders are set to 0% by default. This is problematic because it will mislead most people into thinking they shouldn't pull the sliders very far (e.g. much farther above 50%), when in fact [they should](https://groupincome.org/2016/09/deprecating-mays-theorem/).

### Solution

- Come up with better questions.
- Give the sliders reasonable and safe defaults, and education users in how to properly set them by linking to our blog posts on May's Theorem (and any [GIshorts](https://groupincome.org/shorts/) we create on the topic).

**Comment by taoeffect** [comment]
For reference for folks who don't want to take the time to grab the code and run it for yourselves, this is the .vue that what I'm referring to:

![screen shot 2017-02-15 at 3 23 54 pm](https://cloud.githubusercontent.com/assets/138706/22999930/e5c4e3d0-f392-11e6-97b0-1cb2f82cd2d3.jpg)

**Comment by dsernst** [comment]
> "Is your group open to new members?" — This is unclear, as right below it we ask them how many members it takes to approve a new member, regardless of what the answer to this question is.

- [x] https://github.com/dsernst/group-income-simple/commit/1b5b5c6f28384fb3040309236e7616d4ff03ed06 removes this question, per @taoeffect's specification that all groups are invite-only for now.

**Comment by dsernst** [comment]
> The sliders are set to 0% by default. This is problematic because it will mislead most people into thinking they shouldn't pull the sliders very far (e.g. much farther above 50%), when in fact they should.
- [x] https://github.com/dsernst/group-income-simple/commit/940019271af5bf70f72ec9aad81740c18c31d404 sets these default to 80%, per @taoeffect's instructions

**Comment by dsernst** [comment]
This issue is probably ready to be closed. 

The only remaining item not addressed by the merged PR (https://github.com/okTurtles/group-income-simple/pull/216) is:

> ~~Give the sliders reasonable and safe defaults, and~~ education users in how to properly set them by linking to our blog posts on May's Theorem (and any GIshorts we create on the topic).
