### ISSUE TITLE
User profile picture is not updated after rejoining group

### ISSUE THREAD

**Issue by Silver-IT** [okTurtles/group-income#1840]
### Problem

**Steps to reproduce**
- [Tab1] `u1` signs up, and creates a group
- [Tab2] `u2` joins the group
- [Tab2] `u2` leaves the group
- [Tab2] `u2` rejoins the group
- [Tab1] `u1` updates the profile picture
- [Tab2] `u1`'s profile picture is not updated for `u2`

**What should be happening**
- [Tab2] the profile picture of `u1` should be updated for `u2`

### Solution

Fix it

**Comment by Silver-IT** [comment]
Having tested again, I can say neither profile picture is updated, nor all profile settings(e.g., `displayName`) are updated.
It also happens between all the group members when the group has more than 3 members. I guess it's something related to the sharing keys. Need to investigate more in detail.
![image](https://github.com/okTurtles/group-income/assets/57976479/1b01c950-ea0f-44b6-855f-2ae7c5b7f405)
Attached three screenshots in different tabs
If I add one thing from my investigation, I can say that if there are many leave/join group activity, only the lastly-rejoined member's profile is updated throughout the group members.

cc: @corrideat

**Comment by taoeffect** [comment]
I don't know if this is related, but there were some avatar related issues fixed in this PR that was just merged: https://github.com/okTurtles/group-income/pull/1852

**Comment by corrideat** [comment]
> I guess it's something related to the sharing keys. Need to investigate more in detail.

I think so too. When someone leaves, all group members are supposed to be rotating their keys (which I'm guessing is happening), then sharing the new key with the group (may or may not be happening) and then the key should be available to group members (this should work, but there can be issues with contracts that have already been synced).

**Comment by taoeffect** [comment]
Found and created a possibly related issue: #1853
