### ISSUE TITLE
Allow group creator to delete messages in any group chatroom

### ISSUE THREAD

**Issue by Silver-IT** [okTurtles/group-income#1919]
### Problem

According to the discussion [here](https://github.com/okTurtles/group-income/pull/1892#discussion_r1558539645), a new feature is needed to be implemented. That is to allow group creators to delete messages in any group chatrooms.

### Solution

Implement it

**Comment by taoeffect** [comment]
Indeed, and also DMs should be unaffected by this (only the original author of the message should be able to delete it)

**Comment by Silver-IT** [comment]
@taoeffect, while working on this issue, I found that we missed one thing. The confirm dialog when deleting messages. The Slack has it, but we don't have this in the current application, and also in the Figma too. 
![image](https://github.com/okTurtles/group-income/assets/57976479/64c2136a-615d-4131-9996-6bd8dc3da9cd)

We have this confirm dialog while deleting attachments.
![image](https://github.com/okTurtles/group-income/assets/57976479/5463c93e-aa4f-48b0-b227-07d514e87e3a)

Should we verify that his attempt to delete messages is his intention?

**Comment by taoeffect** [comment]
> Should we verify that his attempt to delete messages is his intention?

@Silver-IT Yes, a confirmation dialogue would be a good idea for both the group creator and the original uploader 👍
