### ISSUE TITLE
Give mobile users a way to know where a link goes

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1935]
### Problem

On Desktop, when someone shares a link in the chat, users can know where it goes without clicking it by hovering the mouse over it. On mobile, there is no such feature, and there is no way to know where the link goes. This can be a potential security risk for users.

### Solution

One way that Slack attempts to address this is by letting users long-press a link. When they do this, a panel appears with more information about the link and various options:

![1000031419](https://github.com/okTurtles/group-income/assets/138706/1e58d5ee-2050-4bb9-a843-3827768863c7)

However, when a link is long-pressed in Group Income, this panel appears instead:

![1000031420](https://github.com/okTurtles/group-income/assets/138706/65ecbd34-ec50-492c-8a48-f13adbf26fc8)

This is the panel for interacting with a message.

What we need is to be able to identify when a link within a message is long-pressed, and display a different panel, similar to the Slack one, instead.

We need to show at least:

- What the full link is
- The ability to open the link
- The ability to copy the link

**Comment by SebinSong** [comment]
@taoeffect 
I'm investigating this issue right now and found out that the link created as part of the chat message currently doesn't do below you mentioned in the description.

> On Desktop, when someone shares a link in the chat, users can know where it goes without clicking it by hovering the mouse over it.

I will work on implementing this too as part of the fix for this issue.
