### ISSUE TITLE
Clicking "report the error" in the emergency banner doesn't work

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1945]
### Problem

![tmp-1713455351100_720](https://github.com/okTurtles/group-income/assets/138706/94632500-b192-47c7-8472-56b76baf0677)

In the PWA on Android/GrapheneOS, I noticed that clicking the "report the error" link in #1944 didn't actually take me to the `UserSettingsModal`.

Instead it opened up a new browser window that I think took me to the dashboard.

This is wrong, it shouldn't open up a new browser window, and it should take me to the `UserSettingsModal`.

### Solution

This code needs to be fixed:

```js
export function LError (error: Error): {|reportError: any|} {
  let url = `/app/dashboard?modal=UserSettingsModal&tab=application-logs&errorMsg=${encodeURI(error.message)}`
  if (!sbp('state/vuex/state').loggedIn) {
    url = 'https://github.com/okTurtles/group-income/issues'
  }
  return {
    reportError: L('"{errorMsg}". You can {a_}report the error{_a}.', {
      errorMsg: error.message,
      'a_': `<a class="link" target="_blank" href="${url}">`,
      '_a': '</a>'
    })
  }
}
```

At minimum, `target="_blank"` shouldn't be used with the modal. But it might require more than that to fix this (potentially even setting up JS logic...).

**Comment by taoeffect** [comment]
Note: I have the same problem clicking "Report the error" here: #2018

**Comment by Silver-IT** [comment]
Update the component `BannerGeneral` and `BannerScoped` just like how we handle onsite redirects inside MessageBase in PR #2005.

This is the comment to me. 😉

**Comment by Silver-IT** [comment]
This issue seems like to be very much similar to the Issue #1949, so I am going to resolve this issue inside the PR #2005.
