### ISSUE TITLE
Channel links in chat

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1947]
### Problem

![Screenshot 2024-04-18 at 11 49 25 AM](https://github.com/okTurtles/group-income/assets/138706/3a4c96d6-1eee-4d59-b582-30ee77cb1457)

We need the ability to link to channels by name from within a chat channel.

### Solution

1. When a user types `#` in the chat area, similar to how they type `@`, we need a popup to appear showing all the channels names that the *currently logged in user has access to inside of the current group* (both public, group, and private channels)
2. When the message is rendered, the channel should appear in blue and clickable (unless it's a private chatroom that the reader doesn't have access to, see note below)

Example:

![Screenshot 2024-04-18 at 12 01 13 PM](https://github.com/okTurtles/group-income/assets/138706/f1ddb81e-03e7-40e2-9e89-4466a2ed36e6)

#### Special note on private chatrooms

When a private chatroom is linked to, the user who is sending it can see the link, and so can anyone who is already a member of the room:

![Screenshot 2024-04-18 at 11 56 59 AM](https://github.com/okTurtles/group-income/assets/138706/76fbc579-1105-499a-bd43-f34a81afa5c7)

But anyone outside of that room sees something else:

![screen_shot_2024-04-18_at_11 53 01_am_360](https://github.com/okTurtles/group-income/assets/138706/4b4cf978-703f-4d29-87a1-d8ab90b4a3f3)

Note that the color of the link should be different (grey), and also that it cannot be clicked, and also that both the blue and grey links use a different symbol: a 🔒 icon instead of a `#`

**Comment by SebinSong** [comment]
@taoeffect 
I am working on this issue right now and have got a question.

<img src='https://github.com/okTurtles/group-income/assets/17641213/a699bfc9-3aab-4183-955f-bc0ba1f95ac9' width='420'>

As you can see from the above screenshot, currently the app allows white-space within the chatroom title.
But then I realised this isn't really compatible with the mention functionality. 
e.g.) Writing `#A random private channel` will lead to only capturing `#A` here.

I was wondering how slack deals with this and tried it there and currently it simply doesn't allow white space within a channel name. (Typing space is automatically converted to `-` there)

<img src='https://github.com/okTurtles/group-income/assets/17641213/272a0562-4eb2-4315-9b2b-773e84c42e56' width='480'>

How would you think we should handle this case in our app?

Thanks,

**Comment by taoeffect** [comment]
Converting spaces to dashes sounds like a good solution 👍

**Comment by SebinSong** [comment]
@taoeffect do you mean converting them when creating a new channel? I can work on it as part of the PR for this issue.

**Comment by taoeffect** [comment]
Yes 👍

**Comment by SebinSong** [comment]
Hey @taoeffect, I've got another question here.

I realised there is a public channel that a user hasn't joined which is below.


<img src='https://github.com/okTurtles/group-income/assets/17641213/31108fe2-f453-4a7a-b9c6-e7af8da77222' width='320'>

So this channel can be navigated to regardless of whether the user is the member of it or not.
But do we allow the user to be able to mention this channel even when he/she hasn't joined it. meaning, do we show those 'not-joined' channels in this menu pop-up?


<img src='https://github.com/okTurtles/group-income/assets/17641213/311f7ee5-9ec7-4589-bf81-690e54c65bab' width='420'>


Thanks,

**Comment by taoeffect** [comment]
> But do we allow the user to be able to mention this channel even when he/she hasn't joined it. meaning, do we show those 'not-joined' channels in this menu pop-up?

Yes.

Also, while we're at it, could you please update the default `General` channel name to `general` (lowercase)?

**Comment by SebinSong** [comment]
@taoeffect Yes, sure.
