### ISSUE TITLE
Linking to messages doesn't work

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1949]
### Problem

1. Copy a link to a message in chat (say, from one of the first messages near the top)
2. Paste the link in the chat and hit send
3. Click the link

Expected result:

- Chat view should jump to the linked message and highlight it

Actual result:

- A new window appears, and we aren't even taken to the message

### Solution

Fix it so that we get the expected result. No new windows should open. We should be immediately taken to that message, or shown an error, according to the following rules:

- If the message is from a different chatroom that we are a part of, we should also be taken to that message
- If the message is from a public or group chatroom that we are not a part of, we should be switched to that chatroom and shown that message, but *not* joined to that chatroom
- If the message is from a *private* chatroom that we are not part of, clicking the link should present a dialog (via `gi.ui/prompt`) that says the `Sorry, this message is from a private chatroom that you are not part of.`, with a single button that says `OK`

**Comment by Silver-IT** [comment]
If I add one thing to the solution, we should also make it work to scroll to the right message and highlight it, when we paste the message link in the **new** tab.

**Comment by Silver-IT** [comment]
@taoeffect, can I use `alert` instead of `gi.ui.prompt` to say `Sorry, this message is from a private chatroom that you are not part of.`? That's because `gi.ui.prompt` updates URL, and makes the unexpected recursive URL changes since we listen the URL changes in GroupChat.vue.

**Comment by taoeffect** [comment]
@Silver-IT no problem 👍 

Please if you can just add a comment explaining that to the code too
