### ISSUE TITLE
Wrong `Someone is typing` indicator

### ISSUE THREAD

**Issue by Silver-IT** [okTurtles/group-income#1950]
### Problem

Steps to reproduce
- [Tab1] `user1` creates group
- [Tab2] `user2` joins the group
- [Tab1] `user1` sends a message
- [Tab1] `user1` clicks to edit message button and cancels editing
- [Tab2] `user2` sees the `user1 is typing` indicator until the `user1` really starts and ends typing

### Solution

Fix it

**Comment by SebinSong** [comment]
@Silver-IT Thanks for creating this issue Alex. This is something I implemented so let me know if you would like me to take over this.

**Comment by Silver-IT** [comment]
@SebinSong, I would like to learn how it works if you don't mind.

**Comment by SebinSong** [comment]
@Silver-IT No problem, then :) let me know if you need a help in while working on this.
