### ISSUE TITLE
Splash page

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#196]
### Problem

Currently the splash page (what you see at http://localhost:8000/simple/) is "Sign Up" whether you're logged in or not.

### Solution

We need to have a dedicated splash page for both scenarios (logged in or not).

- For logged in, I think the answer is clear: it should be the current group overview dashboard, which is yet to be defined in detail (defining all that will be done in separate issues, starting with #198, and be an evolving process with additional issues).
- For logged out, it's not so clear to me what it should be, so for now let's just leave it as "Sign Up" for convenience.

**Comment by vijayee** [comment]
Fixed in #225
