### ISSUE TITLE
Save the recent messages in the chatroom contract state

### ISSUE THREAD

**Issue by Silver-IT** [okTurtles/group-income#1962]
### Problem

In order to solve the issue described [here](https://github.com/okTurtles/group-income/issues/1619#issuecomment-2067529936), we need to save the latest message(or messages) in the chatroom contract state. Now, we don't save any messages in the chatroom contract in order to reduce the memory usage, but instead we are save the recent events in the local storage for each chatroom.
I think we should not use the local storage for the recent events, and should save the recent messages in the chatroom contract state. Additionally, it will be more faster when we open any chatroom too.

### Solution

Implement this

**Comment by Silver-IT** [comment]
@taoeffect, two questions for you here.

1. **How many number of messages do you think is good for the chatroom contract to save?**
2. As you can see in the following two constants, we save two pages of chatroom events in the local storage. Now, I think it's better not to use local storage to save those events for the chatroom since we are going to save some messages in the chatroom contract. We didn't made agreement on this yet. So the question is that **Is it fine to save the enough number of messages in the chatroom contract state, and not to use local storage for saving the recent events?**.
```
export const CHATROOM_ACTIONS_PER_PAGE = 40
export const CHATROOM_MAX_ARCHIVE_ACTION_PAGES = 2 // 2 pages of actions
```

**Comment by taoeffect** [comment]
@Silver-IT Yes, it is fine to switch to using the chatroom contract state to store messages.

Regarding the number of messages - let's save just 1 page (~~40~~ actions EDIT: lets make it 20 actions) worth of messages per chatroom. We do not want to use up too much memory.

**Comment by Silver-IT** [comment]
Based on the discussion on today's call, we will save the 20 messages in the chatroom contract state, instead of previous 40.

**Comment by Silver-IT** [comment]
@taoeffect, let's think about the following situation.
- user1 creates a group, and goes to the General chatroom page
- user1 sends 30 messages (The chatroom contract will save only the recent 20 messages, and 10 messages would be removed)
- user1 removes the last 20 messages (In the chatroom contract, there will be no messages)

But the expected result is that the chatroom contract should save 10 messages, isn't it? So what could be the solution for this problem?

- Should we ignore this **picky** and **unrealistic** situation?
- Should we increase the max number from 20 to 30 or 40? (To decrease the percentage of that picky situation would be happening)
- Or what else?

**Comment by taoeffect** [comment]
> Should we ignore this picky and unrealistic situation?

Yes. 😄 👍
