### ISSUE TITLE
Profile widget menu

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#197]
### Problem

Well, besides being poor UI/UX, it's difficult to know what account you're logged into during development when you're using two browsers.

### Solution

Like on Twitter and GitHub, there should be a drop-down-icon-widget-menu thing in the upper-right, which should at least:

- Display the user's profile picture (if it has one), or a circle with a deterministically generated color based on the username.
- Display a menu when clicked, including a menu item to adjust personal profile settings, and a menu item to adjust settings as they relate to your relation to the group (e.g. your giving/receiving limits)

**Comment by taoeffect** [comment]
This is now partially implemented by #251, but it's not a drop-down menu yet.

**Comment by sandrina-p** [comment]
It's kind a dropdown right now... isn't it?

**Comment by taoeffect** [comment]
From what I recall, it basically overlays on top of the button a new div, covering everything. We want it to look like a normal dropdown, not a new layer on top.

EDIT: i.e. something closer to this:

![screen shot 2018-03-31 at 12 46 48 pm](https://user-images.githubusercontent.com/138706/38165460-9f4d5c16-34e1-11e8-8997-dfc4653dce60.jpg)

Keeping familiar-looking widgets is important. We don't want to invent too much radically different looking UI or users might get confused.
