### ISSUE TITLE
Proposal notification using incorrect icon

### ISSUE THREAD

**Issue by dotmacro** [okTurtles/group-income#1971]
### Problem

The notification for a recently closed proposal is using a random user's avatar rather than any appropriate proposal icon. (The choice of user may not be truly random, but regardless, using a user icon is incorrect.)

### Solution

Wherever an icon/avatar is needed for a proposal, the icon used should be the appropriate proposal icon. 
See proposal iconography on Figma: https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?type=design&node-id=1876%3A17778&mode=design&t=KWfuzXQrEmv1KfXw-1

**Comment by Silver-IT** [comment]
A small issue I found. The username is used instead of displayName in the proposal widget.
![image](https://github.com/okTurtles/group-income/assets/57976479/7699c775-a0b5-406e-a57b-11a2276bb935)

Additionally, I would like to fix this problem in this ticket.

**Comment by Silver-IT** [comment]
And this issue too. In the Figma design, it uses the display name by default.
![image](https://github.com/okTurtles/group-income/assets/57976479/03b437af-785b-4bc3-a844-723fb34dc5f4)

**Comment by Silver-IT** [comment]
@dotmacro, can you please describe the steps to reproduce this issue?
Actually, I can not see the notifications when the proposal is closed.
I can only see the closed proposals in the dashboard, and they seems to be fine as far I as know. User avatars are also correct.
![image](https://github.com/okTurtles/group-income/assets/57976479/08079ee2-ebb3-458c-a136-e3b294214969)

**Comment by dotmacro** [comment]
> Actually, I can not see the notifications when the proposal is closed

Do you mean that the notifications are deleted/removed from the notification card after the proposal is closed? For me, the notifications remain, and one shows a random user's avatar instead of a proposal icon. 

> I can only see the closed proposals in the dashboard

I cannot see the closed proposals in the dashboard (but that is [another issue](https://github.com/okTurtles/group-income/issues/1969)), so I cannot say whether the proposal icon is properly used there. The correct proposal icon is properly used on the Archived Proposals screen though. 

> @dotmacro, can you please describe the steps to reproduce this issue?
This was in a real group (i.e. not carefully documented testing) so I presume the steps were:
1. User A creates proposal
2. Enough members vote (using separate devices) that proposal closes before deadline and before User F votes
3. Proposal is approved
4. Notification appears in notification card
5. "Proposal approved" notification on User F's notification card uses random user's avatar instead of any proposal icon

If I can reproduce in another group, I'll add more info and more detailed reproduction steps.

**Comment by taoeffect** [comment]
Screenshots would really help here.

I think she's referring to this, as an example taken from our group:

![Screenshot 2024-05-03 at 8 51 31 AM](https://github.com/okTurtles/group-income/assets/138706/6fe7c4d8-6972-4d57-bd4c-f7166fc4a9f8)

I am guessing this isn't a completely random icon, but rather the icon of whoever was the last person to vote on the proposal.

I agree that it should instead use one of these icons:

![Screenshot 2024-05-03 at 8 54 22 AM](https://github.com/okTurtles/group-income/assets/138706/1642262a-1eaa-4858-8b2d-b077c662ee42)

And if you want to use a user icon in addition to that icon (i.e. in the lower-right corner), then maybe we can use the icon of the user who made the proposal.

**Comment by Silver-IT** [comment]
According to the Figma design, I think we should use the user's profile picture as the main icon, and the additional icon at the right bottom which indicates the type of the proposal.
![image](https://github.com/okTurtles/group-income/assets/57976479/1aa74e7d-d642-41fb-bf1a-453cc6e86206)

**One question: Should we make a notification that indicates the proposal state when the proposal is closed (accepted or rejected)?**
I can see the design that describes the notifications for closed proposals (above screenshot, and it seems like the issue #1972), but we don't have any design (it could be intention, but for confirmation) for the **accepted proposals**. If the answer is `YES`, should we make two notifications when the proposal to change mincome is closed by acceptance?

**Comment by Silver-IT** [comment]
**Another question: Can you tell me how to set the colour of bottom-right icon of each notification?**
Actually, I got confused from the Figma design. Can't understand how to define the colour(status) of each notification.
![image](https://github.com/okTurtles/group-income/assets/57976479/4f686a65-a182-4ca9-af3d-e2d8511c81e6)
![image](https://github.com/okTurtles/group-income/assets/57976479/2e91e9f8-8eb1-4e58-881f-8ae011c71d4c)

- Green to the approved proposals?
- Red to the rejected proposals?
- Others are all blue?
- What about the proposal to remove group member?

**Comment by taoeffect** [comment]
> One question: Should we make a notification that indicates the proposal state when the proposal is closed (accepted or rejected)?

Yes.

> If the answer is YES, should we make two notifications when the proposal to change mincome is closed by acceptance?

There should only be one notification.

For example, "Felix Kubin's proposal to change the group's mincome to $1500 was [accepted/rejected]".

> Green to the approved proposals?
> Red to the rejected proposals?
> Others are all blue?
> What about the proposal to remove group member?

Let's do it like this:

- When a proposal is created, create a notification using a blue icon, and the appropriate picture (member, money, or generic proposal).
- When a proposal is approved, use green, and either use the checkmark icon, or the same icon as before (please feel free to make this decision)
- When a proposal is rejejcted, use red, and either use the X icon, or the same icon as before (please feel free to make this decision)
