### ISSUE TITLE
Implement GroupDashboard.vue

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#198]
### Problem

Not only do we need a Group Dashboard, but we need one *now* so that testing pull requests like #195 becomes easier.

It's hard for me to test #195 because after I create a group, run some tests, post some comments, close the browser, and then return to it I have no way of continuing to test the invite system without creating yet another group. I also have no way of testing inviting to different groups, which would require switching to between groups (something we need to have a separate issue for).

### Solution

As a first rough draft start, have the dashboard display at least the following:

- The group's name
- The current members
- The ability to invite other members in a widget off to the side, or a link to a widget (probably better, a link that says "Invite new member"

**Comment by dsernst** [comment]
Other components that @taoeffect suggested for this dashboard:

- [ ] graph of how successful the group has been at meeting their minimum income
- [ ] chat log?
- [ ] re-usable customizable components for settings

**Comment by dsernst** [comment]
Hey @taoeffect, can I use the current placeholder [`UserGroupView.vue`](https://github.com/okTurtles/group-income-simple/blob/eae5c26aa83fca198b5203e4031eb01048c05f9b/frontend/simple/views/UserGroupView.vue) for this? Are they distinct?

**Comment by dsernst** [comment]
Also @taoeffect, are these group dashboards supposed to be at unique urls? E.g.:

- /groups/my-first-group
- /groups/awesome-people
- /groups/beekeepers-anonymous

?

**Comment by dsernst** [comment]
Latest mockup: 
![image](https://user-images.githubusercontent.com/6340841/27496806-6fbb862e-580c-11e7-894d-a122722426ec.png)

And here's the sketch asset files for that:
[group-income-dashboard.zip](https://github.com/okTurtles/group-income-simple/files/1098828/group-income-dashboard.zip)

**Comment by hubudibu** [comment]
@taoeffect this seems to be done, how about closing this?

**Comment by taoeffect** [comment]
@hubudibu, good call. 👍
