### ISSUE TITLE
Manage proposal status consistently

### ISSUE THREAD

**Issue by Silver-IT** [okTurtles/group-income#1984]
### Problem

Now, we have two types of constants which represent the proposal state.
One is the list of these variables which have prefix of `STATUS_`.
```
export const STATUS_OPEN = 'open'
export const STATUS_PASSED = 'passed'
export const STATUS_FAILED = 'failed'
export const STATUS_EXPIRED = 'expired'
export const STATUS_CANCELLED = 'cancelled'
```
And the other is `PROPOSAL_VARIANTS` enum.
```
export const PROPOSAL_VARIANTS = {
  CREATED: 'created',
  EXPIRING: 'expiring',
  ACCEPTED: 'accepted',
  REJECTED: 'rejected',
  EXPIRED: 'expired'
}
```

### Solution

Use only one constant, and remove the other.

**Comment by Silver-IT** [comment]
@taoeffect
In the current version, we create a message in the general chatroom, when the proposal is about to be expired. The name of the function that does this is `notifyExpiringProposals`.

Are we planning to create messages in the general chatroom for the status changes of all the proposals?
- When proposal created
- When proposal accepted
- When proposal reject
- When proposal expired
- When proposal cancelled

**Comment by taoeffect** [comment]
@Silver-IT Sure, yes I think that would be helpful 👍

**Comment by Silver-IT** [comment]
@taoeffect, Yeah. If we notify proposal status in several ways, in relative the users would not miss to vote proposals.

But now, we notify the proposal status using notifications.
- When proposal created
- When proposal accepted
- When proposal reject
- When proposal expired
- When proposal cancelled

Do we need to notify using general chatroom too? What I think is that we should notify the proposal status in one way, IMHO it's using notification, not using general chatroom. So, I would like to change workflow and make it to create notification instead of creating message when proposal is expiring.

And I remember you asked me for what we use `MESSAGE_TYPES.INTERACTIVE`. We currently use this type of messages only for notification message that saying the proposal is expiring. The `MESSAGE_TYPES.NOTIFICATION` and `MESSAGE_TYPES.INTERACTIVE` are all automatically created by the system, not by a specific user. But `MESSAGE_TYPES.INTERACTIVE` message uses horn(📢) instead of profile picture while `MESSAGE_TYPES.NOTIFICATION` message uses a picture of the specific user.

**Comment by taoeffect** [comment]
> So, I would like to change workflow and make it to create notification instead of creating message when proposal is expiring.

Go for it 👍
