### ISSUE TITLE
Fix broken lastLoggedIn info (inactive users info wrong)

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#1997]
### Problem

The inactive users list is showing more users than it should

### Solution

I am guessing the problem is that it's only saved when the page is refreshed (on logging in)?

If so, then the solution is to periodically save it (say, every 10 minutes).

**Comment by dotmacro** [comment]
copying from Slack:

I did click all around the app on my normal device (e.g. checking payments, double-checking things on various views) and also opened the app in a second browser and did a hard refresh to force reloading of some components, but I'm I'm listed [in the inactive members].
