### ISSUE TITLE
Poll Notifications could be created no matter what hideVoters is

### ISSUE THREAD

**Issue by Silver-IT** [okTurtles/group-income#2010]
### Problem

While I was investigating the chatroom contract function `gi.contracts/chatroom/voteOnPoll`, I found a wrong workflow to create poll notification.
```
const msgIndex = findMessageIdx(data.hash, state.messages)
if (msgIndex >= 0) {
  ...

  if (pollData.hideVoters) { return }
}

// create a notification for vote (or vote changes)
```
Since the `msgIndex` could be `-1`, `if (pollData.hideVoters) { return }` does not always run. So the notification could be created no matter what the `pollData.hideVoters` is.

### Solution

Fix it

**Comment by Silver-IT** [comment]
It's same for the `gi.contracts/chatroom/changeVoteOnPoll` function too. Fix this function too.

**Comment by SebinSong** [comment]
Great find @Silver-IT
