### ISSUE TITLE
Infinite pending message

### ISSUE THREAD

**Issue by Silver-IT** [okTurtles/group-income#2030]
### Problem

When sending messages in chatroom, the message state isn't changed to `sent` until the next message is sent out.
I don't think this issue happens _always_, and I think _sometimes_ (or very rarely) it happens because **I** have never encounter this issue yet.

[Reference](https://okturtles.slack.com/archives/C0EH7P20Y/p1716222964606209)
`Greg: When I post to the random channel in the PWA the messages are shown in grey and they stay grey until I post another message or switch channels`

### Solution

Fix it

**Comment by taoeffect** [comment]
@Silver-IT another thing that I noticed was that when this started happening, when I switched to a different page (e.g. the Group Settings) and then back to the chat, the message was no longer marked as pending... I think.

I have the logs here from when that happened in case it's helpful:

[gi_logs.json.txt](https://github.com/user-attachments/files/15663734/gi_logs.json.txt)

**Comment by Silver-IT** [comment]
Seems like this is duplicated with Issue #2061.

**Comment by Silver-IT** [comment]
I think this issue should be closed since Issue #2061 is closed which is duplicated with this one.
