### ISSUE TITLE
Contributions page incorrectly claims there are no financial needs

### ISSUE THREAD

**Issue by corrideat** [okTurtles/group-income#2049]
### Problem

The text on the contributions page incorrectly shows that there are no monetary needs when there are.

<figure>

![Capture contributions](https://github.com/okTurtles/group-income/assets/3857362/028bc3cd-aafd-4eef-9aaa-aa3bc45c6c9f)

<figcaption>Contributions: note that the text on the right column claims that there are no monetary needs</figcaption>

</figure>

I had previously posted a redacted screenshot of the dashboard, but maybe it was too redacted and was confusing. The important thing is that all amounts (covered, pledged and not covered) are above $0. In other words, there are financial needs.

### Solution

Fix the text shown.

**Comment by taoeffect** [comment]
Agreed, the text "No one needs monetary contributions at the moment. You can still ..." should be shown only when that's true.

Let's replace it with:

> You can add non-monetary contributions for the group here.

**Comment by Silver-IT** [comment]
I can't understand when the text has incorrect meaning.

I created two users; `user1` and `user2`. And set `user1` to pledge 100$ and `user2` to need 50$.
These are the following screenshots for each user;
![image](https://github.com/okTurtles/group-income/assets/57976479/ab8af899-2725-4c0d-a210-fe4dccd860fc)
![image](https://github.com/okTurtles/group-income/assets/57976479/3564cc79-48fd-4fca-901c-fb4547bb30dd)

So, what's wrong with these?

cc: @taoeffect, @corrideat

**Comment by taoeffect** [comment]
@Silver-IT Ricardo is showing a screenshot from our GIG group on the live server. In our GIG group Ricardo's income details are set to pledging $0, so you might want to test with 3 users and one of them pledging $0
