### ISSUE TITLE
Make `INCOME_DETAILS_UPDATE` notification consistent across user account

### ISSUE THREAD

**Issue by dotmacro** [okTurtles/group-income#2056]
### Problem

The `INCOME_DETAILS_UPDATE` notification on the dashboard seems to be per-device / per-browser. 

1. Dismissed notification & updated income details in browser1. 
2. Opened browser2 and signed in. 
3. Notification visible at top of dashboard on browser2, even after hard refresh. Notification remains dismissed (i.e. not visible) on browser1.
<img width="828" alt="updateIncomeDetails" src="https://github.com/okTurtles/group-income/assets/13082264/23b4f84b-4b0b-4973-8f41-0d9c718fd921">

### Solution

Ensure that the `INCOME_DETAILS_UPDATE` notification on the dashboard is consistent across a user's account (rather than per-device / per-browser).

**Comment by Silver-IT** [comment]
![image](https://github.com/okTurtles/group-income/assets/57976479/889f1fb8-1c45-40e2-bae8-c65432b1d1ca)
```
computed: {
  showBanner () {
    return this.isCloseToDistributionTime && !this.ephemeral.hideBanner
  }
},
methods: {
  updateBannerVisibility () {
    this.ephemeral.hideBanner = localStorage.getItem(this.bannerStorageKey) === 'true'
  }
}
```
As you can see the screenshot and the code to set computed value `showBanner` in `GroupDashboard.vue`, it uses localStorage to save the user config to hide/show notification.

@taoeffect, do you agree to save this in KV store of identity contractID? (Just like how we saved the `chatRoomUnreadMessages`)

**Comment by taoeffect** [comment]
@Silver-IT Yes, solving this issue would indeed require us to store this info in the KV store under the user's identity contract.

You'll need to:

- Store it under the identity contract's KV-space, under a key that uses the group contractID in the key name (so that if the user is part of multiple groups it will work individually for each of them)
- Make sure to update it to turn it back on when the time is right

**Comment by Silver-IT** [comment]
> Make sure to update it to turn it back on when the time is right

Where could users to turn it back on? Is there any user's workflow to do that?

**Comment by taoeffect** [comment]
> Where could users to turn it back on? Is there any user's workflow to do that?

We have existing code that tells the banner to re-appear. Please re-use that code.

Note: I also edited my comment above. Before I had written:

> Store it under the group's key (so that if the user is part of multiple groups it will work individually for each of them)

I meant to write:

> Store it under the identity contract's KV-space, under a key that uses the group contractID in the key name (so that if the user is part of multiple groups it will work individually for each of them)
