### ISSUE TITLE
Broken Cypress test related to login modal (heisenbug)

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#2058]
### Problem

https://cloud.cypress.io/projects/q6whky/runs/2370/test-results/0417b59b-4b92-4529-95bc-8228fffc0f88?actions=%5B%5D&browsers=%5B%5D&groups=%5B%5D&isFlaky=%5B%5D&modificationDateRange=%7B%22startDate%22%3A%221970-01-01%22%2C%22endDate%22%3A%222038-01-19%22%7D&orderBy=EXECUTION_ORDER&oses=%5B%5D&specs=%5B%5D&statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D&testingTypesEnum=%5B%5D&utm_source=github

![Screenshot 2024-06-11 at 10 03 13 AM](https://github.com/okTurtles/group-income/assets/138706/3e88298a-7e62-488c-8057-49469f42c79a)

From: https://cloud.cypress.io/projects/q6whky/runs/2370/test-results/0417b59b-4b92-4529-95bc-8228fffc0f88/video?actions=%5B%5D&browsers=%5B%5D&groups=%5B%5D&isFlaky=%5B%5D&modificationDateRange=%7B%22startDate%22%3A%221970-01-01%22%2C%22endDate%22%3A%222038-01-19%22%7D&orderBy=EXECUTION_ORDER&oses=%5B%5D&specs=%5B%5D&statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D&testingTypesEnum=%5B%5D&utm_source=github

### Solution

It seems like maybe the Cypress tests are written incorrectly, or there's some bug in the vuejs code that causes the modal to not really be closed.

**Comment by Silver-IT** [comment]
I guess this error occasionally happens because the `gi.actions/identity/logout` function doesn't always wait for the new event queue `UNREAD_MESSAGES_QUEUE`, which is added in the recent PR #1998, to be empty.
