### ISSUE TITLE
Implement cash-based payments

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#206]
### Problem

For our demo, we should ideally show basic payments and calculation being done.

EDIT: changed title from "Demo rudimentary payment/receipt of contribution-based payment" to "Implement cash-based payments"

### Solution

Implement it

**Comment by ktamas77** [comment]
- plugins available
	- bitcoin
	- paypal
	- human	

- separate component
  - hidden route
  - pay / receive

- concepts
  - no money storage / wallet functionality

**Comment by ktamas77** [comment]
for reference, current updates with ILP in real world use:
https://www.xrpchat.com/topic/5485-can-we-do-anything-with-ilp-yet/
