### ISSUE TITLE
Testing site broken (private chatroom not syncing across devices)

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#2066]
### Problem

1. While desktop computer was asleep, I created a private chatroom on my phone via the PWA
2. Posted a few messages to it
3. Woke up computer and did not see the chatroom listed. No errors in console. Refreshing page doesn't fix it! However, opening a private window and re-logging in there does show the private chatroom.

Phone PWA:

![tmp-1718337318871](https://github.com/okTurtles/group-income/assets/138706/8b6a3c2f-09dd-4626-82c7-90f2defe4d97)

Desktop:

![Screenshot 2024-06-13 at 8 54 54 PM](https://github.com/okTurtles/group-income/assets/138706/9b334861-7ff7-43ff-be35-bee4d4cb59b3)

### Solution

Find and fix the problem.

**Comment by corrideat** [comment]
Are you able to reproduce this, or do you have a copy of the state or logs?

**Comment by taoeffect** [comment]
Re-opening this as I'm not convinced it's fixed and making it depend on #2110 being closed.
