### ISSUE TITLE
Fix the style of direct message with many members

### ISSUE THREAD

**Issue by Silver-IT** [okTurtles/group-income#2067]
### Problem

I have just noticed that the style is broken when the DM title is overflow with it'
![image](https://github.com/okTurtles/group-income/assets/57976479/17c64aa7-af46-45b8-8324-7ba0908aa9df)
For the greeting message, we should consider the number of users and could display `and more...`.
`You, user1 and more...`

### Solution

Fix it

**Comment by Silver-IT** [comment]
@taoeffect, I would like to know your opinion about my suggestion to display `and more...` in the beginning of direct messages with many members.

Having checked Slack, I can see that it doesn't display `and more...` but it has its limit of DM members, which is 8.

**Comment by taoeffect** [comment]
@Silver-IT sure, if you do that I would make the words `and more` a link, that when clicked brings up something that shows the full list of participants.
