### ISSUE TITLE
Display both app version and contracts version in the user settings modal

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#2081]
### Problem

in `TabWrapper.vue`, we currently only show the contracts version:

```js
      subNav: [{
        title: `${L('Version')} ${contractsVersion}`
      }, {
        title: L('Acknowledgements'),
        url: 'acknowledgements',
        component: 'Acknowledgements',
        index: 11 // NOTE: index should not be duplicated with the link of tabNav
      }]
```

![Screenshot 2024-06-17 at 10 34 38 AM](https://github.com/okTurtles/group-income/assets/138706/c2cdcf5e-2a64-462b-bdba-d26e2696449e)

This is an issue because there are actually two versions that we keep track of: the contracts version and the App Version.

Any time we update the frontend code (but not the contracts) we bump the App Version (but not the contracts). And any time we bump the contracts, we bump both the App Version and the Contracts Version.

### Solution

Display both versions. Make sure it looks good. You can test two different approaches: the versions as one string on one line, or as two separate lines.

E.g.:

```
Version: App (0.5.1) Contracts (0.5.0)
```

Vs:

```
App Version: 0.5.1
Contracts Version: 0.5.0
```

Pick whichever looks best in the UI with the limited space available.

**Comment by Silver-IT** [comment]
![image](https://github.com/okTurtles/group-income/assets/57976479/fe51bc20-9fd4-4616-965a-0e327e51b716)
Since `Version: App (0.5.1) Contracts (0.5.0)` seems to be too long in comparison to the navbar width, I will use the second option.
