### ISSUE TITLE
Bug: can't upload multiple files on mobile

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#2089]
### Problem

On Android, when I go to pick a picture using the file picker, I can only choose one file at a time, and then when I choose another file it replaces the first picture that I chose.

This means there's no way to post multiple pictures at once on mobile (at least on Android, I haven't tested iOS).

### Solution

Ideally, you should be able to pick multiple files at once in the media picker.

Alternatively, if that is impossible for some reason, then you should be able to add files to the existing set of files that are being attached.

**Comment by SebinSong** [comment]
@taoeffect, I am actually able to select and attach mutlple files via the live staging site on my android phone.


<img src='https://github.com/okTurtles/group-income/assets/17641213/64e8a22a-e83d-4141-8f30-2beb277746b6' width='320'>

**Comment by taoeffect** [comment]
Interesting! It seems to be based on what file thingy you choose.

On mine I click the attachment icon, -> click "Media picker" -> then it opens up the built-in GrapheneOS file manager.

At the top of the GrapheneOS file manager, it says "Browse files in other apps". If I choose "Media picker" *again* from that large list of apps, then it will open up a view that will let me pick multiple files at once.

On iOS (just tested) it works just fine. So I'll chalk this up to GrapheneOS weirdness and close the issue.
