### ISSUE TITLE
Set reasonable character limits for contributions

### ISSUE THREAD

**Issue by dotmacro** [okTurtles/group-income#2113]
### Problem

The text boxes on the contribution screen seem to accept an unlimited number of characters. (For reference, I gave up after 30k chars.) Among other issues, this can make the contributions screen unnecessarily long, and make it difficult for users to see any contributions that are listed between/under lengthy contribution descriptions. This will affect all members, as the lengthy descriptions will show up under either "Receiving" or "Giving".

<img width="381" alt="contributions-noCharLimits" src="https://github.com/okTurtles/group-income/assets/13082264/2247dc4d-dbe8-4c7e-a387-3b1296ed6e96">

### Solution

- Limit the input to a reasonable number of characters. 
- Indicate the user has reached the char limit the same way we do with usernames and group descriptions: an error with the text "Contribution descriptions cannot exceed N characters."
- *Enhancement:* Allow a portion of long descriptions to be hidden under a "more..." toggle.

**Comment by Silver-IT** [comment]
@taoeffect, what do you think is the best reasonable number of characters for this non-monetary contribution?

**Comment by taoeffect** [comment]
150 characters is fine.

**Comment by Silver-IT** [comment]
If it is 150, do we need `more ...` toggle?

**Comment by taoeffect** [comment]
@Silver-IT no, limiting it to 150 is fine, and you can show the `x/150` counter above the field here too
