### ISSUE TITLE
Cypress Heisenbug: creating DMs

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#2132]
### Problem

A failing `group-chat-direct-message.spec.js`:

https://cloud.cypress.io/projects/q6whky/runs/2496/test-results/6fa3ba54-21ea-4733-a7ba-34849475fc2b/video?actions=%5B%5D&browsers=%5B%5D&groups=%5B%5D&isFlaky=%5B%5D&modificationDateRange=%7B%22startDate%22%3A%221970-01-01%22%2C%22endDate%22%3A%222038-01-19%22%7D&orderBy=EXECUTION_ORDER&oses=%5B%5D&specs=%5B%5D&statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D&testingTypesEnum=%5B%5D&utm_source=github

As part of this build: https://github.com/okTurtles/group-income/actions/runs/9715820483/job/26818079823?pr=2131

### Solution

Identify and fix the bug.

**Comment by Silver-IT** [comment]
This one too.

https://cloud.cypress.io/projects/q6whky/runs/2508/test-results/34b69802-9c49-4f1a-887b-a11bafe2637a?actions=%5B%5D&browsers=%5B%5D&groups=%5B%5D&isFlaky=%5B%5D&modificationDateRange=%7B%22startDate%22%3A%221970-01-01%22%2C%22endDate%22%3A%222038-01-19%22%7D&orderBy=EXECUTION_ORDER&oses=%5B%5D&specs=%5B%5D&statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D&testingTypesEnum=%5B%5D&utm_source=github

**Comment by Silver-IT** [comment]
As we can see in the screenshot below, the focus is changed from the textarea to the button.
![image](https://github.com/okTurtles/group-income/assets/57976479/154618ec-4b03-4c57-9427-e290f06ecbbe)

**Comment by taoeffect** [comment]
Think this might be fixed.
