### ISSUE TITLE
Privacy: do not log what channels are deleted

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#2143]
### Problem

Whenever someone deletes a chatroom, the fact that they deleted it is logged to `#general`:

![Screenshot 2024-07-01 at 10 11 35 AM](https://github.com/okTurtles/group-income/assets/138706/890a8410-13e8-4096-8097-e217ffa5883f)

This fact is visible even to everyone, even for private chatrooms.

### Solution

If a chatroom is private, this message should not be logged.

**Comment by SebinSong** [comment]
@taoeffect 
While working on this I accidentally found out another issue which is related to mentioning channel

![image](https://github.com/okTurtles/group-income/assets/17641213/23032327-ccc8-41ca-99b4-4f63784336cc)


channel mention after its deletion leads to this cryptic message. will work on fixing it as part of this issue.

**Comment by taoeffect** [comment]
Great find @SebinSong! 👍
