### ISSUE TITLE
Center vues that currently use column centering hack to center like SignUp.vue

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#220]
### Problem

Several views use my ugly columns-based centering, e.g.:

```html
    <div class="columns">
      <div class="column is-1"></div>
      <div class="column is-10" >
```

This is ugly and unnecessary.

### Solution

Go through all vues and center the ones that are using columns to SignUp.vue method, e.g. via:

```html
<div class="box centered" style="max-width:400px">
```

**Comment by hubudibu** [comment]
using inline styles with a magic number `400px` is far from reusable, I would suggest sticking to Bulma's columns for layout and using `is-offset` classes instead of empty elements, like in `CreateGroup.vue`:
```html
   <div class="column is-half is-offset-one-quarter" >
```
what do you think @willstanley ?

**Comment by willstanley** [comment]
Can we use is-centered https://bulma.io/documentation/columns/options/#centering-columns ?

**Comment by taoeffect** [comment]
> Can we use is-centered https://bulma.io/documentation/columns/options/#centering-columns ?

That seems like an elegant solution to me. I didn't see that before, maybe it's a new feature? Might require upgrading bulma.

Just keep in mind that if it does require upgrading bulma, you'll also need to check the rest of the UI and make sure the new bulma didn't break anything (as upgrading bulma, in our experience, often does break some little thing here or there).

**Comment by hubudibu** [comment]
neat! it is not a documented feature in our version http://versions.bulma.io/0.4.4/documentation/grid/columns/, but I checked and it seems to work! the following centers the page nicely:
```html
<div class="columns is-centered">
    <div class="column is-half"> 
...
```

**Comment by taoeffect** [comment]
I'm guessing this is no longer an open issue.
