### ISSUE TITLE
Heisenbug in group-chat.spec.js

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#2215]
### Problem

While testing a PR I found a problem: https://github.com/okTurtles/group-income/pull/2147#pullrequestreview-2184455017

Copying here:

> On my local test run the last test in `group-chat.spec.js` (`user2 joins the ${groupName1} group and ${CHATROOM_GENERAL_NAME} channel again and logout`) failed:
> 
> https://github.com/user-attachments/assets/136109de-d25c-4cc1-8ae8-08cb0b74f2b5
> 
> This is failing here inside of `cy.giAcceptGroupInvite`:
> 
> ```js
>   if (existingMemberUsername) {
>     // NOTE: checking 'data-groupId' is for waiting until joining process would be finished
>     cy.getByDT('pendingApprovalTitle').invoke('attr', 'data-groupId').should('eq', groupId)
>     // NOTE: should wait until KEY_REQUEST event is published
>     cy.giKeyRequestedGroupIDs(groupId)
>     cy.giEmptyInvocationQueue() // <---------remove
> 
>     cy.giLogout()
> ```
> 
> And then in:
> 
> ```js
> Cypress.Commands.add('giLogout', ({ hasNoGroup = false } = {}) => {
>   cy.giEmptyInvocationQueue()
> 
>   if (hasNoGroup) {
>     cy.window().its('sbp').then(async sbp => await sbp('gi.app/identity/logout'))
>   } else {
>     cy.getByDT('settingsBtn').click() // <------ failing here
> ```
> 
> There are multiple problems here:
> 
> 1. `cy.giEmptyInvocationQueue()` is being called an extra time before `cy.giLogout()` (which also calls it) - so that unnecessary call in `giAcceptGroupInvite` on line `commands.js:498` should be removed.
> 2. And the main problem: for some reason we were given the key to join the group and so the approval screen is visible here and the settings button to log out cannot be clicked, and also there is no need for it be clicked because we're already in the group
> 
> It might be because `user2` was already a member of the group before, and so was somehow able join again because the keys were not properly rotated when he left in `'user2 leaves the group by himself'`.
> 
> However, running the tests a second time everything passed, so this is a challenging and important Heisenbug that needs to be fixed. I will open an issue for this.
> 
> cc @corrideat 

### Solution

1. Determine whether the reason the test failed is due to key rotation not happening when it should (and if so, fix it)
2. If it's unrelated to key rotation, then figure out the problem is and fix the test

**Comment by corrideat** [comment]
I'm unable to reproduce this (using #2294, which fixes #2277), even after running `group-chat.spec.js` a very large number of times. Either it's fixed (it also fixes a long-standing issue with foreign keys and key rotation / new keys) or it's difficult to stumble upon this on my system.

Can you please test and report?

**Comment by taoeffect** [comment]
OK, maybe this issue has been fixed mysteriously, but there is another set of heisenbugs in `group-chat.spec.js` that are documented here: #2256 ....

EDIT: oh i see, maybe #2294 fixes this. OK, we'll see! That PR still needs some updates and if the new commits don't fail on `group-chat.spec.js` then maybe it is fixed

**Comment by taoeffect** [comment]
Might've been fixed by @corrideat in #2294
