### ISSUE TITLE
Unread messages notification badge not appearing for messages in channels 

### ISSUE THREAD

**Issue by dotmacro** [okTurtles/group-income#2216]
### Problem

The notification badge is not appearing on `Chat` in the menubar when there are unread messages. Nor is it appearing on the channels list. This is affecting both public and private channels, but not DMs.

1. User1 sends messages in `general` and in a private channel.
![chatNotificationBadge](https://github.com/user-attachments/assets/80ef3e8f-5077-464c-b9b0-700ba90689d3)

2. User2 does not see any notification badge on `Chat` or unread message counter on `general`. (User2 is not a member of private channel).
![chatNotificationBadge-none](https://github.com/user-attachments/assets/91617248-2147-4395-b441-92d9796ca874)\

3. User3 does not see any notification badge on `Chat`, or unread message counters on `general` or the private channel.
![chatNotificationsMissing](https://github.com/user-attachments/assets/d3d10561-bd9f-4127-b667-58de4de14352)

4. User1 Sends a DM to User3.
5. User3 does see a notification badge both on `Chat` and in the DM list (as an unread message counter).
![chatNotifications--DMsOK](https://github.com/user-attachments/assets/608a8ca9-a19f-4635-af14-771c7fde85ed)

### Solution

1. Ensure notification badge appears on `Chat` in the left menubar when there are unread messages.
4. Ensure notification badge appears on proper channel name(s) when there are unread messages in any.

**Comment by Silver-IT** [comment]
I am not sure where the discussion is, but I remember that we made agreement on displaying red badge on the Chat menu of sidebar only when there are `unreadMessages`.
`unreadMessages` contains mentions(e.g., `@alexjin`, `@sebin`, ...) from any channels, messages of `INTERACTIVE` type (e.g., `@alexjin wants to change group's mincome. See proposal`) from any channels, and any messages from DMs.
So just creating a simple message in a public/private chatroom doesn't make badge on the Chat menu.

And, as we can see in the following Figma design, it also says the badge will be display only there is at least 1 notifications. The `notifications` is what we implemented in our codes as `unreadMessages`.
![image](https://github.com/user-attachments/assets/7d9999c8-0045-4871-8ad7-9d10705bacb6)

It also works same to the badges of channels on the right side of the app.

cc: @dotmacro, @taoeffect

**Comment by Silver-IT** [comment]
We are currently display badges for those `unreadMessages`.
![image](https://github.com/user-attachments/assets/14f6fc64-141f-43b8-85ee-627f0e4afd27)
![image](https://github.com/user-attachments/assets/ac25430f-8801-4115-a74e-b36ab13cc983)

**Comment by dotmacro** [comment]
You’re completely correct @Silver-IT , thank you. Closing.
