### ISSUE TITLE
Set safe char limit for pledge, need, mincome

### ISSUE THREAD

**Issue by dotmacro** [okTurtles/group-income#2218]
### Problem

On `testing`, there is no upper limit for pledge, and entering too big of a pledge effectively breaks the app. 

The entry appears to be saved (i.e. no error indicating otherwise) and the user is returned to the dashboard. However, nothing else seems to work again -- no buttons, menus, or links respond to clicks. When refreshed, the Dashboard is blank and the right menu is missing.

User pledges a lot
![pledgeInfinite](https://github.com/user-attachments/assets/c95ea9e4-002b-4a0b-9eb1-8b3e825f4230)

User refreshes dashboard because nothing is responding to clicks, dashboard goes blank
![pledgeInfinite-refreshLosesDashboard](https://github.com/user-attachments/assets/32926be2-196b-49b2-a19e-1bc343a83a61)

![pledge-outOfMemory](https://github.com/user-attachments/assets/3870cc46-ad22-42a1-99ad-d54fd280011b)

 

### Solution

Fix.

**Comment by dotmacro** [comment]
Note: This prevents the user from switching groups or logging out.

**Comment by taoeffect** [comment]
As far as a suggested fix, please limit the upper range of the pledge to `1000000000`. Think that should be sufficient. :)

**Comment by dotmacro** [comment]
This also affects any other groups that user is a member of. Closing the tab and reopening switches to the first group in my group list (which isn't the one with the one hundred twenty-three octillion dollar pledge). The dashboard in that group seems to be properly populated with everything that should be there, but the app still does not respond to clicks etc.
