### ISSUE TITLE
Implement/enforce `CHATROOM_MAX_MESSAGE_LEN`

### ISSUE THREAD

**Issue by dotmacro** [okTurtles/group-income#2237]
### Problem

Users can send/receive messages longer than [`CHATROOM_MAX_MESSAGE_LEN`](https://github.com/okTurtles/group-income/blob/e89cebeb1ae304749ea5df53359d73229b6734fd/frontend/model/contracts/shared/constants.js#L63C40-L63C46). (For reference, the largest message I tested was 262,144 plaintext chars.)

Nothing looks odd or broken. The app doesn't seem to lag. There's just a very long wall-of-text message to scroll past.

### Solution

Fix.

**Comment by SebinSong** [comment]
I think this is a duplicate issue of https://github.com/okTurtles/group-income/issues/2217

**Comment by taoeffect** [comment]
yeah closing as duplicate
