### ISSUE TITLE
Properly handle/enforce `GROUP_NAME_MAX_CHAR` on group settings page

### ISSUE THREAD

**Issue by dotmacro** [okTurtles/group-income#2238]
### Problem

On the `Group Settings` page, the text box for the group name has no char limit in the UI. However, there's clearly an enforced limit on the backend because the error message indicates that `groupName` cannot exceed 50 chars. 

![groupSettings--groupNameUnlimited--Error](https://github.com/user-attachments/assets/867e4d20-5aad-424d-90a7-8aa0db69d1f7)

### Solution

Fix, presumably by handling `GROUP_NAME_MAX_CHAR` the same here as during group creation.

**Comment by dotmacro** [comment]
Additionally, "You can report the error" in the error message is not a link, and not clickable. @taoeffect Should #1945 be reopened, or is this a new issue?

**Comment by SebinSong** [comment]
@dotmacro 
> Additionally, "You can report the error" in the error message is not a link, and not clickable. @taoeffect Should https://github.com/okTurtles/group-income/issues/1945 be reopened, or is this a new issue?

You can see them as separate issues as those are two different UI components. I can handle that bug as part of this task.
