### ISSUE TITLE
Invite links not working reliably 

### ISSUE THREAD

**Issue by dotmacro** [okTurtles/group-income#2240]
### Problem

Invite links don't seem to be working properly 100% of the time.

If the user is already in at least one group, the invite link seems to only redirect them to the dashboard of the first group in their group list. (See comments below).

### Solution

Fix.

**Comment by dotmacro** [comment]
1. Sign in to group1 & group2 as user1.
2. In group2, user1 receives invite link to group3 from user2 via group2 chat.
3. User1 clicks invite link in chat message.
4. App redirects to Dashboard of first group in user1's group list (NOT group3). Group3 is not added to user1's group list. User is not prompted to do anything about group3.

**Comment by dotmacro** [comment]
Same as [above](https://github.com/okTurtles/group-income/issues/2240#issuecomment-2240870920), except invited user is only in one group before receiving the invite link.

1. Sign in to group2 as user5.
2. In group2, user5 receives invite link to group3 from user2 via group2 chat.
3. User5 clicks invite link in chat message.
4. App redirects to Dashboard of group2, the first and only group in user5's group list (NOT group3). Group3 is not added to user5's group list. User is not prompted to do anything about group3.

**Comment by taoeffect** [comment]
In the second example there that I tried, this is the error in the console:

![Screenshot 2024-07-24 at 12 23 55 PM](https://github.com/user-attachments/assets/6fd6072e-bc4c-4665-b166-b4fa8606ccad)
