### ISSUE TITLE
Wide code snippets in chat don't display correctly

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#2243]
### Problem

![Screenshot 2024-07-20 at 6 28 34 PM](https://github.com/user-attachments/assets/acb5cbd8-0b0c-4a7e-80bb-0a184d799fcd)

Notice how it's going off and to the right past the scrollbar in the chatroom.

### Solution

- The code block should be inside of a div that has a maximum width that expands to the side of the chat container.
- When text goes beyond that width, a horizontal scrollbar should appear at the bottom of the codeblock (don't wrap the text, in other words)

**Comment by Silver-IT** [comment]
Also I think we need limit on the number of reactions or to wrap them to fix the overflow of reactions.
![image](https://github.com/user-attachments/assets/d08251cb-40ad-49fe-8565-8d44c3099250)

**Comment by Silver-IT** [comment]
Also for the pinned messages too.
![image](https://github.com/user-attachments/assets/212266a0-3a77-473b-9394-b8f9c143e443)

EDITED: Fine to skip this error in this issue. Since it's added to another issue #2250

**Comment by SebinSong** [comment]
@Silver-IT go ahead and open an issue / work on them yourself.

(EDIT: I actually fixed it myself)

**Comment by Silver-IT** [comment]
Okay, I added the issues in #2250.

**Comment by SebinSong** [comment]
@Silver-IT I actually fixed it as part of the ongoing PR. So, no worries. (And good catch 👍)

**Comment by SebinSong** [comment]
Issue resolved in #2247 . closing.
