### ISSUE TITLE
Newly created chatroom isn't joined on other device.

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#2252]
### Problem

1. On groupincome.app, on mobile, I created a chatroom and joined it while my other computer (desktop) had its internet disabled and the computer asleep.
2. On Desktop I woke the computer and enabled Internet and I was not joined to the newly created chatroom.
3. Then I refreshed the page, still not joined.

During this time I also experienced #1943 for about 2 minutes.

There was another problem: when I deleted the chatroom on mobile, on Desktop I got this error (because on Desktop it had not joined the chatroom):

![Screenshot 2024-07-24 at 5 15 08 PM](https://github.com/user-attachments/assets/605ba803-f85b-449b-9ab8-62b7153d7b7f)

**EDIT: New more reliable and simpler steps to reproduce the problem**

1. Login to group as u1 on Browser 1
2. Login as u1 on Browser 2
3. Quit Browser 1
4. Create private channel in Browser 2
5. Start Browser 1 and visit the site again (if it isn't already opened)

### Solution

FIX.

**Comment by taoeffect** [comment]
Hmm.. Having trouble reproducing this.

**Comment by taoeffect** [comment]
I was able to reproduce this by doing the following:

1. Login to group as u1 on Browser 1
2. Login as u1 on Browser 2
3. Quit Browser 1
4. Create private channel in Browser 2
5. Start Browser 1 and visit the site again (if it isn't already opened)

**Comment by taoeffect** [comment]
Found the source of the problem! (Not yet sure on the solution). It's that in the `'gi.contracts/group/joinChatRoom'` sideEffect, `identityContractID` is `undefined` here:

```js
      sideEffect ({ data, contractID, innerSigningContractID }) {
        const memberID = data.memberID || innerSigningContractID
        const { identityContractID } = sbp('state/vuex/state').loggedIn
        console.info(`!! SIDEFFECT JOINCHATROOM: ID(${identityContractID}) === INNER(${innerSigningContractID}) ${innerSigningContractID === identityContractID}`)
        // If we added someone to the chatroom (including ourselves), we issue
        // the relevant action to the chatroom contract
        if (innerSigningContractID === identityContractID) {
          sbp('chelonia/queueInvocation', contractID, () => sbp('gi.contracts/group/joinGroupChatrooms', contractID, data.chatRoomID, memberID)).catch((e) => {
            console.warn(`[gi.contracts/group/joinChatRoom/sideEffect] Error adding member to group chatroom for ${contractID}`, { e, data })
          })
```

**Comment by corrideat** [comment]
Does using `chreonia/rooState` instead of `state/vuex/state` fix it? There's roughly equivalent (but loggedIn in Cheonia is set a bit earlier). If that fixes, there should be a TODO explaining this and about this needed to change with full SW and/or sandboxing.
