### ISSUE TITLE
Login error on staging server: "hash() !== since"

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#2279]
### Problem

The staging server represents a period copy of the production server.

I was logged in to it at one point and then somehow got logged out. When I tried logging back in I got these errors:

![screenshot_2024-08-01_at_8 47 21___pm](https://github.com/user-attachments/assets/7a133031-fca1-4d48-8880-4f05987a30be)
![screenshot_2024-08-01_at_8 47 55___pm_720](https://github.com/user-attachments/assets/9a944725-d69a-45c7-94f8-6b46f3a749ba)

Note: I _can_ login in a private window, suggesting that this is an issue with the local vuex and/or chelonia state getting out of sync with the server and causing some sort of weird problem that shouldn't ever happen.

### Solution

Diagnose and fix.

**Comment by corrideat** [comment]
@taoeffect Are you able to share the URLs from the network log when you get this error?

**Comment by corrideat** [comment]
It looks like this issue was caused by a fork in the chain, as `state.contracts[identityContractID].HEAD` has a value that doesn't exist as a hash on the server.

This could have been caused while copying the database from one server to the other.

**Comment by taoeffect** [comment]
So to elaborate, the theory that @corrideat came up is that my client performed some sort of operation on the identity contract, i.e. some opcode, whether a contract action or a key operation. This updated my local client state and specifically the value for `recentHEAD` here:

```js
const { HEAD: recentHEAD, height: recentHeight } = state.contracts[contractID] || {}
```

Then when the database from production got copied over to staging, this resulted in a fork between my local client state and the server's, resulting in a 404 because `recentHEAD` was wrong when looking up `eventsAfter`.
