### ISSUE TITLE
Implement placeholders for payment options

### ISSUE THREAD

**Issue by dotmacro** [okTurtles/group-income#2282]
### Problem

Figma design includes placeholders for the `payment info` text boxes. They are not yet implemented.
(Based on potential-user feedback, these specific placeholders are necessary and would be helpful.)

![placeholders](https://github.com/user-attachments/assets/a103fae6-1151-4fde-ab83-b7930d5668d6)

Figma link: https://www.figma.com/design/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?node-id=27201-31990

### Solution

Implement

**Comment by SebinSong** [comment]
@taoeffect 
Is this issue to allow users to add/type any payment options of their choices?
If so, what's the difference between this and choosing 'other' from the dropdown and user entering the payment detail there?

<img src='https://github.com/user-attachments/assets/08895ed7-dc05-444d-beb2-55321cd449f0' width='430'>

**Comment by taoeffect** [comment]
No, I'm pretty sure it's talking about these:
![354960981-a103fae6-1151-4fde-ab83-b7930d5668d6](https://github.com/user-attachments/assets/f1ae2f72-ddbf-4648-8718-e9f7a2f2d241)

**Comment by SebinSong** [comment]
@taoeffect 
The figma doesn't have placeholders for 'Lightning' and 'Other' options. what do we use for their placeholders?

<img src='https://github.com/user-attachments/assets/1dbe8bf3-51be-4b9a-8d96-6f547bb16af5' width='480'>

**Comment by taoeffect** [comment]
Lightning: Lightning address
Other: [leave this blank]
