### ISSUE TITLE
Notification when new non-monetary contributions are added

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#2305]
### Problem

We don't currently notify group members when a new non-monetary contribution has been added.

### Solution

Post these notifications:

- `{memberName} added non-monetary contribution: {contribution}`
- `{memberName} removed non-monetary contribution: {contribution}`

**Comment by SebinSong** [comment]
@taoeffect can be an obvious question but by notifications here, did you mean this in-app notification?

<img src='https://github.com/user-attachments/assets/8f33a626-3214-4f47-81d8-6f14de249483' width='370'>

**Comment by taoeffect** [comment]
@SebinSong yep, those in-app notifications.
