### ISSUE TITLE
Cannot mark notifications as read

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#2311]
### Problem

![Screenshot 2024-08-20 at 9 42 35 AM](https://github.com/user-attachments/assets/e9ecb047-0023-4b07-97e4-08846a2c819d)

In ~~1.0.7~~ 1.0.6, both on desktop and on mobile, no matter whether I click "Mark all as read" or click on the notification itself, the notification does not get marked as read.

In fact this happens on `testing` too, where I have 16 unread notifications:

![Screenshot 2024-08-20 at 9 47 29 AM](https://github.com/user-attachments/assets/5f694193-39f7-460c-8857-07651c69a5fb)

### Solution

Fix!

**Comment by dotmacro** [comment]
I'm having the same problem. 

For notifications that are new (i.e. less than 1 month old and from the current period) I noticed I can mark them as read by clicking on them individually. 
For old notifications (i.e. from a previous period), I cannot mark them as read by clicking on them or by clicking "Mark as read".

**Comment by snowteamer** [comment]
Where is version v1.07 ? I can only find v1.06

On my end, clicking mark all as read marks all notifications as read except the last one, i.e. there is one item still unread at the bottom of the notification popup:
![image](https://github.com/user-attachments/assets/534886dc-40cf-4f1e-ac38-0300abb1db56)

**Comment by taoeffect** [comment]
> Where is version v1.07 ? I can only find v1.06

Oops, I meant 1.0.6!

**Comment by taoeffect** [comment]
Based on this call:

- Increase KV notification status memory to 2 months
- Increase Vuex notification memory to 6 months
- Automatically mark notifications as read after the notification status memory window (e.g. after 2 months)
- Purge notifications from Vuex store that are older than 6 months

**Comment by taoeffect** [comment]
Closed by @corrideat in #2333.

**Comment by dotmacro** [comment]
I'm still having this issue with 1.1.0 on `testing`. As before, for a notification from the previous period, I cannot mark it as read. 

![image](https://github.com/user-attachments/assets/9290df37-5f79-46ab-855c-5a8947b9314a)
