### ISSUE TITLE
Picture viewer

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#2347]
### Problem

We don't have a way to zoom the pictures to view them more closely.

### Solution

Create a picture viewer so that when a picture attachment clicked (or tapped) then it is shown in a view in more detail similar to how other apps do it.

On mobile it should be very simple - simply make the picture full screen and make it possible to pinch to zoom in and out.

**Comment by SebinSong** [comment]
@taoeffect 
I'm referencing Slack's image viewer and it has 200% as the maximum zoom-in limit for all cases, regardless of how big/small the intrinsic image size is.

![image](https://github.com/user-attachments/assets/dcd778ff-7ad4-44f3-bab2-b9782e7e087e)

That's when it's viewed on desktop and on mobile-app  it seems to allows more zoom-in (it's not sure as it doesn't show the in-app slider UI on mobile-app but it feels like 300 or 400%).

What do we want as the maximum value in our app?

**Comment by taoeffect** [comment]
Let's go with 400% and if you feel that doesn't work well feel free to pick a value that you like better
