### ISSUE TITLE
Close proposals when they expire

### ISSUE THREAD

**Issue by dotmacro** [okTurtles/group-income#2373]
### Problem

On `testing`, proposals are not closed when they expire. This was tested with a proposal that closed more than two months ago.

![expiredProposal](https://github.com/user-attachments/assets/caf47aa5-ae46-4522-9452-5921245dcb42)

Even though the proposal has expired, the "Change vote" link remains, and works.

![expiredProposal--canVote](https://github.com/user-attachments/assets/3cdccc82-d1a3-4f70-8cc8-2074b738d7ea)

Even though the proposal has expired, the user can change their vote.

![expiredProposal--changedVote](https://github.com/user-attachments/assets/4257148b-a437-45ed-85bf-e33d55b680b1)

### Solution

When proposals expire, they should be closed. This means that:
- on expirey, proposals should automatically close with `STATUS_FAILED` or `STATUS_PASSED`
- proposals with `STATUS_FAILED` or `STATUS_PASSED` should not be able to be voted on by any member

**Comment by SebinSong** [comment]
Apparently this error message is the cause of the issue:

<img src='https://github.com/user-attachments/assets/aa00d33b-f1ff-4b87-b0d0-c8f0e8828c8d' width='530'>
