### ISSUE TITLE
Compress images before uploading them

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#2411]
### Problem

Images taken by modern phones can be huge, ranging from 5MB to 10MB or even more.

This causes these problems:

- Server running out of space
- Images taking a very long time to load on slower connections

There is no reason for us to upload these massive images in their entirety to the server when they're attached.

### Solution

Similar to how Signal works when uploading an image, find a way to compress the image by reducing its size so that it remains under a specific file size while keeping the quality of the image high.

For example, you could compress images so that they're no larger than 400KB.

**Comment by SebinSong** [comment]
[References for study]
- https://img.ly/blog/how-to-compress-an-image-before-uploading-it-in-javascript/
- https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob
- https://www.adobe.com/uk/creativecloud/photography/discover/lossy-compression.html

<br>

[Check if the browser supports webp image format]
- https://developers.google.com/speed/webp/faq#in_your_own_javascript
