### ISSUE TITLE
Ensure menu expands in visible area

### ISSUE THREAD

**Issue by dotmacro** [okTurtles/group-income#2415]
### Problem

On the `Payments` screen (both the received & sent tabs), each row has three dots that, when clicked, open a menu. However, because the menu opens below the three dots, the menu isn't visible for the last payment in the table. 

Menu properly visible: 
![image](https://github.com/user-attachments/assets/b850b709-3a54-4cfe-840c-53d5ed205f31)

Menu not visible for last payment:
![image](https://github.com/user-attachments/assets/accc8011-3d7e-4049-b484-5e24db54cb3a)

Menu not visible for only (and necessarily last) payment:
![image](https://github.com/user-attachments/assets/d7b6e188-900e-42f7-a0bf-8ccb1fb8195b)

### Solution

Ensure the menu is visible and usable for all items in the table.

**Comment by SebinSong** [comment]
@dotmacro I've created a PR (https://github.com/okTurtles/group-income/pull/2410) that will fix this issue, FYI.

cc. @taoeffect

**Comment by dotmacro** [comment]
Oh, I missed that, thanks!
