### ISSUE TITLE
Ensure info/tooltips show in visible area

### ISSUE THREAD

**Issue by dotmacro** [okTurtles/group-income#2434]
### Problem

On mobile, when the user taps the "n members" link on the dashboard, the tooltip is not fully visible on the screen. 
![image](https://github.com/user-attachments/assets/949b0540-1121-47fd-bfec-05ef134bfef2)

### Solution

Ensure info/tooltip is fully visible on screen.

**Comment by Vayras** [comment]
@dotmacro I'm a new contributor and I wish to contribute towards this issue

**Comment by taoeffect** [comment]
@Vayras I've gone ahead and assigned this issue to you. Feel free to take it on!

**Comment by taoeffect** [comment]
@dotmacro you shouldn't be seeing contractIDs for usernames. Can you open an issue for that too?

**Comment by dotmacro** [comment]
> @dotmacro you shouldn't be seeing contractIDs for usernames. Can you open an issue for that too?

Investigated, opened #2437

**Comment by taoeffect** [comment]
Closed by @Vayras in https://github.com/okTurtles/group-income/pull/2436
