### ISSUE TITLE
Ensure menus expand in visible area

### ISSUE THREAD

**Issue by dotmacro** [okTurtles/group-income#2448]
### Problem

"Create proposal v" menu does not always expand in visible area.

Steps to reproduce:
1. Scroll to bottom of Dashboard (i.e. bottom of "Proposals" section).
2. Tap "Create proposal v" to open menu
3. See menu expand, but not fully onscreen (depending on height of "Proposals" section) **<-- the problem**
4. Optionally, scroll to bottom of screen to see full list of proposal options
5. Tap "Create proposal ^" to hide menu
6. Menu disappears and bottom of "Proposals" section is properly spaced from bottom of screen (via shrink & auto-scrolling if necessary)

Short "Proposals" section means full menu of proposal types isn't visible
![image](https://github.com/user-attachments/assets/552c4ffe-54c9-4ebe-83dd-cc7ef0e40c76)

Sufficiently long "Proposals" section means full menu of proposal types is visible, no problem
![image](https://github.com/user-attachments/assets/5d3b73f9-c1c7-43f6-83cd-ff6cd1dc1c5f)

### Solution

1. Ensure all proposal types are visible when menu is opened. Expanding the page and auto-scrolling so the full menu is visible (i.e. the opposite of functionality in step 6 above) would be a smooth way to do this.
2. Optional: Align menu with right (preferred, current) or left (fallback if necessary) of "Create proposal v" button so that the menu is also fully visible left-to-right.

**Comment by taoeffect** [comment]
What browser/platform did you use to reproduce this? I can't reproduce it in responsive mode on either Brave or Firefox. This for example is in Firefox:

![Screenshot 2024-12-17 at 12 28 44 PM](https://github.com/user-attachments/assets/518e5e82-28e2-4690-812b-f1e5344493c1)

**Comment by dotmacro** [comment]
Reproduced on both Safari and Brave on iOS. Sorry, I thought I’d included that in the issue.
