### ISSUE TITLE
Fix missing Foco font

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#245]
### Problem

The console reports it cannot load Foco, and that's because it's not where it should be, i.e. `http://localhost:8000/simple/fonts/FocoBold.ttf` fails to load because it's not in `dist/simple/fonts/`.

### Solution

Copy the font properly.

**Comment by danawoodman** [comment]
Closing in preference of the PR #249

**Comment by taoeffect** [comment]
Let's follow the standard procedure of closing if a PR is accepted, as there could be issues with a PR.

**Comment by danawoodman** [comment]
Ok, I wasn't aware that was standard. I personally prefer to close an issue if it is dealt with in a PR but I'll keep issues open in the future

**Comment by taoeffect** [comment]
Fixed by #251
