### ISSUE TITLE
Remove `prettier-standard` from deps

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#247]
### Problem

#233 hasn't been merged but for some reason `prettier-standard` made its way into the dependencies

*Note:* This dependency, if/when added in the future, must be specified by the precise version number, no `^`'s allowed.

In the future we should move towards both eliminating dependencies as well as ensuring their integrity, because Yarn doesn't do that for us: `https://github.com/yarnpkg/yarn/issues/2287`

### Solution

Remove `prettier-standard` for now.

**Comment by danawoodman** [comment]
Closing for PR #248

**Comment by danawoodman** [comment]
Regarding dependencies, I get the desire to do that in production dependencies but what purpose does that serve in development where security is not much of a concern?

PS: I didnt have `save-prefix false` set for yarn thats why it saved the version prefix

**Comment by taoeffect** [comment]
> Regarding dependencies, I get the desire to do that in production dependencies but what purpose does that serve in development where security is not much of a concern?

During development, a rogue dependency can compromise your machine, which can be used to compromise the entire project.

**Comment by danawoodman** [comment]
@taoeffect is there any process to ensure this doesn't happen other than "don't have a lot of dependencies"? Are we using any sort of tools to check for this? What is "too many dependencies"? Just looking for a more concrete idea of what you think is acceptable or not

**Comment by taoeffect** [comment]
We don't have a process in place to protect against this yet besides limiting dependencies, having copious tests, and not having anything worth compromising (at this point). There are open issues (see security tag) for other plans on this.

**Comment by danawoodman** [comment]
@taoeffect ok, I'm trying to figure out a measure for when it's appropriate for me to add a dependency in your eyes. I guess we will just discuss this in the PR?

**Comment by taoeffect** [comment]
It would be better to discuss this in Slack/Gitter before you pull the trigger on adding a dependency. Why waste work? Let's talk it over first.
