### ISSUE TITLE
Disable deleting account

### ISSUE THREAD

**Issue by dotmacro** [okTurtles/group-income#2478]
### Problem

Deleting the user's account isn't implemented right now (see #1927). When the user clicks on the "Delete account" button, nothing happens.

![image](https://github.com/user-attachments/assets/9ca4e0b6-aa6f-45ad-9977-49462bcb93bc)

### Solution

1. As in #2173, please make it so that when the "Delete account" button is clicked, a `gi.ui/prompt` is shown that says:

    Sorry, this feature has not been implemented yet. Please check back later.

With a single button: "OK"

2. Fix the typo: add a space between the two sentences in the explanatory text above the button.

**Comment by corrideat** [comment]
IMO, this feature needs some additional thought for its implementation. When we implement deleting contracts, deleting the user account will recursively delete all contracts the parent contract owns, meaning that all groups, chatrooms, attachments, etc. will also be deleted as this happens.
