### ISSUE TITLE
Make standard linter lint .vue files

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#253]
### Problem

It [seems](https://github.com/okTurtles/group-income-simple/pull/251/files#r113324710) like our standard linter isn't linting .vue files.

### Solution

Fix it.

**Comment by danawoodman** [comment]
@taoeffect yeah this seems to be the case for a lot of linters and might be an issue with using .vue files since a parser has trouble knowing what to do. I've looked around a bit and can look deeper if we want?

**Comment by taoeffect** [comment]
Apparently it does seem to lint vue files now.
