### ISSUE TITLE
Icons weirdly offset in registration + login

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#256]
### Problem

While testing out PR #251, noticed that the favicons are now not where they're supposed to be, but oddly placed up and to the left:

![screen shot 2017-05-30 at 6 13 30 pm](https://cloud.githubusercontent.com/assets/138706/26611547/e022f89a-4563-11e7-8d98-910789b6537c.jpg)

In the login, only one of them is messed up:

![screen shot 2017-05-30 at 6 14 15 pm](https://cloud.githubusercontent.com/assets/138706/26611560/f319cd0c-4563-11e7-9977-fc2427367437.jpg)

### Solution

Fix?

**Comment by hubudibu** [comment]
this looks like a duplicate of #302 and thus be fixed by #322 , so can we close this @taoeffect ?

**Comment by taoeffect** [comment]
Wow, nice catch @hubudibu. I even duplicated the screenshot without realizing it, lol.
