### ISSUE TITLE
Switch to NPM 5?

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#262]
### Problem

- Yarn is gives poor output on integrity check failures and also randomly fails (#152)
- Yarn is not "official npm" stuff, yet attempts to integrate with npm

### Solution

NPM 5 was recently released, and besides being much faster than before (maybe comparable to yarn now?) it also claims to do integrity checks via its shrinkwrap functionality. Hopefully it's much better about it than yarn.

If we switch to it, figure out the most secure way of using it. I'm guessing that we'll need to use the "hash-stamped tarballs" feature.

https://medium.com/npm-inc/npm-5-is-now-npm-latest-d674e9e3b0ec

EDIT: [Understanding lock files in NPM 5](http://jpospisil.com/2017/06/02/understanding-lock-files-in-npm-5.html)

**Comment by danawoodman** [comment]
Why not go to Node 7.9 instead?

**Comment by danawoodman** [comment]
Or Node 8 which was just released

**Comment by taoeffect** [comment]
Oops, title should say *NPM*, not node.
