### ISSUE TITLE
PROPOSAL: Use HTTP routes 

### ISSUE THREAD

**Issue by danawoodman** [okTurtles/group-income#266]
I find it counter-intuitive and confusing that routes have no "state" to them. For example, going to `/invite` will allow you to invite members to a group but it's not obvious what group you're inviting members to. Just because we have a SPA doesn't mean we don't need a concept of URL state IMO.

Advantages of using routes:
- Simpler logic for group lookup (router can do a group lookup)
- Ability to bookmark/share links
- No need to manually fire events when wanting to switch between groups, just link to it and the router can do it for us

Routes:
- `/groups`
- `/groups/:id`
- `/groups/:id/invite`

**Comment by taoeffect** [comment]
I think we do this now?
