### ISSUE TITLE
Browserify watch is very slow

### ISSUE THREAD

**Issue by dsernst** [okTurtles/group-income#274]
### Problem

The default settings for `grunt dev` are very slow to watch, compile, and reload new changes.

![image](https://user-images.githubusercontent.com/6340841/27447903-9aeb471a-5737-11e7-93d7-ef1b85d48bd3.png)

This makes front-end development noticeably sluggish and really slows down being able to try out changes.

### Solution

I'm not super familiar with the app's underlying front-end tooling, so I don't know what has already been investigated and optimized.

My first guess would be to investigate using caching for incremental builds. [`watchify`](https://github.com/substack/watchify) should do this out-of-the-box. 

The most important thing is to get those numbers down from the current ~13s to something like 2s or less...

**Comment by taoeffect** [comment]
There's also the option of using webpack with hot module reloading (#170).

But yeah if watchify makes this simple then we can try that route too and go with whichever one is better.

Honestly right now it's really up to whoever gets to doing this first.

**Comment by taoeffect** [comment]
Just came across [browserify-incremental](https://github.com/jsdf/browserify-incremental) which says it has some advantages over watchify. Haven't looked into it in detail though to confirm.

**Comment by taoeffect** [comment]
Here are some possibly outdated tips on running watchify with grunt: http://aeflash.com/2014-05/watchify-and-grunt.html
