### ISSUE TITLE
MembersCircle.vue component

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#282]
### Problem

We need a component for the dashboard (#198) to display the members and the group's progress, but we don't have one.

### Solution

Create it. This will be based/inspired on the work done by @brodeur.

**Comment by taoeffect** [comment]
We're not longer using the member's circle in the Dashboard display, but we might still use in the vue that shows a group to a user who's just been invited to a group.

I.e. it can be useful as a public/world-facing display of the group and its members (if they choose to show that info, which should also be a setting).

**Comment by sandrina-p** [comment]
I didn't understand well this... could you explain it better?

**Comment by taoeffect** [comment]
@sandrina-p Have a look at [this early UI mockup](https://groupincome.org/wp-content/uploads/2016/06/group-dashboard-income_streams.png) that's currently on the groupincome.org homepage.

The `MembersCircle.vue` file implements that sort of view, and originally it was going to be used in the Dashboard but now I'm thinking it's better to place it in the screen that's shown when you've been invited to join a group.

**Comment by taoeffect** [comment]
This has been moved to the invite screen and closed by #407
