### ISSUE TITLE
Make tests not pollute/conflict with an existing database data

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#29]
- Make tests not pollute/conflict with an existing database data
- Make tests clean up after themselves so that you can run `grunt test` (#8) multiple times

**Comment by AnObfuscator** [comment]
I assume that we want to be able to preserve data while developing, that won't get blown away with every test run.

If so, my first instinct is to create another local sqlite database file specifically for running tests. To do this, we'd need to make the database file used when creating the database (currently in backend/index.js) configurable.

Does this sound like a good direction to you?

**Comment by taoeffect** [comment]
@AnObfuscator yeah sounds good. You should rely on `process.argv` for that (see how it's done in Gruntfile.js).
