### ISSUE TITLE
Improve logging on backend

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#32]
## Problem
- it's unclear how to log errors properly
- on travis it's too verbose
- needs colors
## Solution
- See **official [Hapi.js logging documentation](https://hapijs.com/tutorials/logging?lang=en_US)**
- investigate [hapi plugins](http://hapijs.com/tutorials/logging#logging-plugins) for better logging, like **[poop](https://github.com/hapijs/poop)** and **[good-console](https://github.com/hapijs/good-console)** (see [log rotation example](https://github.com/hapijs/good/blob/master/examples/log-to-file.md))
- replace all calls to console.error / console.log with some decent library (the Good of Hapi? Winston?)

EDIT:

- See [Pino](https://github.com/pinojs/pino) and popular [debug](https://github.com/visionmedia/debug) logging libraries, [very fast](https://medium.com/the-node-js-collection/get-ready-a-new-v8-is-coming-node-js-performance-is-changing-46a63d6da4de)
- [bunyan](https://github.com/trentm/node-bunyan) was also recommended [here](https://tomasz.janczuk.org/2015/09/from-kafka-to-zeromq-for-log-aggregation.html) and while it's not as fast as pino or debug, it's faster than winston

**Comment by danawoodman** [comment]
@taoeffect I'd like to take this on if that's ok. I would propose we use [winston](https://github.com/winstonjs/winston) which we can hook up to any logging backend. Also, we can set log levels in our tests suites which would remove logs there (big win for test suite readability). Thoughts?

**Comment by taoeffect** [comment]
@danawoodman As this is not critical for getting the prototype out the door, let's put this off for a bit
