### ISSUE TITLE
Should be able to invite group members by email address or phone number as well

### ISSUE THREAD

**Issue by hubudibu** [okTurtles/group-income#326]
### Problem

Currently we only have the option to invite group members by _username_, which restricts this feature to existing users. Inviting someone who is not yet registered requires another step outside of this platform to tell them to register, which is inconvenient.

### Solution

Make it possible to invite group members by email address or phone number too. 
Have convenience _available_, but _don't require it_. So, the input field would accept an email, a phone number, *and* a username as well.
Prefer not using external services when it comes to sending email and text messages.

**Comment by mmbotelho** [comment]
I am closing this one - the way we invite members has significantly changed. A more updated issue on this would be here - #553
