### ISSUE TITLE
Make UI/UX flow more intuitive

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#327]
### Problem

The prototype will likely be done *not* in Electron but in the browser, and currently the prototype UI isn't very intuitive.

### Solution

Go through UI and address various issues like:

- Back/forward not working in mailbox workflow (e.g. clicking on invite, clicking back, etc.)
- Mailbox being confusing in general
- Various UI glitches
- Handling errors better (like what happens if the backend database is broken, i.e. doesn't return correct info for username e.g. issue #294), etc.

**Be sure to _first_ prioritize the issues in rank of most-urgent to least-urgent** before working through them.

**Comment by mmbotelho** [comment]
@taoeffect do you think this issue can be closed?

**Comment by taoeffect** [comment]
Yeah, thanks for noticing that!
