### ISSUE TITLE
Add donation link

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#332]
### Problem

Current README doesn't include any mention on how to support the project.

### Solution

Add links to https://okturtles.com/donate/ and https://groupincome.org/donate/ to README using buttons and whatnot.

**Comment by dotmacro** [comment]
Mockup w/ donate buttons:

![image](https://user-images.githubusercontent.com/13082264/43751136-58e37d6c-9997-11e8-9335-a9ed3d07ab28.png)

A few questions about the buttons:
- Should the buttons be at the top with the dev buttons, or at the bottom under the `Donating` header (with the text links)?
- Should all buttons be the same color (which color?), or use colors matching the payment type (as in the image)?
- Fiat button shows currencies supported by Donorbox. Other better ideas appreciated :)

**Comment by taoeffect** [comment]
> Should the buttons be at the top with the dev buttons, or at the bottom under the Donating header (with the text links)?

At the top

> Should all buttons be the same color (which color?), or use colors matching the payment type (as in the image)?

Same color, blue.
