### ISSUE TITLE
Error in GroupDashboard when member accepts invite

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#333]
### Problem

While testing PR #325 (new group creation flow), I noticed an error in the console:

![screen shot 2017-11-24 at 6 14 21 pm](https://user-images.githubusercontent.com/138706/33226484-a16f14be-d143-11e7-9cd1-1d1cf38d90c7.jpg)

This is how I created:

1. In **Window 1**, I went through the group creation and invited a user that was created in incognito **Window 2**
2. **Window 1** displayed the GroupDashboard, while in **Window 2** I clicked "Accept" to accept the invite
3. **Window 1**'s console showed the error above

Strangely, in Window 2's GroupDashboard view did not show that error upon visiting the dashboard, and Window 1 wouldn't show the error either after refreshing the page.

The code that errored out is this higlighted line from `state.js` (via a call from GroupMembers.vue):

![screen shot 2017-11-24 at 6 14 51 pm](https://user-images.githubusercontent.com/138706/33226500-2bc32b78-d144-11e7-84c5-11a2cf5501eb.jpg)

### Solution

Figure out what's going on and fix it. I haven't checked whether this is an issue with PR #325 only or if this is also a problem with `master`. /cc @hubudibu

**Comment by hubudibu** [comment]
I could reproduce this in both unfortunately.
The problem is that we are trying to access attributes of a user that did not exist yet when we got the user list from the server. (The good news is that this scenario happens much more often in development than it will with real users.)
The solution could be to either fetch a new state from the server in this case, or ready the UI to not display certain attributes for new users.

**Comment by taoeffect** [comment]
> The solution could be to either fetch a new state from the server in this case, or ready the UI to not display certain attributes for new users.

I think the code just needs to make sure `state[profile.contractId].attributes` is initialized properly.

**Comment by hubudibu** [comment]
I'm not sure I understand you correctly here. when that state is initialized, that user did not exist yet - you created it after that in another window I assume - so it _was_ actually initialized properly. I assume this has a very low chance of happening in production. this is why I suggested to

- either reinitialize the state if it's not filled at this point,
- or handle not having those attributes on the UI gracefully.  

do you mean that I should do the first option, or are you suggesting another solution?

**Comment by taoeffect** [comment]
Copying my reply from Slack just for reference:

> @aniko regarding your comment in: https://github.com/okTurtles/group-income-simple/issues/333#issuecomment-377591240
> 
> i'm saying that the value for `state[profile.contractId].attributes` be initialized properly in `frontend/simple/js/events.js`. Obviously `profile.contractId` exists. We need to make sure that _before_ `profilesForGroup` gets called, that `state[profile.contractId]` gets properly filled in with initial values, even if they are empty
> 
> if that's not clear, then if you're around to do a quick call about this either right now or in like an hour (2pm pacific), let me know, otherwise we can chat about it over the weekend if you like (or on the monday call)
> 
> i don't know if this means that you need to create a contructor-mutation in `IdentityContract`, but that might be one possible way to do it. I'd have to catch up on the code and right now i've gotta go do my daily exercise

To which you replied:

> I will take this as a yes to option 1 - filling `state[profile.contractId]` at some point before getting to the error. you don’t need to dig in the code, I will come up with something

Yes, indeed, except I think just initialize, not re-intialize. :)

**Comment by taoeffect** [comment]
I think this has been fixed? I don't remember seeing it in recent tests. Closing, feel free to reopen if that's not the case.

**Comment by hubudibu** [comment]
unfortunately it's still there :(

**Comment by sandrina-p** [comment]
I tried to replicate these exact steps and the error isn't there anymore. (neither on window 1 or window 2). I believe we can close this?

**Comment by taoeffect** [comment]
Yeah I haven't seen this come back.
