### ISSUE TITLE
Create some generic currency class/object

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#339]
### Problem

https://github.com/okTurtles/group-income-simple/pull/338#issuecomment-357836407

Quoting @hubudibu:

> I also noticed another bug, that the minimum income field didn't accept decimals, which is not that useful for a mincome set in bitcoin :) now it accepts 2 decimals, based on validation I found on the profile page. let me know if I should increase it.

### Solution

https://github.com/okTurtles/group-income-simple/pull/338#issuecomment-357836407

Copying/pasting:

Well, in the future I'm guessing the standard BTC unit will be mBTC or something like that, which is easier to deal with. We might want to have "currency" be a class of some sort that includes various info about the currency like:

- Its full name (Bitcoin)
- Its abbreviated name (BTC)
- Its currency symbol (₿ - yes, [there's now a real](https://en.bitcoin.it/wiki/Bitcoin_symbol), dedicated symbol for Bitcoin in Unicode)
- The number of decimal places allowed (e.g. dollars usually allow for two, whereas BTC requires way more, and mBTC can deal with fewer)

EDIT: it is probably better to simply have functions that operate on the abbreviated name instead of introducing any classes.

**Comment by dotmacro** [comment]
Can this be considered closed by the addition of `currencies.js` in #720?

If not, we may want to have a look at [currency.js](https://currency.js.org), which claims to work with i18n, and also avoid floating point errors (by handling all amounts internally as integers).

**Comment by sandrina-p** [comment]
Yes, I believe it can be closed, `currency.js` does well that job!
