### ISSUE TITLE
Clean install fails with Node 9.*

### ISSUE THREAD

**Issue by hubudibu** [okTurtles/group-income#348]
### Problem

When npm installing the project on a machine running node 9+, the install fails with the following sqlite error message:

```
node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.8/node-v59-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.8 and node@9.4.0 (node-v59 ABI) (falling back to source compile with node-gyp) 
```

### Solution

This seems to be a problem with sqlite according to https://github.com/mapbox/node-sqlite3/issues/902
Until that gets fixed, it would make sense to indicate what version of node we are supporting, either in the README install instructions, or in package.json as an `engines` field

**Comment by taoeffect** [comment]
No longer using sqlite (#431).
