### ISSUE TITLE
Keep track of all errors and warnings in a special database + dashboard

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#353]
### Problem

Once GI is released into the wild, we will want to know what sorts of errors users are encountering while using it in practice. However, we do not want to collect this info unless it is voluntarily disclosed to us, *and* we want to be able to always ask users to share their stats with us voluntarily.

### Solution

Create a special local dashboard .vue where the client software visualizes stats about all the errors and error types (and their frequency over time) that the software has encountered.

It should be able to:

- Show which kinds of errors happen most frequently
- Show users a raw error log
- Allow users to clear the error log + stats
- Show errors over a timeline that includes demarkation points showing version upgrades

**NOTE:** This implies we should create another issue to store all errors in an error log/database.

NOTE: this issue is about the same as #595...

**Comment by dotmacro** [comment]
Note: This issue is related to #595

**Comment by mmbotelho** [comment]
Should we close this one since #595 was closed as well?

**Comment by taoeffect** [comment]
Yeah why not. :)
