### ISSUE TITLE
Uniform way of targeting elements during tests.

### ISSUE THREAD

**Issue by sandrina-p** [okTurtles/group-income#362]
### Problem

Following my comment on this PR #355 
```diff
-   .wait(() => document.querySelectorAll('.member').length > 0)
+   .wait(() => document.querySelectorAll('.invitee').length > 0)
```
> May I ask if we have any "strategy" to target elements used by integration tests?
>
> By only seeing this PR, I can see we are using any kind of way to target an element (id, class, attr, etc..) without consistency. That might cause some confusion during code development. For instance, when I use classes, I expect to use them as a way to style the layout, not to be used as a test target. 

### Solution

> My suggestion here, would be to find a way to improve this lack of consistency. Example: Add an attr`data-test` to elements used to run tests. I see some advantages with that:
> - During developing an element with that attribute is easily "marked" as an element used for tests.
> - Any other element's property (class, id, attr) can be changed without worrying too much about breaking the test but at the same time keeping in mind that element is used for tests.
> - These kind of changes (like this PR) can be avoid. 

And @taoeffect answer

> Yes, that sounds like a great plan! 👍  Feel free to do that, and along the way check with @hubudibu about cleaning up and removing an no-longer-used IDs or classes.

---

So, @hubudibu what do you think about it and where do you believe it's a good starting point? Also defining a naming convention is important as well. I don't have preferences, but personally i like camelCase 🙊

**Comment by hubudibu** [comment]
👍 for the data-test attribute, 👍 for camelCase-ing everything that ends up in JavaScript (eg tests)!
I would suggest 

1. adding this to our styleguide and
2. using the same refactor-as-you-go strategy as what we have for eg. vue data attributes: all new code should follow this, all code we touch should be refactored to follow this

or, if you or anyone feels like refactoring all our tests in one sitting, go for it! :) in that case, I would suggest starting with the CreateGroup part, at this point that's the most recent part of the codebase, probably a good starting point to get to know your way around.

I'm happy to do my part for the invite tests for anything related to Invite.vue

**Comment by sandrina-p** [comment]
I don't mind doing that all in one, I believe is a great task to get to know the codebase. We can decide that better on next Monday call. What do you think @taoeffect ?

**Comment by taoeffect** [comment]
@sandrina-p That sounds like a great plan forward 👍
