### ISSUE TITLE
Replace raw orphaned CSS colors in JS with CSS theme-dervived values

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#373]
### Problem

There are [many places](https://github.com/okTurtles/group-income-simple/pull/355/files#diff-5d34c560bbb96377fe42f7f43bdee938L59) in the JS where raw color values are specified, e.g.:

```js
if (percentage < 1) return '#F6A623'
return '#9CD445'
```

(sidenote: that can also be cleaned up/rewritten as: `return percentage < 1 ? 'color-1' : 'color-2'`)

### Solution

Go through all of the JS/vue files and search for `'#` and `"#`, i.e. all raw values, and replace them with CSS-derived values, so that it's also easy to change the theme, and so that such values are specified in one location only: as variables in the appropriate theme files.

/cc @sandrina-p @hubudibu (feel free to self-assign this, although I'm guessing this might be more up @sandrina-p's alley)

**Comment by sandrina-p** [comment]
I completely agree and I've realised that while doing #371, so I'll take that in consideration during the next developments.

**Comment by taoeffect** [comment]
@sandrina-p @hubudibu - I think that the correct answer here is to just use proper CSS classes. Adding/removing classes is pretty trivial, and having the colors be specified by the classes makes theming simple.

So just look for all instances in the project where there are raw values and replace with CSS classes? Does that work?

**Comment by sandrina-p** [comment]
I agree. After finishing the MR #370 I'll open another MR fixing this.

**Comment by mmbotelho** [comment]
@sandrina-p is this issue still relevant?

**Comment by sandrina-p** [comment]
Nop, it was fixed with the new theming approach /bulma replacement. I'll close it
