### ISSUE TITLE
Update Bulma@0.4.2 -> 0.7.0

### ISSUE THREAD

**Issue by sandrina-p** [okTurtles/group-income#377]
### Problem
The [Bulma](https://bulma.io/) version installed `0.4.2` is outdated. Parts of Documentation don't match the current version, where some features of the framework are missing.

### Solution
Update to the new version `0.7.0`.

**Comment by sandrina-p** [comment]
I've [started working on the update](https://github.com/sandrina-p/group-income-simple/tree/chore/377-update-bulma-0.4.2-to-0.7.0) and one of major Bulma changes is the `.title` component.
Now, by default, all titles have `font-weight` of `600` and before they were `300`

Should we overrides `.title` to be lighter again, or should we keep it as it is for now until we define GIS typography / color palette? @taoeffect @hubudibu 

#### Bulma 0.4.2 vs 0.7.0
![image](https://user-images.githubusercontent.com/14869087/38778397-0bf14460-40b1-11e8-8371-216178bc5c3d.png)
(P.S. Ignore the 3dot icon on right side of each input, that's an extension I use)

**Comment by taoeffect** [comment]
@sandrina-p I probably won't be able to to tell until I run it locally on my machine.

In that panel at least, it doesn't seem to make much of a difference, but if the font weight is changed in a bunch of other places I might feel differently.

I'll trust you for now to just decide what looks better to you, but also don't worry about it too much for now if doing so will hold us up.

**Comment by sandrina-p** [comment]
Okay, It changes all the titles, so it includes each title on dashboard (members, support history, etc...). But as you said I don't worry about it for now. It was just to clarify/communicate that point.
