### ISSUE TITLE
Update CONTRIBUTING.md with "cleanup-as-you-go"

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#383]
### Problem

Our current contributor guidelines emphasize submitting PRs that are minimal answers to a specific issue, but this `SHOULD`-based suggestion can result in contributors thinking that they shouldn't fix little issues that they notice, whereas that's a practice we want to encourage, see discussion here: https://github.com/okTurtles/group-income-simple/pull/382#discussion_r183218040

### Solution

Update the docs to encourage cleaning up code and improving the quality of code overall as developers submit PRs if the PR they're submitting touches relevant areas, and come up with a name for this process... @hubudibu had a good one if I recall correctly.

Again, see [discussion here](https://github.com/okTurtles/group-income-simple/pull/382/files#r183217724), of which I've included a screenshot for convenience:

![screen shot 2018-04-22 at 12 30 55 am](https://user-images.githubusercontent.com/138706/39091585-8174c8a2-45c4-11e8-82ba-f278db45f0cb.jpg)

**Comment by hubudibu** [comment]
👍  it's called the boy scout rule: https://hackernoon.com/object-oriented-tricks-5-boy-scout-rule-cec82aea3b81 the rule to "leave the ~campground~ code cleaner than you found it"

**Comment by sandrina-p** [comment]
@hubudibu can you open a PR with that update?

**Comment by hubudibu** [comment]
@sandrina-p yes that's the plan! I assigned myself now to make that intention clear :)
