### ISSUE TITLE
Hook up the new dashboard to the vuex store

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#386]
### Problem

While testing PR #382 (update bulma to 0.7), there's the obvious issue that the latest and greatest dashboard design is only partially connected to the vuex store.

### Solution

Connecting everything in the Dashboard to the vuex store is a long-term issue, and we have an existing issue to update the design (#347), which #382 addresses, but we need an issue to actually bring it to life, so I'm creating this and assigning to @hubudibu.

Here's a list of things that need to be done (incomplete list):

- [x] hide the proposal box when there are no proposals
- [x] make the proposal box display the actual proposal
- [x] make the proposal box buttons cast actual votes
- [x] hide the proposal box when the logged in user already voted
- [x] make the group members list reflect the actual members in the group
- [x] make the group members list show actual contribution
- [x] make the current contribution monthly overview real
- [ ] make the contribution/support history real
- [x] make all of the "Propose change" links bring up a modal to make the proposal (without leaving the dashboard in other words) -- **this includes the + button to invite a new member!**

Notice a lot of the above items likely require creating child issues of their own in order to close them with individual PRs. Feel free to create those issues @hubudibu as you go and as you feel is necessary, just be sure to back-reference this issue in them when you do so we can keep track of everything here.

**Comment by taoeffect** [comment]
cc @sandrina-p this is an important issue for you and @hubudibu to collaborate on, as some things (like the + button to "propose to invite new member" view) need to be moved into modal displays while keeping the dashboard front and center.

**Comment by sandrina-p** [comment]
I think all of this is a great issue to be transformed to a Github Project [Connect Dashboard to Store](https://github.com/okTurtles/group-income-simple/projects/4) so we can have a better picture of the progress. @hubudibu feel free to complete it with the needed child issues / notes that suits you the best 🙂

**Comment by mmbotelho** [comment]
@taoeffect do you know what the status is on this issue? We have the project [Connect Dashboard to Store](https://github.com/okTurtles/group-income-simple/projects/4) waiting on this task.

Is this issue outdated or is it still valid?

**Comment by taoeffect** [comment]
@mmbotelho This issue is still real. The Dashboard is unfinished, hardly anything on it works.

**Comment by pieer** [comment]
I think this can be close now, what do you reckon @taoeffect ?

**Comment by sandrina-p** [comment]
No @pieer, is still missing the #815

**Comment by taoeffect** [comment]
I guess there's no harm in clearing up the clutter in our open issues. Since the only issue remaining to close this is #815, this is effectively a duplicate issue, so I'm going to close it in favor of #815.
