### ISSUE TITLE
Improve Voting Rules UX

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#409]
### Problem

![screen shot 2018-05-19 at 6 04 31 pm](https://user-images.githubusercontent.com/138706/40273512-1e1fc118-5b8f-11e8-842e-11f2db33764d.jpg)

1. The circle/handle/nob is too small
2. The nob doesn't visually indicate it's selected when clicked / dragged
3. The nob is not adjustable via the keyboard tab-selection
4. **(BUG)** The settings allow 1% to be selected, potentially letting anyone change any setting. This is confusing and probably wrong in all cases.

### Solution

1. Make the circle/handle/nob bigger, along with the circle line width itself
2. The nob needs to "depress" itself (perhaps by making itself a darker shade) to indicate it's selected
3. When `<tab>` is pressed, the knob should be highlightable so that the visually impaired can use screen readers to select it and adjust it (via the up/down arrows)
4. We should probably not allow the percentage to go below a certain amount, or we should say + show in the UI that a minimum of 2 votes is required no matter the threshold amount

Please note, **(1), (2), and (3)** all require forking the widget, which is good, because we need to remove all dependencies (#372).

**Comment by mmbotelho** [comment]
Hey! As mentioned in the issue #343 I've made a few changes to this component. I followed @taoeffect 's solution proposal and also added some ideas of my own:

![screen shot 2018-11-19 at 13 15 59](https://user-images.githubusercontent.com/22004566/48707842-0357ac80-ec01-11e8-8121-e7f185021912.png)

- The handler is now bigger, and added a "drag" icon to it;
- Added an actual number input to the center of the circle. The focus / active states are no longer a problem, and the user can input a fixed amount directly, if they prefer to do so;
- Made it start from the top center, like a clock.
- Added a reset link, that should only be visible after the user changed the value, in case they want to return to the recommended percentage.

I am not sure if this will take a lot of effort to implement, but I believe it will significantly help the usability. I would love to hear @sandrina-p and Simon's input!

**Comment by dotmacro** [comment]
I really like the accessibility-friendly warning icon 👍 
(Likewise with the other mockups in #343)

I also really like the warning text. 
Because users will still be able to propose simple majority (and even minority) voting thresholds, I think we should keep the "at least x members need to agree" text. We could word it as "only x members need to agree", so it still reads as a warning.

> Added a reset link, that should only be visible after the user changed the value, in case they want to return to the recommended percentage.

Will it return to the recommended percentage (80% in the current mockups) or the group's current percentage?

**Comment by mmbotelho** [comment]
@dotmacro 

> I really like the accessibility-friendly warning icon 👍

Awesome! I will create an issue for it, so we can update the component across the platform.

> Because users will still be able to propose simple majority (and even minority) voting thresholds, I think we should keep the "at least x members need to agree" text. We could word it as "only x members need to agree", so it still reads as a warning.

Agreed! What about something like this:

<img width="1440" alt="change voting rules - no warning" src="https://user-images.githubusercontent.com/22004566/48840545-45aef400-ed8f-11e8-801a-b40437ad5fdf.png">

<img width="1440" alt="change voting rules - with warning" src="https://user-images.githubusercontent.com/22004566/48840553-4b0c3e80-ed8f-11e8-9a85-a3f2e8f11441.png">

The idea is to de-escalate or escalate the warning according to what the user has selected. 


_____
>Will it return to the recommended percentage (80% in the current mockups) or the group's current percentage?

If you are proposing a change, it should return to the previously agreed value. When creating the group, I would say that it should go back to the 80% (which seems to be the default in group creation).

_____

I also made a mockup for the onboarding, so there are no doubts about how the component behaves there as well:

<img width="1440" alt="onboarding - voting rules" src="https://user-images.githubusercontent.com/22004566/48840707-c241d280-ed8f-11e8-8651-7d81e781f891.png">

Notice that here I didn't leave the "Only X out of X members will have to approve" for 2 reasons:

- There's 3 voting rules displayed at the same time;
- The group only has 1 person at the moment (the user creating it).

What do you think?

**Comment by mmbotelho** [comment]
Updated the component, as discussed in the issue #343 .

![screen shot 2018-11-23 at 16 42 30](https://user-images.githubusercontent.com/22004566/48951418-ca8c4000-ef3e-11e8-9cbe-8c51f1667619.png)


The input now only accepts numbers and the percentage sign (%) is only a label. [Screens updated on Figma](https://www.figma.com/file/ZR0DRPhhUuHdJtf7PbGAM6tW/Group-Income?node-id=33%3A122)

**Comment by dotmacro** [comment]
> Agreed! What about something like this: 
> The idea is to de-escalate or escalate the warning according to what the user has selected.

Yes, looks good. We could also prepend "If this proposal is accepted, then...", but I think that might add too much text.

> > Will it return to the recommended percentage (80% in the current mockups) or the group's current percentage?
> 
> If you are proposing a change, it should return to the previously agreed value. When creating the group, I would say that it should go back to the 80% (which seems to be the default in group creation).

👍

> I also made a mockup for the onboarding, so there are no doubts about how the component behaves there as well:

One issue I see is that the warning seems to rely on color to convey which voting rule is being warned about. If the user only changes one rule, they can infer that's what the warning is about. They may also infer that the "too low" warning is about the lowest %. Or alternatively, they may think "significant impact on a person's life" doesn't refer to that rule, and end up confused about which of the other two it references. So, I think it's best to be explicit so there's no confusion or doubt. In addition to color, how can we tie the rule to the warning here?

Also, if there multiple rules below the warning threshold, do we show a custom warning for each, multiple identical warnings, or one warning that persists until and unless both thresholds are raised above the warning threshold?

> Notice that here I didn't leave the "Only X out of X members will have to approve" for 2 reasons:
> 
>     * There's 3 voting rules displayed at the same time;
> 
>     * The group only has 1 person at the moment (the user creating it).
> 
> 
> What do you think?

It makes sense to exclude it in this case. If the group creation process is changed to allow/require multiple members during group creation, we can add it then.

**Comment by mmbotelho** [comment]
> One issue I see is that the warning seems to rely on color to convey which voting rule is being warned about. If the user only changes one rule, they can infer that's what the warning is about. They may also infer that the "too low" warning is about the lowest %. Or alternatively, they may think "significant impact on a person's life" doesn't refer to that rule, and end up confused about which of the other two it references. So, I think it's best to be explicit so there's no confusion or doubt. In addition to color, how can we tie the rule to the warning here?

Good point @dotmacro ! I designed 2 possible solutions for this:

1. Adding a warning to the circle itself, so that the user connects the 2 components together (warning and the threshold they're being warned about);

![option 1](https://user-images.githubusercontent.com/22004566/49024027-d1ae8a80-f198-11e8-97ce-c9f006652bc9.png)


2. Adding the name of the "circle" to the warning itself

![option 3](https://user-images.githubusercontent.com/22004566/49023278-2ea94100-f197-11e8-9611-299902d283df.png)

You can [see this in more detail on Figma](https://www.figma.com/file/ZR0DRPhhUuHdJtf7PbGAM6tW/Group-Income?node-id=33%3A122)

> Also, if there multiple rules below the warning threshold, do we show a custom warning for each, multiple identical warnings, or one warning that persists until and unless both thresholds are raised above the warning threshold?

I would say one warning that persists until and unless both thresholds are raised above the warning threshold, for simplicity's sake and to avoid having very similar messages repeated.

**Comment by dotmacro** [comment]
> I designed 2 possible solutions for this:
> 
>     1. Adding a warning to the circle itself, so that the user connects the 2 components together (warning and the threshold they're being warned about);
>     1. Adding the name of the "circle" to the warning itself

Both good solutions. I think the second (adding rule name to warning message) looks cleaner because the circles seem more balanced. 

> I would say one warning that persists until and unless both thresholds are raised above the warning threshold, for simplicity's sake and to avoid having very similar messages repeated.

👍
Design # 2 above also seems to work well when multiple rules have the same warning because the warning message will clearly state which rules it's referring to.

**Comment by mmbotelho** [comment]
Awesome! [Updated on Figma](https://www.figma.com/file/ZR0DRPhhUuHdJtf7PbGAM6tW/Group-Income?node-id=33%3A122)

**Comment by taoeffect** [comment]
@mmbotelho looks fantastic! 🥇 👍

**Comment by sandrina-p** [comment]
@mmbotelho I noticed you designed the proposal itself (see [Design Specs on Figma](https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?node-id=1%3A531)), but the UI to trigger this modal is missing (or I didn't find it again).

**Comment by mmbotelho** [comment]
Yes you are right @sandrina-p. It's on my to-dos. I believe it will be added to the Group Settings page.

**Comment by mmbotelho** [comment]
I believe this issue is outdated now. What do you think @taoeffect ? Can we close it?

**Comment by taoeffect** [comment]
Sure 👍
