### ISSUE TITLE
[vuex] unknown mutation type: deleteMail

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#410]
### Problem

While testing #407, I encountered this bug when declining an invite:

![screen shot 2018-05-19 at 6 14 32 pm](https://user-images.githubusercontent.com/138706/40273584-a6254348-5b90-11e8-91d3-18f420e9d535.jpg)

```
[Error] [vuex] unknown mutation type: deleteMail
	commit (app.js:90398)
	_callee3$ (app.js:8489)
	tryCatch (app.js:13943)
	invoke (app.js:14177)
	step (app.js:13677)
	(anonymous function) (app.js:13688)
	promiseReactionJob
```

The bug is somewhere near `Join.vue:149`.

From that point on, even though the invite remained in the inbox, clicking it would result in further errors and would cause the page to briefly flicker and return to the inbox, along with these log messages:

![screen shot 2018-05-19 at 6 17 46 pm](https://user-images.githubusercontent.com/138706/40273602-09e28e86-5b91-11e8-9077-aca5b3de80a5.jpg)

### Solution

Fix.

**Comment by sandrina-p** [comment]
Closing because the logic for joining a group changed at #747, so this issue is stale now.
