### ISSUE TITLE
Upon accepting an invite, redirect to dashboard

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#411]
### Problem

Currently, accepting the invite redirects us back to the inbox.

### Solution

Either:

- Redirect to the dashboard with a widget that bugs the user to fill out their group profile
- Redirect directly to a view where they're asked to fill out their group profile (and then redirect to the dashboard)

**Comment by sandrina-p** [comment]
IMO redirect to the dashboard is the best option because it's the main purpose of "joining a group". Showing a tip to inform the user (the expression "bugs the user" is a little unfriendly) to fill out their group profile is a good engagement

**Comment by mmbotelho** [comment]
I believe this issue no longer makes sense since the Inbox itself has been deprecated, but I might be missing something. What do you think @taoeffect ?

**Comment by taoeffect** [comment]
I think you're right @mmbotelho, good catch!
