### ISSUE TITLE
User who proposes a vote to invite a member shouldn't be asked to vote

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#412]
### Problem

![screen shot 2018-05-19 at 6 29 55 pm](https://user-images.githubusercontent.com/138706/40273665-af28ad84-5b92-11e8-9826-d34f0281f8c2.jpg)

As shown above, if bob proposes to invite someone, he shouldn't be asked to vote on his proposal again.

### Solution

Just show an "ongoing proposal" widget as @sandrina-p mocked up that lets them withdraw their vote.

**Comment by sandrina-p** [comment]
Yes, like this one I've originally shared at #343 
![image](https://user-images.githubusercontent.com/14869087/39841809-f568a484-53db-11e8-8bcd-4f2ae96e6f43.png)
