### ISSUE TITLE
Put the word "Constitution" somewhere into the Group Creation process

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#413]
### Problem

Conceptually it's not clear what the "Group Settings" represent. It may be difficult for users to think about them and relate to them.

Internally we have used the concept of "Constitution" to discuss this part of the app, and it has helped us in our design, but despite its usefulness, this word appears nowhere in the actual UI.

### Solution

Make it clear via the UI that users are creating a Constitution when they set the group settings, and do that by including that word prominently in the UI.

**Comment by sandrina-p** [comment]
For me, _"Constitution"_ is a too formal word 🤔

**Comment by taoeffect** [comment]
Perhaps this is a localization concern? Maybe in Portuguese some other word fits better?

**Comment by sandrina-p** [comment]
Yes probably you're right. If for English that's a good word I'm totally fine with it :)

**Comment by taoeffect** [comment]
I've changed my mind and agree with you @sandrina-p, this issue isn't worth keeping open, "Constitution" may indeed be too formal.
