### ISSUE TITLE
Replace string-template dependency with a utility function + integrate with i18n

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#417]
### Problem

This issue is a subset of getting rid of / adopting dependencies (#372).

Most languages have a `printf` like function built-in, but [JavaScript doesn't](https://stackoverflow.com/questions/610406/javascript-equivalent-to-printf-string-format).

We need this functionality, especially for i18n localization stuff. For example, in @sandrina-p's recent PR #415, there's [a discussion](https://github.com/okTurtles/group-income-simple/pull/415/files#r191607332) about how to pass in localized props, e.g.:

```vue
<h3 class="title"><i18n>{{title}}</i18n></h3>
```

And:

```vue
<dashboard-section :title="L('Support History')">
```

And in [this file](https://github.com/sandrina-p/group-income-simple/blob/c383c7eeaba8b93f5cc253e7219d1396509f6639/frontend/simple/components/Proposals/Voting.vue#L32-L37):

```vue
      <!-- TODO: fix the i18n stuff here -->
      <div class="gi-voting-info">
        <h5 class="has-text-weight-bold is-uppercase gi-voting-info-title">{{proposal.title}}</h5>
        <p><strong>{{proposal.initiator}}</strong> <i18n>had proposed to</i18n> {{proposal.text}}</p>
      </div>
    </div>
```

There especially, in the line that says `<p><strong>{{proposal.initiator}}</strong> <i18n>had proposed to</i18n> {{proposal.text}}</p>`, it's clearly visible the need for a `string-template` like function that works with `<i18n>` tags and the `L` function.

### Solution

1. Implement [our own simple printf/format-like function](https://stackoverflow.com/questions/610406/javascript-equivalent-to-printf-string-format) and remove the `string-template` dependency. `%s` type flags might be better because localizers won't get confused by whether or not to translate `{some-string}`
2. Add support for this to `L` function and `<i18n>` component, and make it work with props passing
3. Update all relevant .vue files and remove associated TODOs

---

issue search tags: localization internationalization translation

**Comment by taoeffect** [comment]
Note: it's unclear how to handle `<p><strong>{{proposal.initiator}}</strong> <i18n>had proposed to</i18n> {{proposal.text}}</p>` with the i18n component.

E.g. what we really want is for something to take as input either:

```
<p><strong>%s</strong> had proposed to %s</p>
```

Or:

```
<p><strong>{proposal-initiator}</strong> had proposed to {proposal-text}</p>
```

I'm leaning towards the latter, however either way it's not clear how the values are passed in via a `<i18n>` component.

One potential way is:

```vue
<p><i18n :data="i18nMap"><strong>{proposal-initiator}</strong> had proposed to {proposal-text}</i18n></p>
```

And the other option is to simply avoid using a component altogether:

```vue
<p>{{ L('<strong>{proposal-initiator}</strong> had proposed to {proposal-text}', i18nMap) }}</p>
```

The advantage of having an `i18n` component is that markup text can be written like normal HTML instead of having to switch to weird Vue template JS syntax and suddenly having to deal with functions.

**Comment by sandrina-p** [comment]
I like this way

```vue
<p><i18n :data="i18nMap"><strong>{proposal-initiator}</strong> had proposed to {proposal-text}</i18n></p>
```

but how does i18nMap knows what's `{proposal-initiator}` and `{proposal-text}` ?

**Comment by vijayee** [comment]
so they syntax is  going to be 
```
<p><i18n :args="i18nMap"><strong>{proposal-initiator}</strong> had proposed to {proposal-text}</i18n></p>
``` 
because `data` is a property on vue component life cycle and could get confusing and `arguments` was a javascript reserved word.
