### ISSUE TITLE
Move off of GitHub

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#420]
### Problem

Microsoft [bought GitHub and the CEO has left the building in their incapable hands](https://blog.github.com/2018-06-04-github-microsoft/).

Edit: GitHub security likely [to continue degrading](https://nakedsecurity.sophos.com/2018/06/29/linux-distro-hacked-on-github-all-code-considered-compromised/).

Edit2: we want a solution that is portable to local environments without Internet access, ideally all issues would be in git version control itself.

Edit3: [Github acting like Stasi](https://medium.com/@catamphetamine/how-github-blocked-me-and-all-my-libraries-c32c61f061d3).

Edit4: NPM is now [joining Microsoft](https://github.blog/2020-03-16-npm-is-joining-github/).

### Solution

1. Import all existing issues into our Gitlab instance
2. Consider keeping this GH in sync with our Gitlab using [one of these tools](https://mastodon.tetaneutral.net/@roipoussiere/100145969860290815), or better yet just point people to our Gitlab.
3. Move off of Node/NPM and onto Deno (#586).

**Comment by sandrina-p** [comment]
I was reviewing all our current issues and see what has really high priority in order for us to finish the Prototype. This didn't seem to be a high priority based on that.

Feel free to add it again if you think it's really a priority to do it in the next couple of months

**Comment by taoeffect** [comment]
@sandrina-p Good point 👍

**Comment by taoeffect** [comment]
Not needed for now. We have a backup on Gitlab if necessary.
