### ISSUE TITLE
Proposals System: create page with past proposals

### ISSUE THREAD

**Issue by sandrina-p** [okTurtles/group-income#423]
### Problem
As discussed on #415 and Slack, we need to figure out where to display past proposals that no longer require any action from the user. These proposals can either have the following states:
- won (approved)
- lost (disapproved)
- cancelled (the owner closed the proposal before reaching the needed votes)

### Solution
- Design and Implement the UI/UX of the Past Proposals Page
- Decide how the user can access this page.
- Add search/filter/sort feature to look for proposals on that same page.
- Make a vue that retrieves the past proposals from the localstorage database as Type 2 persistent data (see also #426) (@hubudibu)

**Comment by mmbotelho** [comment]
[Solved on the new Dashboard ](https://www.figma.com/file/ZR0DRPhhUuHdJtf7PbGAM6tW/Group-Income?node-id=1988%3A1261)
