### ISSUE TITLE
Personalization: Font-size 

### ISSUE THREAD

**Issue by sandrina-p** [okTurtles/group-income#424]
### Problem

Currently GIS default font-size is `16px`/`1rem` and each one of us have different opinions on what font-size we should have.

### Solution

It's being a common feature to have a "Customize zone", so the user can choose the look and fell of the App she/he is using. Choosing the font size can be one of the features.

**Comment by mmbotelho** [comment]
@sandrina-p I think this is a great idea, both for users that have low vision, and for users that prefer a more compact view. 

However, after doing some research on the topic, there's also the concern that changing the font-size should be done at the browser level, and not at a webpage level. This makes sense, except that finding this setting in the browser requires some digging around and users that DO have low vision often end up using zoom to fix this (which is way more intuitive, but also means that the layout might break in unpredictable ways).

There's also the argument that you might need to increase/decrease on a page by page basis, depending on things like the font used, colors etc...

So... what I think we could do is leave the default at `16px / 1rem` and let the user lower it to `14px / 1rem` or increase it to `18px / 1rem`. We can also include a message, educating the user how to do it on their browser directly, in case they need it on all webpages.

@taoeffect what do you think?

**Comment by taoeffect** [comment]
@mmbotelho Well, it's unclear still what the answer to that question is, because in part it's unclear whether or not there will be a Group Income app. There might be a need for one, in which case we would definitely need to be able to adjust the font size in the settings too. I also see no reason why there can't be both approaches, what's the harm in having a setting?

**Comment by mmbotelho** [comment]
@taoeffect I don't see any harm in having a setting too, let's do it!

**Comment by mmbotelho** [comment]
Issue solved on the [new user settings page](https://www.figma.com/file/ZR0DRPhhUuHdJtf7PbGAM6tW/Group-Income?node-id=458%3A483) - closing it!
