### ISSUE TITLE
Save closed proposals as historical data (Type 2 persistent data)

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#426]
### Problem

PR #425 currently deletes closed proposals in `HashableGroupCloseProposal`. This is a problem because it means we have no way to show historical proposals in the historical proposals vue (something that also needs an issue created for it).

### Solution

Instead of deleting proposals, ensure they are stored in an easy-to-retrieve-and-search way from the localstorage database.

Copying [my comment](https://github.com/okTurtles/group-income-simple/pull/425/files#r194895432) from the PR review:

> Yes, let me summarize the sorts of data that we have that I've documented so far:
> 
> 1. Ephemeral data - data that appears in the `data ()` of a vue component but doesn't (necessarily) get saved to the store or the database
> 2. Persistent data - data that appears in the database and the store
> 
> We should now discuss two types of persistent data:
> 
> 1. Type 1: Persistent data that is "in-memory" and synced between the vuex `$store` and the database
> 2. Type 2: Persistent data that is retrieved on-demand from the database. If it ever appears in the vuex `$store`, it is only temporarily, and likely only partially.
> 
> **The history of proposals is Type 2 persistent data.**
> 
> In other words, there is no need to keep it in RAM all of the time. The only time we need it is to display the historical proposals, and even then, only show about 20 results at a time.
> 
> Another example of Type 2 data that we already have is the history of the entire contract chain for all of the contracts.

**Comment by hubudibu** [comment]
we will also have to get back to how a proposal behaves after being deleted/reaching the threshold on the group dashboard as captured here: https://github.com/okTurtles/group-income-simple/pull/425#issuecomment-397892662 do we need another issue for that or can that count as part of this issue?

**Comment by taoeffect** [comment]
@hubudibu I think that should be a separate issue.

For this issue I've also assigned myself (and you), and I'm thinking about renaming it to make it more focused on updating `model/database.js` to have an API to handle this. I'll work on creating that API, and then once it's ready you can use it to do all these things. Perhaps it's worth creating a separate issue just for the database API for this... but if I manage to do that with my shared/events rewrite PR then it might not be necessary.

**Comment by taoeffect** [comment]
Closed somewhere
