### ISSUE TITLE
Past Proposals vue

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#427]
### Problem

We need to be able to show and easily search the results of all past proposals.

### Solution

- Create a link in the dashboard to show Past Proposals
- Design the UI/UX of the Past Proposals vue (@sandrina-p)
- Make a vue that retrieves the past proposals from the localstorage database as [Type 2 persistent data](https://github.com/okTurtles/group-income-simple/pull/425/files#r194895432) (see also #426) (@hubudibu)

**Comment by hubudibu** [comment]
possible duplicate of #423 ?

**Comment by taoeffect** [comment]
Oops, yep!
