### ISSUE TITLE
Add flow-typed

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#429]
### Problem

Currently, not only does flow now type check third-party dependencies/modules, but we have to manually add and ignore them via `shared/declarations.js`.

It turns out there's a much nicer solution...

### Solution

https://github.com/flowtype/flow-typed/blob/master/README.md

**Comment by snowteamer** [comment]
Unfortunately, flow-typed is missing a lot of libdefs for our current dependencies.

Out of the 83 dependencies found in our package.json, running `flow-typed update` shows that it only covers the following ones:
- chalk
- register
- node-fetch
- localforage
- mocha
- sinon

So for all the other deps it would only generate stubs. This would still be an improvement, but less useful than fully typed module definitions.

**Comment by taoeffect** [comment]
Not needed (considering switching to TypeScript instead)
