### ISSUE TITLE
Figure out why goto(page('mailbox')) broke

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#440]
### Problem

From: https://github.com/okTurtles/group-income-simple/pull/431#issuecomment-410035971

@hubudibu wrote:

> test fix 1 in test/frontend.js line 429:
> 
> ```js
>       await n
>         // .goto(page('mailbox'))
>         // TODO: navigation gets redirected on login guard but nav click doesn't?
>         // we might have logged in state problems
>         .wait(elT('mailboxLink'))
>         .click(elT('mailboxLink'))
> ```

### Solution

We need to figure out why `.goto(page('mailbox'))` is not longer working in #431.

**Comment by sandrina-p** [comment]
Stale issue. We use Cypress #625 now and all tests are working fine! Closing issue
