### ISSUE TITLE
Dashboard GroupMembers.vue doesn't update to show new member

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#459]
### Problem

Some recent PR broke the list of group members display somehow. Now when a member accepts an invite, the member list isn't automatically updated to show the new member. You have to refresh the page to show them. Use Firefox container tabs or multiple browsers to reproduce.

### Solution

1. Restore the lost reactivity to the vuex datastore so that a page refresh isn't needed
2. Update frontend tests to test this case so that it doesn't happen again. This will require creating two nightmare instances instead of having just one, or using some "private tab" feature in nightmare (if such a feature exists).

**Comment by sandrina-p** [comment]
I tried to replicate this bug and it doesn't happen anymore. When the group has new members, the group list is updated correctly. I'll close it.
