### ISSUE TITLE
Improve our README

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#484]
### Problem

Our README is nice, but it can certainly be improved to be even nicer, especially when the bar keeps being raised by other projects.

### Solution

Take some inspiration from [these projects](https://github.com/matiassingers/awesome-readme), ([random example](https://github.com/gitpoint/git-point)). One of the things that's missing from ours that I think we should work on adding is [open collective](https://opencollective.com/) integration.

**Comment by dotmacro** [comment]
Some Open Collective info:  
- the [Open Collective Foundation](https://opencollective.com/foundation) charges a 5% fee
- they only support donations via credit card
- any donations via other platforms/methods (e.g. via the website, BTC, check, cash) would need to be manually added
- it looks like they only support PayPal payouts (another 2.9% + $.30 fee), but donations via other methods can be paid manually and manually added to the log on Open Collective
