### ISSUE TITLE
Chat page: add a loading/skeleton screen

### ISSUE THREAD

**Issue by sandrina-p** [okTurtles/group-income#496]
### Problem

Loading a Chat page (created at #493) can take some time. While the data is loading the user will see a empty white screen. 

### Solution

Design a Loading screen (or even a Skeleton Loading) while a conversation is being loaded. This can be better done only after knowing exactly what data the server will load from each conversation.

A reference to  [know more about skeleton screens](https://uxdesign.cc/what-you-should-know-about-skeleton-screens-a820c45a571a)

**Comment by mmbotelho** [comment]
I am closing this issue because this should be solved on #562
