### ISSUE TITLE
Chat page: mobile enhancements

### ISSUE THREAD

**Issue by sandrina-p** [okTurtles/group-income#499]
### Problem 1

At the moment (#493) any button with a list of options is opened in a menu for all screens.

![image](https://user-images.githubusercontent.com/14869087/48511918-ff6a0a00-e84f-11e8-8de4-b7c6aa450306.png)

### Solution 1

This works fine on a desktop, but on small screens the clickable area can be too far away (in a top corner) and each option has a small clickable area. In small screens is a pattern to have options listen in a bottom drawer.

![image](https://user-images.githubusercontent.com/14869087/48512106-90d97c00-e850-11e8-98aa-068e08944abc.png)

---

### Problem 2

At the moment (#493) the navigation between conversations list and a conversation view is immediately with a simple show/hide system.

![chat_list-to-conversation](https://user-images.githubusercontent.com/14869087/48512270-004f6b80-e851-11e8-85c2-69ad3e9fb1c3.gif)

### Solution 2

Implement a slide in/out pattern navigation between both screens.

**Comment by taoeffect** [comment]
Think this is done
