### ISSUE TITLE
Chat: Add support to markdown formatted text

### ISSUE THREAD

**Issue by sandrina-p** [okTurtles/group-income#502]
## Problem

Currently we do not support any formatted text (such as links, text weight, etc...) and we can't use `v-html` as a solution:

> Dynamically rendering arbitrary HTML on your website can be very dangerous because it can easily lead to [XSS attacks](https://en.wikipedia.org/wiki/Cross-site_scripting). Only use `v-html` on trusted content and **never** on user-provided content.

## Solution
Discuss the best approach to support formatted text.

Related: https://github.com/okTurtles/group-income-simple/pull/493#discussion_r234470204

**Comment by taoeffect** [comment]
This was done by @SebinSong recently
