### ISSUE TITLE
List invitations to a group on dashboard. 

### ISSUE THREAD

**Issue by simonv3** [okTurtles/group-income#510]
### Problem

On the dashboard who has already been invited to the group isn't visible (actually, I'm not sure this is visible anywhere?). This means that it's not clear to users who has or hasn't been invited directly to a group.

### Solution

There are two steps to solving this problem: figuring out how to elegantly display this in the dashboard, what level of detail needs to be displayed (do we need to list everyone who has been invited, when, or is just listing the number of invitations with a link to a list of all invitees). 

The simplest and most information full solution in my mind is to show a little notification at the top of the *Members* section of the dashboard that provides a list of usernames of the people invited to the group.

The second step is to implement it based on the design. That will become clearer depending on how it's designed.

**Comment by mmbotelho** [comment]
I will close this issue because it has been solved (from a UI/UX perspective) on the new [dashboard mockups](https://www.figma.com/file/ZR0DRPhhUuHdJtf7PbGAM6tW/Group-Income?node-id=1204%3A0).
