### ISSUE TITLE
Improve UX of the user button (navbar) 

### ISSUE THREAD

**Issue by mmbotelho** [okTurtles/group-income#512]
### Problem

![screen shot 2018-12-10 at 16 03 54](https://user-images.githubusercontent.com/22004566/49740895-8bc3ed00-fc95-11e8-84aa-6d2ec3cf310e.png)

The current user menu entry in the main navigation bar has a few problems, namely: 

- The **logout button** is not 100% clear;
- Not having an **active state**, meaning that when the user is on this page, there's no visual indication of this.
- Having to click on the **3 dots button** to actually go to the user profile page, instead of the whole component being a link. (3 dots should used for a menu and not a link)

### Solution

- Design and implement an active state;
- Make the whole component clickable (except the logout button);
- Add a label to the logout button, so it's clearer;

**Comment by sandrina-p** [comment]
Related to the *logout button*, besides not being clear, I believe the main issue is that the button is too close to the *3 dots button* and the user might accidentally click at it instead of the button next to it. Have than in mind when redesigning that part of the UI :)

**Comment by mmbotelho** [comment]
@sandrina-p I was thinking about removing the _3 dots button_ entirely, and leaving the user menu entry clickable instead (exactly the same behaviour as the other entries on the navigation bar), so it stays more consistent. What do you think?

**Comment by sandrina-p** [comment]
I believe that's intuitive enough - users are used to their avatars to be clickable... what do you think @taoeffect ?

**Comment by mmbotelho** [comment]
@pieer I believe this issue is also solved with your pull request #537!

**Comment by pieer** [comment]
Correct

**Comment by mmbotelho** [comment]
@taoeffect can we close this issue? 😄

**Comment by taoeffect** [comment]
@mmbotelho yep! Especially as issue opener, if you consider it addressed that means it's closed!  (Feel free to close it!) 😄

**Comment by mmbotelho** [comment]
Awesome, I will do that from now on 🎉
