### ISSUE TITLE
Tooltip text not visible in the UI

### ISSUE THREAD

**Issue by mmbotelho** [okTurtles/group-income#515]
### Problem

Tooltips have dark text over a dark background, making it impossible to read their content. Happening at least on Chrome and Safari.

<img width="880" alt="tooltip" src="https://user-images.githubusercontent.com/22004566/50842109-5c70d080-1366-11e9-8511-14fe6d11a313.png">

### Solution

After inspecting the code, it seems that changing the `text-color` to white solves the problem. The problem seems straight-forward but some further investigation might be necessary, in order to understand what caused this in the first place.

**Comment by taoeffect** [comment]
Closed by #519
