### ISSUE TITLE
Evaluate testcafe

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#520]
### Problem

Nightmare hasn't been updated in a while, it's unclear whether it's been abandoned or not. However, nightmare was [the best testing framework I could find](https://github.com/okTurtles/group-income-simple/issues/22) at the time.

### Solution

There's an interesting (new) UI testing framework called [testcafe](https://testcafe.devexpress.com) that we should have a look at at some point to see if it suits our needs.

**Comment by sandrina-p** [comment]
`testcafe` is cool. Another one with a lot of growing is `https://www.cypress.io/`. Here's a cool [medium article comparing both](https://medium.com/yld-engineering-blog/evaluating-cypress-and-testcafe-for-end-to-end-testing-fcd0303d2103)

**Comment by sandrina-p** [comment]
Closing this issue, since we decided to migrate to Cypress #625.
