### ISSUE TITLE
Make our animation related stuff consistent

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#529]
### Problem

Currently all our Vue.js transition stuff is:

1. Poorly implemented (broken, see `transitions.js`)
2. Scattered about the project (see `CreateGroup.vue`, `GroupRules.vue` and other files that have animation related CSS)

It is not good to have things disorganized, broken, and scattered about.

### Solution

Put all our animation definitions in a single file, whether that is `transitions.js` (currently not being used / commented out in `main.js`), or a file of pure CSS animations, and reference those definitions from that file only.

**Comment by mmbotelho** [comment]
I believe @pieer already worked on this. Can someone confirm and close this issue if it is already done?

cc @taoeffect

**Comment by taoeffect** [comment]
Hmm, @pieer can you confirm what the status of this issue is?

**Comment by pieer** [comment]
I think this is old now yes
