### ISSUE TITLE
Make sure backend clock is synced with clients

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#531]
### Problem

For handling things like onboarding periods, message send/receive timestamps, etc, we need to make sure everyone's clocks are synchronized to the correct time.

### Solution

Create a server API to get the server's time. Make sure it's the same as the client's. Do not let the group to be created if the client's clock is out of sync with the server's time. The server's time is canonical time that all clients must adhere to. Make sure to account for different timezones.

**Comment by Silver-IT** [comment]
We also should consider that the client's datetime could be changed in the middle of using the platform.
He can set the correct time to create group and login but he also can update his datetime while using it.
