### ISSUE TITLE
Turn the "Income Details" modal into a fullscreen modal

### ISSUE THREAD

**Issue by mmbotelho** [okTurtles/group-income#536]
### Problem
<img width="600" alt="captura de ecra 2019-02-21 as 16 07 07" src="https://user-images.githubusercontent.com/22004566/53178758-c7aef300-35f2-11e9-985c-7fcf0d088a62.png">

- The modal shrinks and grows according to how much content is being displayed - not a stable "canvas" to work on;
- There's a lot of information displayed, with not enough white space around it.

### Solution
Now that we have fullscreen modals, these would be more appropriate to use in this case.

**Comment by mmbotelho** [comment]
I have created a solution for this issue - [You can view it here](https://www.figma.com/file/ZR0DRPhhUuHdJtf7PbGAM6tW/Group-Income?node-id=1922%3A0).

This solution does not change the functionality at all - only the UI has been re-organized slightly, to improve readability and to make it look more consistent with the other pages.

@taoeffect I know we have discussed this solution on a previous video meeting, and I got the impression that you aproved it :) can you please confirm that everything is ok? My memory might be failing me. Thank you in advance!

**Comment by taoeffect** [comment]
> @taoeffect I know we have discussed this solution on a previous video meeting, and I got the impression that you aproved it :) can you please confirm that everything is ok?

@mmbotelho - yep! Your mockups look great to me! If there's some minor issue it didn't jump out at me when I looked, and we can always adjust later. From the looks of it, the new direction you've chosen seems great to me as it is :)

**Comment by mmbotelho** [comment]
Thank you @taoeffect for double checking! :) I will close this issue then, as the UX/UI of it has been completed, and create a new one for development.
