### ISSUE TITLE
Implement improved avatar placeholder image

### ISSUE THREAD

**Issue by mmbotelho** [okTurtles/group-income#538]
### Problem

<img width="76" alt="captura de ecra 2019-02-28 as 17 11 28" src="https://user-images.githubusercontent.com/22004566/53580525-1c66e680-3b7c-11e9-808b-3e659c079b83.png">

The current avatar placeholder does not match the UI of the app. Also, because we only have one placeholder, and if users don't upload their own avatars, the interface can become very dull in places where a lot of avatars are displayed together.

E.g.: Using a chat where all avatars look the same is actually more harmful than not having the avatars there at all.

### Solution

We can create a series of avatars that are attributed randomly to users, making it easier to distinguish users that haven't uploaded their own avatars yet. This is also a great opportunity to use more gender and race neutral images. 

If you want to read more about the fascinating world of avatar placeholders, I recommend [this article](https://uxdesign.cc/design-avatars-that-make-sense-and-be-more-inclusive-in-the-process-d4dd6a486ea6).

**Comment by sandrina-p** [comment]
This would be great, it also helps to create the App's personality/vib!

**Comment by dotmacro** [comment]
Using initials seems like a good (maybe temporary) solution because it allows users to most easily identify each other.

**Comment by dotmacro** [comment]
Important consideration: make sure users with the same display name can be distinguished (#745)

**Comment by mmbotelho** [comment]
After doing some research, and trying out some different approaches to solving this issue, my favorite was definitely [Identicons](https://en.wikipedia.org/wiki/Identicon).

> An Identicon is a visual representation of a hash value, usually of an IP address, that serves to identify a user of a computer system as a form of avatar while protecting the users' privacy. The original Identicon was a 9-block graphic, and the representation has been extended to other graphic forms by third parties.

It's what Github uses for their placeholders!

I found this [repository called Blockies](https://github.com/download13/blockies). They take the initial idea of Identicons and make them symmetrical horizontally, which makes some very beautiful images. [Here's a demo](http://download13.github.io/blockies/).

Even though I think the random colors they use look gorgeous, I tried it on a mockup for GI and they look too busy visually. So I created a [codepen](https://codepen.io/mmbotelho/pen/OJVeVxo?editors=0110) (with @sandrina-p's help) and decided to play around a bit with their algorithm. I used our colors and reduced the number of blocks in each generated image, so that they look simpler and blend well with our visual. language. Here's a mockup of how it looks like:

<img width="971" alt="Captura de ecrã 2020-04-05, às 19 51 08" src="https://user-images.githubusercontent.com/22004566/78507549-791dd300-7778-11ea-80b5-8769910a44af.png">

The algorithm uses a seed to generate the image, and this can be whatever we want it to (e.g. the user name, a completely random string, etc...). 

Let me know if you like this approach, and I'll create an issue for development with more technical details!

**Comment by taoeffect** [comment]
@mmbotelho Really love this approach! And of course if anyone wants to go the extra mile with this and give the algorithm a unique twist that's also totally welcome! 😄

**Comment by sandrina-p** [comment]
I totally love this solution! Can't wait to see this on Group Income! 🚀

**Comment by mmbotelho** [comment]
I'm removing myself from this one, since the design is done! 🎉
