### ISSUE TITLE
Document differences between "Group Income Simple" & "Group Income"

### ISSUE THREAD

**Issue by dotmacro** [okTurtles/group-income#54]
## Problem

Differences between "Group Income Simple" (GIS) and "Group Income" (GI) will impact the tests of GIS.
## Solution

Brainstorm and document differences between GIS and GI. Where possible and feasible, include suggestions of how to adjust GIS to be as close to GI as possible

**Comment by dotmacro** [comment]
GIS avoids some of the difficulties in working with income streams other than standard paychecks because GIS allows users to report _net_ income at the end of the month instead of processing each transaction individually. 

<blockquote class="twitter-tweet" data-lang="en"><p lang="nl" dir="ltr">QA Engineer walks into a bar. Orders a beer. Orders 0 beers. Orders 999999999 beers. Orders a lizard. Orders -1 beers. Orders a sfdeljknesv.</p>&mdash; Bill Sempf (@sempf) <a href="https://twitter.com/sempf/status/514473420277694465">September 23, 2014</a></blockquote>

<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

Generally (but [not always](http://cs.thomsonreuters.com/ua/acct_pr/acs/cs_us_en/pr/negative_ck_treatment_overview.htm)), income streams from standard employee relationships will be positive values, and based on post-tax income. 

Employee:
- paycheck is post-tax $ (positive value)
- income tax filing (often positive)

Income streams from businesses, independent contractors, etc, may not be positive values, and will not be equal to post-tax income.

Non-employee:
- incoming payments are likely pre-tax
  - ~7.5% "self employment tax" in USA
  - no withholding --> periodic tax payments (= negative income values)
- incoming payments != "income"
  - "income" = payments - expenses
- charge-backs, returns, & refunds will lead to negative values

Calculating "per month" income in GIS reduces the need for handling negative-value transactions because over the course of a month, most negative-value transactions are likely to be counterbalanced by positive-value transactions (e.g. purchase - refund = $0). Automated GI will process payments near-instantaneously, meaning it will need a system for handling negative values and a way to ensure all income streams are weighted based on income (rather than "incoming payments").

**Comment by dsernst** [comment]
Is this still relevant? Unclear where this documentation would go.

**Comment by taoeffect** [comment]
Definitely outdated, closing.
