### ISSUE TITLE
Bug when clicking the notifications bell

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#542]
### Problem

@sandrina-p noticed [a problem](https://github.com/okTurtles/group-income-simple/pull/537#discussion_r265213981) that I missed in my review of #537:

![](https://user-images.githubusercontent.com/14869087/54295838-b6328880-45ab-11e9-9587-52e3f2a48daf.png)

### Solution

See [her comment](https://github.com/okTurtles/group-income-simple/pull/537#discussion_r265213981) for a possible fix.

**Comment by pieer** [comment]
This is not happening on my version. I've fixed that long time ago. Did you pull all the changes? What browser are you testing on?

**Comment by mmbotelho** [comment]
This is not happening on my end either. I am seeing it correctly on Chrome:

<img width="504" alt="Captura de ecrã 2019-03-14, às 16 06 05" src="https://user-images.githubusercontent.com/22004566/54367801-47b8fd80-4673-11e9-9484-5dc5d47384dd.png">

**Comment by taoeffect** [comment]
Hmm, interesting, yes I too am not able to reproduce. Perhaps this was some sort of browser caching issue?

Please keep an eye out for this folks in case it is a caching issue and we need to fix the headers that the server is sending or something. I'll close this issue for now. @sandrina-p feel free to re-open it if needed!
