### ISSUE TITLE
Make font-size of page titles consistent across the app

### ISSUE THREAD

**Issue by mmbotelho** [okTurtles/group-income#552]
### Problem

Right now, the font sizes across these pages are extremely big:

- Dashboard;
- Contributions;
- Pay Group;

And too small on these pages:

- Group Chat (titles "**Chat**" and "**Lounge**");
- Messages (titles "**Messages**" and "**$person_name**");

### Solution

Make the size of page titles consistent across the app. The following pages should have their titles with the `.title .is-4` style (instead of `.title .is-1`):
- Dashboard;
- Contributions;
- Pay Group;
- Group Chat (titles "**Chat**" and "**Lounge**");
- Messages (titles "**Messages**" and "**$person_name**").

**Comment by SebinSong** [comment]
It seems to be about changing Bulma classes in the corresponding Vue components. Now that @pieer is taking Bulma out of the project, Should this issue be left untouched until removal is completed? :)

**Comment by mmbotelho** [comment]
I think so, yes. Until @pieer finishes removing Bulma, I would say it's not worth doing this change 😄

**Comment by SebinSong** [comment]
Ok, Thank you! 🙂

**Comment by mmbotelho** [comment]
Solved with the new UI.
