### ISSUE TITLE
Create "change minimum income" proposal

### ISSUE THREAD

**Issue by mmbotelho** [okTurtles/group-income#554]
_**Note**: There might be some dependencies with the pull request #343 (Proposals/voting logic)._

## Problem
In the current Master version of the application, there's no way to change the minimum income of the group. I am not sure if this was already implemented on the PR #343.

![Captura de ecrã 2019-04-14, às 17 17](https://user-images.githubusercontent.com/22004566/56095955-e1c1cf00-5ed9-11e9-9e0d-92519aacda65.png)
<img width="805" alt="Captura de ecrã 2019-04-14, às 17 18 02" src="https://user-images.githubusercontent.com/22004566/56095959-e5555600-5ed9-11e9-8079-21affecbb08f.png">

## Solution

There are some differences from what was designed at the time of the PR #343:

- The UI is slightly different (updated to fit the new modal design);
- There's one additional step, where the user can add a description to the proposal they are about to create - this will help other members of the group understand why;
- There's a "success" view in the modal, that tells the user what will happen now that a proposal has been created.

[You can see the Figma file here.](https://www.figma.com/file/ZR0DRPhhUuHdJtf7PbGAM6tW/Group-Income?node-id=2314%3A0)

**Comment by sandrina-p** [comment]
Note: When we address this, let's not forget #405

**Comment by mmbotelho** [comment]
I'm closing this because #679 and #405 were already merged and solved, respectively.

**Comment by sandrina-p** [comment]
I'm reopening this because the proposal wasn't implemented yet. I'll do that this week :)
