### ISSUE TITLE
Implement the "Income Details" modal as a fullscreen modal

### ISSUE THREAD

**Issue by mmbotelho** [okTurtles/group-income#556]
### Problem

The current "Income Details" modal has a lot of information for a small-sized modal. For more context on the problem and the UI/UX solution, go to issue #536 .

### Solution

- Change the UI to make it more readable and better suited for a full-screen modal;
- The functionality should remain the same as before;
- Users will be able to open this modal from the **Contributions** page and the **Dashboard**.

[Here's link to the Figma mockups](https://www.figma.com/file/ZR0DRPhhUuHdJtf7PbGAM6tW/Group-Income?node-id=1922%3A0).

_**Note**: Because the current version is not 100% functional, I was not able to test all the possible scenarios and see if there was some use case missing. If there are, we can address it future issues._

**Comment by dotmacro** [comment]
For reference, [here's a link to the redesigned Figma mockups](https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?node-id=1922%3A0).

**Comment by mmbotelho** [comment]
Update on this - the modal has been implemented, except for the graphic UI. Once that is done this issue can be closed.
