### ISSUE TITLE
Implement the Dashboard's right-hand sidebar

### ISSUE THREAD

**Issue by mmbotelho** [okTurtles/group-income#557]
_Note: These screenshots are using an outdated Design System. The functionality remains the same today. You can see the updated version [here](https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?node-id=1204%3A0)._

### Problem

There is two types of information on the Dashboard:
- **Fixed information** - or information that is seldom changed, like the group members, the group description and the group mincom;
- **Mutable information** - information that can potentially change everyday, like proposals or contributions.

The fixed information needs to be visible on the Dashboard, but should not be in the way of the mutable information.
 
<img width="1277" alt="Captura de ecrã 2019-04-19, às 17 11 50" src="https://user-images.githubusercontent.com/22004566/56432807-b880b480-62c6-11e9-87ab-8aad2e520cc6.png">

### Solution

Create a sidebar that keeps the fixed information at hand, but does not steal the shine from the main content. The sidebar has 3 sections:

- Minimum income;
- Members;
- About the group.

This sidebar has a width of 16,5rem and it pushes the main content to the left, as you can see in this screenshot:

<img width="1101" alt="Captura de ecrã 2019-04-19, às 17 18 42" src="https://user-images.githubusercontent.com/22004566/56433018-68562200-62c7-11e9-8627-6e55e696fff2.png">

Please refer to the [Dashboard mockups](https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?node-id=1204%3A0) for all the variations of this sidebar and further specifications.

**Comment by mmbotelho** [comment]
@sandrina-p is implementing this in PR #630

**Comment by sandrina-p** [comment]
> Please refer to the Dashboard mockups for all the variations of this sidebar and further specifications.

The link goes to the state version, can you update it?

**Comment by mmbotelho** [comment]
Updated! Thank you @sandrina-p
