### ISSUE TITLE
Implement the "This month's overview" dashboard widget

### ISSUE THREAD

**Issue by mmbotelho** [okTurtles/group-income#558]
## Problem

At the moment, it's not easy to understand the "financial health" of the group.

<img width="886" alt="Captura de ecrã 2019-04-20, às 16 13 44" src="https://user-images.githubusercontent.com/22004566/56459134-4d4ae700-6387-11e9-9575-318897214253.png">

## Solution

Iterate on the current "monthly overview" widget, and make it also provide information on the individual distribution of wealth amongst group members. Surplus and deficits are also shown now. 

<img width="1209" alt="Captura de ecrã 2019-04-20, às 16 34 01" src="https://user-images.githubusercontent.com/22004566/56459356-24782100-638a-11e9-8e6a-b18e3566260c.png">

There's also a button that allows the user to see how well the group did in previous months. This is exatly the same widget that exists in the current version of the Dashboard, with very small UI adjustments:

<img width="1300" alt="Captura de ecrã 2019-04-20, às 16 46 09" src="https://user-images.githubusercontent.com/22004566/56459467-ff84ad80-638b-11e9-9495-953b3161412a.png">

To see this widget in context, visit the [Dashboard page on Figma](https://www.figma.com/file/ZR0DRPhhUuHdJtf7PbGAM6tW/Group-Income?node-id=1204%3A0). There's an [artboard with more in-depth information,](https://www.figma.com/file/ZR0DRPhhUuHdJtf7PbGAM6tW/Group-Income?node-id=1476%3A17248) as well as the desktop, tablet and mobile versions.

**Comment by sandrina-p** [comment]
Solved by #789
