### ISSUE TITLE
Implement the "Remove a member" proposal

### ISSUE THREAD

**Issue by mmbotelho** [okTurtles/group-income#560]
### Problem

At the moment, it's not possible to remove a member from a group.

### Solution

It should be possible to do so, from 2 different places in the Dashboard:
1. From the Dashboard's sidebar;
2. From the "All members page";

![Group](https://user-images.githubusercontent.com/22004566/56752204-aba90880-677f-11e9-8316-70bb67c181c2.png)

Removing a member is never a direct action - the group always needs to vote on it.

[You can check out the full userflow for proposing to remove a member on Figma](https://www.figma.com/file/ZR0DRPhhUuHdJtf7PbGAM6tW/Group-Income?node-id=2371%3A0)

**Comment by sandrina-p** [comment]
@taoeffect and @pieer  I'm implementing this modal. I'm almost finishing the layout part, but I was already thinking about the logical part.

Here's a screenshot to better help us understand the context:

![image](https://user-images.githubusercontent.com/14869087/64418243-882d8d00-d092-11e9-95f7-12ee10088d35.png)

The challenge here is: how will we inform the modal about what member should be removed?

My suggestion is to use URL query because it's how modal works at the moment

```
http://localhost:8000/app/dashboard?modal=RemoveMember&username=rick
```

If we go with that option...

```js
// opening a modal
sbp('okTurtles.events/emit', LOAD_MODAL, 'RemoveMember', { username })
```

```js
// Modal.vue
sbp('okTurtles.events/on', LOAD_MODAL, (component, query = {}) => {
      this.openModal(component, query)
})

//  method
openModal (component, query) {
  this.content = component
  
  this.$router.push({ query: {
    modal: this.content,
    ...query // NEW: pass the query received to the URL
  })
}
```

```js
// RemoveMember.vue

// on created fetch/validate username in the query
```

What do you think?

**Comment by taoeffect** [comment]
@sandrina-p That seems like a reasonable approach to me! 😄 

There are two related issues:

- #509 - Improve URL-based navigation
- #432 - Create a core state machine for all user-flow

For closing #432 (down the road), this type is stuff will need to be checked, because, for example, we don't want to be able to load modals when the statemachine is in recovery mode because of a `GIErrorUnrecoverable` error.

**Comment by sandrina-p** [comment]
@taoeffect Cool. I'll do it in a future PR with all the working logic for a fully functional new proposal!

**Comment by taoeffect** [comment]
@sandrina-p Great! Some other things I've noticed to keep in mind:

- Users shouldn't be able to remove themselves via this menu (instead they can click the "Leave Group" button in the Group Settings)
- It's important to also close the bug #648 in order for this to work correctly

**Comment by mmbotelho** [comment]
@sandrina-p here are the copy and element changes in the _Remove a member_ modal, as discussed in the hackathon:

<img width="593" alt="Captura de ecrã 2019-10-16, às 08 43 33" src="https://user-images.githubusercontent.com/22004566/66891267-5db7e380-eff1-11e9-9290-1c826212c4a9.png">

**Comment by sandrina-p** [comment]
@taoeffect, I have some questions about this task I'd like to discuss before implementing the removal action itself.
Here's a list of requirements/constraints that I can remember, let me know what you think about it.

- Remove member profile from `currentGroupState.profiles`. That's obvious I guess.
- Flag the member somehow as an "ex-member" to keep a registry on the payments page? Maybe add the member profile to `currentGroupState.oldProfiles`?
- This removal, how it affects the `groupIncomeDistribution`? Will it stay "frozen" or should we force its rebalance? 
- Should we remove the member `identityContract` from the state?
- _something else?_...

**Comment by taoeffect** [comment]
We're going to start to run up against memory constraints. So to be kind on RAM let's make sure that old profiles are stored as just the username (and display name, if set). No avatar or anything else. We're going to need to put some thought into how to store them. I'm thinking the ideal approach might be a function that takes a username and returns a proxy that abstracts everything (i.e. returning values for active profiles, or inactive profiles, as needed). We will need to make sure all the code accesses profiles through this function.

I'm not sure about `oldProfiles`. Creating that will result in complex code, as we would need code to shuffle profiles back and forth from there and `profiles`. So better yet to simply have a way of accessing profiles, and then for the returned profiles themselves to tell us if they're active or not.

> This removal, how it affects the groupIncomeDistribution? Will it stay "frozen" or should we force its rebalance?

I'll worry about that, as that is where I left off after the hackathon, was working on this exact problem (and similar problems — i.e. the problem of creating multiple frozen distributions).

> Should we remove the member identityContract from the state?

Yes, I think so.

> something else?...

Probably. Can't think of anything at the moment though!

**Comment by taoeffect** [comment]
> We're going to start to run up against memory constraints. So to be kind on RAM [..]

FYI, anytime this sort of thing happens (e.g. when retrieving payment transaction history, old chat messages, etc.), this stuff will be stored outside of the Vuex state to keep it out of RAM, and only portions of it will be brought into RAM temporarily. This means `localStorage`, and anything else browsers decide to create for on-disk storage.

**Comment by sandrina-p** [comment]
I like the idea of having a function to access someone's profile through their username.
