### ISSUE TITLE
Consolidate actual design

### ISSUE THREAD

**Issue by pieer** [okTurtles/group-income#566]
### Problem

At the moment, there is few inconsistencies between the different pages in figma which make the frontend code a bit messy.

For example: 
The modal on user setting:
![image](https://user-images.githubusercontent.com/312402/57246218-559b5700-7002-11e9-87ba-8f2f838bb518.png)
and
![image](https://user-images.githubusercontent.com/312402/57246310-98f5c580-7002-11e9-9cae-01a4458345a0.png)

Or between components:
![image](https://user-images.githubusercontent.com/312402/57246356-b3c83a00-7002-11e9-816a-b322b2150f36.png)

and
![image](https://user-images.githubusercontent.com/312402/57246505-0c97d280-7003-11e9-8d74-a6199e8ee068.png)

### Solution

Make sure that every pages use instance of components. So if we update a component it will automatically update all the instances in the pages

**Comment by mmbotelho** [comment]
Copy-pasted list of possible modifiers, by @pieer on Slack:
>**Text**: Font, Weight, Size, Line Height, Letter Spacing, Paragraph Spacing, Indentation.
>**Color**: Fill, Stroke, Background Color, Opacity.
>**Effects**: Drop Shadow, Inner Shadow, Blur.

**Comment by mmbotelho** [comment]
## Fixed:
- Modal headers on all mockups;
- Consolidated password field design - now it looks the same in all pages: 

<img width="543" alt="Captura de ecrã 2019-05-13, às 16 12 25" src="https://user-images.githubusercontent.com/22004566/57628306-fb6a3b00-7599-11e9-9891-6c117cd851e0.png">
<img width="724" alt="Captura de ecrã 2019-05-13, às 16 12 40" src="https://user-images.githubusercontent.com/22004566/57628309-fb6a3b00-7599-11e9-82e3-bb106cb79678.png">
<img width="726" alt="Captura de ecrã 2019-05-13, às 16 12 47" src="https://user-images.githubusercontent.com/22004566/57628310-fc02d180-7599-11e9-93ec-0fb07e148e04.png">

## Others:
I've encountered several other inconsistencies, that were not yet implemented. I am currently working on fixing those on Figma as well.

**Comment by taoeffect** [comment]
Is this ready to be closed now?

**Comment by mmbotelho** [comment]
Yes @taoeffect
