### ISSUE TITLE
Fix broken Contributions page

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#570]
### Problem

As described [here](https://github.com/okTurtles/group-income-simple/pull/559#issuecomment-488924868), PR #559 has broken the modal / animation in the contributions page, when the "Add Income Details" box is clicked.

Specifically there are 4 problems:

1. Bringing up the modal for the contributions page and closing it makes everything unclickable
2. The [income details](https://github.com/okTurtles/group-income-simple/pull/559#issuecomment-488922890) modal is squashed and looks wrong
3. The "Add Income Details" box disappears and remains hidden, even if nothing was done except closing the modal
4. Editing the contributions no longer looks how it should (see below)

![Screen Shot 2019-05-10 at 10 01 36 PM](https://user-images.githubusercontent.com/138706/57563740-3fc5c300-736f-11e9-9724-b814127fd964.jpg)

### Solution

Restore previous functioning behavior.

**Comment by taoeffect** [comment]
Interesting: clicking the "Cancel" button doesn't result in the problem, but clicking the grey background does.

**Comment by pieer** [comment]
The new modal is not implemented on this page. This is why it's failing.

**Comment by taoeffect** [comment]
Gotcha. Also edited the issue above to note another issue (with editing the field)

**Comment by pieer** [comment]
I don't see this kind of button anywhere in the design anymore

**Comment by mmbotelho** [comment]
I am closing this issue because it is outdated!
