### ISSUE TITLE
Consider switching from Vue.js to Svelte

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#587]
### Problem

- Vue.js is a dependency that we might not need
- A new framework called Svelte promises to "ditch the framework" by doing everything at compile-time, without a virtual DOM, thereby being both faster and with fewer dependencies
- ["50 times faster than Vue"](https://www.youtube.com/watch?v=AdNJ3fydeao&t=1080)

### Solution

Research links:

- Blog post:
  - https://svelte.dev/blog/svelte-3-rethinking-reactivity
  - https://svelte.dev/blog/virtual-dom-is-pure-overhead
- HN discussion: https://news.ycombinator.com/item?id=20335057
- Homepage: https://svelte.dev
- Svelte Native: https://svelte-native.technology
- Preprocessor (Pug, SASS) support:
  - https://svelte.dev/docs#svelte_preprocess
  - https://github.com/sveltejs/svelte/issues/1720

Related:

- #275 - Research nativescript-vue
- Also look into the new [mint language](https://www.mint-lang.com/)

Comparison with future Vue changes:

- https://vue-composition-api-rfc.netlify.com/#comparison-with-svelte
- https://github.com/vuejs/rfcs/pull/78

**Comment by sandrina-p** [comment]
I tried Svelte some weeks ago to do some very basic experiments. I loved its minimal API to handle state! It seemed they really learned from React and Vue expertise and created our next step in FE development.

**Comment by sdegutis** [comment]
My issue with Svelte is that it's not really JavaScript. The main benefit of using either a library or a framework is that you can use all the features of the language from your prior knowledge of it. Using a *similar-but-not-quite-the-same* language always has pitfalls.

For my 2¢, I've been looking into Web Components lately. The raw API is less than convenient, but that's true of DOM too. And so far, the only thing that's really been built on top of it is LitElement, which is more or less trying to mimic only one aspect of React.js (the auto-rendering), and misses the rest.

**Comment by sandrina-p** [comment]
@sdegutis can you point out a JS feature that is not available in Svelte? As far as I know, everything it's available there, even new features through Babel.

**Comment by sdegutis** [comment]
It's not that there's a lack of features, but how the developer's mind works when reaching for features and patterns they're familiar with. The more compilers there are, the more they break those assumptions of what's happening. Some compilers are less complex, like TypeScript which only has the `enum` transformation (the rest is just stripped types). But Svelte actually rewrites variable access/assignment with non-trivial transformations. And the semantics of how it transforms code is very likely to change in the future at least once or twice. This is a lot of mental overhead. That said, lately it seems to be built on top of Web Components also. I think there's got to be a better way to do it though than a compiler, with how powerful JS is.

**Comment by sandrina-p** [comment]
Personally I don't mind using a compiler mainly because of its performance benefits compared to react or any other popular UI Framework. But it's always good to hear the opinions from the other side of the spectrum
