### ISSUE TITLE
Need: generic "Are you sure?" prompt/dialog

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#599]
### Problem

It is extremely common that users will need to be asked an "Are you sure you want to ____?" question.

For example, instead of simply [deleting an existing conflicting user on SignUp](https://github.com/okTurtles/group-income-simple/issues/495#issuecomment-514404784), we should ask the user if they're sure they want to do that first.

### Solution

- Use the default browser prompt
- And/or create a modal/popup/prompt component that takes over the screen and forces the user to answer a Yes or Yes question.
- Make it possible to pass in as props the text that the Yes and No (or Cancel) buttons will have
- Make it possible to switch which button gets the default action (i.e. which one is placed on the right side, is highlighted, and responds to the Enter key)
- Make it simple to bring up this dialog programmatically from JavaScript. Again, see the [SignUp.vue issue for an example of where this would be handy](https://github.com/okTurtles/group-income-simple/issues/495#issuecomment-514404784)

**Comment by mmbotelho** [comment]
This will be a part of the "notifications" task. As discussed with @taoeffect  in one of our calls, we will be using the default JS `window.alert()` method for now

**Comment by mmbotelho** [comment]
I closed issue #511 because it falls under this umbrella. I believe that for now, we can also solve that issue by using the default JS alert method (as mentioned in my comment above) as well.

**Comment by taoeffect** [comment]
For now we can use the native [`window.confirm`](https://developer.mozilla.org/en-US/docs/Web/API/Window/confirm)
