### ISSUE TITLE
frontend overview - quick fixes

### ISSUE THREAD

**Issue by sandrina-p** [okTurtles/group-income#604]
### Problem
These last couple of days I've been exploring the GI app (on Master and  Pierre's branch #594) and found some stuff that I believe that it can be improved quickly and easily:

#### Modal:
- The url is not updated when closing a modal.
- README is outdated.
  - I had some trouble understanding the difference between LOAD_MODAL and OPEN_MODAL and Content vs subcontent. Maybe that could be added to the README.
- CSS animation "enterFromLeft" seems stale (not being used).

#### A11Y:
- The sidebar links have no focus state.
- I find the buttons focus state not easily visible. Maybe adding a border when in focus could help (and it would work in any theme!) @mmbotelho could you re-check that part?
- Password field - can't toggle the visibility by keyboard.

### Solution
I'll fix all of it today with a new branch based on #594.

**Comment by mmbotelho** [comment]
@sandrina-p :
> I find the buttons focus state not easily visible. Maybe adding a border when in focus could help (and it would work in any theme!) @mmbotelho could you re-check that part?

That is fixed in the new Design System

**Comment by mmbotelho** [comment]
@sandrina-p :
> The sidebar links have no focus state.

The hover and focus state for the sidebar is [described here.](https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?node-id=48%3A70)
(Scroll down to the "Behaviour" section). 

It makes more sense to fix that once the sidebar is updated to the new UI though.

**Comment by sandrina-p** [comment]
Just noticed I was checking the wrong Figma file (1.0 instead of 2.0) 🤦‍♀ 

Thanks, I'll leave as it is then and we'll fix it later.

**Comment by mmbotelho** [comment]
Ok, no problem @sandrina-p 😄

**Comment by sandrina-p** [comment]
So, I already fixed all the quick issues except the URL on Modal (I'll explain better later). I'll open PR once Pierre's PR is merged, so the CR easier to do.
