### ISSUE TITLE
Fix all remaining issues found in PR #594

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#605]
### Problem

(Possibly related to #604).

@sandrina-p and I have found several remaining issues with PR #594 and have left comments. However, to speed things along (since @pieer is on vacation) we will go ahead and squash-merge that PR. Still, that means that we will have several issues that need to be quickly fixed in order to bring `master` to a good state.

All of the review comments, [starting with this one](https://github.com/okTurtles/group-income-simple/pull/594#issuecomment-519298888), need to be addressed.

### Solution

1. Let me know Sandrina when you're ready for me to squash-merge his PR and I wlil do it.
2. Fix all of the issues found, and submit a PR to close this issue.

**Comment by sandrina-p** [comment]
Working on it now
