### ISSUE TITLE
Redesign and rewrite Invite.vue to generate invite links

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#609]
### Problem

We no longer invite people by username. Instead:

- If less than 3 members exist, invite links are created (that can each specify how many members they allow to join)
- If at least 3 members exist, a proposal is created, containing the names of the people to be invited (not usernames, just their full names), and if it passes an invite link for those people is created

### Solution

- Completely rewrite/redesign all related views. Delete anything no longer needed.
- Create a page to manage and view all invite links that have been created (see `currentGroupState.invites` after the proposals PR is merged) (This is now #612)
- Create a single proposal when proposing to invite multiple members, instead of multiple proposals

**Comment by mmbotelho** [comment]
Might be useful: 
- [Figma screens to create an add a member proposal](https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?node-id=875%3A2)

**Comment by mmbotelho** [comment]
There is a more in-depth description of the design "whys" of this issue in #553.

I am not sure if this issue is a duplicate and we can just keep #553, or if there is something else here that I am missing.
