### ISSUE TITLE
Implement Signup-And-Join flow when given a link and not logged in

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#614]
### Problem

The types of links generated by #611 , e.g. (copying from `Invite.vue`):

```js
                message: `Hi ${memberName},

                Here's your special invite link:

                ${process.env.FRONTEND_URL}/app/join?groupId=${this.$store.state.currentGroupId}&secret=${invite.inviteSecret}`
```

Should be usable even when no user has been created.

### Solution

Create and implement the Signup and Join flow that @mmbotelho designed and should be instantiated when visiting a link like that while not logged in. [Here is the Figma page for this.](https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?node-id=875%3A2)

**Comment by mmbotelho** [comment]
Edited the issue to include the Figma link cc @taoeffect

**Comment by mmbotelho** [comment]
FYI - I just realized that I need to design some sort of welcome page - I created an issue to address this (#701)
