### ISSUE TITLE
Minor Design system fixes

### ISSUE THREAD

**Issue by mmbotelho** [okTurtles/group-income#626]
### Problem
I found some minor discrepancies between the [design system on Figma](https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?node-id=1%3A7) and what was actually implemented. This list of changes was made after reviewing the `app/design-system` page in `master` (August 19, 2019).

### Solution 

- [x] H1 and H2 should be responsive ([figma](https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?node-id=3070%3A106));

----
- [x] Fix small typo, on the subtitle typography atom. "This is an subtitle" should be "This is a subtitle";

----

- [x] Buttons that have icons as a prefix or sufix should not have a margin on the left or a margin on the right side:
<img width="108" alt="Captura de ecrã 2019-08-19, às 16 52 54" src="https://user-images.githubusercontent.com/22004566/63284053-48009900-c2a2-11e9-89ad-ebc54014c74c.png">

----

-  [x] Fix small text movement in some inputs (dropdown, text + dropdown combo, text + button, text with icon prefix), when they change from their normal state to focus (see gif below - it takes a while to show the change):
![input-movement](https://user-images.githubusercontent.com/22004566/63295840-35478d80-c2bd-11e9-90ae-e147d6d3b445.gif)

----

- [x] Remove hover CSS changes from the text input with icon prefix:
<img width="486" alt="Captura de ecrã 2019-08-19, às 19 56 11" src="https://user-images.githubusercontent.com/22004566/63295868-44c6d680-c2bd-11e9-84df-afbb0f99bb76.png">

----

- [x] The subtitle on modals does not have the correct CSS - the subtitle component in the typography section is correct:
<img width="707" alt="Captura de ecrã 2019-08-19, às 20 11 24" src="https://user-images.githubusercontent.com/22004566/63296058-ba32a700-c2bd-11e9-8376-54de6c918c3e.png">

----

- [x] At the moment, it's possible to resize textareas horizontally. I understand that this is the default behaviour of textareas. The vertical resize is useful, but the horizontal one can be problematic. Is there a way to limit this movement? Bonus question, for 1000€ - how difficult is it to make a textarea increase its vertical size as the content needs it (aka, dynamically)? [I found this codepen example](https://codepen.io/vsync/pen/frudD)

![textarea2](https://user-images.githubusercontent.com/22004566/63297572-40042180-c2c1-11e9-99da-33ec92807b88.gif)

----

- [x] Update selectbox icon (chevron)

**Comment by sandrina-p** [comment]
I'll pick this stuff today, you should expect a PR later today ;)

**Comment by pieer** [comment]
I started to fix those already @sandrina-p

**Comment by sandrina-p** [comment]
Oh okay, no problem! Next time @pieer let us know when you pick this, so we avoid doing the same thing twice :)

**Comment by mmbotelho** [comment]
Let me know if you have any questions. By the way @pieer, I am using google chrome

**Comment by pieer** [comment]
That was mainly fix about my previous commit, so I assume I was going to fix it and you would focus on the sidebar, but yes, I will tell you next time

**Comment by mmbotelho** [comment]
@pieer this is the issue being solved in PR #636 right?

**Comment by mmbotelho** [comment]
Just reviewed this in master - most of these are solved with the exception of:
> H1 and H2 should be responsive

> Buttons that have icons as a prefix or suffix should NOT have a margin on the left or a margin on the right side

---

The first one (H1 and H2) are working as expected in desktop and tablet, but are missing the smaller breakpoint:

<img width="1183" alt="Captura de ecrã 2019-09-07, às 17 56 45" src="https://user-images.githubusercontent.com/22004566/64477233-53582d80-d199-11e9-99e3-24500ef3cf45.png">

---

cc @pieer

**Comment by mmbotelho** [comment]
Also noted that the dropdown input has the wrong icon. See below:
<img width="501" alt="Captura de ecrã 2019-09-07, às 18 02 14" src="https://user-images.githubusercontent.com/22004566/64477265-c497e080-d199-11e9-9465-a781c94ec8d0.png">
<img width="391" alt="Captura de ecrã 2019-09-07, às 18 01 13" src="https://user-images.githubusercontent.com/22004566/64477266-c497e080-d199-11e9-8bd2-4bff0967d68d.png">

Added this one as a task as well

**Comment by sandrina-p** [comment]
@mmbotelho which icon from fontawesome is that little triangle? (I'm realising I'm terrible looking for icons there)

**Comment by mmbotelho** [comment]
Sorry for making you look there, it's not an icon - it's just a div shaped into a triangle (I believe this can be done with the `:after` pseudo-element or something similar). Here are the dimensions:

<img width="191" alt="Captura de ecrã 2019-09-08, às 13 04 32" src="https://user-images.githubusercontent.com/22004566/64487324-3b37eb00-d239-11e9-81dc-e44714b08ce8.png">

It is also placed slightly off-center (1 px closer to the bottom) or else it looks misaligned (because of the upper weight of the shape).

cc @sandrina-p

**Comment by sandrina-p** [comment]
@pieer are you working on these?

**Comment by pieer** [comment]
I forgot the to change the icon ya
