### ISSUE TITLE
Create Multi-Group Invitation Tests

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#645]
### Problem

1. We have no tests for inviting and accepting invites into groups
2. We have no tests for verifying that there are no problems [like this](https://github.com/okTurtles/group-income-simple/pull/636#issuecomment-526709320) for multi-group usage

### Solution

Use Cypress to test:

1. Inviting members to a single group
2. Inviting and voting a proposal to join a single group
3. Creating multiple groups and inviting users to them and switching between them (verifying all the UI elements, like who should be in the group, the mincome, etc.) get updated correctly

*Because of [this issue](https://github.com/okTurtles/group-income-simple/pull/636#issuecomment-526709320), make sure to wait for #636 to be merged first!*

**Comment by sandrina-p** [comment]
Is this issue still relevant @taoeffect? ATM we have all the essentials tests regarding group invitations in place.

**Comment by taoeffect** [comment]
Yeah I think so. Closing, can reopen if it turns out we’re missing something.
