### ISSUE TITLE
TODOs in GroupMembers.vue

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#647]
### Problem

As a hack to fix [this issue (`"TypeError: member is undefined"`)](https://github.com/okTurtles/group-income-simple/pull/636#issuecomment-526709320) in GroupMembers.vue, the following [change and TODOs were pushed](https://github.com/okTurtles/group-income-simple/pull/636/commits/a354399e470fd6abd1fddf3b8e61251a83674132):

![Screen Shot 2019-08-30 at 10 17 29 PM](https://user-images.githubusercontent.com/138706/64058092-f7c3e980-cb73-11e9-80b6-09b7e4d881d7.jpg)

```
    // TODO: Check why removing member condition can fail here
     // TODO: remove v-if in v-for loop and reorder list member by active user limited to 10
```

### Solution

Get to the bottom of what's going on and address the TODOs in GroupMembers.vue.

**Comment by sandrina-p** [comment]
Fixed by #677
