### ISSUE TITLE
Implement invite management section (group settings page)

### ISSUE THREAD

**Issue by mmbotelho** [okTurtles/group-income#664]
### Problem
At the moment, there is no way to manage the invite links that are generated in a group.

### Solution
To implement the solution discussed on issue #612. You can see the Figma mockups here:
https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?node-id=3824%3A0

**Comment by sandrina-p** [comment]
Fixed by #723

**Comment by sandrina-p** [comment]
Dummy layout was made at #723 but the fetching the real data is still missing. @SebinSong will be working on it

**Comment by sandrina-p** [comment]
Functionality missing to close this issue:
- "See original proposal" action
- "Revoke link" action

-- EDIT 22 May --

"See original proposal" action will be left out to another issue #925. That way this issue (the core invite management functionality) can be closed.

**Comment by mmbotelho** [comment]
ooops closed this by mistake
