### ISSUE TITLE
Design Dark Theme

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#665]
### Problem

We don't have a dark theme for the new design.

### Solution

A dark theme needs to be designed. Afterwards, create a new issue to implement it.

**Comment by mmbotelho** [comment]
This [NN Group article about dark themes](https://www.nngroup.com/articles/dark-mode/) might be useful when designing this.

**Comment by mmbotelho** [comment]
Great [Google Material recommendations and guidelines for dark themes](https://material.io/design/color/dark-theme.html).

**Comment by mmbotelho** [comment]
Design for the dark theme is done. The implementation issue is #872 

I am closing this issue!
