### ISSUE TITLE
Uniformize avatar sizes across app

### ISSUE THREAD

**Issue by mmbotelho** [okTurtles/group-income#672]
### Problem
@sandrina-p noticed that we didn't have a size scale for avatars, so I decided to make one! 

<img width="829" alt="Captura de ecrã 2019-09-19, às 18 05 40" src="https://user-images.githubusercontent.com/22004566/65261461-a4a4dd00-db08-11e9-9f3a-590688560947.png">

https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?node-id=1876%3A17778

### Solution

1. Make this avatar scale a part of our front-end style guide;
2. Make sure that all avatars implemented so far have one of these sizes

**When in doubt:**
- Check the Figma mockups for the page you have doubts - I have updated all pages with this new scale;
- If you do find an avatar in the mockups that doesn't respect this scale, let me know!

**Comment by taoeffect** [comment]
Not sure how much this depends on #658 (profile editor), but figured I'd mention it here.

**Comment by sandrina-p** [comment]
Finally, after almost 4 months, I'm picking up this issue 👩‍💻
