### ISSUE TITLE
Create eslint plugin for i18n tag usage

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#683]
### Problem

1. We don't have documentation for how to use i18n tag (open issue: #607)
2. Even if we did, people still might not follow it, and a lot of PR reviews lately have been correcting its usage

### Solution

If we had an eslint plugin for how to use the i18n tag, we could enforce correct i18n usage and save a lot of time on PR reviews, and also guarantee that i18n is used in a way the works for the parser.

Related:

- https://twitter.com/swyx/status/1289306584938508288

**Comment by snowteamer** [comment]
I could be interested in tackling this, once thorough documentation is available regarding allowed and disallowed usages of the tag.

But it will likely have to be very detailed, almost like pseudo-code for me to grasp the requirements, since I'm not yet familiar with Vue nor Pug myself.

**Comment by taoeffect** [comment]
@snowteamer Yes at the moment we don't have documentation on its usage, however it is possible to discern the use-cases from the code and here's why: the `strings` utility that @SGrondin developed has support for all of the usages that we have, and I think it will output an error if the use-case is incorrect.

So if you decide to take on this issue, then as you're developing the eslint plugin for `i18n` usage for Pug (and ideally `L` function usage as well for JS), then you should be able to find all of the instances that you've missed, because your plugin (I'm guessing) will output linter errors for the parts you haven't yet supported.

**Comment by snowteamer** [comment]
So if I understand correctly, that workflow would cover the missed usages, but I hope it can also detect the wrong usages as well

**Comment by taoeffect** [comment]
Let's say there are 6 usages for i18n. If you implement 1 and tell it to error on anything else, you'll discover the other 5.

**Comment by taoeffect** [comment]
Closed in #683 by @snowteamer !
