### ISSUE TITLE
Create self-removing component for scoped banner messages

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#689]
### Problem

The **Type 2** "Context-Sensitive Scoped Success and Error Banners" (or just, "scoped banners") component described in #688 doesn't exist and needs to be designed and implemented.

Moreover, per the discussion in that issue, it needs to be implemented in a very specific way in order to satisfy our DRY **requirement** (which really needs to be part of our JavaScript Style Guidelines...).

### Solution

As shown in the examples in [this comment](https://github.com/okTurtles/group-income-simple/issues/688#issuecomment-536091742), currently the way these sorts of messages are implemented in our UI is through the use of `v-if` directives and corresponding variables.

This is a very ugly violation of DRY. So the goal for this issue is to see if it's possible (and I believe it should be), to create a component that does not require the use of `v-if` directives and variables.

Quoting from [here](https://github.com/okTurtles/group-income-simple/issues/688#issuecomment-536098776):

> I.e. something like this:
> 
> ```
> insertError(<target ref>, {message: 'error message', icon: 'cross'})
> ```
> And for that to insert a component into `<target ref>`, that itself contains all the logic necessary for automatically removing itself from the parent component

In other words, what is needed to close this issue is:

1. Implementing a component for Type 2 errors (i.e. the markup and CSS)
2. For this component to take props specifying what type of message it's displaying (i.e. an error or a success message, the message itself, and how the message should remove itself from the parent component<sup>[1]</sup>)
2. For a function similar to the `insertError` function above to be implemented (perhaps `insertScopedBanner()`), making it possible to use **one line** to insert this banner inside of the node specified by `<target ref>`. Again: to respect DRY, the parent component must not use `v-if` logic to show/hide this banner

<sup>[1]</sup> Possible values include: automatically removing itself after a given amount of time, or when the X to be clicked, or because another call to the same `<target ref>` has been made with `insertScopedBanner()`, causing the previous banner to be replaced. Barring either of those outcomes, it should always remove itself when the parent component is unloaded (i.e. if we navigate to a different page, or close the containing modal, etc., so that when we return to the parent view, the errors/success messages from before are all cleared)

If any of this is confusing or unclear, please ask questions!

**Comment by taoeffect** [comment]
I happened to have written some code for `vue-script2` that handles removing not exactly the entire component itself, but its `Element` from the parent: https://github.com/taoeffect/vue-script2/blob/master/src/index.js#L46-L49

Note that this example just removes the component's HTML DOM node, and so doesn't completely from itself from the parent node, and so it's not how this issue should be closed. But, it might serve as some sort of starting point/inspiration.

**Comment by mmbotelho** [comment]
Note: Design documentation and specs for this can be found on issue #688. Closing this issue will close both!

**Comment by SebinSong** [comment]
I just noticed that the design for the banner component has changed [here](https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?node-id=48%3A60), I'm going to work on updating the design first(which is the task 1 on your list above @taoeffect )..!


> 1. Implementing a component for Type 2 errors (i.e. the markup and CSS)

EDIT: I also just noticed the self-removing scoped banner doesn't exist. I will work on creating it and add it to the design system first.

**Comment by taoeffect** [comment]
@SebinSong sounds good! You might want to have a look at the file `vError.js` for inspiration, as it shows how a self-inserting error message is done
