### ISSUE TITLE
"Light client" for storage-challenged environments (i.e. browsers)

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#691]
### Problem

Local storage on my browsers (especially mobile) will not let us store all of the log history.

### Solution

For non electron-type versions of the app, create a light client mode that discards the history. This may be as simple as not storing the history in the first place.

Edit: suggested solution should modify `shared/domains/gi/db.js` to do the following:

- Between [lines 67-68](https://github.com/okTurtles/group-income-simple/blob/master/shared/domains/gi/db.js#L67-L68), right before `return entry.hash()`, call a function that deletes the old entries from storage if we are a light client
- Implement the function that deletes the old entries
- Implement a `'gi.db/delete` selector that by default calls `'okTurtles.data/remove'`, and is [overwritten in `frontend/model/database.js`](https://github.com/okTurtles/group-income-simple/blob/master/frontend/model/database.js#L13-L17) to remove from localstorage

The reasoning for doing it this way instead of simply not storing it in storage in the first place is to preserve the useful logic checks that `'gi.db/log/addEntry'` performs.

**Comment by taoeffect** [comment]
This just got bumped in priority thanks to Apple.

https://ar.al/2020/03/25/apple-just-killed-offline-web-apps-while-purporting-to-protect-your-privacy-why-thats-a-bad-thing-and-why-you-should-care/

**Comment by corrideat** [comment]
I think I may have a different and simpler solution.

```patch
diff --git a/frontend/model/database.js b/frontend/model/database.js
index fd4a4b2..f4f36ce 100644
--- a/frontend/model/database.js
+++ b/frontend/model/database.js
@@ -13,7 +13,22 @@ const log = localforage.createInstance({
 sbp('sbp/selectors/overwrite', {
   'gi.db/get': key => log.getItem(key),
   // TODO: handle QuotaExceededError
-  'gi.db/set': (key, value) => log.setItem(key, value)
+  'gi.db/set': (key, value) => {
+    const headKeys = []
+    log.iterate((value, key) => {
+      if (key.match(/-HEAD$/)) {
+        headKeys.push(log.getItem(key))
+      }
+    })
+    Promise.all(headKeys).then((keysToPreserve) => {
+      log.iterate((value, key) => {
+        if (!keysToPreserve.includes(key)) {
+          log.removeItem(key)
+        }
+      })
+    })
+    return log.setItem(key, value)
+  }
 })

 // =======================
```

Essentially, instead of implementing a 'delete' function, the set function handles keeping only the head message. I was wondering if this works, or if I'm missing something.

(I was also wondering how to tell if a client is 'lightweight')

**Comment by taoeffect** [comment]
There are a few issues with that code:

1. `gi.db/get` and `gi.db/set` are intended to do what they say they'll do. Set and get. And they're intended to be overwritten. Adding any other behavior to them outside of "get" and "set" will cause DRY violations in the codebase.
2. The way this is written involves iterating over the entire log. There's no need to do that, it's far faster to simply delete the previous entries.

> (I was also wondering how to tell if a client is 'lightweight')

This can be a check to a global boolean constant that is set somewhere. For example, `okTurtles.data` is already used in the app with constants like `'API_URL'` (see `sbp('okTurtles.data/get', 'API_URL')`). The boolean value can be set however we want. For example it can be true by default and also influenced by the presence of a environment variable, and/or whether `NODE_ENV` is `'production'` or not, etc.

**Comment by corrideat** [comment]
Thanks, I think I'll go with the delete selector then.

> gi.db/get and gi.db/set are intended to do what they say they'll do. Set and get. And they're intended to be overwritten. Adding any other behavior to them outside of "get" and "set" will cause DRY violations in the codebase.

Point taken about overriding the meaning of `set` to do something more than setting. I'm not sure about the DRY violations, though, as it is already an overridden selector, which is the one intended for browsers. Do you have a situation in mind that could lead to repetition? (trying to understand the codebase and the impact of a change like this).

> The way this is written involves iterating over the entire log. There's no need to do that, it's far faster to simply delete the previous entries.

Something like `sbp('gi.db/delete', previousHEAD)`? That'd certainly be faster, although the iteration is likely over a few elements because of the delete.

**Comment by taoeffect** [comment]
> I'm not sure about the DRY violations, though, as it is already an overridden selector, which is the one intended for browsers. Do you have a situation in mind that could lead to repetition? (trying to understand the codebase and the impact of a change like this).

Ah - actually, you're right about that. The override was so small I mistook / misread it for the original implementation.

> Something like `sbp('gi.db/delete', previousHEAD)`? That'd certainly be faster, although the iteration is likely over a few elements because of the delete.

Yeah, I mean, even putting it in a loop until it returns `null` just to be sure we deleted everything, will in most cases only result in 1 or 2 iterations, because it's being done on every `addEntry`. So there's no room in the light client to create a long tail of old events.
