### ISSUE TITLE
Improve router usage after a group is created.

### ISSUE THREAD

**Issue by sandrina-p** [okTurtles/group-income#696]
### Problem

Context: https://github.com/okTurtles/group-income-simple/pull/679/files#r329122719

There was a weird rare false positive in a test failure in this step. Let me explain:

![image](https://user-images.githubusercontent.com/14869087/65779693-2798e980-e140-11e9-8564-3c88fd4ca0ae.png)

This view is visible for 1ms. It happens immediately after a user with a group logs in. How is that possible? Well...
Let's see the current conditions for each view:
- sidebar: isloggedIn and hasGroups
- welcomeGroup: isloggedIn

So, both conditions are indeed true.

If we look at the code, after the login happens, there's a tiny moment where we verify it the user has a group and then ask $router to redirect to `/dashboard`.
```js
// Login.vue#L91
await sbp('state/vuex/dispatch', 'login', { username, identityContractID })
if (this.$store.state.currentGroupId) {
  this.$router.push({ path: '/dashboard' })
}
```
That's the exactly moment where this interface (the screenshot) takes place in time.

For that reason, the condition to find "welcomeHomeLoggedIn" (L33) is positive. However, in the next millisecond, when we try to get the element again and assert the text, the element isn't there anymore because the $router has changed to `/dashboard`.

Based on this, it's a tricky task to get the correct element on the page in this moment. So I decided to change the assertions: if the login was successful, it means we won't display the login button anymore. That's it.

I think the ideal solution would be to move the welcome view (create/join group) to another router (ex: `/welcome`).  That would prevent this bug and we would still have better login assertions.

### Solution

Improve how we are using the router `/welcome` and how we present that to the users after a group is created.

cc @pieer and @taoeffect

**Comment by taoeffect** [comment]
@sandrina-p I think you have the best understanding of this issue out of everyone here so if it's alright I've tagged and assigned this issue to you. If you want to leave it as Up-for-Grabs feel free to unassign and re-tag the issue!

**Comment by pieer** [comment]
Probably going to tackle that next week @taoeffect but I'm not sure that creating the new router is the solution as per @mmbotelho request the welcome part is at the end of the popup group creation.

**Comment by taoeffect** [comment]
@pieer ok, then I've assigned it to you!

**Comment by SebinSong** [comment]
@taoeffect as to the '/welcome' route you mentioned [here](https://github.com/okTurtles/group-income-simple/pull/679/files#r330799728), it's actually not being used anymore and can be removed(I was the one who created it).
the group creation process is currently implemented through modal, so the url for 'the welcome confetti animation page' would be something like http://localhost:8000/app/?modal=CreateGroup&step=GroupWelcome right now. (it used to be, http://localhost:8000/app/welcome).

Do you think I need to make a pull request for removing it before someone starts working on this issue?

c.c. @sandrina-p

**Comment by taoeffect** [comment]
Copying my answer from Slack here:

> I think if it’s no longer being used then there’s no harm in submitting such a PR if you’d like!
