### ISSUE TITLE
Having issues running the site

### ISSUE THREAD

**Issue by reyesh** [okTurtles/group-income#70]
I ran

```
brew install node
npm install -g grunt-cli
```

but I still get the following error when running `grunt dev`

```
Running "watch" task
Waiting...
/usr/local/bin/node: bad option: -r
child exited with error code: 9
```

**Comment by taoeffect** [comment]
What OS do you have and what does `npm version` say?

Also, did you try every suggestion in [Troubleshooting](https://github.com/okTurtles/group-income-simple/blob/master/docs/Troubleshooting.md)?

**Comment by taoeffect** [comment]
Closing since no reply.
