### ISSUE TITLE
Create a welcome page for new members of a group

### ISSUE THREAD

**Issue by mmbotelho** [okTurtles/group-income#701]
### Problem
At the moment, we still don't have a substitute for the welcome page - the first page new members see when they join a new group. The current version looks like this:

<img width="669" alt="Captura de ecrã 2019-10-16, às 10 04 07" src="https://user-images.githubusercontent.com/22004566/66895840-5813cb00-effc-11e9-8eb3-a6a5a932fbc2.png">

### Solution
Update this page.

**Comment by mmbotelho** [comment]
Design for this task discussed and approved during the hackathon. 

**Figma link**
https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?node-id=2371%3A0

**Comment by taoeffect** [comment]
NOTE: it is good @mmbotelho designed it this way, since showing who the existing group members are in a group (to someone not-yet-in-the-group) might turn out to be a challenge, since most group information is encrypted.
