### ISSUE TITLE
Use fieldset to layout radio buttons (and anything else)

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#708]
### Problem

We are currently not laying out form fields with labels in an A11Y friendly way, [according to @sandrina-p.](https://github.com/okTurtles/group-income-simple/pull/705#discussion_r335817744)

### Solution

Go through the project, including the design system, and make sure that everywhere we have `label` tags for input fields, we are properly using fieldset and placing the input field inside the label, as @sandrina-p describes here: https://github.com/okTurtles/group-income-simple/pull/705#discussion_r335817744

**Comment by sandrina-p** [comment]
I verified all the inputs with type radio and checkbox. All of them are implemented correctly. Closing this.
