### ISSUE TITLE
Iterate "Add members" UX

### ISSUE THREAD

**Issue by mmbotelho** [okTurtles/group-income#709]
### Problem

When a user clicks on the "Add more" link, the modal is pushed up (as expected), and the content moves. This makes this interaction a bit awkward.

### Solution

As discussed offline in the Hackathon, we would like to have a similar behaviour to what we had previously, where you can use 1 input to add all members.

_Note: This is a low priority task and can be done after the prototype is live_

**Comment by mmbotelho** [comment]
What we will do:
- Margarida will re-design this UX now (hackathon);
- @sandrina-p  will wait for the design;
- When Margarida is done, Sandrina is going to implement it

cc @taoeffect

**Comment by mmbotelho** [comment]
![Add_members](https://user-images.githubusercontent.com/22004566/67144789-8525df00-f283-11e9-8c6c-def42fb7241e.png)

**Comment by taoeffect** [comment]
Yes, but just to be clear, that list of names does not represent input fields but text fields, and the final design may or may not need the 'x' to be inside of the border

**Comment by mmbotelho** [comment]
@taoeffect @sandrina-p : 

After looking at this with more attention, I realized that it doesn't fix our problem at all:

> When a user clicks on the "Add more" link, the modal is pushed up (as expected), and the content moves. This makes this interaction a bit awkward.

The new layout (see the image posted on my previous comment) has exactly the same issue. So I think we need to find a new solution.

**Comment by mmbotelho** [comment]
@sandrina-p how difficult would it be to keep the modal static - I mean, making it only grow downwards? Instead of upwards and downwards

**Comment by mmbotelho** [comment]
Change of plans - we are going to stick with the previously designed version:

<img width="902" alt="Captura de ecrã 2019-10-20, às 08 29 23" src="https://user-images.githubusercontent.com/22004566/67155233-bd74fe00-f313-11e9-9379-ba36da683b7e.png">

cc @taoeffect @sandrina-p
