### ISSUE TITLE
Make i18n.vue handle router-link correctly

### ISSUE THREAD

**Issue by SebinSong** [okTurtles/group-income#721]
* Problem
to understand the context, please refer to this comment [here ](https://github.com/okTurtles/group-income-simple/pull/717#discussion_r336729208) and the `//TODO:` comment in the code.
When `<router-link></router-link>` is passed to `18n.vue` as a part of the `html` attribute, It doesn't work because apparently it doesn't get transformed into `<a></a>` tag (as the final(?) outcome) as you can see in the screenshot.

![router-link](https://user-images.githubusercontent.com/17641213/67144200-9ea14800-f2d0-11e9-8922-9920aa7c3da1.png)

Logic for `i18n.vue` to handle it properly needs to be added.

**Comment by taoeffect** [comment]
Closed by #727
