### ISSUE TITLE
Update proposals widget UI

### ISSUE THREAD

**Issue by mmbotelho** [okTurtles/group-income#741]
### Problem
The title + description + proposal order we had on the proposals dashboard widget did not make a lot of sense.

### Solution
Move the description of the proposals below the actual proposals. I also took this chance to improve the spacings and the mobile UI for this widget (both for the dashboard and the Proposals page). I also added a "Read more" link, so when users add a very long description, it does not "break" the interface.

**Figma:**
https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?node-id=3043%3A524

**Comment by sandrina-p** [comment]
@mmbotelho this will be done at #747. Once it's ready for your review, I'll let you know.
