### ISSUE TITLE
Improve experience when several users have the same display name

### ISSUE THREAD

**Issue by mmbotelho** [okTurtles/group-income#745]
### Problem

As @pieer mentioned during the hackathon, if more than one user has the same display name, it can be very difficult for users to use the app (e.g.: Margarida needs to pay $20 to Pierre and $30 to Pierre).

### Solution

Research and figure out a way of helping users distinguish each other.

**Comment by dotmacro** [comment]
#538 is related because it would be helpful if all users had different avatars (especially if they have similar/identical display names).

**Comment by mmbotelho** [comment]
As @dotmacro mentioned, having different default avatars helps with this already. I'm closing this one, but feel free to re-open if you believe it's not!
