### ISSUE TITLE
Explain the difference between Containers and Components

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#753]
### Problem

Our [Style Guide](https://github.com/okTurtles/group-income-simple/blob/master/docs/Style-Guide.md) doesn't explain what the difference between the "containers" and "components" folders is.

### Solution

- Update the docs to explain the difference
- Audit our files to make sure all files are in the right folder, and move+refactor as necessary

**Comment by sandrina-p** [comment]
This is a good point @greg. There are some components that should be at `containers` instead of `components`. After we close #747 and #724, I can tackle this.
