### ISSUE TITLE
Speed up loading by putting almost all pages into lazyLoadedView

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#754]
### Problem

The main bundle should be split up into more files so that the initial page load goes faster.

### Solution

- Put most pages into `lazyLoadedView.js`, but leave a skeleton that lets the user know components are being loaded
- Use @mmbotelho's designs to create the loading skeleton

**Comment by sandrina-p** [comment]
Just for reference, you can [find the designs at Figma](https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?node-id=5886%3A0)

**Comment by mmbotelho** [comment]
This is also related to #562

**Comment by pieer** [comment]
Implemented here: https://github.com/okTurtles/group-income-simple/pull/948
