### ISSUE TITLE
Uniformize invitation link display across the app 

### ISSUE THREAD

**Issue by sandrina-p** [okTurtles/group-income#756]
# Problem

Recently @mmbotelho designed a better invitation link display with "click-to-copy" functionality. That was implemented only in the Invite Links table (#664).

<img width="653" alt="image" src="https://user-images.githubusercontent.com/14869087/68019620-38370500-fc94-11e9-924c-7b6cbe3918f5.png">

We need to also implement it at:
- [Modal "Add members"](https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?node-id=2335%3A1437) when the group has less than 3 members.
- [Proposal widget](https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?node-id=1579%3A202) when an invite member proposal is accepted.

### Solution
- Implement the component in the missing places.
- Add a usage demo to the Design System

**Comment by sandrina-p** [comment]
@SebinSong, I wonder if you would like to pick up this issue. It would be a great way for you to practice your skills when it comes to create reusable components. If you want to, feel free to assign this issue to yourself.

**Comment by SebinSong** [comment]
@sandrina-p I would definitely love to work on this issue.
