### ISSUE TITLE
Create a recovery page

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#761]
### Problem

I have experienced very strange problems with the vuex state, possibly caused by accidentally clicking the wrong thing in the VueDevTools, where the vuex state is completely out of sync, and contract submodules are missing mutations. Messages like the following appear in the console:

```
[vuex] unknown mutation type: 21XWnNVY3JQGbGqNXyCwTXebDhKTRDYhmtN5Wh3mZeYsfbLChT/processMessage
```

### Solution

Part of the problem is that the error message above is a `console.error` message from vuex (when it should be an exception). I've already opened an issue in the Vuex repo for that. However, why that's happening to begin with is the real problem, and it's unclear that at this point catching the exception would fix anything, since the exception means that the vuex module hasn't been registered (even though it appears to be registered in the vuex dev tools!!).

For this particular error we can check for it by looking at the vuex internals themselves:

```js
Store.prototype.commit = function commit (_type, _payload, _options) {
    var this$1 = this;

  // check object-style commit
  var ref = unifyObjectStyle(_type, _payload, _options);
    var type = ref.type;
    var payload = ref.payload;
    var options = ref.options;

  var mutation = { type: type, payload: payload };
  var entry = this._mutations[type];
  if (!entry) {
    if (process.env.NODE_ENV !== 'production') {
      console.error(("[vuex] unknown mutation type: " + type));
    }
    return
  }
```

Here we can ourselves check make sure that `store._mutations[type]` exists, and if it doesn't, take steps to recover somehow (or take them to the recovery page).

The recovery page itself should have an option to unregister all of the vuex modules for every subscribed contract, and re-sync/re-register everything.

**Related issues**

- #432 - state machine

**Comment by mmbotelho** [comment]
@taoeffect will this page be seen by users or is this just a tool for development purposes?

I'm wondering if this is the issue I should take on this week (the recovery page for when users encounter a critical error and need to recover from that), or if I should create a different one.

**Comment by taoeffect** [comment]
@mmbotelho Yes users will see this page, they'll be automatically taken to it in certain situations.

**Comment by mmbotelho** [comment]
@taoeffect I have a rough draft of what I believe needs to be on this page. Let me know what you think! https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?node-id=10216%3A0

I need some help with the copy there, I'm not sure what the right words are!

**Comment by taoeffect** [comment]
@mmbotelho Great job! I left a comment. My main focus after seeing that is getting the structure/layout right, and then allowing that structure to help guide the copy. See Figma for details!

**Comment by mmbotelho** [comment]
I believe this was already implemented by @sandrina-p. Can we close it?

**Comment by sandrina-p** [comment]
No @mmbotelho. I implemented the Applications Logs page (#595), this one is still needed.

**Comment by mmbotelho** [comment]
Oh I thought you implemented the recovery page as well 🤦 nevermind then!

**Comment by taoeffect** [comment]
This "unknown mutation type" error no longer occurs, so the issue problem description isn't up-to-date anymore.

Also, PR #1224 significantly changed how errors are handled now, so even though we should create the ability to recover the state if things go wrong, the chance of that ever happening in the first place is now much lower (thanks also to #1308). Also, some additional thought needs to be put into writing a better and more up-to-date issue & solution description. So I'm closing this issue for now.
