### ISSUE TITLE
Unable to communicate with server(on trying to log in) using Ngrok

### ISSUE THREAD

**Issue by SebinSong** [okTurtles/group-income#780]
### Problem

Trying to test `grunt dev` server on mobile phone using [Ngrok](https://ngrok.com/) produces some issues(it appears that it fails to communicate with the server upon requests).

1) When trying to log in, with an account already created by other device(PC).

![ngrok_unable_to_login](https://user-images.githubusercontent.com/17641213/69138363-62f1dc00-0b23-11ea-86cc-464f10657317.jpg)

2) When trying to sign up on mobile device.

![ngrok1](https://user-images.githubusercontent.com/17641213/69138680-fdeab600-0b23-11ea-8c23-0b22510d6769.jpg)

P.S.
@taoeffect I tried the other way you advised me first(connecting the phone with the same wifi as the laptop and then trying http://ipv4_address:8000 which worked this time), and also was presented with the same error messages.

### Solution

Close #852

**Comment by taoeffect** [comment]
Closing this might require sending all communication over a single port, meaning:

- Serving static files over the same port as the API, and using the URL to switch on it
- Same goes for web sockets (will need to research this more)
