### ISSUE TITLE
Finish Group Settings page

### ISSUE THREAD

**Issue by sandrina-p** [okTurtles/group-income#792]
### Problem

The **Group Settings** page has an incomplete layout and it's not functional yet.

### Solution
- [x] 1. Update the page following the [design specs](https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?node-id=123%3A1378)
- [x] 2. Group Profile (first card) - add logic
- [x] 3. Leave Group - add logic
- [ ] 4. ~Delete Group - add logic~ not needed for the prototype

**Comment by sandrina-p** [comment]
I'll pick this issue and address points 1 and 2.

**Comment by sandrina-p** [comment]
While developing #823, I realized something:

It doesn't make sense to show "Leave group" and "Delete Group" at the same time. We can only Leave the group if there are more members. And we can only delete the group if we are the only member.

@mmbotelho, can you review the UX of this part of the page?

**Comment by mmbotelho** [comment]
@sandrina-p done!

https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?node-id=9720%3A0
