### ISSUE TITLE
Update radio buttons UI and create checkbox component

### ISSUE THREAD

**Issue by mmbotelho** [okTurtles/group-income#794]
# Problem

I have updated the UI for the radio buttons and created a new UI for checkboxes that will be needed for the payments page. The change to the radio buttons was made so that the radios and checkboxes:
- Have more contrast;
- Have more distinct selected / not selected states;
- Work well with each other.

I have also added the focused / active states for both the checkbox and radio components to our Figma design system.

# Solution

- [ ] Update radio buttons UI;
- [ ] Implement new checkbox component;
- [ ] Make sure that the active / focused states for both components are according to design.

You can find the [relevant design system documentation here](https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?node-id=48%3A4) (should scroll down a little, it's close to the end of the artboard). Let me know if you have any questions!

**Comment by mmbotelho** [comment]
FYI @taoeffect : I am removing my assignment because my part is already done :) what's left now is to implement!

**Comment by sandrina-p** [comment]
I'm picking up this. Should have a PR in a few hours :)
