### ISSUE TITLE
Create a way to see other group members profile

### ISSUE THREAD

**Issue by mmbotelho** [okTurtles/group-income#798]
### Problem

There should be a place where group members can see others:
- Payment information;
- Bio;
- Date they joined the group;
- [Action] Send message;
- [Action] Create proposal to remove member.

### Solution

Figure out how, where and when this information is displayed:
- Add a way for users to preview their profile. Probably somewhere in the User Settings;
- [Desktop] show this information on-hover;
- [Mobile] use a drawer component;

What I have in mind is very similar to the way Slack does it. 

Next steps:
- Create mockups and get feedback!

**Comment by sandrina-p** [comment]
Here's the [Figma mockups](https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?node-id=9671%3A87389) as reference.
