### ISSUE TITLE
Explain header styling in CSS section of Style Guide

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#805]
### Problem

From [this conversation](https://github.com/okTurtles/group-income-simple/pull/793/files#r369806131):

<img width="588" alt="Screen Shot 2020-01-23 at 2 08 03 PM" src="https://user-images.githubusercontent.com/138706/73028163-d2b56900-3de9-11ea-94c1-b14086dcd8ea.png">

It might not be clear to new contributors how and when to use `.is-title-X` with header tags.

### Solution

In our Style Guidelines CSS section, explain:

- How and when to use `.is-title-X` with header tags
- Why we do it this way

**Comment by sandrina-p** [comment]
I edited the comment a minute later. [Here's an explanation for it](https://stackoverflow.com/a/19166926/4737729). W can add the explanation on our Design System, I think it's the best place for something so specific

**Comment by taoeffect** [comment]
OK, sure, feel free to include that link so that you don't have to give the long explanation. I think it would be useful to include that link in our Style Guidelines too. Just a sentence would be sufficient if it includes that link.

**Comment by sandrina-p** [comment]
@taoeffect I did this directly at #793, you can review it there, it's the last commit.
