### ISSUE TITLE
Fix spacing between cards on dashboard

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#812]
### Problem

See screenshot:

<img width="797" alt="Screen Shot 2020-01-28 at 4 23 27 PM" src="https://user-images.githubusercontent.com/138706/73317619-8a33ec00-41eb-11ea-81a7-d49d46b15976.png">

### Solution

The gaps between the contributions widget and the proposals needs to be adjusted to match the designs.

**Comment by sandrina-p** [comment]
I'll fix that on my next PR and link it to here :)
