### ISSUE TITLE
Hitting enter twice fast in Signup form causes console exception

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#816]
### Problem

When signing up a user, hit the enter key twice really fast and you'll get this in the console:

<img width="1292" alt="Screen Shot 2020-01-29 at 1 22 33 PM" src="https://user-images.githubusercontent.com/138706/73398647-b78ba300-429a-11ea-8dc9-3ee7ed836b73.png">

### Solution

Go through not just the SignupForm.vue, but all the other forms and make sure that this is fixed in all of them.

**Comment by sandrina-p** [comment]
#802 is related to this, we need a loading state on the button when the internet is slow.
But until then, I fixed it with code only. The fix at #817

Note: Keep in mind that this can happen in **any** action. create a group, create a proposal, vote in a proposal, etc... I suggest when #802 is designed, to review those places and prevent this from happening.
