### ISSUE TITLE
Make group description optional

### ISSUE THREAD

**Issue by mmbotelho** [okTurtles/group-income#821]
### Problem

At the moment, the group description is a mandatory step. The problem with this is:
- It's not vital information;
- It can add friction when creating a group;
- Users might want to add a description in some other moment other than the group creation.

### Solution

- Make the group description step optional on the group creation flow;
- Add an empty state to the dashboard sidebar to prompt users to add a description, if they didn't on the group creation flow.

**Comment by mmbotelho** [comment]
Optional group description, on the group creation: 
<img width="825" alt="Captura de ecrã 2020-02-15, às 20 28 43" src="https://user-images.githubusercontent.com/22004566/74594015-d24b6f00-5031-11ea-99d6-4a0c8533b070.png">

Empty state for the dashboard sidebar, when the group has no description:
<img width="231" alt="Captura de ecrã 2020-02-15, às 20 28 26" src="https://user-images.githubusercontent.com/22004566/74594024-e5f6d580-5031-11ea-9333-d5481073bfa6.png">

**Comment by dotmacro** [comment]
Mostly just curious: Will the app accept any group description? (e.g. spaces, punctuation/emoji with no other characters)

**Comment by taoeffect** [comment]
@dotmacro I think so. There will be limits to prevent XSS attacks, but beyond that I think anything in the Unicode set should be OK.
