### ISSUE TITLE
Upgrade us to Cypress 4.0.1 or greater

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#826]
### Problem

We currently cannot use Cypress with Firefox Developer Edition because we're running an outdated version of Cypress.

### Solution

Update our Cypress version and update our npm scripts and anything else (e.g. Gruntfile.babel.js, if needed) based the relevant instructions at:

- https://cypress.io/blog/2020/02/06/introducing-firefox-and-edge-support-in-cypress-4-0/
- https://docs.cypress.io/guides/guides/cross-browser-testing.html
- **Migration guide:** https://docs.cypress.io/guides/references/migration-guide.html#Migrating-to-Cypress-4-0

**Comment by sandrina-p** [comment]
I can do this during next week, I think it's an easy update ;)

**Comment by sandrina-p** [comment]
Update: There are some problems with the current version (See PR #829). Once those are addressed by Cypress community, we can take a look at this again.

**Comment by snowteamer** [comment]
Cypress is now at 6.2.0, we probably could take a look at this again
