### ISSUE TITLE
Removing a member from a group - detect what identity contracts should be deleted

### ISSUE THREAD

**Issue by sandrina-p** [okTurtles/group-income#828]
### Problem

When removing a member from the group (#560), their related identity contracts should also be removed from the state, based on this condition:

- If we are the member being removed, we need to remove the contracts of all the other members of the group.
- If we are another member of the group, we need to remove the contract of the member being removed. 

**However,** we can only remove an identity contract if we don't have any other type of connections with this member (ex: another group in common or a chat message).

> Imagine if a friend of ours gets kicked out of a group, but we have an open DM chat with them. We need to be subscribed to their identity contract still if the chat is outside of the group. Otherwise, we won't be able to see their profile picture or their displayName. Basically, if we're interacting with someone at all in any way, we need to keep their identity contract in the state.

### Solution

Implement an algorithm that detects this relationship between identity contracts and use it to conditionally remove an identity contract after a member is removed from a group.

**Comment by taoeffect** [comment]
I suspect solving this will require adding the concept of manual reference counting to the contract system, and storing that reference count in `state.contracts`, which currently stores the HEAD and the contract type only.
