### ISSUE TITLE
Replace Sequelize with Knex-API compatible ORM?

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#83]
Every nodejs ORM [fails at SQL](https://github.com/okTurtles/group-income-simple/issues/82), but a few of them use Knex to build queries. Knex can be [swapped out for an API-compatible can version of node-sql](https://github.com/okTurtles/group-income-simple/issues/82), giving us at least 3 ORM options to choose from that use SQL correctly.

Alternatively, Knex could be modified to make use of parameterized queries.
- [x] Figure out which of [the three](https://github.com/okTurtles/group-income-simple/issues/82#issuecomment-223443658) we should switch to.
  - [Bookshelf](http://bookshelfjs.org) seems to be the winner, with a decent community and a fairly similar API to Sequelize.
- [ ] Switch to it.
#### Alternatives

There are at least [two other alternatives](https://github.com/okTurtles/group-income-simple/issues/82) to using an ORM based on the Knex-API:
- Modify Sequelize to use node-sql
- Create our own ORM on top of node-sql

**Comment by taoeffect** [comment]
Closed in favor of #85.

**Comment by manuelfink** [comment]
@taoeffect what's your reason for changing away from sequelize to knex/bookshelf?  I'm just getting started and evaluate both not being sure which to use.

**Comment by taoeffect** [comment]
> @taoeffect what's your reason for changing away from sequelize to knex/bookshelf? I'm just getting started and evaluate both not being sure which to use.

First sentence of this issue:

> Every nodejs [ORM fails at SQL](https://github.com/okTurtles/group-income-simple/issues/82), [...]

First sentence of link:

> See [rant](https://twitter.com/taoeffect/status/738478839148339200).

**Comment by manuelfink** [comment]
I do like the idea of interchangeable orm's though, which make me prefer knex anyhow. 

However your argument "fails on SQL" is still unclear to me. In your tweets you write about prepared statements. Sequelize implements prepared statements through "replacements". Little bit unclear term, but reading the [docs](http://docs.sequelizejs.com/en/latest/docs/raw-queries/) it seems to be the same or?

Are there any other reasons prefering knex?

**Comment by taoeffect** [comment]
> Sequelize implements prepared statements through "replacements". Little bit unclear term, but reading the docs it seems to be the same or?

If I wanted to do raw queries I wouldn't be looking for an ORM.

Knex's code/tests indicated to me that it allows non-parameterized queries. Any ORM or SQL library that allows non-parameterized queries is written by someone who doesn't know what they are doing.
