### ISSUE TITLE
Implement new toggle component

### ISSUE THREAD

**Issue by mmbotelho** [okTurtles/group-income#832]
### Problem

Some of our new pages are using a new component - a toggle!

### Solution

Implement this component according to the [specifications on Figma](https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?node-id=48%3A4). Please note that whatever label is used along with the toggle, should activate it as well (same as checkboxes and radio buttons). 

Let me know if you have any questions!

**Comment by sandrina-p** [comment]
I'll pick it up during this week
