### ISSUE TITLE
Fix missing border on combo inputs

### ISSUE THREAD

**Issue by mmbotelho** [okTurtles/group-income#833]
### Problem

All combination inputs (except the `.input-shifted`) have a missing gray border when they are focused, but not hovered:

<img width="1047" alt="Captura de ecrã 2020-02-13, às 12 31 29" src="https://user-images.githubusercontent.com/22004566/74430901-16861600-4e5e-11ea-9809-c7dd5c41b0f2.png">

### Solution

Keep the gray border when the inputs are focused but not hovered.

**Comment by taoeffect** [comment]
Closed in #862
