### ISSUE TITLE
Make group activity history private

### ISSUE THREAD

**Issue by sandrina-p** [okTurtles/group-income#839]
## Problem

When visiting the `/join` page to join a group through an invitation link, the group activity history is public. In this example, we can see the group already invited 2 members and proposed to remove one of them.
 
![image](https://user-images.githubusercontent.com/14869087/74663279-5e28dc80-5193-11ea-8294-c42bcc9b31af.png)

### Solution

Keep the group activity and any other sensitive information private from people outside of the group.

**Comment by taoeffect** [comment]
Yep, this will be closed once #92 and #603 are closed. 👍
