### ISSUE TITLE
Don't need IS_CONSTRUCTOR in Contract.js

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#845]
### Problem

Bit of overengineering [here](https://github.com/okTurtles/group-income-simple/blob/f180ea13c68d837ef7f19db285e883186114141b/frontend/model/contracts/Contract.js#L39):

```js
        } else if (!IS_CONSTRUCTOR.test(`${action}/create`)) {
          throw new Error(`contractID required when calling '${action}/create'`)
        }
```

`IS_CONSTRUCTOR` is only used once, right there, and a simple `!== contract.name` would have sufficed.

### Solution

Remove `IS_CONSTRUCTOR` and replace that code with:

```js
        } else if (action !== contract.name) {
          throw new Error(`contractID required when calling '${action}/create'`)
        }
```

@sandrina-p assigning to both of us, whoever gets to it first! (Likely you with your Remove Member PR)

**Comment by sandrina-p** [comment]
Fixed at #823 ;)
