### ISSUE TITLE
Income Details - Add Payment Info

### ISSUE THREAD

**Issue by sandrina-p** [okTurtles/group-income#846]
### Problem

We have a new way for users to introduce their payment info, but it's not implemented yet.

![image](https://user-images.githubusercontent.com/14869087/75098561-8eb3b080-55af-11ea-8782-f143b3ee0699.png)

### Solution

Implement it based on [Figma mockups](https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?node-id=2763%3A3352).

**Comment by sandrina-p** [comment]
@taoeffect, I was studying what's the best place to add the member payment info and this is my suggestion:

Under `currentGroupState.profiles[username]` add object `paymentMethods` with key:value corresponding to the UI (method: description), example:

```
{
  paypal: 'name@mail.com',
  bitcoin: 'bitcoin_hash_the_user_did_past'
}
```

What do you think?

**Comment by taoeffect** [comment]
@sandrina-p that seems perfectly reasonable to me, the only thing I would consider changing is making the value for each of the payment method keys also an object instead of a string. The reason is to future-proof things, when we will need to add more info to each payment method.
