### ISSUE TITLE
Rename 'name' property in Identity contract to 'username' or delete it

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#848]
### Problem

It's appeared a few times now in the code that the global profile's username is stored in the `name` property, and it's caused confusion in a few PRs where this was viewed as different from `username`. In fact the two are the same, and `username` should be preferred. It's not clear that we need the one in the global profile, and if we do it should be renamed to `username` to avoid confusion.

### Solution

One way of guaranteeing that they're the same is to simply remove the `name` property entirely, and rely on the namespace mapping (that is what in fact gets us access to the identity contract in the first place) for the username. This might be the best approach, as it means we don't need to write any code to keep the two in sync.

However, if for some reason there is a reason to keep the username in the identity contract as a property, then at the very least it should be renamed from `name` to `username` to make it clear that the two are the same.

**Comment by sandrina-p** [comment]
I can do this.

Another thing I noticed is how we say "identity contract" and "user contract" and they mean the same thing. We actually have 2 files: `contracts/identity.js`(`gi.contracts/identity/*`) and `actions/user.js` (`gi.actions/user/*`)

Which one should we stick with? Perhaps `identity` because most of the code uses it.

**Comment by taoeffect** [comment]
> Which one should we stick with? Perhaps identity because most of the code uses it.

Yeah agreed... feel free to do that in another PR
