### ISSUE TITLE
Payments.vue: hovering the selectcombo the icon disappears

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#861]
### Problem

Copying from [here](https://github.com/okTurtles/group-income-simple/pull/847#discussion_r391081221):

> Why did you remove this z-index?
> 
> I also noticed when hovering the selectcombo the icon disappears:
![image](https://user-images.githubusercontent.com/14869087/76437372-626ea100-63b1-11ea-9177-9d1acd2f4cbb.png)

### Solution

Fix.

**Comment by sandrina-p** [comment]
I can fix this at the same time I fix #833 and #831

**Comment by taoeffect** [comment]
Closed in #862
