### ISSUE TITLE
Design way to submit a generic proposal to vote on

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#867]
### Problem

I do not think we have any designs for submitting generic text-based proposals to the group to vote on.

I think this was planned for the chat maybe? But I see no reason why we can't add them to our existing proposals component as well. There is plenty of room for that.

### Solution

Design a way to submit a generic text-based proposal that group members can vote Yes/No on. In the future, we might implement multiple-choice voting as well, but for now, let's just do a simple yes/no proposal.

**Comment by leihla** [comment]
Here's a proposal to creating new generic proposals. The behaviour is the same as other proposal creation, in a modal.

- User must give a title to the proposal, we should impose a character limit to this field (115)
- Description is optional
- Other users are able to vote YES/NO on the proposal
- Generic proposal icon shows on dashboard, accompanied by the avatar of the user who proposed it

Please check figma file here: https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?node-id=23051%3A213049

---
![1  Generic Proposal](https://user-images.githubusercontent.com/158178/173551395-6657e5d2-fc84-4fdd-9cfd-e3a935c7418d.png)
![2  Generic Proposal](https://user-images.githubusercontent.com/158178/173551404-cdb15003-b248-456a-9b69-5f4a401dccfe.png)
![3  Generic Proposal](https://user-images.githubusercontent.com/158178/173551410-0320e72e-d90c-44ca-8255-4fc79c99d435.png)
![11  Dashboard](https://user-images.githubusercontent.com/158178/173551413-18786b4c-efca-459b-a6ae-0ae61972e4a1.png)


--- 

@taoeffect can you assigned this to the correct person?

**Comment by taoeffect** [comment]
Closing in favor of #1300 and #1303.
