### ISSUE TITLE
Add Loading ButtonSubmit everywhere it's needed

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#868]
### Problem

With #854 merged we have a new `ButtonSubmit` component thanks to @sandrina-p that turns into a loading symbol on form submission of asynchronous actions.

#854 added this component in some places but not everywhere. For example, it doesn't exist on the voting buttons for voting on proposals.

### Solution

Figure out, on a case-by-case basis, how this button should be integrated in all remaining submit forms where asynchronous network-based actions take place.

**Comment by sandrina-p** [comment]
Cc @mmbotelho. When ready, share here the figma link for proposals update with the error and loading states

**Comment by mmbotelho** [comment]
### Update:
- [Added the loading state to our Figma DS (all possible buttons);](https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?node-id=48%3A26)
- [Added example of an error when voting on a proposal;](https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?node-id=11049%3A56)

Note: There's no success banner when a proposal is voted on, the success is the "You voted yes. Change" message.
