### ISSUE TITLE
Implement sort of group members list

### ISSUE THREAD

**Issue by mmbotelho** [okTurtles/group-income#869]
### Problem

At the moment, the group members list, on the Dashboard sidebar as well as the "Group Members" page, are not sorted correctly.

### Solution
The sort should be, in both places:
1. Pending members (from A to Z);
2. New members (from A to Z);
3. All others (from A to Z).

**Comment by sandrina-p** [comment]
Additional note: The sort should give preference to the `displayName` first and then the `username`. Example: `@user1` with a display name `Aba` should come before `@user1`.
![image](https://user-images.githubusercontent.com/14869087/79155650-5d927800-7dc9-11ea-93ab-d31486fea46d.png)
