### ISSUE TITLE
Implement Dark Theme 🦹‍♂️

### ISSUE THREAD

**Issue by mmbotelho** [okTurtles/group-income#872]
## Problem

We don't have a dark theme implemented yet!

## Solution

In most cases, swapping the color variables will make components ready to be used in dark mode. [See color variables in light and dark theme (screenshot below).](https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?node-id=3210%3A32947). 

The Figma design system has all the components in dark and light theme, so if anything is looking weird as you implement, please double check there. 

<img width="460" alt="Captura de ecrã 2020-03-23, às 18 11 10" src="https://user-images.githubusercontent.com/22004566/77348712-d43fd680-6d31-11ea-8b04-0b585994b23c.png">

## Exceptions:
- Content cards dont have a box-shadow;
<img width="200" alt="Captura de ecrã 2020-03-23, às 18 18 23" src="https://user-images.githubusercontent.com/22004566/77349323-c50d5880-6d32-11ea-911e-68d9cc2d3799.png">

- The modal overlay color is the same on the light and dark themes;
<img width="400" alt="Captura de ecrã 2020-03-23, às 18 21 06" src="https://user-images.githubusercontent.com/22004566/77349573-1e758780-6d33-11ea-890a-9623b1cf960d.png">

- The info, warning, danger and success banners' have completely different colors in the dark theme. [Check them out here](https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?node-id=48%3A60)
<img width="400" alt="Captura de ecrã 2020-03-23, às 18 28 10" src="https://user-images.githubusercontent.com/22004566/77350208-0fdba000-6d34-11ea-9ba4-0c10e05acf23.png">

- The white on checkboxes, radio buttons and toggles remains white in the dark theme;
- Checkboxes, radio buttons and toggles also have custom colors (the white is not swapped). [You can see them here](https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?node-id=48%3A4).
<img width="400" alt="Captura de ecrã 2020-03-23, às 18 31 35" src="https://user-images.githubusercontent.com/22004566/77350552-97291380-6d34-11ea-84f8-761ac79238ff.png">

- The tips component has a different background color in the dark theme. [Check the Figma here](https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?node-id=2870%3A7);
<img width="400" alt="Captura de ecrã 2020-03-23, às 18 36 21" src="https://user-images.githubusercontent.com/22004566/77351084-377f3800-6d35-11ea-8f7f-82b03b5b3f49.png">

- The illustrations we use accross the app have completely different colors. [You can see them here](https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?node-id=1876%3A17778)

- Buttons are lighter when hovered / active, unlie the light theme, where they are darker. [You can see it here](https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?node-id=48%3A26)
<img width="400" alt="Captura de ecrã 2020-03-23, às 18 39 10" src="https://user-images.githubusercontent.com/22004566/77351386-9a70cf00-6d35-11ea-8075-7837294fd94b.png">

**Comment by sandrina-p** [comment]
Wow, thanks for the detailed mockups and explanations for each exception! It will be so much fun to implement it. (not saying it will be me, perhaps @pieer is excited to do it too!)

**Comment by taoeffect** [comment]
@mmbotelho continuing from your comment here: https://github.com/okTurtles/group-income-simple/pull/911#pullrequestreview-404910618

I agree that some of the colors are off. I liked all of the shades of black/grey, so for me it was only/mostly the blue and green buttons that seemed a bit off:

<img width="674" alt="Screen Shot 2020-05-06 at 4 01 12 PM" src="https://user-images.githubusercontent.com/138706/81236911-20c63500-8fb3-11ea-9789-cc027c3a37ea.png">

I feel like both the color of the button and the color of the text inside of it are off somehow.
