### ISSUE TITLE
Bug 1 in RULE_DISAGREEMENT

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#876]
### Problem

```js
    if (totalAgainst >= threshold) {
      return VOTE_AGAINST
    }
    // consider proposal passed if more vote for it than against it and there aren't
    // enough votes left to tip the scales past the threshold
    return totalAgainst + absent < threshold && totalFor > totalAgainst ? VOTE_FOR : VOTE_UNDECIDED
```

In a group of 10 people, with a threshold of 2, if 8 people vote for a proposal, and 0 vote against it, then the proposal should pass upon expiry.

However, in the way it's currently written (shown above), it will remain `VOTE_UNDECIDED`, which equates to it not passing.

### Solution

Fix.

EDIT: but make sure there's at least one `VOTE_FOR` vote before passing. If there are 0 votes for or against, the result should be `VOTE_UNDECIDED`.

**Comment by sandrina-p** [comment]
Fixed at #893
