### ISSUE TITLE
UI doesn't support VOTE_INDIFFERENT

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#878]
### Problem

Currently you can only vote "yes" or "no" on a proposal, but cannot indicate that you don't care. A non-vote is not the same as a vote of not caring. Our `RULE_THRESHOLD` supports the math for handling `VOTE_INDIFFERENT`, but our UI does not.

### Solution

Implement in UI a way to indicate indifference about the outcome of a proposal.

**Comment by mmbotelho** [comment]
@taoeffect isn't this the same as issue #596 ?

**Comment by taoeffect** [comment]
@mmbotelho yep, you're right, it's effectively the same but focuses more on some details that #596 left out. In truth I totally forgot that was an existing issue. I'll close this but copy its text over.
