### ISSUE TITLE
Testing across different browsers/devices

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#88]
## Problem

Browsers render things differently.
## Solution
- https://www.browserstack.com/
- See also notes from #22

**Comment by dotmacro** [comment]
Screen readers "render" things differently than traditional visual browsers. We should also consider accessibility when testing (e.g. can the keyboard access all elements?). Should this be a separate issue?

**Comment by taoeffect** [comment]
This issue isn't an accessibility issue. You can open another issue for accessibility (although I think we might have one already open for that; can't find it now though).

**Comment by dotmacro** [comment]
We have an accessibility Milepost, which needs all relevant issues. Just checking whether I should include this one, or make another. Thanks :)
