### ISSUE TITLE
Fix/improve our form validation situation

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#89]
## Problem

Forms need to be validated. Most form validation libraries are bloated. It would also be nice to have one that worked well with Vue.
## Solution

Use a custom version of vue-form.

Move a bunch of [this stuff](https://github.com/okTurtles/group-income-simple/blob/5d84057b93527236897fbfcbea22dc9346d185d1/frontend/simple/views/SignUp.vue#L77-L114), which is meant to make vue-form usable without having to add `v-model`'s to all the input elements, into [our fork of `vue-form`](https://github.com/taoeffect/vue-form).
- [ ] Make `vue-form` use standard vanilla `addEventListener`s (as we do [here](https://github.com/okTurtles/group-income-simple/blob/5d84057b93527236897fbfcbea22dc9346d185d1/frontend/simple/views/SignUp.vue#L81-L101))
- [ ] Make it so that we don't even need a `formHook`
- [ ] And so that `formData` isn't needed either
- [ ] Merge [other useful PRs](https://github.com/fergaldoyle/vue-form/pulls) into [our fork](https://github.com/taoeffect/vue-form)
- [ ] Submit PR to `vue-form`

**Comment by taoeffect** [comment]
Another possibility is using [vee-validate](https://github.com/logaretm/vee-validate) (which is compatible with Vue 2) as suggested by @vijayee.

**Comment by vijayee** [comment]
Updated in pull request #129.
