### ISSUE TITLE
Verify color contrast ratio to comply Level AA

### ISSUE THREAD

**Issue by sandrina-p** [okTurtles/group-income#908]
### Problem

The small grey text of light theme does not comply with [WCAG 2.0 Level AA contrast ratio](https://webaim.org/resources/contrastchecker/).

![image](https://user-images.githubusercontent.com/14869087/80592846-0a026a00-8a18-11ea-9c1c-994c58bf9281.png)

### Solution

- Improve the contrast ratio to comply with Level AA.
- Double-check all the other texts comply with Level AA.

**Comment by mmbotelho** [comment]
Updated the Text / 1 color to #707070.

I believe I can remove myself from this one now @sandrina-p ?

**Comment by sandrina-p** [comment]
Yes! That will be fixed on my next PR :)

**Comment by mmbotelho** [comment]
Awesome, thank you for noticing that!
