### ISSUE TITLE
Group creation page

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#91]
## Problem

We need a UI for creating groups (along with their initial set of rules, i.e. "Constitution").
## Solution

Create `CreateGroup.vue` that takes care of this. The interface that we mocked up for this is viewable in the [Group Income presentation slides](https://groupincome.org/other/Group_Income.pdf).

As I'm working I'm noticing that in fact working with `.vue` files does seem more preferable (to me at least) to `.ejs` files. It certainly makes it easier to fully take advantage of Vue.js's features/workflow.
- [x] Create `CreateGroup.vue`
- [ ] Make sure that it's only accessible once you're ["logged in"](https://github.com/okTurtles/group-income-simple/issues/92)
- [ ] All the various "constitution stuff" as shown in the mockups
- [ ] Don't re-invent the wheel, use bulma and [awesome-vue](https://github.com/vuejs/awesome-vue) as appropriate
- [ ] Incorporate ideas from [our blog post](https://groupincome.org/2016/06/what-makes-a-good-voting-system/)

**Comment by taoeffect** [comment]
>  Make sure that it's only accessible once you're "logged in"

This broke in the Vue 2.x transition. It's supposed to redirect to SignUp.vue with `?next=/creategroup` (or something like that) but it not longer does.

**Comment by vijayee** [comment]
Fixed in #173
