### ISSUE TITLE
Bug: pressing enter in Log In modal doesn't log user in

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#914]
### Problem

After creating a user, logging out, and then using the login modal to log back in, if you press "Enter" while the cursor is inside the password field, you'll get this:

<img width="627" alt="Screen Shot 2020-05-06 at 1 01 44 PM" src="https://user-images.githubusercontent.com/138706/81225544-4137c480-8f9e-11ea-979e-2a25a4e4b135.png">

### Solution

Bring back previous behavior where it will log you in.

**Comment by sandrina-p** [comment]
I'll fix this during my next PR :)
