### ISSUE TITLE
BUG: QuotaExceededError for localStorage

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#920]
### Problem

While testing out Group Income I've been running into `QuotaExceededError`s. These errors are being triggered because the `localStorage` is running out of room. When I check `localStorage.length`, I get a value that exceeds what it should be:

```
> localStorage.length
7072
> localStorage.getItem('giConsole/john/count')
"167"
> localStorage.getItem('giConsole/john/limit')
"5000"
> localStorage.getItem('giConsole/john/markers')
"[]"
> localStorage.getItem('giConsole/john/markerNth')
"1000"
```

### Solution

Call `clearLogs` when the user log in, and clear the entire logs for `giConsole`, not just the logs for the current user.

The problem in this case was that there were logs for other users stored as well, that for some reason weren't cleared properly (I guess because the "Logout" code was never called). So we want to clear the entire localStorage for all of `giConsole` upon login.

E.g. replace:

```js
if (key.indexOf(`giConsole/${username}`) >= 0)
```

With:

```js
if (key.indexOf('giConsole') >= 0)
```

And make sure `clearLogs` is called on login.

**Comment by sandrina-p** [comment]
It would be a matter of time for this to happen indeed, as I said during the implementation of this feature.

> The problem in this case was that there were logs for other users stored as well, that for some reason weren't cleared properly

Yes, for example, if we stop the server and close the browser immediately, the logs won't be cleaned.

I'll fix this during the weekend :)
