### ISSUE TITLE
PWA: create a progressive web app wrapper [$200 bounty]

### ISSUE THREAD

**Issue by pieer** [okTurtles/group-income#926]
### Problem

The user needs to get notifications about actions that happen in the app.

### Solution

The easiest way to implement this at the moment other than relying on emails or chat is to create an application that the user can install on their device and receive notifications

This ticket concern only the PWA implementation and not the notifications itself
Step 1: Create the PWA
Step 2: Test PWA with PWA Builder (https://www.pwabuilder.com/)
Step 3: Test app on different devices
Step 4: Test notifications to see if it work

Useful link: https://whatpwacando.today/

### Bounty

$200 bounty for a clean solution to this (paid in cryptocurrency).

**Comment by SebinSong** [comment]
### Details of things to take care of for this issue

- [x] Creating an web app manifest (reference: [here](https://developer.mozilla.org/en-US/docs/Web/Manifest))
- [x] Extend the existing service-worker file(`primary.js`) for updates that are required for the app to be installable (e.g. add `fetch` event handler there, reference: [here](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Guides/Making_PWAs_installable))
- [x] Check/Make sure the web app is installable in both desktop and mobile device
- [x] Add push notification code to the service-worker and test if it works (possibly using [`web-push`](https://www.npmjs.com/package/web-push) npm pkg)
- [ ] Research [PWAbuilder](https://www.pwabuilder.com/) to see if it can be useful.

[ Feature branch for tracking commit history (cc. @taoeffect) ] : **[sebin/task/926-create-pwa](https://github.com/okTurtles/group-income/commits/sebin/task/926-create-pwa)**

**Comment by taoeffect** [comment]
Closed by @SebinSong in #1770!
