### ISSUE TITLE
Add French translation

### ISSUE THREAD

**Issue by snowteamer** [okTurtles/group-income#957]
### Problem

The user interface is currently only available in English, making it difficult to test whether the app is ready for i18n.

A `french.strings` file is actually present in the `strings` folder, but its contents are yet to be translated.

### Solution

I think French is a good candidate language for a first translation effort, mainly because we've got several great French-speaking contributors.

**Comment by taoeffect** [comment]
This this can be closed now, great job @snowteamer!! 🎉
