### ISSUE TITLE
Ensure GIS (and GI) are accessible

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#96]
The primary branch for this [milepost](https://github.com/taoeffect/mileposts) is located **[here](URL to branch).** (not pushed yet)

#### Description

This milepost concerns itself with [accessibility](https://www.w3.org/WAI/intro/accessibility.php) of Group Income and Group Income Simple. Questions about how users navigate through app without a mouse, how the UI (e.g. contrast) affects their ability to navigate through the app, adding image descriptions (alt text), including captions on videos, etc., all relate to this Milepost. Additionally, the work done on this Milepost will need to take into consideration, and will affect, the overall UI of the entire app, as well as its documentation.
#### Issues

List of issues that need to be closed for closing this milepost:

- [x] #2 - retina display support for assets
- [x] #122 - Accessibility Testing

**Comment by sandrina-p** [comment]
Both issues #2 and #122 are resolved, so this can be closed.
