### ISSUE TITLE
The same email can be used for multiple accounts

### ISSUE THREAD

**Issue by sdegutis** [okTurtles/group-income#965]
### Problem

Users seem to be able to sign up for multiple accounts using the same email.

I just signed up for three accounts locally, all using "test@example.com" for email.

There doesn't seem to be a good reason to expect that two distinct users are sharing the same email address yet want different accounts on Group Income.

If the same user wants to have multiple accounts (I can't imagine why), they can use email aliases like "test+second@example.com" or just get a second email address if their mail server doesn't support that.

### Solution

Make emails unique.

**Comment by taoeffect** [comment]
This will not be an issue once #852 is closed.
