### ISSUE TITLE
Invite-links form is broken when <3 group members.

### ISSUE THREAD

**Issue by sdegutis** [okTurtles/group-income#967]
### Problem

Under Group Settings -> Invite Links -> "propose adding a new member", the "Add new members" form fails when there are fewer than 3 members.

1. There is no visual feedback that it failed.
2. In devtools, this error shows up:

     | (anonymous) | @ | captureLogs.js:157
   -- | -- | -- | --
     | submit | @ | AddMembers.vue?rollu…n-vue=script.js:136
     | invokeWithErrorHandling | @ | vue.esm.js:1863
     | invoker | @ | vue.esm.js:2188
     | submit | @ | ProposalTemplate.vue…n-vue=script.js:207
     | invokeWithErrorHandling | @ | vue.esm.js:1863
     | invoker | @ | vue.esm.js:2188
     | submit | @ | ButtonSubmit.vue?rol…in-vue=script.js:65
     | invokeWithErrorHandling | @ | vue.esm.js:1863
     | invoker | @ | vue.esm.js:2188
     | original._wrapper | @ | vue.esm.js:7565

   It makes sense that `form.reason` on line 126 is `null` since that field doesn't exist in the form:

   <img width="672" alt="Screen Shot 2020-09-03 at 11 04 39 AM" src="https://user-images.githubusercontent.com/4399718/92139180-01121280-edd5-11ea-9b6b-08f428921737.png">
3. ~~It also seems impossible to invite someone with only a full name, not an email.~~ (The third point can be ignored, since I misunderstood this: the name is only to identify the invitation in the site UI, but the link is meant to be shared manually rather than automatically emailed.)

### Solution

1. When an error occurs, the UI should show some feedback, even if it's a generic error message like "Oops, something went wrong, sorry. Let us know at [email]".
2. Either the reason field should be added, or the line should be removed.
3. ~~I think there needs to be an "email" field too.~~

**Comment by sdegutis** [comment]
After using this form with 3+ group members, I see that the "Reason" form appears when "Next ->" is clicked. So this form just needs to change to omit the reason field, or pass an empty string, when <3 members.

**Comment by Silver-IT** [comment]
I think we should open a `InvitationLinkModal` instead of `AddMembers` modal in this case.

Reasons I think
- No need to propose considering the voting rule
- Should have the same workflow of create `Add new member` proposal
- It's a simple solution

What do you think, @taoeffect?

**Comment by taoeffect** [comment]
@Silver-IT I agree!
