### ISSUE TITLE
Fix docker script

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#971]
### Problem

I [broke](https://github.com/okTurtles/group-income-simple/commit/2c8ec32de76b88f65f78e7f0ce2a1aa2fde3b369#diff-285f5a875bc5897c56a0b51aea6307ffL12-L27) the networking in a change by removing these lines:

```sh
PORT_SHIFT=${PORT_SHIFT:-0}	
FRONTEND_PORT=$(( 8000 + $PORT_SHIFT ))	
BACKEND_PORT=$(( 3000 + $PORT_SHIFT ))	
REFRESH_PORT=$(( 35729 + $PORT_SHIFT ))

# .... [snip] ...

  -p 127.0.0.1:${FRONTEND_PORT}:${FRONTEND_PORT} \
  -p 127.0.0.1:${BACKEND_PORT}:${BACKEND_PORT} \
  -p 127.0.0.1:${REFRESH_PORT}:${REFRESH_PORT} \
```

### Solution

I think I removed them because I didn't want to have to make assumptions in the script about what the base port was (e.g. whether it was 8000 or 3000). However, removing these lines breaks the networking entirely, and I probably mistakenly thought `--ipc=host` would make it work, but I probably meant to write `--network=host`.

So either change it to `--network=host` (and verify that that fixes the problem), or add back those lines (and later one figure out how to guarantee they are synced between code and script).

**Comment by F1LT3R** [comment]
I compared the two methods you mentioned @taoeffect 

1. Specify Ports

    ```bash
    FRONTEND_PORT=$(( 8000 + $PORT_SHIFT ))	
    # ...
    -p 127.0.0.1:${FRONTEND_PORT}:${FRONTEND_PORT} \
    ```

2. Map Network to Host

    ```bash
    --network=host \
    ```

Results:

| Address | Specify Ports | Map Network to Host |
| --- |  --- |  --- |
| [localhost:8000](http://localhost:8000) | ✓ | 𐄂 | 
| [127.0.0.1:8000](http://127.0.0.1:8000)  | ✓ | 𐄂 | 
| [0.0.0.0:8000](http://0.0.0.0:8000) | ✓ | 𐄂 | 

It appears from the Docker documentation that using host networking is only available on Linux.

> The host networking driver only works on Linux hosts, and is not supported on Docker Desktop for Mac, Docker Desktop for Windows, or Docker EE for Windows Server.  
> https://docs.docker.com/network/host/
