### ISSUE TITLE
Finish "Avatar Placeholders" review

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#981]
### Problem

To speed things along we decided to merge #923 even though there was a pending request for changes.

Specifically two things were left unaddressed:

1. [Making `imageDataURItoBlob` support extraction of data type from the URI](https://github.com/okTurtles/group-income-simple/pull/923#discussion_r485243638)
2. [Replacing AvatarGenerator with an SBP function/selector](https://github.com/okTurtles/group-income-simple/pull/923#discussion_r487380628)
3. (Possibly) [generating the avatar inside of `'gi.actions/identity/create'`, and *IF* it fails for some reason, then using the default URL](https://github.com/okTurtles/group-income-simple/pull/923#discussion_r487380791)

### Solution

Submit a PR that addresses the above remaining issues.

**Comment by SebinSong** [comment]
regarding 2. up in the description, @taoeffect  what would you suggest for the sbp selector name? Does `utils/generate-avatar` sound good? Also, Do you think the logics for `blockies.create()` that are currently in `AvatarGenerator.vue` should be moved to `@utils/image.js`(since we are going to remove `AvatarGenerator.vue` file)? 

EDIT: where should the sbp function for Avatar generator be placed in the source code? 

Sorry for too many questions all at once.

**Comment by taoeffect** [comment]
> regarding 2. up in the description, @taoeffect  what would you suggest for the sbp selector name? Does `utils/generate-avatar` sound good?

If you think there will be only a single avatar related selector, then how about `gi.utils/avatar/create`? Or, if you think there might be multiple avatar-related selectors, then maybe `gi.avatar/create` ?

> Also, Do you think the logics for `blockies.create()` that are currently in `AvatarGenerator.vue` should be moved to `@utils/image.js`(since we are going to remove `AvatarGenerator.vue` file)? 

Sure? And/or place it into the file that defines `gi.avatar`-related selectors, depending on whether or not you decided to put all avatar-generating stuff together under its own domain/namespace.

> EDIT: where should the sbp function for Avatar generator be placed in the source code?

We currently have multiple utils folders. One in `frontend/utils` (aliased as `@utils`), and `frontend/views/utils` (aliased as `@view-utils`).

Think about the difference between these two.

If I were to put it into words, I would say that `frontend/utils` are small miscellaneous functions that can be referenced across multiple top-level folders.

The top-level folder correspond to the MVC paradigm. So `frontend/model`, `fronend/views`, and `frontend/controller`, are the main top-level folders corresponding to Movel-View-Controller. If a utility function is referenced across two or more of these folders, it goes into `frontend/utils`. Otherwise, if it's clearly a View-related utility, and is only referenced in the Vue.js related code, it goes somewhere under `frontend/views/utils`.
