### ISSUE TITLE
Finish cleaning up currencies.js

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/group-income#989]
### Problem

To speed things along we decided to merge #988 before finishing addressing all of the remaining cleanup/boy-scouting for `currencies.js`. Here I'm copying [the comment](https://github.com/okTurtles/group-income-simple/pull/988#discussion_r491088408) that got partially addressed:

> This file is getting unwieldy and there were some things in #950 that did not get reviewed properly. Let's fix all of that in this PR.
> 
> The function `withReasonableDecimals` is doing way too much, and looks to be entirely unnecessary in the face of `decimalsOrInt`, which is supposed to do what `withReasonableDecimals` does. So let's fix `decimalsOrInt` instead, and clean up some of the stuff that was missed in #950.
> 
> 1. (NOTE: this was done ✅)  There is a bug in `decimalsOrInt`, which is on line 51 here, and that is that `fixed` is a float, and yet it is being regex'd on in line 51. That is wrong. `parseFloat` shouldn't have been called in line 50.  The call to `.toFixed` should do nearly everything that `withReasonableDecimals` attempts to do, the only thing missing is to account for `.00`, and that is what line 51 and 52 should be doing.
> 2. (NOTE: this was done ✅) `withReasonableDecimals` should be removed unless for the some reason the short & sweet `decimalsOrInt` cannot do what it does (but AFAICT, that is exactly what `decimalsOrInt` was written to do)
> 3. (NOTE: this was done ✅) `decimalsOrInt` should return a string, not a number, and the type definitions should be updated accordingly, and all type issue should be fixed.
> 4. The review of #950 missed that `commaToDots` should take a string or a number and return a number. Everything got confused in that PR because strings and numbers were being mixed together and without any consistent type annotations, an no clear rules being followed. Actually running flowtype would have caught many of those errors. `saferFloat`'s type definition should be restored. It should take a number or string and return a number.
> 5. `isInDecimalsLimit` is missing type annotations, and so are other functions. Every single function in this file should be type annotated, both for the parameters and the return value, and all of the actual internal usage of those parameters and the actual return values must match the type annotations.

### Solution

Finish cleaning up and addressing all type usage, while making sure that no new bugs are introduced by checking all usage across all files.

Clean up and simplify anything else you notice.

**Comment by sdegutis** [comment]
Thanks for moving the remaining items to this new issue, and for detailing what's left. Just sent a PR, looking forward to your feedback when you get around to it.
